### ISSUE TITLE
Getting screen tearing in the 2003 Plus core

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#1018]
using the nightly build 8-31-2020

Pie 4

I have tried a few games in MAME 2003 Plus and you can see screen tearing.

Play the game Alpha Mission II / ASO II - Last Guardian you can let the demo run to see it.

**Comment by Ntemis** [comment]
Thank you for the report. An rpi4 is coming my way.
I will have a shining new image for you to test asap i have it

**Comment by Cibomatto2002** [comment]
I just downloaded the new nightly September 1 tearing still there.

**Comment by Cibomatto2002** [comment]
Played some nes today and seen some tearing played it for over a hour.

**Comment by Ntemis** [comment]
@Cibomatto2002 please test this image https://nightly.builds.lakka.tv/2020-09-10/RPi4.arm/Lakka-RPi4.arm-3.0-devel-20200910021956-82f7874.img.gz

**Comment by Cibomatto2002** [comment]
Still there I made a video for you to see maybe it can help.


https://youtu.be/qEy1_abb6jE

**Comment by Ntemis** [comment]
the "tearing" you see can be core related or even how your screen is handling the very fast refresh rate but i wouldn't blame lakka for this either we can fix such issues.
Please report the "tearing" you see to the core maintainer for the individual core you have it.
Am closing this down. Thank for the video btw, it was enlightening.

**Comment by Cibomatto2002** [comment]
I hope I did not waste your time working on this I felt like I was that's why I made a video.

**Comment by Cibomatto2002** [comment]
I just wanted to tell you I got it working disabling the bypass audio skew fixed it.
