### ISSUE TITLE
RetroArch reboots on o2em (Magnavox - Odyssey2 / Phillips Videopac+) core if making a save state

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#1021]
If I try to make a ave state in Lakka on the pie 4 with the o2em (Magnavox - Odyssey2 / Phillips Videopac+) core it will reset. RetroArch on windows 10 the save state works.

**Comment by ToKe79** [comment]
please retest with [Lakka 3.x release](https://le.builds.lakka.tv) and open new issue if the problem persists.
