### ISSUE TITLE
Request: Add support for OpenBOR

### ISSUE THREAD

**Issue by josefprado** [libretro/Lakka-LibreELEC#103]
Team, this is not a bug report, but a suggestion/request.

Is it possible to include OpenBOR into Lakka?

For those who does not know it, here is the projeto page: https://github.com/DCurrent/openbor

Regards,

Josef Prado

**Comment by Kivutar** [comment]
Nice program! But you should do this request on the RetroArch or libretro tracker. Not much libretto dev visit the Lakka tracker.
