### ISSUE TITLE
Myst crash (PCSX ReARMed)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#1032]
Here is a video I made in the video you can see it does not crash that's because i'm on Windows 10 but if you play this in lakka nightly 2020-09-13 on the pie 4 it will crash when the video in the book starts to play

https://www.youtube.com/watch?v=AM8bXWyKdK4

Maybe the PCSX ReARMed core is out of date on the Pie 4? It did update in Retroarch on windows 10 the other day

**Comment by Cibomatto2002** [comment]
It works on duckstation.

**Comment by Ntemis** [comment]
So duckstation works better.

**Comment by Cibomatto2002** [comment]
way better. here is a Compatibility list. https://docs.google.com/spreadsheets/d/1H66MxViRjjE5f8hOl5RQmF5woS1murio2dsLn14kEqo/edit#gid=0
