### ISSUE TITLE
librga sources missing for OdroidGoAdvance

### ISSUE THREAD

**Issue by bhartshorn** [libretro/Lakka-LibreELEC#1043]
Hi. I am attempting to build Lakka for the OGA. It seems that the repository relied upon for [this librga package](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/graphics/librga/package.mk) has mysteriously disappeared: https://github.com/rockchip-linux/linux-rga

I looked around to see if it was moved or replaced, but I'm in over my head here. I did find rga sources in the rockchip-linux kernel tree, but I have no idea if it's the same code: https://github.com/rockchip-linux/kernel/tree/release-4.4/drivers/media/platform/rockchip/rga

Also, is there somewhere that development chatter for the project happens? I've been in the IRC channel a couple days and haven't heard from any main devs.

**Comment by Ntemis** [comment]
We wait to return

**Comment by shantigilbert** [comment]
Meanwhile you can use this: https://github.com/Caesar-github/linux-rga

**Comment by bhartshorn** [comment]
@shantigilbert thanks!
@Ntemis if it's known that it's coming back some time, feel free to close the issue. Thanks for response.

**Comment by gouchi** [comment]
@bhartshorn [repository](https://github.com/rockchip-linux/linux-rga) is back.

You can also come to [discord](https://discordapp.com/invite/27Xxm2h).
