### ISSUE TITLE
WeTekPlay Lakka-V2.0 RC4 shaders too slow

### ISSUE THREAD

**Issue by NuisMons** [libretro/Lakka-LibreELEC#105]
- Which version of Lakka are you using?
Lakka V2.0rc4 with latest patches
- What system hardware are you using?
Wetek Play
- What did you do?
Try using some shaders to games
- What did you expect to happen?
Play games with improved looks
- What happened instead?
Lakka extremelly slows ui, and games worked too slow (No hardware acceleration?)

In 2016, i played games on raspberry Pi 1 B  with using some shaders, and there is no problems with it. Now, I try shaders at wetek play and all goes very slow, No hardware acceleration in wetek play and its ok? 
 Its correct, or prefer to not use shaders on Lakka?

**Comment by Kivutar** [comment]
I notice that the shaders were very slow on WeTek Play too.

I suggest you to set the scale to 2 when you try a shader. It prevents them to run at the resolution of your TV. It will run them at the resolution of the game * 2.

Also, I'm going to change how the shaders work in Lakka soon, by adding a simple mode with 10 to 20 popular shader presets scaled at 2.

It may fix this bug as a side effect. If not, I scare that it will be a "won't fix".

**Comment by NuisMons** [comment]
Just try shaders and games again, and now I think gpu of wetek play really bad.
I think slow shaders is not bug (find some useful), but I want shaders work only in games, not in lakka ui, because sometimes need to poweroff wetekplay to unfreeze user interface.
Thanks, and sorry my bad english)

**Comment by Kivutar** [comment]
I don't think we can fix this.
