### ISSUE TITLE
ODROID GO ADVANCE

### ISSUE THREAD

**Issue by cederom** [libretro/Lakka-LibreELEC#1058]
Hello world :-) Is Lakka available on ODROID GO ADVANCE? I was redirected here from EmuELEC project as they tend to use Emulationstation and remove RetroArch GUI..

**Comment by Ntemis** [comment]
https://nightly.builds.lakka.tv/2020-10-09/OdroidGoAdvance.arm/

**Comment by cederom** [comment]
Awsome, thank you! :-)
