### ISSUE TITLE
consider adding Lakka-LibreELEC to libretro on github (regarding bounties)

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#106]
I have been experimenting with the new bounty system, which seems nice.

From what I can tell so far, Bountysource groups the bounties by their github 'team'. I noticed that Lakka-OpenELEC is part of the libretro team so [bounties on LakkaOE would be grouped together with libretro](https://www.bountysource.com/teams/libretro), but the new Lakka is under the lakkatv team , and bounties would listed separately on the Bountysource site. 

Perhaps you already know this, but I wanted to mention in case not.

**Comment by Kivutar** [comment]
Done, thanks.
