### ISSUE TITLE
WiFi broken in Lakka-H3.arm-3.0-devel-*-orangepi-plus2e nightly builds

### ISSUE THREAD

**Issue by cjom** [libretro/Lakka-LibreELEC#1067]
- Which version of Lakka are you using?

Lakka-H3.arm-3.0-devel-20200828000658-d9ba9d8-orangepi-plus2e.img.gz works very well.
All builds after that date have wifi broken.

- What system hardware are you using?

Capcom Home Arcade console uses a customized orangepi-plus2e.
Lakka-H3.arm-3.0-devel-20200828000658-d9ba9d8-orangepi-plus2e.img.gz works very well.
more info on installing and using here: https://cha-choko-mod.fandom.com/wiki/DUAL_BOOT_-_Installing_Lakka_in_the_CHA

- What did you do?

Scan wifi to connect to my home network.

- What did you expect to happen?

To see a list of networks and connect to mine.

- What happened instead?

Builds from September: Lakka crashes and reboots; Builds from October: don't crash but no networks are found, showing only 1 garbage name (see picture).
![lakkawifi](https://user-images.githubusercontent.com/55603581/96636983-8f9f0c80-130d-11eb-815a-296dca8be682.jpg)

I can't attach any logs because I'm unable to use SSH since it doesn't connects to wifi.

**Comment by Ntemis** [comment]
Can you confirm that the onboard wifi chip is the Realtek RTL8189ETV?

**Comment by cjom** [comment]
I see that it's not... it's RTL8188ETV (previous version?)
![chawifi](https://user-images.githubusercontent.com/55603581/96646395-99c80780-131b-11eb-8bc9-950cf9e30d91.jpg)

At least the build from 2020-08-28 works... but would be awesome if future versions would work too.

**Comment by Ntemis** [comment]
That changes everything :)

**Comment by cjom** [comment]
Any clue as why older builds work?
Or any tip about another version to test?
It has Allwinner H3 cpu and  for sure.

**Comment by Ntemis** [comment]
https://github.com/libretro/Lakka-LibreELEC/commit/09408f8d668919b2ef95af73aef3740668ae5bc0

**Comment by Ntemis** [comment]
try next nightly version and report back(you have to wait 24h)

**Comment by cjom** [comment]
Thank you! Will test for sure!

**Comment by Ntemis** [comment]
If Debian wiki doesn't lie it should work fine :)
https://wiki.debian.org/rtl819x#supported-r8188eu

**Comment by ToKe79** [comment]
New image is up - [Latest images - Allwinner H3](https://nightly.builds.lakka.tv/latest/H3.arm/)

**Comment by cjom** [comment]
And it works!
Thank you so much!
