### ISSUE TITLE
Stuck in the flower screen after boot

### ISSUE THREAD

**Issue by apellegr06** [libretro/Lakka-LibreELEC#1079]
Hi,

Here is the requested informations :

- version of Lakka : Lakka-Generic.x86_64-2.3.2.img
- system hardware : Intel Atom D525 (Dual Core 1.8 GHz - 1 Mo de cache) - chipset Intel NM10 Express - graphic chipset NVIDIA ION 2
- What did you do : install and boot
- What did you expect to happen : see the graphic interface
- What happened instead : stuck on the flower screen

Thank you

**Comment by Ntemis** [comment]
2.3.2 is eol so this issue is not going to get fixed.
Try to use nightlies
https://nightly.builds.lakka.tv/

**Comment by apellegr06** [comment]
In fact it's ok, I used that to force HDMI : http://www.lakka.tv/doc/PC/
