### ISSUE TITLE
Does not seem responsive on the Rpi4

### ISSUE THREAD

**Issue by abnormisdictum** [libretro/Lakka-LibreELEC#1084]
I burnt lakka on a SD card for my Rpi4 4GB. After the initial bootup resizing, i was able to connect to my wifi network. But when I tried to update Lakka, it simply stated that task failed and that there were no entries to display.

So i tried loading a psp core. But after selecting the core nothing happened.

Mind you i was using a keyboard and not a controller. Could that be the issue?

I would appretiate any help on this to point me in the right direction.

Warm regards.

**Comment by Ntemis** [comment]
What lakka version did you use?

**Comment by abnormisdictum** [comment]
2.3.2

**Comment by abnormisdictum** [comment]
> 2.3.2. The latest one available on the website lakka.tv

Ok. To be certain it's not because of a lack of a controller, i used my XBox 360 wireless controller.

The issue persists

**Comment by Ntemis** [comment]
Try migrating to a nightly version

**Comment by abnormisdictum** [comment]
> Try migrating to a nightly version

Will give it a go and report back.

**Comment by Ntemis** [comment]
Please switch to more recent nightlies versions from here https://nightly.builds.lakka.tv/
Version 2.3.2 is the last version on v2.x branch and is not destined to get any more updates or bug fixes.
Switching to nightlies help us too to catch and fix bugs before the final release and prevents any issues like this show up in the future.
