### ISSUE TITLE
Playstion psx/ps1 image distortion 

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1085]
Raspberry Pi 4 model B 
Lakka stable image 2.3.2

I'm getting these image distortions from the following: Glover, Monkey Hero and Guardian's Crusade. I'm not sure if its a ROM issue or a core issue. This is from using the only Playstion core that is used currently on the Raspberry pi 4b lakka 2.3.2 image. One of them uses a ccd format.

![Glover (USA)](https://user-images.githubusercontent.com/73009731/98427231-2af3e980-2051-11eb-89fb-98decc31a597.png)

![Monkey Hero-200120-183321](https://user-images.githubusercontent.com/73009731/98427103-9ee1c200-2050-11eb-8604-91b96f77c079.png)
311f8.png)

![Guardian's Crusade (USA)-200120-181835](https://user-images.githubusercontent.com/73009731/98427100-9ee1c200-2050-11eb-9fc7-87e57cac6292.png)

**Comment by Ntemis** [comment]
https://nightly.builds.lakka.tv/2020-11-05/RPi4.arm/

**Comment by Ntemis** [comment]
Please switch to more recent nightlies versions from here https://nightly.builds.lakka.tv/
Version 2.3.2 is the last version on v2.x branch and is not destined to get any more updates or bug fixes.
Switching to nightlies help us too to catch and fix bugs before the final release and prevents any issues like this show up in the future.
