### ISSUE TITLE
Boot seems to freeze on Bananapi M1

### ISSUE THREAD

**Issue by Jannled** [libretro/Lakka-LibreELEC#1092]
I am currently facing several issues on my **BananaPi M1**. 

1. First of, the **2.3.2 build is not available** from http://le-builds.lakka.tv/Allwinner.Bananapi.arm/ or http://www.lakka.tv/get/linux/allwinner/ .

2. So I tried using the 2.3.1 and 2.3.0 builds. They are installed on a new SD Card using Etcher. They launch up as expected and expand the partitions. After the reboot the Lakka Logo appears together with some boot messages. After this I would expect the Lakka Main menue to show up, but Lakka seems to be stuck with the last lines usually beeing 
_[OK] Started WPA supplicant._
or
_[OK] Reached target Retroarch_

When it seems frozen, the device would responds to ICMP requests but denys SSH access _(Connection refused)_. New USB devices are not recognized (for e.g. my USB Gamepad wont light up after pluging it in). And I can smash whatever button on the connected keyboard without a reaction.

3. I would like to provide more debug infos, but since I can't log in via SSH and Serial console seems disabled, I have no clue how to gather more information.

4. I attached a screenshot of the boot process. Sadly I don't own a screen grabber, I hope the quality is sufficent.

![IMG_20201109_232736](https://user-images.githubusercontent.com/7737131/98604056-568e0280-22e3-11eb-9252-bd38eef6d76a.jpg)

5. I've also tried disk images from https://nightly.builds.lakka.tv/latest/H3.arm/ with no success (it is trying to download a file from a TFTP server), but I guess this belongs in a seperate Bug report.

**Comment by Ntemis** [comment]
A20 is unsupported
