### ISSUE TITLE
Bad screen tearing on Beetle neoPop Emulator

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#1093]
Pie 4 2gig 

Nightly Sep 22 2020 I know this is a older nightly but this one works the best on my pie. I would like someone to test newer builds on there pie 4  I have trouble  with screen tearing on emulators changing the Vsync to 2 almost fixes it but not quite.

Bad screen tearing on Beetle neoPop Emulator 

Just play any game like metal slug 1st mission

**Comment by Ntemis** [comment]
Its a clear vsync issue please take this to neopop core issues.
