### ISSUE TITLE
Video rotation doesn't work correctly when RunAhead is activated - RPi4

### ISSUE THREAD

**Issue by MikeSynth** [libretro/Lakka-LibreELEC#1097]
Lakka-RPi2.RPi4.arm-2.3.2

I have a folder of vertically oriented FBNeo roms (aspect ratio 4:3) with it's own config file with video_rotate setting.
If RunAhead is enabled, the video_rotate instruction doesn't kick in.
The  scanline shaders are vertical (relative to the image), but the image is horizontal and stretched.
However, when I go into video settings, I see that the rotation is still set to 90 degrees.
When I toggle to rotation to 0 degrees and back to 90 degrees, the image displays correctly.
I have tested this with RunAhead disabled and the rotation config works as it should.

**Comment by Ntemis** [comment]
Please switch to more recent nightlies versions from here https://nightly.builds.lakka.tv/
Version 2.3.2 is the last version on v2.x branch and is not destined to get any more updates or bug fixes.
Switching to nightlies help us too to catch and fix bugs before the final release too to prevent any issues like this in the future.
