### ISSUE TITLE
Occasional severe screen-tearing on MGBA - RPi4

### ISSUE THREAD

**Issue by MikeSynth** [libretro/Lakka-LibreELEC#1098]
Lakka-RPi2.RPi4.arm-2.3.2

I did notice this on FB Neo at one point, but I am mainly noticing it on MGBA.
So far I haven't noticed this effect on other cores.
My V-Sync is active, but occasionally I experience severe screen-tearing.
Not just a tear in the center, but on several places on the screen.
This usually lasts for a second or two.

**Comment by Ntemis** [comment]
Please switch to more recent nightlies versions from here https://nightly.builds.lakka.tv/
Version 2.3.2 is the last version on v2.x branch and is not destined to get any more updates or bug fixes.
Switching to nightlies help us too to catch and fix bugs before the final release too to prevent any issues like this in the future.
