### ISSUE TITLE
Flower logo background only

### ISSUE THREAD

**Issue by ItzShittyPaper** [libretro/Lakka-LibreELEC#1102]
- Which version of Lakka are you using?
Nightly 2020/11/16-ab89503

- What system hardware are you using?
Raspberry Pi 4 4GB

- What did you do?
I downloaded an image from lakka website, flashed it to sd card via etcher, inserted sd card into raspberry pi 4, booted it up.

- What did you expect to happen?
Lakka boots.

- What happened instead?
Gray background of traditional flower logo loading screen, no text or logo at all, lakka isn't loading.

**Comment by ToKe79** [comment]
please retest with [Lakka 3.x release](https://le.builds.lakka.tv) and open new issue if the problem persists.
