### ISSUE TITLE
Pi4 - BuildBot Link doesn't contain flycast core for ARM architecture

### ISSUE THREAD

**Issue by Philps** [libretro/Lakka-LibreELEC#1103]
LE 9.2.6 + Lakka 2.3.2

The Retroarch configurations link to the following buildbot page: https://buildbot.libretro.com/nightly/linux/armhf/latest/

However there is no flycast core available\listed

**Comment by ToKe79** [comment]
not a Lakka issue, Lakka does not support core downloader and Lakka does not maintain the cores built by the libretro buildbot.
