### ISSUE TITLE
Audio Output Menu options stuck, 

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1108]
Raspberry Pi 4 Model B
Lakka OS: Nightly build Nov 19 2020 RPI 4 ARM

First when setting it up there is no sound, so usually I have enable the mixer menu and XMB background noise so I don't have to launch a ROM to test out sound, but the options were not there when trying to cycle them left or right. When I did select one of the options I usually have to reboot to let it take effect, the bgm was sounding  off and a little static-y. When trying to cycle device options for sound ie **default:CARD=vc4hdmi1** it wasn't cycling and needed  to be cleared and then rebooted before I can cycle through them again. Usually setting up sound on a RPi 4b is kinda iffy I don't remember ever having sound working out of the box without messing with Settings ->Audio->Output

Its on **alsathread** right now but what is the default or preferred setting for a Raspberry Pi 4 model B?

**Comment by SethBarberee** [comment]
Any change to audio requires a retroarch restart.
https://www.lakka.tv/doc/Audio-settings/

Default for RPi4 is `alsa` (non thread)
https://github.com/libretro/Lakka-LibreELEC/blob/31ef8f9723fda749d5e887abdcd3df7a960792cb/packages/libretro/retroarch/package.mk#L200-L201
