### ISSUE TITLE
PPSSPP rom black screen / rom crashing rpi4b 

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1110]
Raspberry PI 4 model B
Lakka OS: Nightly Build Nov 11,2020 RPI4 ARM

I have seen this particular game crash on a PC as well "Jeanne D' Arc" it boots up then shows a studio screen and crashes shortly after. Even using a different rom source there the crash still happens. 

Log files
[retroarch_PPSSPP.log](https://github.com/libretro/Lakka-LibreELEC/files/5579709/retroarch_PPSSPP.log)

And another game, "DarkStalkers Chronicle The Chaos Tower"  ends up with just a black screen

log files
[Retroarch PPSSPP 2 dsc.log](https://github.com/libretro/Lakka-LibreELEC/files/5579713/Retroarch.PPSSPP.2.dsc.log)

**Comment by ToKe79** [comment]
please, re-test with [latest nightly](https://nightly.builds.lakka.tv/latest/) / [latest release](https://le.builds.lakka.tv/).
