### ISSUE TITLE
[OGA][RG351] Remaining issues

### ISSUE THREAD

**Issue by vanfanel** [libretro/Lakka-LibreELEC#1111]
Hi,

I recently received my RG351P, and of course Lakka became my instant choice as OS to use on it.
I found that OGA/RG351 was just added by @davidgfnet , first nightly version including it is here:

https://nightly.builds.lakka.tv/2020-11-19/OdroidGoAdvance.arm/

However, there are some small issues with it, just three really that I have noticed:

1) GenesisPlusGX: MegaDrive games fail after some seconds, going back to the RetroArch menu. Master System/GameGear games don't do this. 
 Seems like core-related to me: build options, included core version, etc.

2) Battery charge is not correctly displayed, nor is LED indicator correctly set up to green on charged unit.

3) Hybernation doesn't work: it usually works on a light push on the power button.

None of those issues happen in 351elec (Emuelec fixed for RG351) available here:
https://github.com/fewtarius/351ELEC
...So maybe the charge indicator are related to kernel/dtb?
Or maybe emuelec has some hybernation service? I failed to contact with Emuelec devs or 351elec devs to ask.

**Comment by jdalmanza** [comment]
Tried nightly from 01/08 and can confirm the GenesisPlusGX behavior exists on OGA BE as well.

**Comment by THTB614** [comment]
From a bit of digging, it looks like the battery display is essentially reading the battery as if it were the OGA's battery, which is 500MaH smaller in capacity, if that helps any.

**Comment by Ntemis** [comment]
@davidgfnet can we close this now?

**Comment by jdalmanza** [comment]
just tested nightly from 04/06 and genesis-plus-gx still crashes when gameplay starts

**Comment by ToKe79** [comment]
#1248 should have fixed the genesis crash.

**Comment by davidgfnet** [comment]
Yep, genesis issue is now fixed! Seems like aarch64 kernels are not 100% compatible with armv7 binaries :) For the curious: https://news.ycombinator.com/item?id=18855047
I'm gonna tacke the battery and sleep mode things soon, I've got some work in progress stuff sitting on my local git.

**Comment by davidgfnet** [comment]
Sent PR #1262 for the battery issue
