### ISSUE TITLE
[Feature Request] scripts for safe shutdown buttons and reset buttons

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1112]
Raspberry Pi 4 B
Lakka OS: Nightly Nov 19,2020 rpi4 arm

**Comment by SethBarberee** [comment]
This isn't really something to add to the default image. However, there are ways to do it with GPIO overlays or other programs. I believe a few of the other projects in the repo for commercial products have safe shutdown scripts.

One example:
https://github.com/edus44/lakka-gpio-control/tree/master/scripts

**Comment by Rstation4** [comment]
Is there something that has changed for the shutdown process on the current images for the rpi4b? I have a NesPi 4 case that has not worked with either sripts.
 https://github.com/marcelonovaes/lakka_nespi_power   That is the one I have used before without an success

**Comment by Ntemis** [comment]
Not happening unless we have the case for r&d case closed
