### ISSUE TITLE
Nightly N64 cores no sound / core crashing parraLLEL N64 RPI4B

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1114]
Raspberry Pi 4 B
Lakka, Nightly build 11-19-2020 RPI4 ARM

Parrallel N64 crashes whenever booting up a rom. Mupen64 on the other hand was having a issue with no sound. Tested with default setting and lowest resolution with Mupen64 with the same result on no sound. Even the FPS was dropping.

I have also experienced no sound from the DeSmuME core and some low FPS around the 30s when playing a rom.

Edit: roms tested are Pokemon HeartGold, Pokemon Black (1 and 2), there are other roms tested but it has been low fps and off sounding audio for the most part. Even DeSmuMe 2015 doesnt have any luck with it either. I recall MelonDS not working right either. I wont test this out anymore at the moment.

**Comment by SethBarberee** [comment]
Which date nightly? 

What rom are you testing Desmume with? From my testing on RPi3, desumume is kinda meh on any RPi.

**Comment by basilean** [comment]
Hello @Rstation4 ,

Using parallel on rpi4, I get best results with gfxplugin=rice, not the best but at least playable.
