### ISSUE TITLE
Updater Is Broken.

### ISSUE THREAD

**Issue by GitCoder23** [libretro/Lakka-LibreELEC#1121]
Hardware: 
Raspberry Pi Zero W (With Wifi Enabled)

Using Lakka 2.3.2 (From The Official Site.)

When In The Main Menu , I Click Update Lakka , It Gives Me An Error.

**Comment by Cibomatto2002** [comment]
Thy this nightly build.  
https://nightly.builds.lakka.tv/2020-09-22/

**Comment by Bizzle1** [comment]
Hello,
I have the same issue and have not been able to resolve this on latest build rpi4 8gb.

**Comment by Ntemis** [comment]
Please test 3.1 release

**Comment by oldschoolskunk** [comment]
Updater appears to work on my pi4 with 3.1 release.  
Is there a way to do manual update?

**Comment by ToKe79** [comment]
this was most probably server error (response with 301 - redirect http to https)
