### ISSUE TITLE
Flycast crashing upon using save states RPi4

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1126]
Raspberry Pi 4 B
Lakka Nightly Build 11 19 2020 RPI4 ARM

When using save states from saving and loading on Dreamcast ROM's it ends up crashing Lakka OS.
Logs
[retroarch__2019_04_11_ dc.log](https://github.com/libretro/Lakka-LibreELEC/files/5662643/retroarch__2019_04_11_.dc.log)

**Comment by Cibomatto2002** [comment]
Try this nightly 

https://nightly.builds.lakka.tv/2020-12-14/

**Comment by Ntemis** [comment]
Please test 3.1 release
