### ISSUE TITLE
Feature request - rsync & git

### ISSUE THREAD

**Issue by WHK102** [libretro/Lakka-LibreELEC#1127]
Please, add rsync and git or dpkg manager to lakka image for fast sincronization of new files. With SMB need reupload all content, but with rsync upload only files changed, useful for make backups, upgrades or upload new content from server repository.

**Comment by gouchi** [comment]
Please check with [nightly build](https://nightly.builds.lakka.tv/latest/) as @Ntemis added rsync with this [commit](https://github.com/libretro/Lakka-LibreELEC/commit/f4bed0f54adba71d4425c9a74340eb4c4b23277d).

**Comment by WHK102** [comment]
Very good news! Does this mean that future stable releases will include rsync?

**Comment by Ntemis** [comment]
Yes i will enable the package today so next nightly will have it
