### ISSUE TITLE
PS1/PSX  PCSX ReARMed core bugs 

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1128]
Raspberry Pi 4 model B
Nightly Build Lakka RPI4 ARM Nov-9-2020

With some ROM's there are some compatibility errors. 

Legend of Mana: I've tried several rom versions and for some reasons the controller inputs do not work its a weird bug to explain.

Brave Fencer Musashi: screen went black and stayed that way until reseting, in past **Lakkka** versions there has been slowdowns as well.

Quake: upon reaching a certain level I get graphical errors

Final Doom: graphical glitches so far when using the higher resolution option.

![Final Doom (USA)2](https://user-images.githubusercontent.com/73009731/101833978-93ba0000-3aee-11eb-8dde-68b3c620162e.png)
![Final Doom (USA)- 1](https://user-images.githubusercontent.com/73009731/101833980-94529680-3aee-11eb-980f-045b9da7ce9d.png)
![Quake II (USA)-2](https://user-images.githubusercontent.com/73009731/101833983-94529680-3aee-11eb-9e1e-d3464be8362b.png)
![Quake II (USA)- 1](https://user-images.githubusercontent.com/73009731/101833984-94eb2d00-3aee-11eb-9e08-8afde93b3618.png)

**Comment by Ntemis** [comment]
can you please retest using this image?
http://demetris@buildserver3.lakka.tv:8080/Lakka-RPi4.aarch64-3.0-devel-20201210183618-f79b1b0.img.gz
Thank you in advance

**Comment by Ntemis** [comment]
Please test 3.1 release
