### ISSUE TITLE
Please add stella for the pie 4

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#1133]
If you could add stella to the pie 4 I would test it to see if it can run it at 60 fps or not.

**Comment by gouchi** [comment]
You can try this [nightly build](https://nightly.builds.lakka.tv/latest/RPi4.arm) as @Ntemis added per [this commit](https://github.com/libretro/Lakka-LibreELEC/commit/809fc40cbfcee21a3a2556b446246a3fa17a9dd9).

Thank you.

**Comment by Cibomatto2002** [comment]
I tried the link you gave me I don't see stella only stella 2014.

**Comment by Cibomatto2002** [comment]
Will this be ready in the next nightly?
