### ISSUE TITLE
Please Add Writable Path to PATH variable

### ISSUE THREAD

**Issue by cbluth** [libretro/Lakka-LibreELEC#1134]
Please see this issue:
https://github.com/libretro/Lakka-LibreELEC/issues/289#issuecomment-745033117

It would be nice to allow users to upload their own binaries to the system, and then the binaries survive a reboot.

A good use-case scenario is adding `rsync` as explained in the ticket above ^

adding the PATH variable, something like `/storage/bin` and `/storage/lib`, seems like a good idea to allow users of lakka to customize their installation.

**Comment by basilean** [comment]
Hello @cbluth ,
 You should be able to do so as it is today.

- Create directories under /storage and copy your files there.
- Add a "/storage/.profile" file and set environment variables as usual.
 
 After reboot, you should see results you are looking for.
