### ISSUE TITLE
ZIP not loading when using SAMBA

### ISSUE THREAD

**Issue by brianblakely** [libretro/Lakka-LibreELEC#115]
So far, I have been able to reproduce this issue with both NES and SNES content:

- Which version of Lakka are you using?
2.0

- What system hardware are you using?
RPi3

- What did you do?
Tried to load zipped content.  Selected "load archive".

- What did you expect to happen?
An appropriate core should become available for selection.

- What happened instead?
Several cores become available, but none appropriate for the content.

**Comment by Kivutar** [comment]
OK, what ROM was it?

**Comment by brianblakely** [comment]
Mega Man 2 (US)

Super Mario Kart (US)

no-intro

**Comment by Kivutar** [comment]
You need to do Load Content->Super Mario Kart (US).zip->Browse Archive->Snes9x2010

I checked on my RPi3 and it works as intended, 4 Snes cores appear when I hit Browse Archive

**Comment by brianblakely** [comment]
Browse Archive shows "no items," although there is a single SFC file in the zip.

I've conducted some tests, and this only happens when files are served off of a Windows PC via a Samba mount.  When stored locally in the Lakka device's ROMs folder, it works as expected.  Is this an issue with Samba?

**Comment by Kivutar** [comment]
OK, it's the known SAMBA bug then. Sombody found that it was due to mounting samba shares in read only mode. RetroArch tries to unzip the rom and fails. You need to pass the rw option like that:

    mount -t cifs -o user=guest,rw //{IP}/{SHARE} /storage/roms/samba

You're using a systemd unit to mount?

**Comment by brianblakely** [comment]
Strange, that does not resolve the issue for me.  I am not using systemd.

**Comment by brianblakely** [comment]
I just gave this guide a try: http://www.lakka.tv/doc/Serving-ROMs-from-a-NAS/

Sadly, same result.  Samba-mounted Super Mario Kart zip will not reveal its contents.

**Comment by Kivutar** [comment]
OK, somebody on IRC suceeded one month ago. I'm trying to find who it was to ask for advice.

**Comment by Kivutar** [comment]
Also, let check this page in case you haven't yet https://github.com/libretro/Lakka-LibreELEC/wiki/Serving-ROMs-from-a-NAS

**Comment by brianblakely** [comment]
Those are the same instructions.  On a side note, these instructions do not work as-written.  The first line should read `mkdir /storage/nas` or the systemd unit should be rewritten to use `/storage/roms/nas`.

**Comment by Kivutar** [comment]
Thanks I fixed the docs.

**Comment by RobLoach** [comment]
http://wiki.openelec.tv/index.php/Mounting_network_shares

Use a `/storage/.config/system.d/storage-retroarch.mount` file.

**Comment by Kivutar** [comment]
I think he did. The problem is that even when we mount rw, retroarch can't extract the content. I don't know why.

It's worth testing setting the temporary directory to /tmp

**Comment by Haris1977** [comment]
@brianblakely did y find a solution 4 non - working mame roms? I have the same prob..

**Comment by brianblakely** [comment]
Nope, need to unzip the ROMs.

**Comment by Haris1977** [comment]
I dont have any problem loading snes/nes files. In fact i only have problem in my mame (mame-mame4all) roms. I dont use lakka but retropie (v4.2) but i guess they use the same cores (?). I think it is a permission matter (i use my win7 64bit pc as a server) and i cant load them. I have opened a thread [here](https://retropie.org.uk/forum/topic/14469/success-in-running-roms-from-nas-but-no-mame-roms) trying to get as much help. 

I know it is a different thread here but maybe there are some similarities.

**Comment by Haris1977** [comment]
Well. After some fiddling i was able to play my mame roms through samba:) What did i do? I followed [this](https://github.com/RetroPie/RetroPie-Setup/wiki/Running-ROMs-from-a-Network-Share) - Option 2 - (Option 1 didnt work for me). So it was not a mame core problem but rather a "command" error.

**Comment by ToKe79** [comment]
Editing/modifying /etc/fstab is not possible with Lakka, as the root-fs is read-only (squashfs).

**Comment by ToKe79** [comment]
Is this still an issue? If so, feel free to re-open/post here.
