### ISSUE TITLE
Lakka LibreELEC support for the new ODROID-Go Super by Hardkernel

### ISSUE THREAD

**Issue by Hedda** [libretro/Lakka-LibreELEC#1156]
Hardkernel has announced ODROID-Go Super a few weeks ago and I believe that they offer HW samples to OS developers like you?

https://forum.odroid.com/viewtopic.php?f=187&t=41283&p=315650

OGS (ODROID-Go Super) hardware has the same Rockchip RK3326 internals as the previous OGA (ODROID-Go Advance) variant model but OGS comes with larger 5-inch 16:9 (FWVGA) square-pixel aspect radio screen with 854 x 480 pixels resolution, a higher capacity battery, and the addition of a second analog joystick and dedicated volume buttons.

https://github.com/hardkernel/linux/commits/odroidgoA-4.4.y

https://github.com/hardkernel/u-boot/commits/odroidgoA-v2017.09

OGS (ODROID-Go Super) is already supported in EmuELEC (CoreELEC fork) according to shantigilbert -> https://github.com/EmuELEC/EmuELEC/issues/411

PS: OGS also looks to be an offline device as it is without built-in WiFi but users can temporarily use an external USB WiFi dongle.

**Comment by Ntemis** [comment]
Yes it's time to add support. Thanks for reminding me.

**Comment by h1aji** [comment]
Would be very nice to see Lakka running on OGS @Ntemis

**Comment by h1aji** [comment]
Patches could be ported from this commit: https://github.com/EmuELEC/EmuELEC/commit/8e3f73cbb865b2ddcbfa91949092723d6a93405e

**Comment by h1aji** [comment]
@Ntemis thanks for merging my PR, I have noticed that nightly build failed. Is there any chance to build 
`PROJECT=Rockchip DEVICE=OdroidGoAdvance ARCH=aarch64 make image`
instead of ARCH=arm

Thanks

**Comment by h1aji** [comment]
I have added a few more commits in this PR https://github.com/libretro/Lakka-LibreELEC/pull/1192
This one is going to fix previously broken Rockchip builds

**Comment by davidgfnet** [comment]
This should be now fixed.
Sent an announcement to the odroid forum: https://forum.odroid.com/viewtopic.php?f=193&t=42159
