### ISSUE TITLE
Travado na flor de inicialização com reboot 

### ISSUE THREAD

**Issue by mbmoreira84** [libretro/Lakka-LibreELEC#1161]
- Qual versão do Lakka você está usando?
- não sei, técnico de informática que fez pra mim.
 - Qual hardware de sistema você está usando?
 - PC Linux Dell Inspiron 1525 2gb dualcore
 - O que você fez?
 - Acessar inclusão de emulador
 - O que você esperava que fosse acontecer?
 - abrir pasta de emuladores
 - O que aconteceu em vez disso?
 - travando na flor da inicialização com reboot.

**Comment by Ntemis** [comment]
English please

**Comment by mbmoreira84** [comment]
What version of Lakka are you using?

I don't know, computer technician who did it for me.

What system hardware are you using?

Dell Inspiron 1525 2gb dualcore Linux PC

What did you do?

Access emulator inclusion

What did you expect to happen?

open emulators folder

What happened instead?

locking on the boot flower with reboot.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Ntemis** [comment]
Try this build https://nightly.builds.lakka.tv/2021-01-15/Lakka-Generic.x86_64-3.0-devel-20210115230201-6f20233.img.gz

**Comment by mbmoreira84** [comment]
Thanks.  I give information about the procedure.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by gouchi** [comment]
Hi,

Did you have some opportunity to make some tests otherwise we will close this issue ?

Thank you.

**Comment by mbmoreira84** [comment]
Good Morning.  I haven't had the opportunity to work on fixing the problem yet.  Thanks for listening.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
