### ISSUE TITLE
No Sound / sound muting on nightly build on RPi4

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1177]
Raspberry Pi 4 B 4gb
Lakka: Lakka-RPi4.arm-nightly-20210207-c96c51a

I have not tested all cores but so far the N64 Mupen does not have sound and of course when I went to test the other core it did not function or launch the game. Another core where I notice that sound was being muted or more like skipped is in the Dreamcast core FLycast.  Desmune did not have any sound when launching roms, I need further testing to see if Desmune 2015 has sound skipping/muting.

Edit- I just updated it manually by placing Lakka-RPi4.arm-nightly-20210211-e537c5b.img in the .update folder. I tested DesMune off the bat to see that it still has no sound.  Is it more appropriate to post bugs from nightly builds here on this github or in that discord server for Lakka?

Edit 2- Updated again manually with nightly build Lakka-RPi4.arm-nightly-20210212-b996abe.img only to have it still have the same audio muting on cores. I also see that there was muting on a Sega Genesis core as well which was discoverable by playing more than 6 minutes.

Edit3- Another manual update to arm nightly Feb 13,2020 still had noise issues.

Update 4: updated some of the replies also tested nightly build Lakka-RPi4.arm-nightly-20210310-6c07e38

**Comment by gouchi** [comment]
Uncomment/add `hdmi_drive=2` to `config.txt` does not help ?

[Source](http://www.lakka.tv/doc/Raspberry-Pi/#audio-not-working-on-some-tvs)

**Comment by Rstation4** [comment]
I ended up wiping that sd card and reinstalling a newer nightly, I haven't fiddled to much on games but on RPG Maker there are instances of sound muting/ sound cutting off. I may have heard a tiny fraction of the sound being temporarily cut/muted on another core, but I will not be able to continue today or maybe tomorrow to test that out since I gave that unit away to introduce someone to Lakka and emulation. I will have to hear from that person if there was any additional problems.

Maybe unrelated but I was getting a error on Yume Nikki english (uboachan fan translation ver) where it will freeze everything and needed a forced powering off the RPI4b.

**Comment by gouchi** [comment]
So at the end did you succeed to have sound working ? You have this sound issue for all core ?

**Comment by Rstation4** [comment]
I did not get to fully test all the cores before giving away that Raspberry pi 4 setup, I gave it to a relative and they did mention to me later about N64 having no sound. I will ask them about it the next time I see them.

**Comment by Rstation4** [comment]
I went ahead and used another RPi 4B 4gb Unit and used this nightly build **Lakka-RPi4.arm-nightly-20210227-e925215** on it. I noticed on Dreamcast, that the sound will cut off like a hiccup for a short bit. 

On **Desmune** it does not play sound which I tried on two separate roms. But for **Desmune 2015** it does play sound although not perfectly, because it sounds like you do get a sound hiccup once in a while, the second rom that was zipped did not play any sound. Will try with a few more roms later.

**Sega Saturn (Yabuse)**: I get no audio when I was trying out a single rom, a little bit of sound was working on the startup bios logo but that was all.  Rom tested- Keio Flying Squadron 2 (Europe)

N64 **Parrallel** does not work still, and **Mupen** does not have sound. Tested only two roms shortly with these two cores.

**Comment by gouchi** [comment]
So you've got some sound not no sound...

Please check this [documentation](http://www.lakka.tv/doc/Timezone-settings/) for the timezone.

**Comment by Rstation4** [comment]
In some instances there is a bit of sound being temporarily muted. I have more logs from another core.
[retroarch DC and Psx SM.log](https://github.com/libretro/Lakka-LibreELEC/files/6086619/retroarch.DC.and.Psx.SM.log)

I have also encountered in that particular psx rom that the menu screen input does not work or allow me to get past the menu, similar to "The Legend of Mana" rom. While testing a rom a psx rom after that one at a later time I was experiencing audio issues again.

**Comment by Rstation4** [comment]
I just used the new nightly build and it still has the same persistent no sound/sound muting bug. Several cores still affected by this.
Lakka-RPi4.arm-nightly-20210312-2e60af4

**Comment by Rstation4** [comment]
This is a very short 3 second clip of lagging and sound mutting/hiccups on the PPSSPP core.

https://user-images.githubusercontent.com/73009731/111112448-1623e700-8558-11eb-918a-4e7ae3f9eaa6.mp4

Since Ive been on this issue it varies by core and rom. Some roms will get to a particular part till you hear a sound issue. 

https://user-images.githubusercontent.com/73009731/111112950-ede8b800-8558-11eb-8a91-c605b3a7a41c.mp4

**Comment by Rstation4** [comment]
Used the latest nightly build for RPI4 and there's still that audio issue. Only core I tested so far was Dreamcast's Flycast core.

**Comment by dmrlawson** [comment]
I've found changing the audio driver to `alsathread` solves this for me. If it works for others I suggest we set that as default

**Comment by Rstation4** [comment]
In the past few nightly builds before I moved on to the stable release I have not heard any audio issues. Should we considered this issue fixed and closed?

**Comment by dmrlawson** [comment]
Sounds good to me
