### ISSUE TITLE
[Wiki] SSH access does not mention enabling SSH in Lakka

### ISSUE THREAD

**Issue by brianblakely** [libretro/Lakka-LibreELEC#118]
https://github.com/libretro/Lakka-LibreELEC/wiki/Accessing-Lakka-command-line-interface

Recently made a fresh 2.0 install. I spent about 30 minutes trying to figure out why I couldn't SSH into it before I noticed the option under **Settings->Services**

**Comment by Kivutar** [comment]
Thanks, I updated the doc.
