### ISSUE TITLE
Audio issues on Raspberry Pi 4

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1183]
Raspberry Pi 4 B 4gb
Lakka: Lakka-RPi4.arm-nightly2021_02_20

Still reoccurring problem that started once I updated the nightly build to another nightly build. No clean install, it was a manual update by placing the updated image in the .update folder.  N64 core still no audio, Dreamcast core has audio that cuts out after a short amount of being run.

Issue has still persisted for several nightly builds. Did the update process break something? Did it change settings? What is the difference of the RPi4 aarch64 versions?

This is why i request we have proper documentation, I am no programmer so I when something gets broken or changed I wouldn't know how to fix it. Libretro lakka forums seem dead as well when it comes to troubleshooting, so I may not hear a answer from there for quite a while.

Audio settings-
Audio: on
Audio: alsa
Device: default:CARD=vc4hdmi
Audio Latency (ms): 64

What are the best settings for a 4gb rpi4b? I see multiple devices listed on audio:
default
sysdefault
default:CARD=vc4hdmi
sysdefault:CARD=vc4hdmi
hdmi:CARD=vc4hdmi,DEV=0
default:CARD=vc4hdmi1
sysdefault:CARD=vc4hdmi1
hdmi:CARD=vc4hdmi1,DEV=0
null

Does audio output fucntion on the 3.5mm output port?

**Comment by gouchi** [comment]
Hi,

Please open one issue per subject as you already opened an issue about [sound issue](https://github.com/libretro/Lakka-LibreELEC/issues/1177).

Thank you.

Kind regards,
