### ISSUE TITLE
Gamecon module is not enabled in the latest Lakka x86_64 version(Lakka (official): devel-20200902003240-291d416 (Generic.x86_64))

### ISSUE THREAD

**Issue by BDJoe360** [libretro/Lakka-LibreELEC#1185]
This issue tracker is NOT for help or support. Please use the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general) or IRC @ #lakka on freenode.net for those kinds of posts.

BEFORE you report a bug make sure you have tried the latest nightly version of Lakka at http://le.builds.lakka.tv/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
- What system hardware are you using?
- What did you do?
- What did you expect to happen?
- What happened instead?

It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at http://www.lakka.tv/doc/Troubleshooting-Lakka/

Please delete this text before posting.

**Comment by gouchi** [comment]
Hi,

Can you make a test with this  [image](https://we.tl/t-zMeduF3Dno) ?

Thank you.

Kind regards,

**Comment by BDJoe360** [comment]
Hi, Gouchi
Thank you for your letter and test file.
I tested the file in an upgrade way,The good news is:
After checking with putty, you can see that gamecon module has taken effect：



But now there is another, more serious problem
The system just passed this screen when it started：









And then it's stuck in this picture:




And the old file will not restore the system to normal
The hash value and log of your file are attached here. I hope you can solve this problem






Thank you.

Kind regards！

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "libretro/Lakka-LibreELEC"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 凌晨4:22
收件人:&nbsp;"libretro/Lakka-LibreELEC"<Lakka-LibreELEC@noreply.github.com&gt;;
抄送:&nbsp;"穷凶极恶"<395140560@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [libretro/Lakka-LibreELEC] Gamecon module is not enabled in the latest Lakka x86_64 version(Lakka (official): devel-20200902003240-291d416 (Generic.x86_64)) (#1185)





 
Hi,
 
Can you make a test with this  image ?
 
Thank you.
 
Kind regards,

**Comment by gouchi** [comment]
I am glad gamcon module is working.

It seems the screenshots are missing.
