### ISSUE TITLE
Graphical system glitch on PPSSPP core (Raspberry Pi 4)

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1198]
Raspberry pi 4 B 4gb
Lakka Nightly rpi4 arm feb-27 2021

This rom was getting this graphical error. I also included a performance counter log. I have the logs set to debug and timestamp so not all is lost upon freezing and I can copy and paste them to my pc. Does the performance counter logs help out or are they kinda worthless to post?

![Disgaea Infinite (USA) (v1 01) ](https://user-images.githubusercontent.com/73009731/110549329-cf825700-8129-11eb-86ef-5d9bba51cec5.png)

PPSSPP Log:
[PPSSPP run.log](https://github.com/libretro/Lakka-LibreELEC/files/6111858/PPSSPP.run.log)

Performance Log: 
[Performance Counter log.log](https://github.com/libretro/Lakka-LibreELEC/files/6111861/Performance.Counter.log.log)

**Comment by Ntemis** [comment]
Please test 3.1 release

**Comment by ToKe79** [comment]
To me this looks like issue with ppsspp-assets, which should be already included in the image, but adding them to `/storage/system` may cause an issue. Please check if you have the ppsspp-assets (iirc folder name `PPSSPP`) in `/storage/system` and if so, remove/rename the folder, reboot and try again. If the issue persists, please comment/re-open. Thank you!
