### ISSUE TITLE
Duckstation graphical glitch (RPi 4B)

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1199]
Raspberry Pi 4 b 4gb
Nightly Lakka build rpi4 arm  2021 February(02) - 27

Duckstation has some graphical issues. For some reason this rom just like the Legend of Mana does not let you get past the menu screen with the other ps1 core (PCSX-ReARMed).

[retroarch DC and Psx SM.log](https://github.com/libretro/Lakka-LibreELEC/files/6111883/retroarch.DC.and.Psx.SM.log)

Graphic glitch screenshots:
![Silhouette Mirage (USA)](https://user-images.githubusercontent.com/73009731/110550245-348a7c80-812b-11eb-9218-f22030f44038.png)

![Silhouette Mirage (USA) g2](https://user-images.githubusercontent.com/73009731/110550255-38b69a00-812b-11eb-8f84-cbebd3ac8b6f.png)

**Comment by Ntemis** [comment]
Please test 3.1 release
