### ISSUE TITLE
Shaders failed to load and slowdowns occurring RPI4

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1200]
Raspberry pi 4b 4gb
lakka version: Lakka-RPi4.arm-nightly-20210310-6c07e38

Some of the shaders are failing to load and some are causing retroarch to slowdown and lag.

Logs: 
[Shaders log rpi4.log](https://github.com/libretro/Lakka-LibreELEC/files/6114290/Shaders.log.rpi4.log)

Update 1: I now ran a clean install on my RPI4 unit and it has Lakka 3.0 RPI4 stable on it. Some shaders fail to load and others still slow the system done to  a crawl. I was wondering if some of these will be removed on Raspberry Pi images in future builds.

**Comment by Ntemis** [comment]
Please test 3.1 release
