### ISSUE TITLE
Bsnes Screenshot corruption

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1204]
Raspberry Pi 4B 4gb
Lakka Version: Lakka-RPi4.arm-nightly-20210310-6c07e38

Tried 3 separate
![Killer Instinct-Bsnes core scs](https://user-images.githubusercontent.com/73009731/110790158-98668f80-8268-11eb-9dea-60e57a84d0a2.png)
 roms with Bsnes, the results were the same.

**Comment by Ntemis** [comment]
Hardware limitation of the gpu as Raspberry Pi 4 V3D Driver  only supports OpenGL ES 3.1 where an rk3288 as tinkerboard which is 6 years old supports OpenGL ES 3.2
