### ISSUE TITLE
Background image display corruption RPi 4 

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#1212]
Raspberry pi 4 B 4gb
Lakka Nightly build:

I've only tested this out on nightly builds, I do see a pattern on more complex wallpapers are showing pixels or not displaying the image right. 

Update 1: Lakka Version 3.6 still has this issue

Default image
![Arcade Wallpaper](https://user-images.githubusercontent.com/73009731/111141823-e1c22200-857b-11eb-90c6-9a085d3969df.jpg)

Screenshot
![wallpaper pixelation](https://user-images.githubusercontent.com/73009731/111141850-e8509980-857b-11eb-87ef-808eaea074d1.png)

Update: I tried a few others in jpg and png formats as well as 1920x1080 and 1400x900 resolution images and some of them just end up with pixel bugs. Did more trial and error and saw that none of the png files were affected, the ones that were are jpg files.

**Comment by ToKe79** [comment]
The original image is 1440x1080 so the corruption may come from resizing the image. Have you tried using the image with regular RetroArch (not Lakka), if the corruption appears as well?

**Comment by Rstation4** [comment]
Ill try that later today, I currently dont have Retroarch installed on my Linux build on my PC.

**Comment by DevilBlackDeath** [comment]
Had a similar issue. Have you by chance tried converting your image to png (if it isn't already this format), personally it helped !

**Comment by Rstation4** [comment]
Raspberry Pi 4 (2gb)
RPi4 -arm-devel-20210520 
Before some of them that were converted did have issues as well.  I retested with 2 images that were jpeg  and converted them via Pix to .png at level 9 compression.

Jpeg Version (Original version) 1920x1080
![Lakka OS Wallpaper jpg 1920x1080](https://user-images.githubusercontent.com/73009731/119320542-8de55080-bc30-11eb-94bf-72c4fcf8e651.png)

Png converted version (Level 9 Compression) 1920x1080
![Lakka OS Wallpaper png 1920x1080 ](https://user-images.githubusercontent.com/73009731/119320657-ab1a1f00-bc30-11eb-9a4c-3f7ae03c407a.png)

**Comment by dmrlawson** [comment]
Is it possible this image is relying on transparency (which jpeg does not support)?

**Comment by DevilBlackDeath** [comment]
@dmrlawson Personally I tested it with around 10 wallpapers that were originally jpeg and had no issues at all on my desktop computer and had the same issue. Converting them to png solved the issue as well. There's something happening with jpeg's display code but I wouldn't be able to say what (though it's clearly around "borders" so probably something related to jpeg's compression).

**Comment by dmrlawson** [comment]
> @dmrlawson Personally I tested it with around 10 wallpapers that were originally jpeg and had no issues at all on my desktop computer and had the same issue. Converting them to png solved the issue as well. There's something happening with jpeg's display code but I wouldn't be able to say what (though it's clearly around "borders" so probably something related to jpeg's compression).

Ok, do you have a link to one of the images? On your desktop pc were you using Lakka or just retroarch (on windows? Linux?)

**Comment by DevilBlackDeath** [comment]
One of these was that one : https://i.redd.it/g71062xwmsz51.jpg
Also, by working on my computer, I meant as images and normal wallpaper, not Retroarch's wallpaper. Though I did just test on Retroarch and it worked just fine.

**Comment by dmrlawson** [comment]
OK, I can reproduce. Will investigate

**Comment by Rstation4** [comment]
On Lakka 3.3 aarch64 stable version for the RPi 4 I still get that image issue. That image used as a background is a jpg file.

Screenshot:
![Lakka 3 3 xmb jpeg](https://user-images.githubusercontent.com/73009731/128136731-ba8d5ebb-6f5e-48f1-93c3-986759d10eba.png)

**Comment by dmrlawson** [comment]
Really not sure where to go with this.

@Ntemis would you mind trying this on a different device? I can reproduce in Lakka on rpi4 it's fine on Retroarch on my laptop. I suspect it's to do with how Retroarch decodes jpegs but I'm clueless as to whether it might be using the graphics driver for that.

**Comment by Rstation4** [comment]
As for the new Lakka OS aarch64 3.5.2 Stable branch jpeg background images still show up incorrectly. (tested on a Full HD tv, with a Raspberry Pi 4 model B 4GB Ram hardware).
