### ISSUE TITLE
Feature request - allow SD card file transfer

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/Lakka-LibreELEC#125]
I don't know if this is feasible or not, but right now with a working Lakka system (for example Raspberry Pi) if you access the SD card on a PC (like via Windows) the only partition that appears is the small boot partition. 

It is not possible to copy roms, etc directly to the SD card easily (must be done through network).

Alternatively (as a workaround), are there any good cross platform tools to access the partition with roms?

**Comment by Kivutar** [comment]
Yes, they are listed in the documentation: https://github.com/libretro/Lakka-LibreELEC/wiki/Accessing-Lakka-filesystem#direct-drive-access

**Comment by Mr-Jake** [comment]
@Kivutar

For Windows users that want to access the SD card to manage roms, would it would work to use partition software to shrink the Lakka ext4 partition and then create a new FAT or NTFS partition to use for the folders roms / savefiles / savestates / screenshots / system / playlists ....... etc?

**Comment by Kivutar** [comment]
I'm not sure, you can try.

**Comment by Ntemis** [comment]
Its because the other partition is ext4 you need linux os or a special app
on windows and maybe macos

Στις 13 Μαΐ 2017 7:11 μ.μ., ο χρήστης "Jean-André Santoni" <
notifications@github.com> έγραψε:

**Comment by Kivutar** [comment]
I close this, we can't deviate from LibreELEC that much.
