### ISSUE TITLE
Add Snes9x core to RPi

### ISSUE THREAD

**Issue by TwoToneEddy** [libretro/Lakka-LibreELEC#1253]
Hi,
Is it possible to add another core? I have the Snes9x core on my ambernic351p and I would like the same core on my lakka install on my raspberry pi. The reason for this is I would like to be able to use the same save states.
Thanks

**Comment by ToKe79** [comment]
snes9x core is shipped with Lakka, except for RPi0/1 (probably due to lack of performance) - at least in [Lakka development/nightly builds](https://nightly.builds.lakka.tv/).

**Comment by gouchi** [comment]
I am not sure if [libretro supafaust core](https://github.com/libretro/supafaust) will help for RPi0/1.

**Comment by gouchi** [comment]
@TwoToneEddy if you are not talking about RPi0/1 please close this issue.

Thank you.
