### ISSUE TITLE
ParaLLEl-n64 - CXD4 RSP plugin crashes RetroArch on AArch64 RPi4

### ISSUE THREAD

**Issue by autofire372** [libretro/Lakka-LibreELEC#1256]
Lakka version: latest AAarch64 nightly
Hardware: Raspberry Pi 4

Attempting to run any game with the parallel-n64 core with the cxd4 rsp plugin active causes RetroArch to crash with the following error, rendering use of the angrylion and parallel gfx plugins impossible:

`[libretro ERROR] mupen64plus: Compile at bogus memory address: a4001550`

This error was captured by adding `retroarch=0` to cmdline.txt, then SSHing into Lakka and running `retroarch -v`.

**Comment by Ntemis** [comment]
@dmrlawson is Rpi4 up to specs for this core?

**Comment by dmrlawson** [comment]
I'd say not. It barely performs with HLE and these are all LLE plugins.

It'd be nice if it didn't crash though. One thing to note is that parallel-rdp (the vulkan plugin) requires Vulkan 1.1 whereas we only have 1.0 on rpi4 so far, so there's no chance of this working atm.

**Comment by autofire372** [comment]
I admit I was trying parellel-n64 out of desperation, as mupen-next has suffered severe performance regressions (as noted in #1232) that render even Super Mario 64 unplayable, when that core used to allow rpi4 to handle anything that wasn't Goldeneye or Perfect Dark.
