### ISSUE TITLE
[Feature Request] Option to eject the optical drive

### ISSUE THREAD

**Issue by tiagolascasas** [libretro/Lakka-LibreELEC#1261]
Hi, I have a bit of an odd request...

I'm using Lakka on an x86_64-based PC with an optical drive. It works fine with the latest version of Lakka, but unfortunately my optical drive is really old and the eject button does not work, which requires me to eject it through software (on Windows, for example, this would be done by right-clicking the drive and clicking "Eject"). 

On Lakka, though, the only way of doing this is to ssh into the machine and type in the `eject` command, which is really inconvenient. It'd be nice if there was an extra option to eject it through Lakka itself, maybe alongside the "Load Disc" and "Dump Disc" options. I know this would probably be a super low priority QoL improvement for you guys, but still, it'd solve my problem.

Thanks in advance!

**Comment by ToKe79** [comment]
Hi,
can you test image from [here](https://nightly.builds.lakka.tv/members/vudiq/Generic.x86_64-EJECT/) if [this](https://github.com/ToKe79/RetroArch/commit/314727456586122a13ef9bdc3e4baeacd48f5b21) implementation works?
Thank you!

**Comment by gouchi** [comment]
I confirm it is working ;)
