### ISSUE TITLE
Can‘t load roms from NAS storage

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#1269]
I can't load roms from nas anymore since 0078a9d. I am guessing the whole network stack and cifs have been updated and a bug was introduced. Everything works fine if I try to access the files from other platforms, so it is a Lakka issue.

**Comment by Ntemis** [comment]
There is nothing there that could interfere on how samba works. Its just a bunch of core updates

**Comment by coldspark29** [comment]
Okay, let me install an older version and try to exclude Lakka from the equation

**Comment by coldspark29** [comment]
Works again. Guess I just misconfigured something.
