### ISSUE TITLE
SMB CIFS v3 share not mounting on Lakka filesystem

### ISSUE THREAD

**Issue by wisewtf** [libretro/Lakka-LibreELEC#1281]
This is not a bug report but a suggestion to implement information on the official documentation here:  https://www.lakka.tv/doc/Serving-ROMs-from-a-NAS/

In my particular system and with my particular SMB share (residing on a Ubuntu ARM installation) I couldn't mount the share on the Lakka filesystem (Residing on an RPi3) as I was getting `operation not permitted` and I noticed the systemd service missed an option argument `vers=3.0` for people using CIFS ver 3.0.

So if anyone's got this problem (meaning they are using CIFS ver 3.0) they must add this option resulting with the following systemd mount service:

```
# /storage/.config/system.d/storage-roms-nas.mount
[Unit]
Description=cifs mount script
Requires=network-online.service
After=network-online.service
Before=retroarch.service

[Mount]
What=//share/
Where=/storage/roms/nas
Options=username=user,vers=3.0,password=password
Type=cifs

[Install]
WantedBy=multi-user.target
```

I would recommend adding this information to the documentation. I would've done it myself I just have no idea how to.
Thank you.

**Comment by ToKe79** [comment]
updated the wiki, documentation on lakka.tv will be updated with next update of the web page
