### ISSUE TITLE
no sound/mouse on chromebook lenovo 500e

### ISSUE THREAD

**Issue by hugyry** [libretro/Lakka-LibreELEC#1285]
is it a out put problem like on pi 4

**Comment by gouchi** [comment]
As described in the [issue template](https://github.com/libretro/Lakka-LibreELEC/blob/master/ISSUE_TEMPLATE.md), please try to provide some [logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/) at least `audio` and `dmesg` log.

Thank you.

**Comment by Ntemis** [comment]
no response closing down
