### ISSUE TITLE
dolphin emu running mario kart wii could not write to/read from wii system memory

### ISSUE THREAD

**Issue by hugyry** [libretro/Lakka-LibreELEC#1295]
https://www.reddit.com/r/RetroArch/comments/a09qri/could_not_write_toread_from_wii_system_memory/
exsplain some but i know how to fix it 
1. go to dolphin repo
2. in your lakka make a folder in /system/ named dolphin-emu
3. in the repo of dolphin download the zip and open it
4. go into the data folder and copy sys
5. and put it in the /system/dolphin-emu/
6. just run lakka and it should work

**Comment by ToKe79** [comment]
should be fixed with c1e52a057d7dfb874e09e5c59dc54b9f34a0f2bc
