### ISSUE TITLE
Can beetle-saturn be re-added as a core?

### ISSUE THREAD

**Issue by Mr-Jake** [libretro/Lakka-LibreELEC#1309]
The core cleanup commit on March 25, 2021 dropped the beetle-saturn core from Lakka. This was a surprise because even though beetle-saturn has not been updated in a while, it has much better compatibility and performance compared to Kronos, especially for PC Generic x86_64.

I saw the recent commit that increased the partition size from 512mb to 2gb. If there is extra space now, could beetle-saturn be re-added even if only for Generic x86_64?

**Comment by Ntemis** [comment]
Did you try yabasanshiro?

**Comment by Mr-Jake** [comment]
I did not try yabasanshiro because I thought Kronos was an updated improved fork of it.

I may just be more of a fan of the beetle-saturn core. I could always just manually grab it from the buildbot and copy it to core folder in Lakka.
