### ISSUE TITLE
Lakka-RPi4.aarch64-nightly builds not booting since 2021-04-26

### ISSUE THREAD

**Issue by DutchDude69** [libretro/Lakka-LibreELEC#1313]
Hi,

I did not find any related issue report yet, so I thought I mention it here.

Since April 26 I noticed the RPI4 64bit Nightly builds are no longer usable.
The packed size decreased to 11M (normally around 430M). And trying the build to boot is failing with a mounting error.
The last booting/working RPI4 64bit build I found is from April 23.

If this was already known just close this issue report ;-)

BR

**Comment by ToKe79** [comment]
This was addressed - the FAT32 partition was too small to include the system, partition was size increased to 2GB.
