### ISSUE TITLE
Atomiswave Gets Stuck on System Settings Menu (RPI4) (Flycast)

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1328]
Raspberry Pi 4 2gb
Lakka Nightly Version for RPI 4

I already tried this with a different awbios.zip but it still happens when I try to exit the system settings menu. I tried this with another rom as well with the same result of it freezing up Lakka OS when I try to close the rom. 

 Why does the "Allow Naomi Service Buttons" option need to be enabled to use Atomiswave System Settings? I wasn't able to do so unless I enabled that in the menu
 
 Logs:
 
[Atomiswave lakka os.log](https://github.com/libretro/Lakka-LibreELEC/files/6530886/Atomiswave.lakka.os.log)
[Atomiswave peformance mark.log](https://github.com/libretro/Lakka-LibreELEC/files/6530887/Atomiswave.peformance.mark.log)

 image:
![Atomiswave system menu](https://user-images.githubusercontent.com/73009731/119319491-5fb34100-bc2f-11eb-9125-bc64cdea55e4.png)

**Comment by gouchi** [comment]
Hi,

You did try to use L3 (Test) and R3 (Service) ?

**Comment by Rstation4** [comment]
Yes I did, while the rom ends up freezing when you try to exit, the whole Lakka OS will freeze when you try then try to close it via close content.

**Comment by Rstation4** [comment]
@gouchi I moved on to the Lakka OS 3.0 Stable Release and something there fixed. It has not happend since then, though I have only tested it on 4 roms. Should this issue be considered fixed and closed?

**Comment by ToKe79** [comment]
please reopen when needed
