### ISSUE TITLE
Pinebook Pro image request

### ISSUE THREAD

**Issue by ura43** [libretro/Lakka-LibreELEC#1338]
Hi, I have recently discovered that you already package and maintain an image for the rockpro64. Since the pinebook pro is really just a rockpro64 with a screen and in a laptop form factor, Lakka should be very easy to port and the addition should cause little to no maintenance overhead

**Comment by Ntemis** [comment]
We require someone of the team to own one so we can test and fix reported issues.
No one likes blind fixing
