### ISSUE TITLE
Lakka 3.0. Orangepi plus2e. Wifi doesn't work.

### ISSUE THREAD

**Issue by zarkon0** [libretro/Lakka-LibreELEC#1340]
With lakka v. 3.0 wifi doesn't work in Orangepi plus 2e.
The wifi doesnt find any network.

**Comment by davidgfnet** [comment]
Do you know how to ssh into your device?
Could you please check whether the wifi works on Linux? 
You could run "ifconfig -a" and check whether there's a wifi interface. That could help to udnerstand whether we have a Linux issue or a Retroarch issue.
Also dmesg and "lsusb" outputs would help.
Thanks!

**Comment by ToKe79** [comment]
Hi @zarkon0,
can you check community image from [here](https://nightly.builds.lakka.tv/members/vudiq/Lakka-LE_master/H3.arm/)?
It is based on LibreELEC master branch, Lakka 3.0 is based on the LE9.2 branch.

**Comment by zarkon0** [comment]
Hi.

I can't connect with ssh because I can't connect with ethernet wire.
Can I acess to linux console stand alone in lakka?

I'm to try a nightly build.

Thanks.

**Comment by zarkon0** [comment]
Hi again.

I've install Lakka-H3.arm-LE_master-devel-20210530212829-152e433-orangepi-plus2e.img.gz and the wifi doesnt' work.

The menu shows the driver connmanctl but if I press the button to change only null appears and the item connmanctl doesn`t
show checked.

This happens in 3.0 and nighty versions.

**Comment by ToKe79** [comment]
Can you test an image from LE directly - https://test.libreelec.tv/.
If it does not work, you have to check for issue / open new issue in their repo.

**Comment by diegohvanni** [comment]
I have a similar problem with Orange pi lite. The wireless module works properly on Lakka 2.3.1, retrorangepi and armbian.

**Comment by Ntemis** [comment]
RTL8189ETV is not supported yet by any kernel.
