### ISSUE TITLE
Lakka 3.0 on XU4 not booting after initial boot

### ISSUE THREAD

**Issue by poetzmij** [libretro/Lakka-LibreELEC#1353]
I'm attempting to clean install 3.0 or nightly 20210530 on my XU4. Tried writing images to emmc or SD and both produce same results. I expect to see the splash, then the restart after partitions are worked, and finally the UI. It boots up, seems to do work on partitions and restarts, however, never reaches UI, boot seems stuck.

**Comment by Ntemis** [comment]
ow ok i will have a look soon. Thank you for the report.

**Comment by Ntemis** [comment]
@poetzmij can you test the 3.1 release
