### ISSUE TITLE
lakka 3.0 Chinese display problem

### ISSUE THREAD

**Issue by root-pi** [libretro/Lakka-LibreELEC#1354]
I installed version 3.0 of Lakka on the Raspberry Pi 3B+ and selected Chinese as the language, but the Chinese display was incomplete.Some words show squares.The more fatal problem was that after I rebooted the system.They all appear as squares and don't show any characters.Could you please fix the Chinese display error when updating the version?Thanks a million!

**Comment by gouchi** [comment]
Hi,

Did you change the font in between your actions ?

As it seems it causes an [issue](https://github.com/libretro/RetroArch/issues/12215).

**Comment by root-pi** [comment]
> 你好，
> 
> 它可能与这个[问题有关](https://github.com/libretro/RetroArch/issues/12215)？

Thanks for your reply.Yes, I'm using Lakka 3.0 exactly like this one.X MB theme.The Chinese display problem remains unresolved.Please also fix this problem when you update the version.Thanks again!

**Comment by root-pi** [comment]
> 你好，
> 
> 它可能与这个[问题有关](https://github.com/libretro/RetroArch/issues/12215)？

Thanks for your reply.Yes, I'm using Lakka 3.0 exactly like this one.X MB theme.The Chinese display problem remains unresolved.Please also fix this problem when you update the version.Thanks again!

**Comment by ToKe79** [comment]
can you please test with [latest nightly build](https://nightly.builds.lakka.tv/latest/)?

**Comment by atlus666** [comment]
hi , this problem can be fix
because the theme default font not support chinese 
you can upload any chinese font (ex: TaipeiSansTCBeta-Bold.ttf) to your lakka
first change the theme font to your font 
and change system language you will see the complete chinese menu

**Comment by root-pi** [comment]
> 你能用[最新的每晚构建](https://nightly.builds.lakka.tv/latest/)测试吗？

I'm sorry to see that the problem I tested in version 3.2 still exists, and the system font can be displayed normally after replacing it with Yahei, but after rebooting it, it all becomes a block and does not display any characters.

**Comment by root-pi** [comment]
> hi , this problem can be fix
> because the theme default font not support chinese
> you can upload any chinese font (ex: TaipeiSansTCBeta-Bold.ttf) to your lakka
> first change the theme font to your font
> and change system language you will see the complete chinese menu

I have tried, is replaced by other font can be completely displayed.But if you reboot all the characters become squares.No substantive solution to the problem

**Comment by Zalica** [comment]
I'm Chinese user and I have similar problem. 
In lakka 3.2, the rgui can display chinese font,althought it's not quite a pleasure sight. 
The xmb  glui  an ozone just can't display Chinese font by default.

**Comment by root-pi** [comment]
是的。现在没有改过来。按照网上教程替换字体可以正常显示中文了。但是重启后显示的都是一个个小方块，一个中文都没有。






------------------ 原始邮件 ------------------
发件人:                                                                                                                         "libretro/Lakka-LibreELEC" ***@***.***&gt;;
发送时间: &nbsp;2021年6月30日(星期三)下午5:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: &nbsp;Re: [libretro/Lakka-LibreELEC] lakka 3.0 Chinese display problem (#1354)





 
I'm Chinese user and I have similar problem. 
 In lakka 3.2, the rgui can display chinese font,althought it's not quite a pleasure sight. 
 The xmb glui an ozone just can't display Chinese font by default.

**Comment by gouchi** [comment]
I did bisect and the first bad commit is [[8132303d4f9400e0a37051a4f7b43e26c6eb958e](https://github.com/libretro/RetroArch/commit/8132303d4f9400e0a37051a4f7b43e26c6eb958e)] (FontRenderer/FreeType) Use fontconfig to select fonts if available.

**Comment by ToKe79** [comment]
Possible workaround for XMB menu is to download a font that has all the required glyphs and store it somewhere in the /storage partition. Then in RetroArch navigate to `Settings` -> `User Interface` - `Appearance` -> `Menu Font` -> locate the font you want to use. From this point that font will be used even after reboot/restart. Maybe changing the theme will reset to theme font, so this steps have to be reproduced again to display the characters correctly again.
Note: If you do not see Menu Font item, activate `Show Advanced Settings` in `Settings` -> `User Interface`.

**Comment by linlinio** [comment]
I use the l4t 3.2 (Nintendo switch) version.i guess that lakka loads another ttfs in system starting.so i find to change files which locate at ”\usr\share\fonts\liberation\LiberationMono-Bold.ttf" and "\usr\share\fonts\liberation\LiberationMono-regular.ttf".and also replace ttfs under ozone.Then issue is resolved.
