### ISSUE TITLE
lakka 3.0 on pi 400 wifi wont work 

### ISSUE THREAD

**Issue by kellenqian** [libretro/Lakka-LibreELEC#1355]
seems the wifi firmware was not built into the system.

file name is brcmfmac43456-sdio.bin , only brcm/brcmfmac43455-sdio.bin found

**Comment by Ntemis** [comment]
We use the firmware package from rpi github directly, weird.

**Comment by dmrlawson** [comment]
I don't have one to test, but let's try https://github.com/libretro/Lakka-LibreELEC/pull/1378
