### ISSUE TITLE
Computer Module 4 & Lakka 3.0 issue with the USB 2.0

### ISSUE THREAD

**Issue by kelroy1990** [libretro/Lakka-LibreELEC#1358]
Hi guys, i am testing the lakka 3.0 release on the Computer Module 4 and the raspberry pi IO board.

The display and the HDMI its working well as i see the image correctly. But we have a few issue with the USB.

Computer Module 4 has his USB off by default, so we need to use the **dtoverlay=dwc2,dr_mode=host** to activate it. But on Lakka 3.0 it seems to dont have any kind of effect, so i cannot control the SO.

I see that Lakka have the dwc2 overlays on the /boot/overlays.... so i cannot figure where the problem is.

Its somebody testing it like me?.

Next Steps:
-Configure SSH with a pi4 destkop to have internet and test it on the CM4

Regards, Carlos.

**Comment by shawhall** [comment]
Did this get fixed?  I see the issue was closed but no comments were left.

**Comment by Ntemis** [comment]
You didnt update the issue after all the stable releases and no one on the team has the Cm4 so no idea if it was fixed or not but we cant walk blindly. Try v3.2 and let me know though.

**Comment by shawhall** [comment]
Just tried v3.2 today and it does not work.

**Comment by kelroy1990** [comment]
Hi guys, tried to and it does not work. If the lakka team need one, i could send it to they, just contact with me.

I was cheking the kernel build and the dwc2 module seems to be active to compile, i need further work to see where its the fail.

**Comment by dmrlawson** [comment]
Hi, I think this should work now in the latest nightlies if you enable it in distroconfig.txt
