### ISSUE TITLE
issue with korean language setting

### ISSUE THREAD

**Issue by vus7294** [libretro/Lakka-LibreELEC#1362]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? 3.0 stable
- What system hardware are you using? nintendo switch
- What did you do? setting to korean language
- What did you expect to happen? setting normally
- What happened instead? reboot, all font crashes(except latin language) and force to set english

and that's the bottom line.

**Comment by gouchi** [comment]
I reproduced the issue 

- Change language to Korean OK
- Restart RA or reboot KO it displays square.

**Comment by gouchi** [comment]
Maybe related to this [issue](https://github.com/libretro/RetroArch/issues/12215). We may have issue with CJK language.

**Comment by ToKe79** [comment]
can you please test with [latest nightly build](https://nightly.builds.lakka.tv/latest/)?

**Comment by vus7294** [comment]
No. the Bug is still present in latest nightly build.

**Comment by gouchi** [comment]
I did bisect and the first bad commit is [8132303d4f9400e0a37051a4f7b43e26c6eb958e] (FontRenderer/FreeType) Use fontconfig to select fonts if available.

**Comment by ToKe79** [comment]
Please see for possible workaround: https://github.com/libretro/Lakka-LibreELEC/issues/1354#issuecomment-880622077

**Comment by gouchi** [comment]
It will be fixed in Lakka 3.4
