### ISSUE TITLE
[feature request] add duckstation core or replace swanstation → duckstation core

### ISSUE THREAD

**Issue by vus7294** [libretro/Lakka-LibreELEC#1363]
Swanstation is unofficial forked version to optimized for piepacker. but seems duckstation developer doesn't like it and he made original duckstation libretro core to seperate to swanstation.
[Github Link](https://github.com/stenzek/duckstation)
this libretro version is much better performance and supports pbp perfectly. also supports linux and android both. seems like easy to port with l4t.

**Comment by ToKe79** [comment]
Hi, the duckstation-libretro is not open-source, so we cannot build it. We could only download binaries and ship them together with Lakka, but I'm not sure if we want to go this way. You have always the possibility to download the core by yourself and then store it in /system/cores.
