### ISSUE TITLE
No Wii Mote IR settings in latest dolphin core options menu for Lakka on the Nintendo switch. The top image is from the 3.0 release tthe bottom image is from the 2.2 release. Thank you.

### ISSUE THREAD

**Issue by Singledad7** [libretro/Lakka-LibreELEC#1366]
![Wiimote IR](https://user-images.githubusercontent.com/21270740/120542011-35405100-c3b0-11eb-9f60-3a9e07983450.PNG)

**Comment by plaidman** [comment]
nobody has bit on this one @Singledad7. my recommendation would be to add an issue on the libretro dolphin repo and hope someone bites there. https://github.com/libretro/dolphin

**Comment by plaidman** [comment]
Then this issue may be closed.
