### ISSUE TITLE
DSI Display black on Raspberry Pi 3 Model A [Lakka 3.1]

### ISSUE THREAD

**Issue by nsilveri** [libretro/Lakka-LibreELEC#1375]
I tried boot Lakka 3.1 on a RPi 3 A+ with a DSI display, it seems boot but the screen is always black, with previous Lakka 2.x all was working good.

**Comment by SethBarberee** [comment]
Which display is it? If all else doesn't work, try changing `vc4-kms` to `vc4-fkms` and follow the standard configuration in `distroconfig.txt`.

**Comment by nsilveri** [comment]
thanks, i changed vc4-kms to vc4-fkms and it works good.
the screen is this:
https://osoyoo.com/2020/05/29/instruction-for-raspberry-pi-3-5-dsi-touch-screen/
