### ISSUE TITLE
Any estimated date to give compatibility with virtualbox? 

### ISSUE THREAD

**Issue by WHK102** [libretro/Lakka-LibreELEC#1376]
In 2017 says: https://github.com/libretro/Lakka-LibreELEC/issues/66

> Hello, only VMWare is supported **for now**.

Now is 2021, are there any plans to make lakka compatible in generic virtual machines like virtualbox? Is there any development on the way or similar?.

I understand that today there is no support for virtualization but there is no announcement that says if there will finally be a compatible version in the future or will never be made.

**Comment by Ntemis** [comment]
VB support is dropped
