### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by bite-your-idols** [libretro/Lakka-LibreELEC#138]
Hi @Kivutar! Just a little request, could you please create a release point in this repo's releases page for each lakka stable or RC launch? It would be nice for us when compiling lakka ourselves to checkout different history points using release names instead looking through commits. 

For instance 2.0 stable is efa1a8c.

Thanks for your hard work!

**Comment by Kivutar** [comment]
Hi, I pushed my tags to the github repo.
