### ISSUE TITLE
Mupen64 plus next does not open in Lakka 3.1

### ISSUE THREAD

**Issue by Carcharodon** [libretro/Lakka-LibreELEC#1389]
Good afternoon, I would like to report an error that is happening in Mupen64 Plus Next, Lakka 3.1 cannot open any game through this emulator.

**Comment by ToKe79** [comment]
when you open a new issue, the is a template - for a reason. can you be more specific with your issue, e.g. which platform you use?

**Comment by Carcharodon** [comment]
I am using 64bit linux pc version every time I try to use Mupen64 Plus Next the game doesn't load and goes back to the Lakka start menu. This error only occurs with that emulator specifically.

**Comment by ToKe79** [comment]
can you provide more details on your setup and some [logs](https://github.com/libretro/Lakka-LibreELEC/wiki/Troubleshooting-Lakka)?

**Comment by Carcharodon** [comment]
I found the solution, the Mupen64 Plus Next emulator only works if the video driver is set to glcore or vulkan. Now I can play, the strange thing is that in other versions of Lakka there was no such problem.
