### ISSUE TITLE
(Switch) System freezes when trying to connect PS3 controller

### ISSUE THREAD

**Issue by brenodantas10** [libretro/Lakka-LibreELEC#1397]
I'm using Lakka-Switch.aarch64-nightly-20210619-cb6ac9c on my Switch and tried to use my PS3 controller with it by different methods and all of then results in a frozen state that sometimes reboots the Switch.

Methods:
 - USB cable while docked or OTG -> Recognizes Ps3 controller, but it messes with controller configuration when start a game (makes ps3 controller the first without any buttons configured) and freezes when the controller is removed (probably because it tries to connect via bluetooth)
 - Terminal with bluetoothctl (with previous given Switch's mac address to PS3 controller) -> Switch insta-freezes.

I couldn't turn on logging because retroarch just resets when i try to save configuration with logging to file turned on, but i managed to get cached bluetooth information from /storage/.cache/bluetooth folder of my ps3 controller

[bluetooth.zip](https://github.com/libretro/Lakka-LibreELEC/files/6679898/bluetooth.zip)

EDIT: When connecting ps3 controller via usb the Switch gives it's mac-address to the controller successfully. The problem is only when I try to connect it via bluetooth, it just freezes the system when I press PS button without any cable.

**Comment by brenodantas10** [comment]
I don't have any other console controller to test if this problem is PS3 controller only

**Comment by Ntemis** [comment]
@GavinDarkglider

**Comment by GavinDarkglider** [comment]
I have no idea the state of the ps3/ps4 controller driver in the 4.9 kernel that nvidia is using. as for the controller stuff in retroarch in general, I dont have autoconf stuff enabled, as there is no autoconf for linux joycons in retroarch, it only has android joycon support, and I am not sure how to get around that. I am not sure, but I do know xbox 1 controllers need you do disable ertm before they will work, but I have no idea about ps3 controllers. The only controllers I am supporting is the joycons, anything other than that you are on your own.
