### ISSUE TITLE
Lakka 3.2 extend SD card partition error in Raspberry Pi 4 

### ISSUE THREAD

**Issue by atlus666** [libretro/Lakka-LibreELEC#1401]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? =>  Lakka-RPi4.aarch64-nightly-20210621-3da012b
- What system hardware are you using?  => Raspberry Pi 4 4gb + 128 GB SD card
I burn img to SD Card , When the first boot , It resize partition and stop at reboot
It can't reboot
I force reboot it and enter the terminal to show mount
the /storage is still not extend ,but in parted ,the mmcblk0p2 already have 127GB

but this issue not happen in 64gb sd card  , maybe in bigger SD card extend script have problem?

![IMG_20210622_234835](https://user-images.githubusercontent.com/86314787/122964554-f81d1c80-d3b9-11eb-88a7-656076292726.jpg)
It can;t reboot ,Just stop there, but no other message so I don't know what happend in bakground
![IMG_20210622_235432](https://user-images.githubusercontent.com/86314787/122964567-fb180d00-d3b9-11eb-8630-26446557a87d.jpg)
After force reboot  
![IMG_20210622_235857](https://user-images.githubusercontent.com/86314787/122964586-feab9400-d3b9-11eb-8af3-a615c1bf14df.jpg)
/storage only have 27mb
![IMG_20210622_235928](https://user-images.githubusercontent.com/86314787/122964596-01a68480-d3ba-11eb-8c76-4fd605567171.jpg)
![IMG_20210622_235954](https://user-images.githubusercontent.com/86314787/122964615-04a17500-d3ba-11eb-8114-c01508c0a37a.jpg)
in parted , mmblk0p2 have 127gb

**Comment by dmrlawson** [comment]
Do you have a spare 128GB sd card to test?

I have it running on a 128GB sd card but I can't say I've tested it from scratch on it (and I'd really rather not format it)

**Comment by dmrlawson** [comment]
AFAIK this is not a common issue and I suspect the SD card is faulty
