### ISSUE TITLE
NO WIFI  on cubox 3.1 or 3.2

### ISSUE THREAD

**Issue by bluemonkeysuit07** [libretro/Lakka-LibreELEC#1403]
scan for wifi networks fails to identify any network with lakka 3.1 and 3.2 on cubox

**Comment by by-gnome** [comment]
Can you make a `dmesg` log and `connmanctl technologies` output using SSH?
Have you tried previous versions?

**Comment by bluemonkeysuit07** [comment]
[    9.275185] systemd[1]: Condition check resulted in Huge
Pages File System being skipped.
[    9.278646] systemd[1]: Listening on udev Control Socket.
[    9.281112] systemd[1]: Created slice User and Session Sl
ice.
[    9.634969] kernel-overlays-setup: setup base modules
[    9.712744] kernel-overlays-setup: added modules from /us
r/lib/kernel-overlays/base/lib/modules/5.10.35
[    9.834586] kernel-overlays-setup: added firmware from /u
sr/lib/kernel-overlays/base/lib/firmware
[    9.835021] kernel-overlays-setup: adding overlays from /
storage/.cache/kernel-overlays
[    9.843363] kernel-overlays-setup: done
[   10.511272] systemd-journald[274]: Received request to fl
ush runtime journal from PID 1
[   14.532109] coda 2040000.vpu: Firmware code revision: 460
72
[   14.532158] coda 2040000.vpu: Initialized CODA960.
[   14.532177] coda 2040000.vpu: Firmware version: 3.1.1
[   14.536162] coda 2040000.vpu: encoder registered as video
0
[   14.557537] coda 2040000.vpu: decoder registered as video
1
[   14.558531] coda 2040000.vpu: encoder registered as video
2
[   14.560368] coda 2040000.vpu: decoder registered as video
3
[   14.824799] Bluetooth: HCI UART driver ver 2.3
[   14.824834] Bluetooth: HCI UART protocol H4 registered
[   14.825881] Bluetooth: HCI UART protocol Broadcom registe
red
[   14.826158] hci_uart_bcm serial0-0: supply vbat not found
, using dummy regulator
[   14.827774] hci_uart_bcm serial0-0: supply vddio not foun
d, using dummy regulator
[   14.828410] hci_uart_bcm serial0-0: No reset resource, us
ing default baud rate
[   14.870450] rtc-pcf8523 2-0068: low voltage detected, tim
e is unreliable
[   15.228573] Bluetooth: hci0: BCM: chip id 62
[   15.239747] Bluetooth: hci0: BCM: features 0x0f
[   15.264422] Bluetooth: hci0: BCM4330B1
[   15.264466] Bluetooth: hci0: BCM4330B1 (002.001.003) buil
d 0000
[   15.316243] Bluetooth: hci0: BCM4330B1 'brcm/BCM4330B1.hc
d' Patch
[   15.499955] cfg80211: Loading compiled-in X.509 certifica
tes for regulatory database
[   15.621942] cfg80211: Loaded X.509 cert 'sforshee: 00b28d
df47aef9cea7'
[   15.773016] Qualcomm Atheros AR8035 2188000.ethernet-1:04
: attached PHY driver [Qualcomm Atheros AR8035] (mii_bus:phy
_addr=2188000.ethernet-1:04, irq=POLL)
[   15.907547] brcmfmac: brcmf_fw_alloc_request: using brcm/
brcmfmac4330-sdio for chip BCM4330/4
[   15.977101] brcmfmac mmc0:0001:1: Direct firmware load fo
r brcm/brcmfmac4330-sdio.solidrun,cubox-i-q.txt failed with
error -2
[   16.203108] brcmfmac: brcmf_fw_alloc_request: using brcm/
brcmfmac4330-sdio for chip BCM4330/4
[   16.204132] brcmfmac: brcmf_c_process_clm_blob: no clm_bl
ob available (err=-2), device may have limited channels avai
lable
[   16.205598] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BC
M4330/4 wl0: Oct 25 2011 19:34:12 version 5.90.125.104
[   16.361505] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 184
[   16.361542] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 188
[   16.361565] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 192
[   16.361588] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 196
[   16.361613] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 200
[   16.361634] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 204
[   16.361656] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 208
[   16.361679] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 212
[   16.361700] ieee80211 phy0: brcmf_construct_chaninfo: Ign
oring unexpected firmware channel 216
[   17.843105] fec 2188000.ethernet eth0: Link is Up - 100Mb
ps/Full - flow control rx/tx
[   17.843362] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link bec
omes ready
[   18.701293] rtc-pcf8523 2-0068: low voltage detected, tim
e is unreliable
[   18.902596] FAT-fs (sda1): Volume was not properly unmoun
ted. Some data may be corrupt. Please run fsck.
[   18.911292] rc rc0: two consecutive events of type space
[   21.077790] process '/usr/bin/retroarch' started with exe
cutable stack
[   21.988833] Bluetooth: hci0: Win8 Tablet Semco SWB-B42G -
 BCM4330B1 37.4 MHz Class 2 NoExtLNA
[   21.988877] Bluetooth: hci0: BCM4330B1 (002.001.003) buil
d 1316
Lakka:~ # connmanctl technologies
/net/connman/technology/p2p
  Name = P2P
  Type = p2p
  Powered = False
  Connected = False
  Tethering = False
/net/connman/technology/wifi
  Name = WiFi
  Type = wifi
  Powered = True
  Connected = False
  Tethering = False
  TetheringIdentifier = LakkaAccessPoint
  TetheringPassphrase = RetroArch
/net/connman/technology/ethernet
  Name = Wired
  Type = ethernet
  Powered = True
  Connected = True
  Tethering = False
Lakka:~ #

**Comment by by-gnome** [comment]
Forgot to update `brcmfmac sdio-firmware` pakage.
Will be fixed next release or nightly build.
