### ISSUE TITLE
RG351P/M Battery Level Issues on Lakka 3.2

### ISSUE THREAD

**Issue by taquitoboy** [libretro/Lakka-LibreELEC#1407]
- Which version of Lakka are you using?
Lakka 3.2

- What system hardware are you using?
RG351P and RG351M

- What did you do?
Deplete battery, recharge device while the device is powered off until LED indicator is turned off, and check battery levels.

- What did you expect to happen?
Battery level should be 100%.

- What happened instead?
Battery level maxes out at 12% - 13%. While depleting the battery again, it sits at 1% for the longest time.
Occurs on both of my RG351P and RG351M

**Comment by ToKe79** [comment]
refers to discontinued branch, only updates to RetroArch / libretro-cores. As a workaround try using .dtb from 351ELEC.

**Comment by Unix0815** [comment]
> refers to discontinued branch, only updates to RetroArch / libretro-cores. As a workaround try using .dtb from 351ELEC.

I'm using the latest Lakka 3.7 with the 351elec dtb on my rg351p. At first, the battery was showing correct values. But after charging the device over night, it maxes out at 31%, even though the battery should be fully charged.

Any fix for this behavior? Where can I download the 4.0 release for the rg351p?

**Comment by Unix0815** [comment]
Will this ever be fixed?

**Comment by Ntemis** [comment]
not on 3.2 for sure
