### ISSUE TITLE
GPi 2.3.2 - can't upgrade

### ISSUE THREAD

**Issue by acranglesim** [libretro/Lakka-LibreELEC#1417]
Hi,

I have tried downloading the latest 3.2 image (img.gz) and placing it in upgrade folder. When it reboots it says it is incompatible with my 2.3.2 installation.

I have ssh'd on, and tried running lakka-update which returns:
```
Lakka (official): 2.3.2 (RPi.GPICase.arm)
Lakka:~ # lakka-update
wget: server returned error: HTTP/1.1 404 Not Found
:: Downloading upgrade
Connecting to le.builds.lakka.tv (195.201.56.250:80)
wget: server returned error: HTTP/1.1 404 Not Found
:: Done, you can now reboot
```

Is my only option to backup my savestates, save files, and ROMs, and then reflash the card?

**Comment by Ntemis** [comment]
Please read the release notes of stable release.
