### ISSUE TITLE
Raspberry Pi2 + Netgear Wifi Dongle : No SSID detected (works with Raspbian / Raspberry Pi OS)

### ISSUE THREAD

**Issue by leskenazi** [libretro/Lakka-LibreELEC#1418]
- Which version of Lakka are you using?
Lakka-RPi2.arm-nightly-20210705-857b254
- What system hardware are you using?
Raspberry Pi2 + Netgear Wifi Dongle
- What did you do?
Tried to list wifi networks available
- What did you expect to happen?
List of SSIDs
- What happened instead?
No network detected

Wifi works perfectly with Raspbian / Raspberry Pi OS.

Please see attached log file.
[log-2019-04-11-16.28.55.zip](https://github.com/libretro/Lakka-LibreELEC/files/6771077/log-2019-04-11-16.28.55.zip)

Thanks a lot for your help and work on this nice project!

Best regards,

Laurent

**Comment by Ntemis** [comment]
[    4.694902] usb 1-1.4: Product: 802.11n WLAN Adapter
[    4.694921] usb 1-1.4: Manufacturer: Realtek
We have no power over quality of usb chips. Your wifi is recognized just fine but if it cant find any SSID's its range is an issue we cant fix

**Comment by leskenazi** [comment]
Are you sure ? That's strange because I also runs Raspberry Pi OS with the same hardware (and at the same place) and it detects all SSIDs perfectly.

**Comment by Ntemis** [comment]
The wifi is working fine from the logs you sent.

**Comment by leskenazi** [comment]
These are the networks I can connect to from Raspberry Pi OS :

![IMG_3327](https://user-images.githubusercontent.com/26414541/124655506-388f9680-dea0-11eb-9de6-90cf06205be1.jpeg)
![IMG_3327 (1)](https://user-images.githubusercontent.com/26414541/124655528-3f1e0e00-dea0-11eb-9544-89c84f8eacce.jpeg)

And this is the network I can connect to from Lakka (same hardware / location) :

![IMG_3328](https://user-images.githubusercontent.com/26414541/124655578-52c97480-dea0-11eb-8d2f-eaac35adfdc6.jpeg)
![IMG_3328 (1)](https://user-images.githubusercontent.com/26414541/124655606-5b21af80-dea0-11eb-98d2-2b52ad3d0c52.jpeg)

I checked Lakka configuration, everything seems fine to me.

What may I be missing ?

**Comment by Ntemis** [comment]
Give me a dmesg log

**Comment by leskenazi** [comment]
Thanks for your help. Here is a dmesg log.

Best regards,

Laurent
[dmesglog.txt](https://github.com/libretro/Lakka-LibreELEC/files/6776843/dmesglog.txt)

**Comment by gouchi** [comment]
Don't know if they have used the [kernel driver](https://cateee.net/lkddb/web-lkddb/RTL8192CU.html) or the [outside kernel driver](https://github.com/libretro/Lakka-LibreELEC/tree/master/packages/linux-drivers/RTL8192CU) ?

**Comment by leskenazi** [comment]
Hi @gouchi. I suppose your message is for @Ntemis, right ?

**Comment by gouchi** [comment]
Hi @leskenazi, everybody so that we can advance to fix this issue ;)
