### ISSUE TITLE
OSS driver doesn't work on rg351m

### ISSUE THREAD

**Issue by Zalica** [libretro/Lakka-LibreELEC#1425]
- Which version of Lakka are you using?
3.2

- What system hardware are you using?
rg351m

- What did you do?
I selected OSS audio driver

- What did you expect to happen?
there should be sound.

- What happened instead?
There was no sound at all.
I tried nestopia,beetle supafaust,mesen,mgba, PCSX rearmed,none of them worked.

The following is the log after I switched to OSS audio driver

[INFO] [Playlist]: Written to playlist file: /storage/playlists/FBNeo - Arcade Games.lpl
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [CORE]: Using content: /storage/roms/FBN/19xx.7z.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 2437, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/tmp/cores/fbneo_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at "/storage/.config/retroarch/config/FinalBurn Neo/FinalBurn Neo.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/storage/.config/retroarch/config/FinalBurn Neo/FBN.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/storage/.config/retroarch/config/FinalBurn Neo/19xx.cfg".
[INFO] [Remaps]: Remap directory: "/storage/remappings".
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/FinalBurn Neo/19xx.srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/FinalBurn Neo/19xx.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] Setting save dir to /storage/savefiles/FinalBurn Neo
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[libretro INFO] Setting system dir to /tmp/system
[INFO] [Environ]: SET_CONTROLLER_INFO.
[libretro INFO] Initialize DIP switches.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[libretro INFO] [FBNeo] Searching all possible locations for romset 19xx
[libretro INFO] [FBNeo] Romset found at /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] No romset found at /tmp/system/fbneo/19xx
[libretro INFO] [FBNeo] No romset found at /tmp/system/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x9bf9d9b1 and name 19xe.03b from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x9aa46476 and name 19xe.04b from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xa04a2c5e and name 19xe.05b from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xf0a81c33 and name 19xe.06b from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x61c0296c and name 19x.07 from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x427aeb18 and name 19x.13m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x63bdbf54 and name 19x.15m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x2dfe18b5 and name 19x.17m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xcbef9579 and name 19x.19m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xe916967c and name 19x.14m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x6e75f3db and name 19x.16m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x2213e798 and name 19x.18m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xab9d5b96 and name 19x.20m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xef55195e and name 19x.01 from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xd38beef3 and name 19x.11m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0xd47c96e2 and name 19x.12m from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] Using ROM with known crc 0x6f5d6406 and name 19xx.key from archive /storage/roms/FBN/19xx
[libretro INFO] [FBNeo] No missing files, proceeding
[libretro INFO] [FBNeo] Samplerate set to 44100
[libretro INFO] [FBNeo] Applied dipswitches from core options
[libretro INFO] [FBNeo] Initialized driver for 19xx
[libretro INFO] [FBNeo] Adjusted audio buffer to match driver's refresh rate (59.630001 Hz)
[libretro INFO] [Cheevos] System RAM set to 0x9c4650, size is 65536
[INFO] [Environ]: SET_ROTATION: 1
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[libretro INFO] [FBNeo] Driver 19xx was successfully started : game's full name is 19XX - the war against destiny (960104 Euro)
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44400.00 Hz.
[INFO] [Video]: Video @ 1008x672
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1008x672 rgb32 1 smooth 0 ctx_scaling 0 input_scale 2 force_aspect 1 fullscreen 0 threaded 1 base_width 384 base_height 224 max_width 384 max_height 384 aw 384 ah 224
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [Playlist]: Written to playlist file: /storage/playlists/content_history.lpl
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 14 seconds.
[INFO] [CORE]: No content, starting dummy core.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading game..
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/storage/.config/retroarch/config/FinalBurn Neo/FinalBurn Neo.opt"
[INFO] Threaded video stats: Frames pushed: 929, Frames dropped: 156.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 1080x720
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1080x720 rgb32 0 smooth 0 ctx_scaling 0 input_scale 2 force_aspect 1 fullscreen 0 threaded 1 base_width 320 base_height 240 max_width 320 max_height 240 aw 320 ah 256
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [Playlist]: Written to playlist file: /storage/playlists/content_favorites.lpl
[INFO] [CORE]: Using content: /storage/roms/NES/B-Wings (Japan).zip.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 1239, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/tmp/cores/nestopia_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at "/storage/.config/retroarch/config/Nestopia/Nestopia.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/storage/.config/retroarch/config/Nestopia/NES.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/storage/.config/retroarch/config/Nestopia/B-Wings (Japan).cfg".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: Remap directory: "/storage/remappings".
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/Nestopia/B-Wings (Japan).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/Nestopia/B-Wings (Japan).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] [CONTENT LOAD]: Loading content file: /storage/roms/NES/B-Wings (Japan).zip#B-Wings (Japan).nes
[INFO] Did not find a valid content patch.
[INFO] [CONTENT LOAD]: CRC32: 0x15a4facb
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[libretro INFO] Custom palette path: /tmp/system/custom.pal
[libretro INFO] custom.pal not found in system directory.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_GEOMETRY: 256x240, aspect: 1.219.
[INFO] [Environ]: SET_GEOMETRY.
[libretro INFO] [Nestopia]: Machine is NTSC.
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 1080x720
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1080x720 rgb32 1 smooth 0 ctx_scaling 0 input_scale 4 force_aspect 1 fullscreen 0 threaded 1 base_width 256 base_height 240 max_width 602 max_height 240 aw 256 ah 256
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [Playlist]: Written to playlist file: /storage/playlists/content_history.lpl
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 06 seconds.
[INFO] [CORE]: No content, starting dummy core.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading game..
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/storage/.config/retroarch/config/Nestopia/Nestopia.opt"
[INFO] Threaded video stats: Frames pushed: 546, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 1080x720
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1080x720 rgb32 0 smooth 0 ctx_scaling 0 input_scale 2 force_aspect 1 fullscreen 0 threaded 1 base_width 320 base_height 240 max_width 320 max_height 240 aw 320 ah 256
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [Playlist]: Written to playlist file: /storage/playlists/content_favorites.lpl
[INFO] [CORE]: Using content: /storage/roms/SNES/EarthBound (USA).zip.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 1036, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/tmp/cores/mednafen_supafaust_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at "/storage/.config/retroarch/config/Supafaust/Supafaust.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/storage/.config/retroarch/config/Supafaust/SNES.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/storage/.config/retroarch/config/Supafaust/EarthBound (USA).cfg".
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Remaps]: Remap directory: "/storage/remappings".
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/Supafaust/EarthBound (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/Supafaust/EarthBound (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_SERIALIZATION_QUIRKS.
[INFO] [CONTENT LOAD]: Loading content file: /storage/roms/SNES/EarthBound (USA).zip#EarthBound (USA).sfc
[INFO] Did not find a valid content patch.
[INFO] [CONTENT LOAD]: CRC32: 0xdc9bb451
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO]  Using module: snes_faust(Super Nintendo Entertainment System/Super Famicom)
[libretro INFO] 
[libretro INFO]   SpecEx: 0
[libretro INFO]   SpecExSoundToo: 0
[libretro INFO]   Renderer: Multi-threaded
[libretro INFO]   PAL: 0
[libretro INFO]   PAL PPU Bit: 0
[libretro INFO]   FrameBeginVBlank: 1
[libretro INFO]   PPUThreadAffinity: 0x1
[libretro INFO]   CAspect: 1
[libretro INFO]   HFilter: 4
[libretro INFO]   SLS,SLE: [0,223]
[libretro INFO]   FPS: 60.099823
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 31991.38 Hz.
[INFO] [Video]: Video @ 1008x672
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1008x672 rgb32 0 smooth 0 ctx_scaling 0 input_scale 2 force_aspect 1 fullscreen 0 threaded 1 base_width 292 base_height 224 max_width 512 max_height 480 aw 320 ah 224
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [Playlist]: Written to playlist file: /storage/playlists/content_history.lpl
[libretro INFO] Bypassing snes_faust internal resampler.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 22 seconds.
[INFO] [CORE]: No content, starting dummy core.
[INFO] [SRAM]: Saving RAM type #0 to "/storage/savefiles/Supafaust/EarthBound (USA).srm".
[INFO] [SRAM]: Saved successfully to "/storage/savefiles/Supafaust/EarthBound (USA).srm".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading game..
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/storage/.config/retroarch/config/Supafaust/Supafaust.opt"
[INFO] Threaded video stats: Frames pushed: 1471, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 1080x720
[INFO] [Video]: Starting threaded video driver ...
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] oga_gfx_init video 1080x720 rgb32 0 smooth 0 ctx_scaling 0 input_scale 2 force_aspect 1 fullscreen 0 threaded 1 base_width 320 base_height 240 max_width 320 max_height 240 aw 320 ah 256
[INFO] [Video]: Found display server: null
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/playlists/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/playlists/content_favorites.lpl].
[ERROR] failed_to_start_audio_driver
[INFO] [CORE]: Using content: /storage/roms/PS/Castlevania - Symphony of the Night (USA).chd.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 478, Frames dropped: 0.
[INFO] RetroArch 1.9.5 (Git 6738fa57aa)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun 18 2021
[INFO] Version: 1.9.5
[INFO] Git: 6738fa57aa
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/tmp/cores/pcsx_rearmed_libretro.so"
[INFO] [Overrides]: Core-specific overrides found at "/storage/.config/retroarch/config/PCSX-ReARMed/PCSX-ReARMed.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "/storage/.config/retroarch/config/PCSX-ReARMed/PS.cfg".
[INFO] [Overrides]: No game-specific overrides found at "/storage/.config/retroarch/config/PCSX-ReARMed/Castlevania - Symphony of the Night (USA).cfg".
[INFO] [Config]: Appending config "/storage/.config/retroarch/config/PCSX-ReARMed/PCSX-ReARMed.cfg".

**Comment by Ntemis** [comment]
Oss is depreciated all devices on Linux use the alsa driver and this is not going to change any time soon.
