### ISSUE TITLE
Can't mount /dev/mmcblk after reboot Odroid C1.

### ISSUE THREAD

**Issue by 0lace** [libretro/Lakka-LibreELEC#143]
- Which version of Lakka are you using?
Lakka-OdroidC1.arm-2.1-rc2.
- What system hardware are you using?
Odroid C1.
- What did you do?
reboot from GUI or CLI.
- What did you expect to happen?
To load Lakka.
- What happened instead?
Stop after reboot with one message: "Can't mount /dev/mmcblk "
![img_20170614_214441](https://user-images.githubusercontent.com/26717070/27160467-f31cfe62-514a-11e7-83af-723970562dad.jpg)

**Comment by Kivutar** [comment]
Usually this is due to a flashing corruption. Try reflashing 2 or 3 times using Etcher.

**Comment by 0lace** [comment]
@Kivutar I have used dd on the first time.
I have tried Etcher, 3 times and the result is the same.

**Comment by Kivutar** [comment]
You're using an SD or an eMMC?

**Comment by 0lace** [comment]
Hi, I'm using SD.

**Comment by Kivutar** [comment]
I could reproduce the problem. RC2 and RC3 are indeed broken for C1. Was it also the case with 2.1-rc1?

**Comment by 0lace** [comment]
I have tested the RC2 only, I could test and post the result here.

**Comment by Kivutar** [comment]
Yes please, It would save me time :)

**Comment by Kivutar** [comment]
It doesn't happen with RC1

**Comment by Kivutar** [comment]
Ah, I flashed on another SD card, and this time 2.1-rc2 worked!!!
