### ISSUE TITLE
Libretro Dolphin crashes using the vulkan renderer on the Raspberry Pi 4b.

### ISSUE THREAD

**Issue by Zarklord** [libretro/Lakka-LibreELEC#1432]
Which version of Lakka are you using?
3.2 x64

What system hardware are you using?
Raspberry PI 4B 8gb

What did you do?
Fresh installed Lakka, turned on vulkan renderer, followed the [dolphin setup](https://docs.libretro.com/library/dolphin/#setup) of copying the dolphin-emu to /storage/system/, and turning allow cores to change the video driver to OFF, and then booted Animal Crossing GCN.

What did you expect to happen?
The game to have worked with the vulkan renderer

What happened instead?
Lakka crashed on the restarting screen.

The error itself:
```
[libretro ERROR] 28:46:465 VideoBackends/Vulkan/VulkanLoader.cpp:219 E[Video]: (CreateDevice) vkCreateDevice failed:  (-7: VK_ERROR_EXTENSION_NOT_PRESENT)
[libretro ERROR] 28:46:465 DolphinLibretro/Video.cpp:280 E[Video]: Failed to create Vulkan device
```
Logfile:
[retroarch__2019_04_11__16_28_39.log](https://github.com/libretro/Lakka-LibreELEC/files/6863477/retroarch__2019_04_11__16_28_39.log)

I also tried one other Gamecube Game and two other Wii Games, all with the same crashes.
All of these games can load just fine if I use GL or GLCORE.

**Comment by Ntemis** [comment]
Report on mesa gitlab not here
