### ISSUE TITLE
 RG351P/M aarch64 build

### ISSUE THREAD

**Issue by YourWishes** [libretro/Lakka-LibreELEC#1434]
Wondering if we can have the RG351P/M have an aarch64 build of the Odroid device family.

Attempting to compile myself presents a few linux kernal compile issues that could be related to an out of date package.mk for hardkernal.
I attempted to upgrade myself but the patches are out of date by the look of things, and that's beyond my technical skills unfortunately.

**Comment by Ntemis** [comment]
We have a discord channel for this
