### ISSUE TITLE
Add support for builtin wifi with ap6210 module on BananaPro image

### ISSUE THREAD

**Issue by haseHH** [libretro/Lakka-LibreELEC#144]
Can you add support for the on-board wifi on Banana Pro boards?
The standard way to activate wifi on other Banana Pro distros would be:
`# modprobe ap6210`
`modprobe: FATAL: Module ap6210 not found in directory /lib/modules/3.4.91`
Seems like it would be as "easy" as adding the module to the image, but I couldn't do it.

**Comment by Kivutar** [comment]
Are you talking about the build we're calling Bananapi or H3?

**Comment by agent94ger** [comment]
I'm using the Lakka-Bananapi.arm-2.0.img image.

**Comment by Kivutar** [comment]
Sadly, adding back ap6210 will not help. Wifi is broken anyway because of an incompatibility between the old 3.4 sunxi kernel and modern systemd versions.

**Comment by agent94ger** [comment]
So no easy fix? That's really kinda sad...

**Comment by Kivutar** [comment]
No real fix. I will still try to add back the ap6210 for you to test. But you will get an error "no carrier" when starting connmanctl.

**Comment by agent94ger** [comment]
Thank you for the testing opportunity, just tell me what I need to do

**Comment by Kivutar** [comment]
Ok this image has the driver. You need to modprobe it manually. http://static.kivutar.me/Lakka-Bananapi.arm-2.1-rc3.img.gz

**Comment by agent94ger** [comment]
Thanks for the image! We got a new error though:
`Lakka:~ # modprobe ap6210`
`modprobe: ERROR: could not insert 'ap6210': No such device`
That errormessage appears on the first run after booting. If I try again, this message appears:
`Lakka:~ # modprobe ap6210`
`modprobe: ERROR: could not insert 'ap6210': Operation not permitted`
What will we try next?

**Comment by Kivutar** [comment]
Can you also try this?

    modprobe bcmdhd

**Comment by agent94ger** [comment]
That gives me the same message:
`Lakka:~ # modprobe bcmdhd`
`modprobe: ERROR: could not insert 'bcmdhd': No such device`

**Comment by Kivutar** [comment]
OK I found something that can help.

According to this link https://forum.armbian.com/index.php?/topic/219-bananapi-pro-debian-wheezy-kernel-34108-wifi-problem/ we need to add something in the fex.

But we need to make sure that I have to apply the ap6210 patch, because there is already bcmdhd in the kernel and it's supposed to be the same driver.

**Comment by Kivutar** [comment]
Please try this new image http://static.kivutar.me/Lakka-Bananapi.arm-2.1-rc3.img.gz

I changed the kernel config and I updated the script.bin

**Comment by agent94ger** [comment]
Modprobing the bcmdhd driver still gives me the same error...
`Lakka:~ # modprobe bcmdhd`
`modprobe: ERROR: could not insert 'bcmdhd': No such device`

Trying to recreate the "No such device"/"Operation not permitted" error combination gave me an new phenomenon:
`Lakka:~ # modprobe ap6210`
`modprobe: ERROR: could not insert 'ap6210': No such device`
`Lakka:~ # modprobe ap6210`
`Segmentation fault`
A third try seemed successful at first:
`Lakka:~ # modprobe ap6210`
`Lakka:~ # lsmod`
`Module                  Size  Used by`
`ap6210                623323  1`
But I still couldn't scan for/find any wifi networks
