### ISSUE TITLE
RG351P/M Startup script

### ISSUE THREAD

**Issue by Sichroteph** [libretro/Lakka-LibreELEC#1443]
Is there a place to put SSH scripts ?

I would like to have a shortcut to turn off the console in game, and to resume it automatically after the boot.

**Comment by gouchi** [comment]
> This issue tracker is NOT for help or support. Please use one of the following channels for help and support:
> 
>     the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general)
>     via IRC @ #lakkatv on freenode.net
>     #lakkatv on libretro discord https://discord.gg/retroarch

[Source](https://github.com/libretro/Lakka-LibreELEC/blob/master/.github/ISSUE_TEMPLATE.md)
