### ISSUE TITLE
Black screen on switch

### ISSUE THREAD

**Issue by Jfowler30** [libretro/Lakka-LibreELEC#1444]
I have an original switch and I have the latest heketate and the latest lakka I have it in fat32 or whatever the recommended one is and I transferred all the files properly but I load it and it just sits on a black screen? Do I need a brand new ad card or something or is there a list of as cards that don't work with lakka?

**Comment by Ntemis** [comment]
@GavinDarkglider

**Comment by GavinDarkglider** [comment]
Are you sure it is fat32. even then, using the latest hekate, it should pass frame buffer, until kernel loads, so you must have done something wrong.
