### ISSUE TITLE
fuse core missing on RPi3.aarch64

### ISSUE THREAD

**Issue by fdziarmagowski** [libretro/Lakka-LibreELEC#1445]
Using Lakka.tv 3.3 on RPi3.aarch64, the fuse (zx spectrum) core seems to be **missing**. "Seems" as same Lakka.tv on GPiCase happily runs Spectrum games with this core.

**Comment by fdziarmagowski** [comment]
Any particular reason for limiting PKG_ARCH to i386 x86_64 arm?

**Comment by Ntemis** [comment]
Not really :)

**Comment by fdziarmagowski** [comment]
Great, thanks!

**Comment by Ntemis** [comment]
Thank you for the report
