### ISSUE TITLE
[Feature request] Remove bluetooth devices from the frontend

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#1446]
If you pair the Dual Sense controller with another machine and want to use it again on Lakka, you have to remove it via bluetoothctl and pair it again. Since this is a tedious process that might overwhelm some users, I suggest that devices should able to be removed from the frontend directly.

**Comment by Ntemis** [comment]
For this to happen you have to ask here https://github.com/libretro/RetroArch

**Comment by coldspark29** [comment]
Done

**Comment by Ntemis** [comment]
You need to be clear this is only for Linux

**Comment by coldspark29** [comment]
I was assuming that the developers know what bluetoothctl and Lakka are.

**Comment by Ntemis** [comment]
You have a point :)
