### ISSUE TITLE
Lakka 3.3: MAME 2000 core crash on RPi 1 / Zero

### ISSUE THREAD

**Issue by modeler** [libretro/Lakka-LibreELEC#1447]
The MAME 2000 core appears to crash 100% of the time when running Lakka 3.3 on an original Raspberry Pi or Pi Zero. This seems to be a Lakka issue as I have built the core from source and have it running on Raspbian with RetroArch 1.9.7.

**Comment by SethBarberee** [comment]
Logs of the core crashing in Lakka?

Also do you have logs/command when you compiled in Raspbian (for comparison)?

**Comment by modeler** [comment]
Hi Seth,

I should clarify that I raised this issue because the bundled MAME 2000 core within the Lakka 3.3 distribution crashes every time on a Pi 1 / Zero, so the fault is very easy to reproduce. I only rebuilt it from the current source tree to see if it would run under Raspbian, which it does.

Although I have built several cores other under Raspbian (on the same Pi) that work under Lakka, this one doesn't. I will try to generate / upload the logs ASAP.

Thanks.

**Comment by modeler** [comment]
This what is written to /storage/.config/retroarch/logs/retroarch.log when loading any ROM set (e.g. 1942), "Core Logging Level" set to 0 (Debug):

`[INFO] [CORE]: Using content: /storage/roms/MAME 2000/1942.zip.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.`

RetroArch restarts immediately afterwards.

Log from recompilation attached:
[raspbian_build.txt](https://github.com/libretro/Lakka-LibreELEC/files/6970263/raspbian_build.txt)

**Comment by gouchi** [comment]
Please specify which parameters you are using for compilation.

We are using [those parameters ](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/mame2000/package.mk#L39)on Lakka for arm.

`make ARM=1 USE_CYCLONE=1 USE_DRZ80=1`

Thank you.

**Comment by modeler** [comment]
Hi,

This is still an issue in Lakka 3.4, using the bundled MAME 2000 core. Sorry if this wasn't clear, but I only rebuilt the core from source to see if it would crash in the same way and it does, but only in Lakka. The same build of the core works okay in RetroArch under Raspbian on the same RPi v1.

Is there any further testing I can do to assist?

Thanks.

**Comment by Ntemis** [comment]
Tell us how you build it for raspian because we do NOT find any issue with our build package

**Comment by modeler** [comment]
You aren't able to reproduce the problem? If I'm right, taking any Pi 1 or Pi Zero and booting with a fresh install of Lakka 3.x (v2.6.2 is okay) and loading any ROM with the bundled MAME 2000 core will cause RetroArch to crash / restart.

If this is only happening for me, I will work out what's going on and provide as much info as I can once resolved.

**Comment by modeler** [comment]
It seems to be caused by something in my system directory, but I have no idea what. I will find out and let you know, apologies for wasting your time.

**Comment by modeler** [comment]
The "mame2000" directory in my system directory wasn't writable, changed permissions to 777 and the core no longer crashes. I think something must have changed in the way this directory is handled between 2.x and 3.x, perhaps 2.x runs RetroArch as root and 3.x moved to a non-privileged user?

In any case, it's not an issue with the core. It's a side-effect of moving the contents of my SD card from a Lakka 2.x build to a 3.x build. Sorry again for the confusion here.
