### ISSUE TITLE
Lakka 3.x: OSD text is illegible on low-resolution screens

### ISSUE THREAD

**Issue by modeler** [libretro/Lakka-LibreELEC#1448]
Running the current build of Lakka with a GPi case, the on-screen text is not readable due to the low DPI. When using the 2.3.x build with the old OSD system, the text is perfectly fine.

**Comment by modeler** [comment]
Turning off graphical widgets is a reasonable work-around, may I suggest this option be set as default in the GPi Case build?

**Comment by SethBarberee** [comment]
Graphical widgets were turned off in the recent commit for GPiCase. When the nightly builds tonight, give it a try!
