### ISSUE TITLE
LAKKA SafeMode / Recovery Menu

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka-LibreELEC#1463]
As LAKKA is mainly designed as a retrogaming console, it lacks a robust and easy way for users to "restore defaults". 
There are numerous examples where a configuration change in RetroArch can lead to an unusable system that requires either a keyboard or SSH access.
There are also quite a few use cases that make connecting a keyboard or an external display difficult - handhelds, streaming boxes stuck behind a TV, etc.

I wanted to suggest a "Recovery Menu" that can be accessed by holding or pressing a key combo (joystick or keyboard) and that will display a menu with several recovery options such as:
- Deleting retroarch.cfg
- Deleting the entire ~/.config/retroarch folder
IMHO The menu should be unrelated to retroarch and accessible before RetroArch even starts up.

I'm currently trying to adapt the following python ncurses script: https://gist.github.com/abishur/2482046 it seems suitable as it doesn't require any dependencies outside of what already ships with LAKKA.
The following python script reads joystick/gamepad input: https://gist.github.com/emdeex/97b771b264bebbd1e18dd897404040be
And can be used together with the ncurses menu to enable gamepad navigation, it can also be used to activate the menu by detecting a key press combo.

I've started working on this and will share code as I go along, would love to have assistance from a more experienced coder if possible.

**Comment by Ntemis** [comment]
This belongs to a forum post https://forums.libretro.com/c/libretro/lakka-tv-general
