### ISSUE TITLE
Lakka 3.3 (Aarch64, Stable) (RPi4) Screenshots Taken End up Rotated

### ISSUE THREAD

**Issue by Rstation4** [libretro/Lakka-LibreELEC#1466]
Raspberry Pi 4B 4gb
Lakka 3.3 Aarch64 Stable Release

It's a very small issue but the screenshots when taken are ending up sideways or rotated in another direction. I've been mostly doing some screenshots with ROMs from the FBNeo core.

PS. I'm trying to make thumbnails with at least a size of 512x512, how would I be able to adjust the screenshot sizes? For instance a lot of FBNeo roms end up with a screenshot size of 320 x 240.

**Comment by Ntemis** [comment]
https://github.com/libretro/RetroArch/issues
