### ISSUE TITLE
Add compatibility with GamePi43 case.

### ISSUE THREAD

**Issue by SkushaKutusha** [libretro/Lakka-LibreELEC#1474]
Please add Raspberry Pi 3\4 compatibility with GamePi43 case.
At the moment, Lakka does not work correctly with this case (or rather, the control buttons do not work).
More information about this device can be found here https://www.waveshare.com/wiki/GamePi43

**Comment by SkushaKutusha** [comment]
Here's what the GamePi developers answered me:
**"I'm sorry that the GamePi43 cannot support the Lakka system now. For the control of the handle, we do not have a corresponding driver for this system, and may need to be modified according to the driver on our Wiki."**
Can you provide them this driver which they need?!

**Comment by dmrlawson** [comment]
There's nothing for us to provide. They have the driver for their system, and it would need to be added in to Lakka

**Comment by SkushaKutusha** [comment]
In the end, what's the solution?! What needs to be done? Ask them to post this driver or what? 
We have to solve the problem somehow (or have to go to a competitor like recalbox).

**Comment by Ntemis** [comment]
Have fun on recalbox. FYI we are not here to compete and recalbox doesnt have native support for this hardware either and by the looks of the makers it never will too

**Comment by SkushaKutusha** [comment]
If you can't solve the problem, say so, rather than looking for excuses. In my opinion, you didn't even try to help me, because you weren't interested in it in the first place. That's great support, and there's nothing to be said for that.

**Comment by dmschwartzii** [comment]
You have to be kidding you want support for hardware and the manufacturer of said hardware has no interest in helping, and this community is the problem?

On September 4, 2021 7:55:58 AM CDT, SkushaKutusha ***@***.***> wrote:
>If you can't solve the problem, say so, rather than looking for excuses. In my opinion, you didn't even try to help me, because you weren't interested in it in the first place. That's great support, and there's nothing to be said for that. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/Lakka-LibreELEC/issues/1474#issuecomment-912969988
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SkushaKutusha** [comment]
Well you also, as it seems to me, are not particularly interested in adding this compatibility, otherwise you would have already contacted them and jointly solved this problem.  I wonder why other devices (like GPI case) have their own Lakka build?

**Comment by dmschwartzii** [comment]
The makers of the gpi case made information and needed files readily available 

On September 4, 2021 8:07:16 AM CDT, SkushaKutusha ***@***.***> wrote:
>Well you also, as it seems to me, are not particularly interested in adding this compatibility, otherwise you would have already contacted them and jointly solved this problem.  I wonder why other devices (like GPI case) have their own Lakka build? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/Lakka-LibreELEC/issues/1474#issuecomment-912971621
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ntemis** [comment]
not only that but also @SethBarberee has one

**Comment by Ntemis** [comment]
@SkushaKutusha ask the makers to join our discord and we will help them add support for the hardware if they are willing to take over maintenance for it. There is no issue there.

**Comment by SkushaKutusha** [comment]
Okay, I'll write to them about discord as soon as they respond. I think that makes sense.
