### ISSUE TITLE
Retroarch.cfg is messed up when shutting down on generic x64

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#1477]
- Which version of Lakka are you using?
    497be54

- What system hardware are you using?
   x64

- What did you do?
  Shut down the system

- What did you expect to happen?
  That Lakka would only shutdown

- What happened instead?
  My retorach.cfg is messed up. The menu driver changed, all the playlists and settings are gone. Second time now.

**Comment by Ntemis** [comment]
Did you save the config prior to shutdown?

**Comment by coldspark29** [comment]
Not that I know of. It automatically saves the config by default when you close Retroarch, but even then it should be fine, because it was fine when I shutdown Lakka. When I delete the ``retroarch.cfg``, everything is fine again. So no idea why it suddenly sets the driver to Ozone. Even when you chosse xmb again, the fonts are messed up.

**Comment by Ntemis** [comment]
Try running a memtest and next time save the retroarch.cfg prior you shutdown

**Comment by coldspark29** [comment]
Yeah, I was also thinking my memory could be faulty. It is an old computer. Will try that.

**Comment by coldspark29** [comment]
Hasn't happened in a while. Could have also been a memory issue, because I exchanged them. Closing.
