### ISSUE TITLE
Korean does not display correctly after restarting RetroArch on Stable 3.4 Switch(Even 4.1 on x64)

### ISSUE THREAD

**Issue by vus7294** [libretro/Lakka-LibreELEC#1494]
![IMG_5878](https://user-images.githubusercontent.com/13133961/132484875-6b4400ca-84d4-4451-890e-a0a6caa2d0e5.JPG)
Lakka 3.4 Stable on Switch. Default Video Setting on Vulkan.

**Comment by gouchi** [comment]
Hi,

You did restart one time RetroArch ?

Do you reproduce the issue using `gl` or `glcore` video driver ?

Now RA should take automatically the font in  `/usr/share/retroarch-assets/pkg/korean-fallback-font.ttf`

Thank you.

**Comment by vus7294** [comment]
I set language and Reset, then That Glitch.

I Always use Video driver as Vulkan.

**Comment by gouchi** [comment]
When you say Reset you mean Restart RetroArch ?

I will have to make some test with Korean language.

**Comment by losernator** [comment]
> When you say Reset you mean Restart RetroArch ?
> 
> I will have to make some test with Korean language.

CJK fallback Fonts feature doesn't seem to work properly.
(not just Switch version also happens in unix-distro like raspberry pi, odroid)

Actually Korean does not need fall-back feature. default XMB and OZONE already have enough font glyph for Korean language

**Comment by gouchi** [comment]
I made some test on my PC with Xorg and using Korean language 

1. XMB or Ozone

Using video driver `gl` or `glcore` it is using font `assets/pkg/korean-fallback-font.ttf`
Using video driver `vulkan` it is using font `assets/ozone/regular.ttf`

I will have to make some test with Lakka.

**Comment by vus7294** [comment]
> I made some test on my PC with Xorg and using Korean language 
> 
> 
> 
> 1. XMB or Ozone
> 
> 
> 
> Using video driver `gl` or `glcore` it is using font `assets/pkg/korean-fallback-font.ttf`
> 
> Using video driver `vulkan` it is using font `assets/ozone/regular.ttf`
> 
> 
> 
> I will have to make some test with Lakka.

Sadly This bug is STILL PRESENT in 3.5 Stable for Switch.

**Comment by gouchi** [comment]
Can you try to make a test by switching to xmb menu ?

It seems if you set the xmb menu font to ` /usr/share/retroarch-assets/ozone/regular.ttf` it will work after restart RA (Settings tab > User Interface > Appearance > Menu Font)

You will have to enable advanced settings to get access to xmb menu font (Settings tab > User Interface > Show Advanced Settings).

Thank you.

**Comment by vus7294** [comment]
It Works, But I Can't Set Language with OZONE UI. This Seems Bad Glitch. Thanks.

**Comment by vus7294** [comment]
I Tested x64 Lakka Even Can't Display Korean on XMB Theme. :(

**Comment by Ntemis** [comment]
take it to retroarch gh
