### ISSUE TITLE
vcgencmd missing dependency (Pi4 AARCH64)

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka-LibreELEC#1496]
`vcgencmd` under LAKKA versions v3.3 and v3.4 on AARCH64 cannot run due to a missing dependency.
When running `/usr/bin/vcgencmd` it reports:
`-sh: vcgencmd: not found`
I believe this is due to it being compiled against `ld-linux-armhf.so.3` which is missing from /usr/lib.

**Comment by dmrlawson** [comment]
Yep. This is due to using the 32bit precompiled version from https://github.com/raspberrypi/firmware

I was trying to make a new package from https://github.com/raspberrypi/userland to compile it ourselves, I'll have another go

**Comment by ToKe79** [comment]
@duduke Hi, can you test build from here (choose your flavor):
https://nightly.builds.lakka.tv/PRs/pr_1500_000431/
Thank you!
