### ISSUE TITLE
xmbb in /storage/assets is not work

### ISSUE THREAD

**Issue by WHK102** [libretro/Lakka-LibreELEC#1510]
I use Lakka (Generic.x86_64-3.1) and have a single playlist called `/storage/playlists/arcade.lpl`, the playlist works fine but need change icon (playlist icon). I copied any png and save in:

```bash
mkdir -p /storage/assets/xmbb/monochrome/png;
cp /usr/share/retroarch-assets/xmb/monochrome/png/MAME.png /storage/assets/xmb/monochrome/png/arcade.png
cp /usr/share/retroarch-assets/xmb/monochrome/png/MAME-content.png /storage/assets/xmb/monochrome/png/arcade-content.png
```

And restart lakka but icon not change, if change playlist filename to `MAME.lpl` the icon works fine.

`/storage/assets/xmb/monochrome/png` folder does not work.

**Comment by ToKe79** [comment]
Try following:
```
cp /tmp/assets/xmb/monochrome/png/MAME.png /tmp/assets/xmb/monochrome/png/arcade.png
```
And same for arcade-content.png
