### ISSUE TITLE
Add RK3326 - oga, ogs, rg351*

### ISSUE THREAD

**Issue by ToKe79** [libretro/Lakka-LibreELEC#1512]
probably belongs to `projects/Rockchip`, most of the changes for RA and cores should be already included in 4.x branch

**Comment by Ntemis** [comment]
Looks like @davidgfnet is MIA so we close this down as not possible anymore

**Comment by davidgfnet** [comment]
So Lakka v4 has no OGA support yet? For some reason I thought someone had added it.

**Comment by Ntemis** [comment]
Are you willing to work on this? I can reopen it if you do

**Comment by Ntemis** [comment]
Also kindly check the remaining two issues as i want them close asap

**Comment by armadillu** [comment]
I saw a while ago that @ToKe79 had a branch focusing on this? https://github.com/ToKe79/Lakka-LibreELEC/commits/anbernic
