### ISSUE TITLE
Lakka on Nintendo Switch in Portable mode has incorrect refresh rate result in stuttering framerates

### ISSUE THREAD

**Issue by HappehLemons** [libretro/Lakka-LibreELEC#1525]
All games in portable mode have jittering framerate issues. Issue becomes apparent in any side scrolling game (Sega Genesis, SNES, NES, ect..). This is due to the refresh rate in RA not matching the screens refresh rate. vsync has no effect here. 

This does not happen when using Retroarch on Switch thru its native OS with CFW. Framerates are smooth and consistent in all games. 

For some reason, it also seems like Retroarch has removed its "“Vertical Refresh Rate” option in Video Settings -> Output so there's no way to manually adjust this for testing to see if it can be self-fixed. 

Also reports of this here:
https://gbatemp.net/threads/retroarch-switch.492920/page-443

- Which version of Lakka are you using?
3.5
- What system hardware are you using?
Nintendo Switch
All settings are default

**Comment by HappehLemons** [comment]
Just to add on here, I was able find that RA allows you un-hide the setting that allow you to manually set the refresh rate by enable advanced options in the settings. 

However - manually setting the refresh rate to 60.00hz, 59.999hz, 60.02hz, 60.002hz, enabling v-sync, turning off audio sync, or enabling threaded video does not fix this issue. Contact frame pacing issues.

**Comment by HappehLemons** [comment]
> This is an issue with the video card driver and is beyond us to fix, since it is a closed source driver. The issue has been brought up to Nvidia, and is reported fixed in an unreleased version of the driver, so maybe at some point this will be fixed properly, but it wont be until nvidia has pushed out their next release, and CTC gets ahold of it, to diff the changes to the binary, and try to patch them into the version of the driver we use currently, which has less issues with our kernel.
> 
> Nvidia report: https://forums.developer.nvidia.com/t/very-poor-framepacing-and-performance-when-using-xorg-rotation/178451

Interesting. It looks like according to that post, it will be released soon as it will be in their next update. Hoping to see this patched in eventually, because Lakka is really great on swtich.

**Comment by HappehLemons** [comment]
Checkin in here since it’s been a while. Does this issue still exist? Not sure if the driver was updated yet or not.

**Comment by GavinDarkglider** [comment]
Well, we have the new driver, due to a mistake on nvidia's end, and from what I am hearing, they may have made the problem worse, but there are still configurations to test.... I will close this, if there is ever a proper fix.
