### ISSUE TITLE
Please add wifi driver for RTL8821CU

### ISSUE THREAD

**Issue by s3tupw1zard** [libretro/Lakka-LibreELEC#1532]
Hello,
I don't really know where I could ask this, so I'm asking it here:

Could you please add the driver for RTL8821CU Wifi stick to Lakka?

I want to use it on Odroid Go Super.

Here's the link:
https://github.com/morrownr/8821cu

There is a script inside called raspi32.sh to prepare it to build for arm. I tried to build lakka on my own, but the retroarch part isn't compiling, so maybe you could add the driver and build it. The driver part is compiling fine, so it should work.

Thanks in Advance

**Comment by ToKe79** [comment]
Hi @s3tupw1zard 
I added the driver locally, you can test image from https://nightly.builds.lakka.tv/members/vudiq/rk3326+rtl8821cu/
Let me know, if the driver works as expected and if yes, I can merge the changes.
Thank you!

**Comment by s3tupw1zard** [comment]
Hi @ToKe79 
The driver doesn't seem to load. The LED isn't blinking at all.
Thank you

**Comment by ToKe79** [comment]
Hi @s3tupw1zard 
I found different repo with the driver - https://github.com/brektrou/rtl8821CU
Can you retest with image from https://nightly.builds.lakka.tv/members/vudiq/rk3326+rtl8821cu/
