### ISSUE TITLE
PiBoy DMG HDMI & Controller issues

### ISSUE THREAD

**Issue by squeezebunny** [libretro/Lakka-LibreELEC#1542]
These were last tested with Lakka 3.5.1. The last two versions seem to have no change in the piboy dmg package, and I have commented out the HDMI-related config lines from the 3.5.2 release notes; there was no difference.
My device has a RP4 inside, and is upgraded to the latest firmware, 1.0.5.
### HDMI
HDMI does not work on the PiBoy DMG by default. I have gotten it to work by adding the following lines in "distroconfig.txt" They were lifted from an RetroPie image which was edited with ExperimentalPi's installation scripts.
```
[edid=*]
enable_dpi_lcd=0
```
Under the "edid=*" tag, I also added the following two lines, which I sourced elsewhere. They ensure the PiBoy outputs 1080p, since it outputs 4K by default on my TV and that causes low framerates and an eventual crash.
```
hdmi_group=2
hdmi_mode=82
```
### On-device controller in HDMI
By default, RetroArch will place the device's controller as player 1. This is not good for use on a TV. In order to use RetroArch with an external controller, I have to plug one in or turn it on with bluetooth, and then restart RetroArch somehow. (using either the controls or ssh.) It's just inconvenient since it'd be nice to not have to navigate retroarch using the device whenever I want to plug in a controller.

Luckily RetroArch does place a new controller as player 1, instead of the in-built controls. But only if the new controller is already active when RetroArch launches.

**Comment by Ntemis** [comment]
We dont support pi boy
