### ISSUE TITLE
No audio through Composite output

### ISSUE THREAD

**Issue by paqman3d** [libretro/Lakka-LibreELEC#1546]
- What system hardware are you using?

Pi3 with 64bit Lakka 3.5.2 

- What did you do?

Hooked up system via composite out.

- What did you expect to happen?

Have sound

- What happened instead?

No sound.

Basically was testing the CRT fix and did a clean install. However, after loading any game I have no sound output at all. Is there something that changed in the config.txt on the lakka partition of the sd card perhaps? Is anything different for outputting sound through composite after the crt fix?

**Comment by ToKe79** [comment]
I think you have to change the audio device to something appropriate for the analog output. I think somebody in discord mentioned setting it to `default:CARD=Headphones` worked for them.

**Comment by paqman3d** [comment]
Yep, that did the trick. Happy to have CRT output working again!
