### ISSUE TITLE
Can lakka be ported to other soc like F1C200S？

### ISSUE THREAD

**Issue by jiangotto** [libretro/Lakka-LibreELEC#1549]

**Comment by RobLoach** [comment]
Is that an Allwinner? Lakka uses LibreELEC, so if LibreELEC can do it, then yes.

**Comment by gouchi** [comment]
It might be possible but as we don't own one this device it will be difficult to port it.

Source : [1](https://linux-sunxi.org/F1C100s) [2](https://mangopi.cc/mangopi_r) [3](https://github.com/mangopi-sbc)
