### ISSUE TITLE
WiFi driver listed null, still connected to Internet

### ISSUE THREAD

**Issue by mbc3** [libretro/Lakka-LibreELEC#1554]
Under the drivers section, my WiFi driver is listed as null, and I am unable to select anything else.

I SSH'd into my Pi4 and set up my network there - and ip addr show + pinging confirms that I have access to the Internet and am on my network.

I'm not sure if this is merely a graphical display bug or if it's indicative of anything else - I'm unable to download thumbnails, for example.

**Comment by RobLoach** [comment]
Confirmed this is fixed. Tested on a RPi3.
