### ISSUE TITLE
DuckStation on Switch has performance issues in-game with Um Jammer Lammy

### ISSUE THREAD

**Issue by dantini32** [libretro/Lakka-LibreELEC#1557]
- Which version of Lakka are you using?
11/25/2021 nightly
- What system hardware are you using?
Nintendo Switch
- What did you do?
Play a stage in Um Jammer Lammy running in DuckStation
- What did you expect to happen?
The game runs at full speed
- What happened instead?
The game slows down considerably to unplayable framerates

Um Jammer Lammy is the only game I've run that has performance issues. I'm using default settings for everything except aspect ratio, cropping, and renderer (Hardware - Vulkan), though performance issues still occur regardless of which renderer I use. PaRappa the Rapper and other PlayStation games such as Gran Turismo 2 and Croc run perfectly under DuckStation on Switch. Any help?

https://user-images.githubusercontent.com/95075135/143629890-58132c5f-3f91-4995-8e2f-53e9464ebed9.mp4

**Comment by RobLoach** [comment]
If other games are functional, it seems like a core/DuckStation issue.
