### ISSUE TITLE
RG351V battery indicator and charging.

### ISSUE THREAD

**Issue by Lucius1202** [libretro/Lakka-LibreELEC#1558]
I would like to report a problem with the battery indicator.

- Which version of Lakka are you using? 
- Lakka (official) 3.6 
- What system hardware are you using?
- Anbernic RG351V
- What did you do?
- Charge the device.
- What did you expect to happen?
- The battery normally charges up to 100%
- What happened instead?
- The battery gauge does not rise above 43 percent and the LED behaves accordingly (orange to red).

"Long explanation".
With the original system received with console, the battery normally charges up to 100% and discharges accordingly, the LED behaves accordingly, green, yellow, orange and finally red below 20%. When the system is 100% charged with green LED, I turn off the console, replace with official Lakka 3.6, and the battery reports 43% and orange LED. The console is new as well as the SD cards.

**Comment by Graham15** [comment]
I have noticed the same with my Anbernic RG351MP. 351ELEC reports 100% but Lakka 3.6 reporting 39%.

**Comment by Lucius1202** [comment]
After a few days I thought my console was broken and asked for a new unit. After a first charge and discharge the problem has reoccurred, indicator at 37% but battery that seems fully charged. The legacy system is retropie based and works normally. Hope this information will help.

**Comment by Graham15** [comment]
Mine is now showing 0% even though it's 100% charged. Works fine in 351Elec. Tried Lakka 4 (dev) but unfortunately, same issue.

**Comment by Lucius1202** [comment]
I was thinking if it is possible to get the battery level through ssh? Any system files to read with grep or cat? Maybe with other commands?

**Comment by ToKe79** [comment]
not fixing this. there is plan to port RK3326 and all the consoles (Odroid Go Advance/Super, Anbernic RG351 series, ...) to the 4.x branch in the future, so focus on the port, not fixing old bug, sorry. As a workaround you may try to use .dtb file from 351ELEC build (helps with RG351MP at least).
