### ISSUE TITLE
Flycast Libretro Upstream Repo

### ISSUE THREAD

**Issue by Mr-Jake** [libretro/Lakka-LibreELEC#1560]
Lakka still builds Flycast from the Libretro repo:
```
packages/libretro/flycast/package.mk 

PKG_NAME="flycast"
PKG_VERSION="beb9a61"
PKG_ARCH="any"
PKG_LICENSE="GPLv2"
PKG_SITE="https://github.com/libretro/flycast"
```

However, there is a notice in the about section in the Libretro repo.

<blockquote> 

About

Flycast is a multiplatform Sega Dreamcast emulator. **NOTE: No longer actively developed, use upstream repo for libretro from now on** - https://github.com/flyinghead/flycast 
</blockquote>

Should Lakka switch to the Flycast Libretro upstream repo?

**Comment by Ntemis** [comment]
We will if this is valid. Thanks for noticing it

Στις Τετ, 1 Δεκ 2021, 17:05 ο χρήστης Mr-Jake ***@***.***>
έγραψε:

**Comment by RobLoach** [comment]
It looks like most of libretro references the libretro/flycast repo:
https://github.com/libretro/libretro-super/blob/master/recipes/linux/cores-linux-x64-generic#L114

**Comment by gouchi** [comment]
Yes we will have to switch to upstream repository  [https://github.com/flyinghead/flycast](https://github.com/flyinghead/flycast).

It will be done when we release the new Lakka version with RA version 1.9.14.

**Comment by RobLoach** [comment]
Thanks for providing the updated package file :+1:
