### ISSUE TITLE
Raspberry Pi 4 - Not reading input from connected Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by TylerHooper** [libretro/Lakka-LibreELEC#1574]
Version: Lakka 3.6
Hardware: Raspberry Pi 4, Nintendo Switch Pro Controller, Nintendo Switch SNES Controller
Steps to reproduce:
 1. Connect Nintendo Switch Controller via Bluetooth.
 2. Notice that device is recognized and assigned to controller port # 2.
 3. Navigate to Settings > Input > Port 2 Controls.
 4. Confirm that Device Index = Nintendo Switch Pro Controller.
 5. Attempt setting any controls.
 6. Press applicable button on controller, notice that no input is read, and prompt times out.
 7. Repeat above steps connected via USB-C, with same result.
 8. Above steps repeatable with Nintendo Switch SNES Controller with same results.
 9. Issue is reproducible on latest Nightly build as of writing.
- Expected results: Once connected and recognized, input should be received from controller when buttons are pressed.
- Actual result: While controller is connected and recognized, no input is received from the controller.

(Logs obtained from latest Nightly build as of writing) [log-2022-01-06-22.05.10.zip](https://github.com/libretro/Lakka-LibreELEC/files/7824999/log-2022-01-06-22.05.10.zip)

**Comment by Ntemis** [comment]
```Jan 06 16:50:59 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 5 dropped IMU reports
Jan 06 16:50:59 Lakka kernel: nintendo 0005:057E:2009.0002: delta=100 avg_delta=15
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:00 Lakka joycond[619]: adding epoll_subscriber: fd=5
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:00 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:01 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 4 dropped IMU reports
Jan 06 16:51:01 Lakka kernel: nintendo 0005:057E:2009.0002: delta=84 avg_delta=15
Jan 06 16:51:01 Lakka kernel: nintendo 0005:057E:2009.0002: compensating for 5 dropped IMU reports
Jan 06 16:51:01 Lakka kernel: nintendo 0005:057E:2009.0002: delta=104 avg_delta=15```
Looks like a driver issue with the specific controller, report to raspberry pi kernel github to add proper support
