### ISSUE TITLE
Audio problems in some 32x sega games In lakka OS 2.1 rc2 pc X64

### ISSUE THREAD

**Issue by marleyap** [libretro/Lakka-LibreELEC#158]
I am having audio problems When the volume is increased beyond the default in some 32x sega games on the pico drive lakka OS 2.1 rc2, the audio of some games are showing hisses, flaws such as brutal unleashed 32x, virtua fighter 32x, blackthrone, metal head and emulator version that Use is picodrive 1.91cbc93b6, I use lakka x64 on the PC on which is an HP pavilion g4-2117br. Please correct the problem in these games, thank you.

**Comment by gouchi** [comment]
Do you reproduce the issue with [Lakka 2.1 rc4 ](http://le.builds.lakka.tv/Generic.x86_64/Lakka-Generic.x86_64-2.1-rc4.img.gz)?

**Comment by ToKe79** [comment]
Closing this issue, as no response received. If the issue still exists in the latest [stable](http://www.lakka.tv/get) and/or [nightly](http://nightly.builds.lakka.tv) releases, please feel free to re-open this issue. Thank you!
