### ISSUE TITLE
Database: Directory Not Found

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka-LibreELEC#1586]
Seems the RDBs in the database are not there on install.

>Which version of Lakka are you using? 

Lakka-RPi3.aarch64-nightly-20220116-8bb17e6.img.gz

> What system hardware are you using?

RPi3

> What did you do?

1. Install the latest nightly build of Lakka
2. Visit Information > Database Manager
3. Find that there are no files.... "Directory Not Found"

> What did you expect to happen?

For there to be a list of .rdb files.

> What happened instead?

There are no .rdb files listed in the Database Manager list.

**Comment by RobLoach** [comment]
It could be my SD card though, so if someone else could verify the database still works, that'd be incredible.

**Comment by Ntemis** [comment]
From what package we take the rdb files from?

**Comment by RobLoach** [comment]
libretro-database over at https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/libretro-database/package.mk

**Comment by gouchi** [comment]
I don't reproduce the issue on Generic x86_64 nightly-20220116-8bb17e6.img.gz

**Comment by RobLoach** [comment]
Good to hear! Thanks for the testing :+1:
