### ISSUE TITLE
please add the emulation station UI to lakka

### ISSUE THREAD

**Issue by coreybruce** [libretro/Lakka-LibreELEC#1610]
Hi just wanted to ask if you could add the emulation station UI to lakka as it has so many UI options would would work so much better with Lakka and its features not to mention would be a Far better looking/running UI for handheld devices like the GPI cases and other hand held devices.

**Comment by RobLoach** [comment]
The aim of Lakka is to be Just Enough OS for RetroArch. Emulation Station may be out of scope for that. I'd recommend trying out RetroPie or Batocera if you're looking to use EmulationStation as a launcher.

**Comment by coreybruce** [comment]
> The aim of Lakka is to be Just Enough OS for RetroArch. Emulation Station may be out of scope for that. I'd recommend trying out RetroPie or Batocera if you're looking to use EmulationStation as a launcher.

It wouldn't be any different the the already existing UI choices on Lakka like xmb, rgui, ozone or fluid. All I am asking for is to add the emulation station UI to lakka :)

**Comment by GavinDarkglider** [comment]
> > The aim of Lakka is to be Just Enough OS for RetroArch. Emulation Station may be out of scope for that. I'd recommend trying out RetroPie or Batocera if you're looking to use EmulationStation as a launcher.
> 
> It wouldn't be any different the the already existing UI choices on Lakka like xmb, rgui, ozone or glui. All I am asking for is to add the emulation station UI to lakka :)

Um, this is actually completely different. Retroarch is one program, Emulation Station is a different program. Both programs do the same thing essentially. But comparing  EmulationStation to xmb, rgui, ozone or glui which are basically skin engines in retroarch, is rediculous. Lakka is designed to be just enough OS to run retroarch, not retroarch and ...

**Comment by coreybruce** [comment]
> > > The aim of Lakka is to be Just Enough OS for RetroArch. Emulation Station may be out of scope for that. I'd recommend trying out RetroPie or Batocera if you're looking to use EmulationStation as a launcher.
> > 
> > 
> > It wouldn't be any different the the already existing UI choices on Lakka like xmb, rgui, ozone or glui. All I am asking for is to add the emulation station UI to lakka :)
> 
> Um, this is actually completely different. Retroarch is one program, Emulation Station is a different program. Both programs do the same thing essentially. But comparing EmulationStation to xmb, rgui, ozone or glui which are basically skin engines in retroarch, is rediculous. Lakka is designed to be just enough OS to run retroarch, not retroarch and ...

Would it be to much to even add it if it's different UI/launcher? it still would be just enough of a OS just another gui option.

**Comment by RobLoach** [comment]
Yes...
- Allow configuration of which application to launch on boot
- New documentation for how to configure it
- Adding all the packages to build it properly
- Maintaining the upgrades for the packages
- Setting up the launch configuration for RetroArch across all platforms, along with which core is used
- Manage support requests surrounding emulation station
- etc

Again, if you're looking to use EmulationStation as a Frontend Launcher rather than RetroArch out of the box, I'd recommend looking at Recalbox, Batocera, or Retropie. There are a few others out there too... The other thing you could try is making your own fork of Lakka to try it out yourself!

**Comment by coreybruce** [comment]
Understandable, thanks for the chat.

**Comment by ShadowrunHerzogZwei** [comment]
I support. I thought about this too and googled this topic. This should have been done a long time ago. Why do you need two shells, one inside the other? It would be much more convenient if we removed all menu items from EmulationStation and replaced them with RetroArch. And then hide all unnecessary menu items in RetroArch. Plus make a console installer for Raspberry and Radxa and PC x86.
