### ISSUE TITLE
[Request] - Add SameDuck core (Mega Duck/Cougar Boy)

### ISSUE THREAD

**Issue by Levine91** [libretro/Lakka-LibreELEC#1632]
Hello, I'm just wanting to request the addition of the SameDuck core to Lakka, as it would make things far smoother for the very few of us who would love to play Mega Duck/Cougar Boy without going through MAME. Thanks!

**Comment by gouchi** [comment]
It seems there is a [branch SameDuck](https://github.com/LIJI32/SameBoy/tree/SameDuck).

Also @ToKe79 we might need to switch to [buildbot tree](https://github.com/libretro/SameBoy/tree/buildbot) from the Libretro repo as it is the default one. 

I don't know the difference between the SameDuck libretro core and the upstream one which also supports Libretro.

**Comment by ToKe79** [comment]
I think that builds SameBoy, but the [upstream branch](https://github.com/LIJI32/SameBoy/tree/SameDuck) seems to be the right spot. I will push PR, package is ready.

**Comment by ToKe79** [comment]
@Levine91 can you test image from [here](http://nightly.builds.lakka.tv/PRs/pr_1633_000476/), if the core works as you expect?
