### ISSUE TITLE
Add SAME_CDI core 

### ISSUE THREAD

**Issue by Eusino** [libretro/Lakka-LibreELEC#1636]
Hi! 
Would it be possible to add this core to Lakka?
https://github.com/libretro/same_cdi

**Comment by ToKe79** [comment]
@Eusino you can test image from here, which includes the same_cdi core - http://nightly.builds.lakka.tv/PRs/pr_1654_000490/

**Comment by ToKe79** [comment]
@Eusino the core can be downloaded from [here](https://nightly.builds.lakka.tv/members/vudiq/same_cdi/), then store it in `/tmp/cores` / samba share `Cores` / copy to `LAKKA_DISK:/cores`.
