### ISSUE TITLE
Black screen when booting Lakka USB

### ISSUE THREAD

**Issue by RedCoder09** [libretro/Lakka-LibreELEC#1637]
I'm trying to install Lakka on an old Dell Inspiron PC, but when I boot live or installer, the screen just goes black. No berry, no nothing. It has an Intel Pentium inside, and it seems that it's using the wrong video output. I have Windows 10 on it, and have tried the stable and nightly builds. Any help appreciated!

**Comment by gouchi** [comment]
Please try to boot with boot parameters 

`live ssh textmode`

Then provide some log with [createlog](https://lakka.tv/doc/Troubleshooting-Lakka/).

Thank you.

**Comment by RedCoder09** [comment]
Textmode doesn't work either.

**Comment by ToKe79** [comment]
Hi @RedCoder09,
you mentioned, that you suspect that it is outputting to the wrong video output - can you be more specific on your hardware, mostly GPU(s)? Can you try the other video outpu?
Thanks!

**Comment by RedCoder09** [comment]
I have an ATI Mobility Radeon HD 4300 Series GPU, and I unfortunately don't have the cable needed for connecting to another display.

**Comment by gouchi** [comment]
You may try to [ssh to the station](https://www.lakka.tv/doc/Finding-the-IP-of-your-Lakka-box/) if you plugged Ethernet cable.

**Comment by RedCoder09** [comment]
It's not showing up either.

**Comment by gouchi** [comment]
Strange try to add `debugging` so boot with `live ssh textmode debugging`

Thank you.

**Comment by RedCoder09** [comment]
Nope, still not working.

**Comment by gouchi** [comment]
You should try to get another cable or adapter of the the other output. You tried DVI output but you don't have VGA cable ?

**Comment by RedCoder09** [comment]
No, I can't try either.

**Comment by gouchi** [comment]
As you can't use other cable, you may try to force video output using something like on boot parameters depending of your cable 

Force DVI output and disable VGA 
`video=DVI-I-1:1024x768@85 video=VGA-1:d`

Or force VGA output and disable DVI
`video=VGA-1:640x480@75 video=DVI-I-1:d`

[Source](https://wiki.archlinux.org/title/kernel_mode_setting#Forcing_modes)

**Comment by gouchi** [comment]
@RedCoder09 Did you have the opportunity to make some test ?

**Comment by Ntemis** [comment]
Unsupported gpu

**Comment by RedCoder09** [comment]
I believe it was working fine before, when I tried to reinstall Lakka is when the issues started. As such, I have reason to believe that the GPU is supported.

**Comment by Ntemis** [comment]
Try this one but with a clean image https://nightly.builds.lakka.tv/2022-06-05/Generic.x86_64/
And by the way ATI Mobility Radeon HD 4300 Series GPU has no Windows 10 drivers so i take your words with a pinch of salt

**Comment by Ntemis** [comment]
No feedback closing down permanently

**Comment by RedCoder09** [comment]
Unfortunately I did not.
