### ISSUE TITLE
Second wiimote doesn't connect automaticaly

### ISSUE THREAD

**Issue by aitor-hernandez** [libretro/Lakka-LibreELEC#164]
I have configured 2 wiimotes with the tutorial (http://www.lakka.tv/doc/Wii-Remote/), but after reboot just one of the wiiimotes connects when I push the buttons 1+2, I must connect the second with the console (connect <MAC>).

Also, when both wiimotes are connected, the led 1 is on in both.

Laka version: 2.0
System hardware: RPi3

**Comment by SebDominguez** [comment]
I only have one Wiimote configured and each time the Pi reboot I can't get the controller to be reconnected by pressing 1 + 2.
