### ISSUE TITLE
Wi-fi connmanctl error

### ISSUE THREAD

**Issue by Nill2016** [libretro/Lakka-LibreELEC#165]
connmanctl I do not understand how this works, can anyone help? The following statement appears: Error getting VPN connections: The name net.connman.vpn was not provided by any

**Comment by Kivutar** [comment]
What hardware are you using?

**Comment by Nill2016** [comment]
Orange Pi PC Plus

**Comment by Kivutar** [comment]
I think it's a know bug then. Can you confirm @Ntemis ?

**Comment by Ntemis** [comment]
we need to add systemctl service to start connman

**Comment by Kivutar** [comment]
How some it's not yet there? Or maybe I don't get what it is

**Comment by ToKe79** [comment]
I was looking at the `package.mk` of `connman` package (in `packages/network/connman`) and maybe I miss someting obvious, but it looks like we do not copy the `system.d` files - there are two of them (`connman.service` and `network-online.service`) - in `post_makeinstall_target()` function.

**Comment by ToKe79** [comment]
Is this still an issue? I have checked again and the `$PKG_DIR/system.d/*.*` files are copied by the install script.
https://github.com/libretro/Lakka-LibreELEC/blob/6bc8da9f88273cc94fc9428e1e1ed6619b749d95/scripts/install#L85-L88
However in `/etc/dbus-1/system.d/connman.conf` there is really no `net.connman.vpn` - I guess no VPN support in Lakka?

**Comment by ToKe79** [comment]
no response. closing stale issue.
