### ISSUE TITLE
Freeze on lakka logo on x96 mini using AMLGX aarch64 4.0 image

### ISSUE THREAD

**Issue by sajjadsabzkar** [libretro/Lakka-LibreELEC#1659]
i bootable my sd card with etcher and plug sd card in my device boot successfully.  first step resize partition and reboot after 15 second is ok but after reboot device lock on lakka image and no happen anything.

- Which version of Lakka are you using? 4.0
- What system hardware are you using? x96mini 2g ram / 16g rom
- What did you do?  truning on device
- What did you expect to happen? boot to main menu lakka
- What happened instead? freeze at lakka logo

**Comment by ToKe79** [comment]
Hi, can you gather some logs by following [this guide](https://github.com/libretro/Lakka-LibreELEC/wiki/Troubleshooting-Lakka#troubleshooting-stuck-on-lakka-flower-logo) - as you have Amlogic device, you will have to edit `uEnv.ini` in the root of the SD card.

**Comment by sajjadsabzkar** [comment]
> Hi, can you gather some logs by following [this guide](https://github.com/libretro/Lakka-LibreELEC/wiki/Troubleshooting-Lakka#troubleshooting-stuck-on-lakka-flower-logo) - as you have Amlogic device, you will have to edit `uEnv.ini` in the root of the SD card.

Ok i'll check it

**Comment by cesartaqui** [comment]
Same insue here. Lakka 4.0 pc 64bits USB image.

**Comment by ToKe79** [comment]
> Same insue here. Lakka 4.0 pc 64bits USB image.

If you have Nvidia GPU, we have a bug, you can try image from here - http://nightly.builds.lakka.tv/PRs/pr_1655_000488/

**Comment by cesartaqui** [comment]
> > Same insue here. Lakka 4.0 pc 64bits USB image.
> 
> If you have Nvidia GPU, we have a bug, you can try image from here - http://nightly.builds.lakka.tv/PRs/pr_1655_000488/

Yes! I have Nvidia GPU. Thanks!

**Comment by sajjadsabzkar** [comment]
> Hi, can you gather some logs by following [this guide](https://github.com/libretro/Lakka-LibreELEC/wiki/Troubleshooting-Lakka#troubleshooting-stuck-on-lakka-flower-logo) - as you have Amlogic device, you will have to edit `uEnv.ini` in the root of the SD card.

i followed  the guide and now i have shell / terminal for use . which command to start lakka main menu ?

**Comment by sajjadsabzkar** [comment]
i run command retroarch -v and save response to log.txt 
i also test Lakka-S905.arm-2.3.1.img.gz  version of lakka and everything is ok but in latest image this problem happen .
[log.txt](https://github.com/libretro/Lakka-LibreELEC/files/8338710/log.txt)

**Comment by ToKe79** [comment]
can you also give me output of `ldd /usr/bin/retroarch` and also `LIBGL_DEBUG=verbose retroarch -v`. Thank you!

**Comment by sajjadsabzkar** [comment]
> 



> can you also give me output of `ldd /usr/bin/retroarch` and also `LIBGL_DEBUG=
[libgl_d_retroarch.txt](https://github.com/libretro/Lakka-LibreELEC/files/8341043/libgl_d_retroarch.txt)
verbose retroarch -v`. Thank you!

Yes of course , output of `ldd /usr/bin/retroarch` into ldd_log.txt file and output of  `LIBGL_DEBUG=verbose retroarch -v` into libgl_d_retroarch.txt file 

[ldd_log.txt](https://github.com/libretro/Lakka-LibreELEC/files/8341041/ldd_log.txt)
[libgl_d_retroarch.txt](https://github.com/libretro/Lakka-LibreELEC/files/8341049/libgl_d_retroarch.txt)

**Comment by ToKe79** [comment]
okay, I think we would need full logs - after you get to the shell prompt and execute `systemctl start retroarch.target` (there will be no output to this command, only back to shell prompt), please run `createlog` to collect all logs. As you will have no network and probably do not have the possibilty to read the ext4 partition, select the option "2" - to store the archive with logs on the FAT32 partition. Then upload this file (will be named `log-<year>-<month>-<day>-<hour>-<minute>-<second>.zip`). Thank you!

**Comment by sajjadsabzkar** [comment]
> 



> okay, I think we would need full logs - after you get to the shell prompt and execute `systemctl start retroarch.target` (there will be no output to this command, only back to shell prompt), please run `createlog` to collect all logs. As you will have no network and probably do not have the possibilty to read the ext4 partition, select the option "2" - to store the archive with logs on the FAT32 partition. Then upload this file (will be named `log-<year>-<month>-<day>-<hour>-<minute>-<second>.zip`). Thank you!

Ok I upload the zip file contain all logs for you.

[log-1970-01-01-00.00.53.zip](https://github.com/libretro/Lakka-LibreELEC/files/8342003/log-1970-01-01-00.00.53.zip)

**Comment by ToKe79** [comment]
thank you - can you try image from here:
https://nightly.builds.lakka.tv/members/vudiq/AMLGX+mali_fbdev/

which DTB are you using?

**Comment by ToKe79** [comment]
@SajjadSabzkar you can ignore the previous comment, `mali_fbdev` would not help, as we are using `lima` opensource driver. but I made a build where RetroArch is configured for GLESv2 (instead of GLESv3): https://nightly.builds.lakka.tv/members/vudiq/AMLGX.aarch64-GLESv2only/

Can you please test with this build and provide logs?

I noticed in the `01_RetroArch.log` missing verbose output from libGL.

Thank you!

**Comment by ToKe79** [comment]
Additional question - is [Lakka 3.7](https://le-builds.lakka.tv/AMLGX.arm/Lakka-AMLGX.arm-3.7-box.img.gz) working on your TV Box?

**Comment by sajjadsabzkar** [comment]
> Thank you!

Hi , Yes of Course , Sorry to see your Comment now

**Comment by sajjadsabzkar** [comment]
> stion -

I'll test this version too

**Comment by sajjadsabzkar** [comment]
> @SajjadSabzkar you can ignore the previous comment, `mali_fbdev` would not help, as we are using `lima` opensource driver. but I made a build where RetroArch is configured for GLESv2 (instead of GLESv3): https://nightly.builds.lakka.tv/members/vudiq/AMLGX.aarch64-GLESv2only/
> 
> Can you please test with this build and provide logs?
> 
> I noticed in the `01_RetroArch.log` missing verbose output from libGL.
> 
> Thank you!

Hi , i followed your Comment and Upload the file .
[log-2021-10-29-09.25.18.zip](https://github.com/libretro/Lakka-LibreELEC/files/8473886/log-2021-10-29-09.25.18.zip)

**Comment by sajjadsabzkar** [comment]
> Additional question - is [Lakka 3.7](https://le-builds.lakka.tv/AMLGX.arm/Lakka-AMLGX.arm-3.7-box.img.gz) working on your TV Box?

I tested this version and this version is no work on my tvbox too

**Comment by igyenes** [comment]
@SajjadSabzkar Hello, can you please give this a try? 
https://drive.google.com/file/d/1gSzDkveByanIleJQ9eeuPswG0iV4jxSi/view?usp=sharing

**Comment by sajjadsabzkar** [comment]
> @SajjadSabzkar Hello, can you please give this a try? https://drive.google.com/file/d/1gSzDkveByanIleJQ9eeuPswG0iV4jxSi/view?usp=sharing

Yes Sure!

**Comment by sajjadsabzkar** [comment]
> @SajjadSabzkar Hello, can you please give this a try? https://drive.google.com/file/d/1gSzDkveByanIleJQ9eeuPswG0iV4jxSi/view?usp=sharing

Wow This Version is ok but Why ? :)

**Comment by igyenes** [comment]
Thanks for the feedback! 
Disabled the composite output, so it forces retroarch to start on the HDMI.

**Comment by sajjadsabzkar** [comment]
> Thanks for the feedback! Disabled the composite output, so it forces retroarch to start on the HDMI.

Thanks .
