### ISSUE TITLE
Genesis Plus GX - Only the "Wide" variant available

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#1667]
Hello!

I'd like to report that, as of version 4.0, the regular Genesis Plus GX core is missing from Lakka, while only the Wide variant core remains. Browsing through the available cores, I can see that the regular Genesis Plus GX is "available", but in name only – loading a content reveals it's the Wide core instead. Everything was normal up to version 3.7, but that changed after I upgraded to version 4.0 using the " online updater" option.

- Which version of Lakka are you using?
  Version 4.0, aarch64.
- What system hardware are you using?
  Raspberry Pi 4.
- What did you do?
  Used the "online updater" to upgrade Lakka from version 3.7 to 4.0.
- What did you expect to happen?
  To keep the regular Genesis Plus GX core present in the OS.
- What happened instead?
  Regular Genesis Plus GX core was replaced by the Genesis Plus GX Wide core, even though all name references still point to the regular one.

**Comment by ToKe79** [comment]
Try resetting the core association with the game in playlist.

**Comment by ToKe79** [comment]
ok, found the error in the package.mk - the wide core was copied to the image with the "regular" name. fixed in #1661

**Comment by ghost** [comment]
Thank you for helping!
