### ISSUE TITLE
[Feature request] Support Wi-Fi on Orange Pi Plus 2E (Realtek RTL8189ETV, IEEE 802.11 b/g/n)

### ISSUE THREAD

**Issue by d-apps** [libretro/Lakka-LibreELEC#1668]
Which version of Lakka are you using?
4.1

What system hardware are you using?
Orange Pi Plus 2E

What did you do?
Enter in Configuration, Wi-F, enable Wi-Fi, search for networks.

What did you expect to happen?
Show the networks available to connect.

What happened instead?
Networks are not showing.

Is it possible to support Wi-Fi in Orange Pi Plus 2E (Realtek RTL8189ETV, IEEE 802.11 b/g/n) please?

Thank you.

**Comment by ToKe79** [comment]
Hi,
based on information from [here](https://linux-sunxi.org/Wifi#:~:text=%C2%A0%3F%3F-,RTL8189ES%20/%20RTL8189ETV,make%20%2Dj4%20ARCH%3Darm%20CROSS_COMPILE%3Darm%2Dlinux%2Dgnu%2D%20KSRC%3D../linux,-RTL8189FTV) I added the driver/module. You can test with image from [here](https://nightly.builds.lakka.tv/members/vudiq/h3-rtl8189es/) and give me feedback. If positive, then it can be included in the next version.

**Comment by d-apps** [comment]
Hi,

Is there any way a can keep all the configurations I made in my current image installed, before installing this image? I have around 20gb of roms and lots of custom configs.

Thanks

Edit: I have another sd card, I will install it, thanks.

**Comment by d-apps** [comment]
@ToKe79 I just tested and it didn't work.

I enabled Wi-Fi, it scans, after scan complete it doesn't show any network.

**Comment by ToKe79** [comment]
please, provide some logs from the system.
[Troubleshooting Guide](http://www.lakka.tv/doc/Troubleshooting-Lakka/)

**Comment by d-apps** [comment]
> please, provide some logs from the system. [Troubleshooting Guide](http://www.lakka.tv/doc/Troubleshooting-Lakka/)

Sorry for the delay.
Logs were uploaded.

[log-2022-04-29-13.50.57.zip](https://github.com/libretro/Lakka-LibreELEC/files/8591289/log-2022-04-29-13.50.57.zip)

**Comment by Ntemis** [comment]
I checked and even after the driver is enabled there is no wifi in the system logs so the board file might need fixing + no one of the team owns this device so no way to fix it
