### ISSUE TITLE
No network on odroid c2 since Lakka 4.0

### ISSUE THREAD

**Issue by aeloya** [libretro/Lakka-LibreELEC#1679]
There is no network for eth0 in Lakka 4.0,  4.1 & 4.2
Last system message on screen tells that eth0 cannot be configured. 
In Network settings only 127.0.0.1 displayed. 
Lakka 3.7 works fine.

**Comment by Ntemis** [comment]
Odroid c2 works fine here, hw issue maybe?

**Comment by dehart** [comment]
@Ntemis I don't think it's a hardware issue. I have the exact same experience.

I've made some shots of the log. Hope it's useful

![PXL_20220812_000258850](https://user-images.githubusercontent.com/3679323/184347139-4f63fa24-2dc6-49ec-9696-ffd9b8b4bcb5.jpg)
![PXL_20220812_000330490](https://user-images.githubusercontent.com/3679323/184347145-96e28817-7a16-4e9d-baaf-92665ec99762.jpg)
![PXL_20220812_000515605](https://user-images.githubusercontent.com/3679323/184347151-6c9fd265-c411-43ab-8e04-8b7df17208fd.jpg)
