### ISSUE TITLE
outdated docs: 'The Bootloader' and 'Accessing Lakka command line interface'

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#168]
I have just tried to access the Bootloader in Lakka-LibreELEC and I'm finding that I evidently can't press tab to change the commands as in Lakka-OpenElec.

Two docs would seem to need updating:
* http://www.lakka.tv/doc/The-bootloader/
* http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/

If I get a chance in the next week or two I will try learn the new system and propose specific changes. For now I wanted to get the issue logged at least.

**Comment by Kivutar** [comment]
Done, thanks.
