### ISSUE TITLE
Failed to mount

### ISSUE THREAD

**Issue by nelson80s** [libretro/Lakka-LibreELEC#1682]
Good morning, I don't know if this is the right place, please correct me. Does anyone have any idea what it is or could help? 
My preference for Lakka for both PC and Arm S905x is because it is light, fast and well designed.
thanks
![Untitled](https://user-images.githubusercontent.com/103575065/163184703-427fded1-a841-4380-8f35-2e2cf116d094.jpg)
- -Which version of Lakka are you using?
- 4.1
- - What system hardware are you using?
- Amlogic S905x
- - What did you do?
I'm trying to install the new version 4.1 on a s905x box  I tried with several .dtb (p212 and etc) 
- -What did you expect to happen?
-The installation and the normal start of retroarch/lakka
- -What happened instead?
- the screen during boot looks like this according to the print. Freezes at failed to mount directories

**Comment by ToKe79** [comment]
during the very first boot, did you get messages regarding expanding storage partition? can you try flashing the image again? what exact TV box do you have (not only the SOC, but manufacturer/model)?

**Comment by nelson80s** [comment]
> during the very first boot, did you get messages regarding expanding storage partition? can you try flashing the image again? what exact TV box do you have (not only the SOC, but manufacturer/model)?


Sorry by delayed Feedback
Im newbie on these Technologies and github
Yes. The first boot was ok with expandings etc
This issue occurs at the second boot.
I will try with new lakka 4.2 
The tv box is a super console x pro 1gb p212
Tv is a smart lg 32 in 

Cheers
[edit]

This time, after the previous screen that I posted in the first post, the initial screen of retroarch appears, however, unusable (without cores, import content, etc)
DTB: meson-gxl-s905x-p212.dtb
Image: https://le-builds.lakka.tv/AMLGX.aarch64/Lakka-AMLGX.aarch64-4.2-box.img.gz
Ruffus to burn a 8gb sdcard. (attempted with etcher and other cards, but same results.
![IMG_1790](https://user-images.githubusercontent.com/103575065/165891477-9c053d89-8319-4685-8475-8f60a1e9005f.JPG)
![IMG_1789](https://user-images.githubusercontent.com/103575065/165891483-3e24e49a-691f-4d77-bf23-5147deacedf6.JPG)

**Comment by Ntemis** [comment]
Nobody from the team owns a console x pro  and looks like meson-gxl-s905x-p212.dtb is incompatible with your board,
tough luck
