### ISSUE TITLE
Intel UHD 750 GPU isn't detected - Couldn't find a suitable DRM device.

### ISSUE THREAD

**Issue by gyllegert** [libretro/Lakka-LibreELEC#1688]
Using Lakka 4.1 and the latest nightly (2022-04-20) to test.

The system is a Lenovo ThinkCentre M70q Gen2
i5-11500t
8GB RAM in single channel configuration
256GB NVME SSD

I had a look at the log and it ends like this i both 4.1 and the latest nightly build.
RetroArch [ERROR] :: [KMS]: Couldn't find a suitable DRM device.
RetroArch [INFO] :: Found GL context: null
RetroArch [INFO] :: Detecting screen resolution 320x240.
RetroArch [INFO] :: [GL]: Vendor: (null), Renderer: (null).
RetroArch [INFO] :: [GL]: Version: (null).

**Comment by ToKe79** [comment]
does your laptop have multiple display outputs? can you try disabling unused ones via kernel command line options by editing the `syslinux.cfg` and `EFI/BOOT/grub.cfg` files on the LAKKA partition? just add `video=<port>:d` after the text `quiet` to disable certain output port (it is enough just to modify the "live" section in each file). to get list of ports you can check first by editing the above files and only adding `textmode retroarch=0` after `quiet` and boot again. after you get the shell prompt just enter this command:

```
for port in /sys/class/drm/*/status ; do echo -n "${port}: " ; cat ${port} ; done
```

it will output something like:

```
/sys/class/drm/card0-HDMI-A-1/status: Disconnected
/sys/class/drm/card0-eDP-1/status: Connected
```

the `<port>` part for the kernel command line option is after `card0-` and before `/`, so in above example the values `HDMI-A-1` and `eDP-1`. It is possible that you have also composite output that is always enabled/connected?

**Comment by gyllegert** [comment]
Just to clarify, this is a desktop, but it does have multiple display outputs. HDMI and DP specifically.

I tried getting the status, but none of the folders within sys/class/drm/ contained a status folder. It seems like the device isn't initialized. Since I know the PC is connected using HDMI though I tried writing video=HDMI-A-1 in the cfg files just to test. I still get the Lakka flower with the Lakka (official): <version number> on the screen, but Retroarch never boots up.

After some digging around on various forums it seems like the 5.10 Linux kernel used in Lakka has issues with my specific GPU, and 5.11 doesn't have this issue. So I might just have to wait for an updated version of LibreElec.

**Comment by ToKe79** [comment]
please try build from here, it has Kernel version 5.17 - https://nightly.builds.lakka.tv/2022-04-19_LE-master/Generic.x86_64/

**Comment by gyllegert** [comment]
I tried but got this error

![image](https://user-images.githubusercontent.com/24224643/164423195-724d335b-7db1-4e0d-a56e-e8eea14573b8.jpeg)

I'm not sure what happened, but I tried two different flash drives just to make sure that wasn't the issue.

Thank you for looking into this by the way. :)

**Comment by ToKe79** [comment]
this tends to happen when Lakka is installed already on internal drive - or something else interferes with the mount process of the `LAKKA` (FAT32) partition. can you try unplugging all internal drives and use only the thumb drive to boot?

edit: it could also be that the image file on the server is corrupted, but I don't have a way of testing currently - how did you write it to the thumb drive? anyway - if the 4.1 image is booting, just RetroArch does not start (due to kernel not supporting your GPU), if you can mount the `LAKKA_DISK` (ext4) partition and put the tarball from the LE-master build into the `.update` folder, it will update the kernel/system from the tar.

Also during the boot of the LE-master - did you get grub or syslinux bootloader?

**Comment by gyllegert** [comment]
Hey!

I tried what you wrote in your edit and it totally worked! Retroarch boots just fine now. Thank you so much for your help, this might be a good temporary workaround for others having the same issue until a new version comes out. Apologies for this becoming more of a support post. It wasn't my intention.
