### ISSUE TITLE
Need mirrors?

### ISSUE THREAD

**Issue by karibuTW** [libretro/Lakka-LibreELEC#1690]
Hello,
I'm the admin of mirror.freedif.org and got few servers available in various locations.
Will you need some mirrors to support the projects?

I have 4 locations. Most needs are in Singapore as Asia is usually not that well covered.
But I can do France, Germany or Finland if needed (Usually pretty well covered)

Ping me if needed, I'll be pleased to contribute.

Thank you

**Comment by Ntemis** [comment]
Thank you for the kind offer please come to lakka.tv channel in retroarch discord and ping Demetris or Vudiq

**Comment by karibuTW** [comment]
Hello, I did twice. No reply so far.
Probably high workload ;)

**Comment by ToKe79** [comment]
Hi @karibuTW,

sorry for a late response.

Thank you very much for your offer. I personally do not think that project of this size would benefit from additional mirrors. We have one primary download server for stable releases / direct updates, and other server for dev builds. We also use the GitHub release assets for distribution via RPi Imager.

If other devs think there is additional benefit, please, speak out.

But as the images are freely available, they can be mirrored by anybody and we can just provide links to the mirrors, where the user can then browse for the image they want. I don't think that we will be maintaining list of direct links and redirect the user to a location closest to them.

**Comment by gouchi** [comment]
We might use mirror also as an "archive" for old builds.

**Comment by karibuTW** [comment]
Thanks @ToKe79 
Ping me if you need any infra. Happy to help

**Comment by Ntemis** [comment]
@ToKe79 I wanted this opportunity to remain feasible in case we need to move to a newer server that retroarch team uses which is ~6 times faster of the one we currently have for stable releases until we can enable the new links on the newer server after migration

**Comment by Ntemis** [comment]
Thank you for the offer but lets close this
