### ISSUE TITLE
Include PUAE 2021 Core

### ISSUE THREAD

**Issue by rsn8887** [libretro/Lakka-LibreELEC#1691]
Can the Commodore - Amiga (PUAE 2021) core be included in Lakka distros, especially for slower devices like ODroid and others? It is useful for games and cases where current PUAE struggles to run at full speed. PUAE 2021 seems is much faster than the current PUAE, and is already available in Retroarch on the Switch.

**Comment by gouchi** [comment]
[Source](https://git.libretro.com/libretro/libretro-uae2021/)

**Comment by rsn8887** [comment]
I think here is also the official source code here:
https://github.com/libretro/libretro-uae/tree/2.6.1

PUAE (2021) is simply branch 2.6.1 of the official PUAE core repository. The core name in the branch was changed to "puae2021", see here: https://github.com/libretro/libretro-uae/commit/6ecf1c6f1a0f61387f1d1a74e10cae18a60a66b6

**Comment by iconoclusterdotexe** [comment]
> I think here is also the official source code here:
> https://github.com/libretro/libretro-uae/tree/2.6.1
> 
> PUAE (2021) is simply branch 2.6.1 of the official PUAE core repository. The core name in the branch was changed to "puae2021", see here: https://github.com/libretro/libretro-uae/commit/6ecf1c6f1a0f61387f1d1a74e10cae18a60a66b6
> 

yes, but it is updated with the same (or similar) options as the master version.

**Comment by rsn8887** [comment]
With latest Lakka 4.2, PUAE was updated, and I am now getting slow-down in some Amiga games even on my Pi 400. So inclusion of PUAE2021 would be a great benefit on all systems, at least Pi 400 and slower.

**Comment by ToKe79** [comment]
@rsn8887 the core is now included in test images here: http://nightly.builds.lakka.tv/PRs/pr_1702_000522/
