### ISSUE TITLE
VOLUME BUTTONS NOT WORKING & VOLUME GAIN TOO HIGH (RG351MP)

### ISSUE THREAD

**Issue by blindm0use** [libretro/Lakka-LibreELEC#1694]
- Which version of Lakka are you using? 3.7.3
- What system hardware are you using? RG351MP
- What did you do? Volume Control
- What did you expect to happen? Volume Control buttons to work
- What happened instead? No reaction to volume control button presses
---
Sound volume buttons not working on Lakka.
Please add support for controlling volume with volume buttons. It just requires daemon listening for button presses.

Please do also fix volume gain on RG351MP, because the default volume gain level is too high while the volume level is too low, and, when increased - the sound gets distorted, which is not a case on any other roms available for RG351MP.

**Comment by zyliu-OU** [comment]
Did you try Lakka 4.0?

**Comment by blindm0use** [comment]
> Did you try Lakka 4.0?

Well, Lakka 4.0 is not available for RG351MP
