### ISSUE TITLE
[Orange Pi Plus 2E] System freeze after sometime of inactivity, cannot transfer list of roms

### ISSUE THREAD

**Issue by d-apps** [libretro/Lakka-LibreELEC#1695]
Which version of Lakka are you using?
4.1

What system hardware are you using?
Orange Pi Plus 2E

What did you do?
Open filezilla and connectec to device ip, selected some roms and started transfering to roms folder.

What did you expect to happen?
Roms gets transfered successfully.

What happened instead?
After some minutes the system freeze and system is not connectable through internet anymore.

I was trying to transfer a list of roms to my sd card and minutes after start transfering the system freezes and the connection was down, I tried multiple times.

With that issue in mind I would like to request if is it possible to enable roms folder through pc so I can transfer roms without internet, like emuELEC does, for example:

Only roms folder is mounted automatically when the sd card is connected to pc, so I can transfer roms there easy and very fast.

![image](https://user-images.githubusercontent.com/20110433/165961394-9e7c19ae-7dfa-443e-a4de-47a10f8d9bea.png)

[log-2022-04-29-13.50.57.zip](https://github.com/libretro/Lakka-LibreELEC/files/8591361/log-2022-04-29-13.50.57.zip)

**Comment by Ntemis** [comment]
We dont own any Orange Pi Plus 2E so we cant reproduce nor fix the issue
