### ISSUE TITLE
Quick menu freeze if opened with netplay enabled

### ISSUE THREAD

**Issue by d-apps** [libretro/Lakka-LibreELEC#1697]
Which version of Lakka are you using?
4.1

What system hardware are you using?
Orange Pi Plus 2E

What did you do?
While at game with netplay host enabled, I pressed the button to open retroarch's quick menu.

What did you expect to happen?
Quick menu navigation work.

What happened instead?
 Retroarch quick menu freeze, it only works if I disable netplay , which I had to use a hotkey button for that.

**Comment by gouchi** [comment]
Does it still happen with [Lakka 4.2](https://www.lakka.tv/get/) or [nightly builds](https://nightly.builds.lakka.tv/latest/H3.arm/) ?

Thank you.

**Comment by Ntemis** [comment]
No answer no feedback closing down
