### ISSUE TITLE
Dualshock 3 rumble/vibration not working

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/Lakka-LibreELEC#170]
- Which version of Lakka are you using?
2.0
- What system hardware are you using?
Orange Pi, USB Bluetooth adapter, Dualshock 3
- What did you do?
Play PS1 games using PCSX ReArmed.
I can confirm the rumble is working with other controllers. 
- What did you expect to happen?
Rumble should work on DS3.
- What happened instead?
Rumble does not work. The controller works alright otherwise.

Not sure if this is a feature request or regression.

**Comment by Diskutant** [comment]
Same here. Couldn't get rumble to work yet with either DS3 nor DS4.
(Lakka 2.0 on a Pi3)

**Comment by Kivutar** [comment]
We have `CONFIG_SONY_FF=y` in the kernel, so it must come from RetroArch..

**Comment by Ntemis** [comment]
Since we switched to mainline kernel am closing this
