### ISSUE TITLE
lakka partitions are not visible in windows, to edit config.txt (you assumed all use linux)

### ISSUE THREAD

**Issue by goofyseeker311** [libretro/Lakka-LibreELEC#1700]
please add partition fat32 support for windows, or just provide through ui editing of config files, this is a bug not a feature

**Comment by ToKe79** [comment]
Which config.txt are you trying to edit? The boot (`LAKKA`) partition is FAT32, the second partition (`LAKKA_DISK`) is ext4 and has to stay like that. You can manually repartition the disk and add partition(s) of your preference.

**Comment by goofyseeker311** [comment]
Sorry the FAT32 partition on the sd card did not appear in windows right
away.
