### ISSUE TITLE
Menu Shader Pipeline dissapears after setting it to OFF

### ISSUE THREAD

**Issue by valter12437** [libretro/Lakka-LibreELEC#1703]
- Which version of Lakka are you using?
4.2 arm

- What system hardware are you using?
Raspberry Pi 3 B +

- What did you do?
 I set the "Menu Shader Pipeline" option to "OFF"

- What did you expect to happen?
The option would remain in the menu to be changed again later

- What happened instead?
The option dissapeared completely.

**Comment by Ntemis** [comment]
Try the Aarch64 version too please and report back. Thanks

**Comment by valter12437** [comment]
It happens with the arch64 version as well

**Comment by Ntemis** [comment]
close this and open the issue here
https://github.com/libretro/RetroArch/issues
