### ISSUE TITLE
NTFS drive not working

### ISSUE THREAD

**Issue by Jonathan20122** [libretro/Lakka-LibreELEC#1705]
NTFS game drive not showing up. I am using the newest nightly build. I can get the drive to work on other formats on LAKKA but NTFS would be the most ideal format if I can get it to work.

**Comment by Ntemis** [comment]
We need some more context than this platform? what you tried so far ? did you try another ntfs drive?
NTFS should be supported and is for years now, take this to forum or come to discord channel , gh issues is not a place to seek help and def is not a bug to fix
