### ISSUE TITLE
[FEATURE REQUEST] Disconnect bluetooth controller after five minutes of inactivity

### ISSUE THREAD

**Issue by jclsn** [libretro/Lakka-LibreELEC#1706]
I know some controllers do this by default, but my Dual Sense controller just drains empty if you leave Lakka on. It would be great if it could automatically disconnect after five minutes.

**Comment by Moonlacer** [comment]
I think you need to clarify that it should just turn the controller off, and not remove the Bluetooth pairing profile

**Comment by jclsn** [comment]
I thought that would be clear. Who would think I would want to repair my controller every five minutes?

**Comment by Ntemis** [comment]
this is how your hardware works and bt driver has nothing to do with when your controller enters sleep state if ever
