### ISSUE TITLE
2560 x 1440p Resolution

### ISSUE THREAD

**Issue by FraggerFred** [libretro/Lakka-LibreELEC#1708]
I own a 4K TV and run retroarch in 1080p. Is it possible to manually run it in 1440p 60hz using config.txt? because obviously 4k would be too high. I used to have a resolution option in retroarch but for some reason it aint there anymore.
edit: I own a raspberry pi 400

**Comment by Ntemis** [comment]
We are no here to answer your questions bud, go to forum or come to lakka channel over discord for help
