### ISSUE TITLE
Not work bluetooth gamepad

### ISSUE THREAD

**Issue by bennington111** [libretro/Lakka-LibreELEC#1709]
Not work bluetooth gamepad on **PC**.
Lakka version - **4.2**, **4.0**.
Gamepad connect and pair, but not work. 
On Retroarch on windows 10, gamepad work great.
On Retroarch on Linux Mint, gamepad work great.
I save autoconfig file on Retroarch on Linux Mint - **V013.cfg** and put this file to **joypad** folder on Lakka. But gamepad not work.
How to fix this problem?
![IMG_20220610_124140](https://user-images.githubusercontent.com/36040586/173043484-b5745c0d-2b8a-4ad1-a973-b1f75d3a0d51.jpg)
![IMG_20220610_124211](https://user-images.githubusercontent.com/36040586/173043524-3bc08be8-fa48-4763-a139-9900bb78e142.jpg)
File V013.cfg
`input_driver = "udev"
input_device = "V013"
input_vendor_id = "1949"
input_product_id = "0402"
input_b_btn = "0"
input_y_btn = "3"
input_select_btn = "10"
input_start_btn = "11"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "4"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+5"
input_r_y_minus_axis = "-5"
input_gun_trigger_mbtn = "1"`

**Comment by Ntemis** [comment]
create a new config for your joystick/gamepad and send a pr here https://github.com/libretro/retroarch-joypad-autoconfig
