### ISSUE TITLE
Problems with build image for Odroid XU4

### ISSUE THREAD

**Issue by Split7fire** [libretro/Lakka-LibreELEC#1710]
Trying to build Lakka for Odroid XU4. At package number 258 I got an errors:
`error: 'struct mm_struct' has no member named 'mmap_sem'; did you mean 'mmap_base'?`
Seems that mali driver dont match linux 5.10.76. Any ideas?
P.S. I attach full log.
[258.log](https://github.com/libretro/Lakka-LibreELEC/files/8883773/258.log)

**Comment by Ntemis** [comment]
Odroid XU4 has no panfrost support and we consider that board EOL for us, we wont go back to libmali.
I would advice you to open an issue on mesa gitlab asking for gpu support and maybe if enough people do this we might revive it if ever. Salut
