### ISSUE TITLE
laka freezes than restarts when using the online updater GPI Case Raspberry pi zero W 2

### ISSUE THREAD

**Issue by coreybruce** [libretro/Lakka-LibreELEC#1712]
Hey all just wanted to report a ongoing bug on the Gpi Case powered by the Raspberry pi zero W 2.

If you use the online updater to update to the latest nightly build it will freeze than eventually restart the lakka UI and fail to download.

**Comment by Ntemis** [comment]
Unfortunately is humanly impossible to have all the after market gadgets if any, so some bugs can only being addressed by the individual owners of the said ones. The other way around is to send them our way so we can research the issue and fix it ourselves but until then the issue will remain unresolved

**Comment by coreybruce** [comment]
Well hang on don't close it yet, I'm just reporting the bug but your forgetting the other people who have this device and help develop and bug test this.

Let's wait for more people to come in first and they can help debug the issue with more knowledge and still than I have to actually figure the issue out :)

**Comment by Ntemis** [comment]
Sure but this cant stay open forever though i"ll give it a few months give or take because actually is not a lakka issue but a developer shortage issue

**Comment by coreybruce** [comment]
Yeah that's understandable, I'm sure the community can help with this

**Comment by smilerliu** [comment]
I've had this problem for a long time, on both Pi Zero W and Pi Zero W 2. The workaround is to just ssh in and use wget to download the update file into the update folder.

**Comment by coreybruce** [comment]
> I've had this problem for a long time, on both Pi Zero W and Pi Zero W 2. The workaround is to just ssh in and use wget to download the update file into the update folder.

Yeah that's pretty much how I've been manually updating but I was hoping the online updater would work which sucks

**Comment by Ntemis** [comment]
This is now expired @coreybruce Thank you for the reports

**Comment by coreybruce** [comment]
Can this please be re-opened, did this get fixed?

**Comment by ToKe79** [comment]
Currently there is no plan to fix this, as it is related to the limited memory of the device and how RA downloads the update (caches to memory, when complete dumps to storage). You have to use `lakka-update.sh` script from shell (or wget).

**Comment by coreybruce** [comment]
> Currently there is no plan to fix this, as it is related to the limited memory of the device and how RA downloads the update (caches to memory, when complete dumps to storage). You have to use `lakka-update.sh` script from shell (or wget).

Ah so it can't do the updater because it only has 512mbs of ram? I know you said there was no plans to fix this but couldn't this be optimised and just not cache it to memory for low memory devices?
