### ISSUE TITLE
Battery life issues GPI Case 1 Raspberry pi zero w 2

### ISSUE THREAD

**Issue by coreybruce** [libretro/Lakka-LibreELEC#1716]
Hey guys just wanted to report a issue with the battery life on the GPI Case 1 Raspberry pi zero w 2. I have been using the nightly releases and noticed my battery life has been poor and a using 3 2000mah rechargeable energizer batteries with the screen brightness turned right down which would last for many hours in the past but I am not sure if it's a bug or batteries but I wanted to check with people using the latest nightly updates if they had the same issues or not.

**Comment by Ntemis** [comment]
take it to the forum
