### ISSUE TITLE
Feature Request - 'System Information' include available space of /storage

### ISSUE THREAD

**Issue by jdalmanza** [libretro/Lakka-LibreELEC#1719]
i know you can ssh into your lakka device and run the df -h command to see how much space is used, but I think users would benefit from including similar df output in the 'System Information' menu item, perhaps derive the available space % from the df output of the /storage mount point?

**Comment by Ntemis** [comment]
We offer what retroarch GUI has to offer any deviation and we have to keep patching it to kingdom come no thank you.
Report this as a request to retroarch github they might listen they might not ¯\_(ツ)_/¯
