### ISSUE TITLE
Include: JACK Audio for x86

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#172]
Not sure if this applies to the other builds but for x86 at least can you please include 'JACK Audio' as a selection for the audio driver alongside 'Alsa' and 'Alsathread'.

It is included as part of the standalone Linux build of Retroarch https://github.com/libretro/RetroArch/blob/master/audio/drivers/jack.c

**Comment by Kivutar** [comment]
Do I need to package http://jackaudio.org/downloads/ or jackd?
