### ISSUE TITLE
FTP transfer speed on wired network.

### ISSUE THREAD

**Issue by greatliu** [libretro/Lakka-LibreELEC#1723]
Dear author,
I found that if WiFi is connected, the FTP transfer speed on wired network will be limited as same as using WiFi.
It happened on every version of lakka X86.

Hope it will be improved.

**Comment by gouchi** [comment]
Hi,

I don't remember we have FTP ? We have SFTP or Samba. 

Which software did you use ? You did try wit Filezilla or Winscp as describe in the [documentation](https://www.lakka.tv/doc/Accessing-Lakka-filesystem/) ?

Can you give us some screenshot for the speed but I am not sure we can optimize it.

Thank you.

**Comment by greatliu** [comment]
Hi, frined.
I use Filezilla to transfer.

I do not know how to show you screenshot, sorry. I will describe this problem with detail:
1. connect WiFi;
2. in "network information", lakka will display 2 IP: one is wlan, another is eth0;
3. transfer files by Filezilla using eth0's IP, you will find the speed is the same as using WiFi (less than 100mb/s);
4. get off wifi, then reboot lakka, transfer files by Filezilla using eth0's IP, the speed is recovered to gigabyte.

I just tried it, the problem is still as I said.

Thanks.

**Comment by barrystaes** [comment]
@greatliu what happens if you connect to a unrelated WiFi network such as your phone hotspot, and then try to FTP with something on your LAN via wire? In case you have a VPN running on Lakka disable it temporarily.
