### ISSUE TITLE
Chinese characters are not displayed correctly for the widget osd

### ISSUE THREAD

**Issue by greatliu** [libretro/Lakka-LibreELEC#1724]
Dear author,
I found that when I use Chinese UI language, some characters displayed as "口". Especially in the pop-up message in the left-buttom.
Can you improve this bug?

all the X86 lakka version have this bug, since lakka supported Chinese.

**Comment by gouchi** [comment]
Hi,

Can you try [this](https://github.com/libretro/Lakka-LibreELEC/issues/1354#issuecomment-880622077) if you are using xmb menu ?

You can find some fonts in `/usr/share/retroarch-assets/pkg`

Thank you.

**Comment by greatliu** [comment]
Hi, firend.
As your reply, I just have tried all the fonts in /usr/share/retroarch-assets/pkg. Unfortunately, all of them diaplay Chinese characters as "口".

And, I wish all the lakka UI can display Chinese characters correctly. I usually use "OZONE", It can do in retroarch on windows 10. 

Can you help?

**Comment by gouchi** [comment]
If you are using xmb you need to restart RetroArch after you changed the font.

**Comment by greatliu** [comment]
> If you are using xmb you need to restart RetroArch after you changed the font.
I confirm restarted, the problem is still unsolved.

**Comment by gouchi** [comment]
I can't reproduce your issue using [nightly build](https://nightly.builds.lakka.tv/2022-08-04/Generic.x86_64/Lakka-Generic.x86_64-nightly-v4.x-20220804-9e969c4.img.gz) and `chinese-fallback-font.ttf`.

![font](https://user-images.githubusercontent.com/7869503/183306314-09301fdb-97c0-480b-a5ac-411ecc19541a.jpg)

You have to restart RA

![restart](https://user-images.githubusercontent.com/7869503/183306328-4e834e6f-4953-4e71-a847-e307624788c7.jpg)

And Ozone menu is working also in Chinese.

![ozone](https://user-images.githubusercontent.com/7869503/183306343-7a0fbc55-d625-478c-87e0-4684c01b9f0f.jpg)

**Comment by greatliu** [comment]
> I can't reproduce your issue using [nightly build](https://nightly.builds.lakka.tv/2022-08-04/Generic.x86_64/Lakka-Generic.x86_64-nightly-v4.x-20220804-9e969c4.img.gz) and `chinese-fallback-font.ttf`.
> 
> ![font](https://user-images.githubusercontent.com/7869503/183306314-09301fdb-97c0-480b-a5ac-411ecc19541a.jpg)
> 
> You have to restart RA
> 
> ![restart](https://user-images.githubusercontent.com/7869503/183306328-4e834e6f-4953-4e71-a847-e307624788c7.jpg)
> 
> And Ozone menu is working also in Chinese.
> 
> ![ozone](https://user-images.githubusercontent.com/7869503/183306343-7a0fbc55-d625-478c-87e0-4684c01b9f0f.jpg)

My version is 4.2 release, there were no chinese-fallback-font.ttf in dir. I downloaded some kinds of Chinese fonts and tested (sorry I did not find chinese-fallback-font.ttf to download). It runs, the main UI displays correctly, but the on-screen display message in the left-buttom, there were some "口" still.
Finally, I changed the on-screen display setting, selectd the Chinese font, it works correctly.

So, the problem is, the default on-screen display font did not completely support Chinese character.

The main UI displays Chinese correctly on default setting, so I advice the default on-screen display font use the same font as main UI.

Thank you very much for your help and patience,
