### ISSUE TITLE
Cannot control volume by keyboard hotkey.

### ISSUE THREAD

**Issue by greatliu** [libretro/Lakka-LibreELEC#1725]
Dear author,
I found Lakka cannot use the "volume+" and "volume-" button, so when I run Lakka on some laptop or all-in-one computer, I need to use Lakka menu to control volume.
I tried, and found that Lakka cannot recognize the "volume+" and "volume-" hotkeys on all keyboards at all.
I think keyboard hotkeys is useful for laptop or all-in-one computer users.
Lakka version: X86.

Can you add this function? Thanks.

**Comment by gouchi** [comment]
Hi,

By default, it should be `-` and `+` . You can change it from `Settings tab > Input > Hotkeys > Volume Up/Down`.

Thank you.

**Comment by greatliu** [comment]
> Hi,
> 
> By default, it should be `-` and `+` . You can change it from `Settings tab > Input > Hotkeys > Volume Up/Down`.
> 
> Thank you.

Hi,
Thanks for your notify.

But if I use lakka on an all-in-one computer without keyboard, it is still a problem.
Can lakka support  "volume+" and "volume-" keyboard hotkeys?

**Comment by gouchi** [comment]
I will close this issue as there is [one](https://github.com/libretro/RetroArch/issues/14298) opened on RetroArch issue tracker.
