### ISSUE TITLE
Please add encryption/luks support for file systems

### ISSUE THREAD

**Issue by pasnox** [libretro/Lakka-LibreELEC#1727]
LibreElec, on which is based Lakka does not support encryption / luks by default.
Though, there is a small community fork that enable that.
I would like to see lakka supporting encrytion as well.
See https://forum.libreelec.tv/thread/20338-le-9-2-with-lvm2-luks-dm-crypt-veracrypt-ext4-encryption-and-some-newclock5-kodi/ for more information.

**Comment by Ntemis** [comment]
Am not against this but i think you should take this upsteam https://github.com/LibreELEC/LibreELEC.tv/issues
Then we can have it and stay maintained so a win-win  for everyone.
Also feel free to send them a pr if you like.

**Comment by pasnox** [comment]
They want not that feature in LE - not enough user friendly 😭
