### ISSUE TITLE
dosbox-core inclusion in Lakka

### ISSUE THREAD

**Issue by vanfanel** [libretro/Lakka-LibreELEC#1730]
Hi!

After years and years of bad audio/video sync in DOSBox sourceports, I finally found out the perfect DOS core: dosbox-core (https://github.com/libretro/dosbox-core) by @realnc

This core is unique in that it allows perfect audio and video synchronization, allowing games like SuperFrog, Turrican II, etc... to run with PERFECTLY smooth scroll, unlike other DOS cores.

So, can this core please be included in Lakka? Really, this is the good one.

Thanks!

**Comment by gouchi** [comment]
@Ntemis @ToKe79 @RobLoach So we should consider it and it should replace dosbox-libretro and dosbox-svn.

> Dosbox-core is a replacement for both -libretro and -svn.

We should make a note in the release if we replace it so that people know they have to switch to the new one.
