### ISSUE TITLE
Error while compiling RPi4 aarch64 with same_cdi libretro core

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#1731]
I was compiling the newest version of lakka(atm) and i got this error
FAILURE: scripts/build same_cdi:target during make_target (package.mk)
*********** FAILED COMMAND ***********
make ${PKG_MAKE_OPTS_TARGET}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install same_cdi:target has failed!

[312.log](https://github.com/libretro/Lakka-LibreELEC/files/9378480/312.log)

Thoughts?

**Comment by gouchi** [comment]
Hi,

Can you retry with

`DISTRO=Lakka PROJECT=RPi DEVICE=RPi4 ARCH=aarch64 scripts/clean same_cdi`

then

`DISTRO=Lakka PROJECT=RPi DEVICE=RPi4 ARCH=aarch64 scripts/build same_cdi`

Thank you.

**Comment by Ntemis** [comment]
No feedback since open, closing down
