### ISSUE TITLE
Fresh installation won't boot on Raspberry Pi 1 (Model B)

### ISSUE THREAD

**Issue by danielemegna** [libretro/Lakka-LibreELEC#1732]
> Which version of Lakka are you using?

Latest official stable build Lakka-RPi.arm-4.2

> What system hardware are you using?

Raspberry Pi 1 Model B

> What did you do?

Flash the downloaded image `Lakka-RPi.arm-4.2.img.gz` via Balena Etcher on a large sd card (64gb) and boot it.

> What did you expect to happen?

First boot with resizing file system phase, automatic reboot and first boot on retroarch interface.

> What happened instead?

- succefully first boot with resizing file system phase
- automatic reboot
- failure on any next os boot with just this log on screen

```
Lakka (official): 4.2
[ TIME ] Timed out waiting for device /dev/serial1.
[DEPEND] Dependency failed for Broadcom sdio firmware update for BCH43430A1.
[FAILED] Failed to start Samba NMB Daemon.
[FAILED] Failed to start Samba MMD Daemon.
[FAILED] Failed to start Samba SMB Daemon.
[FAILED] Failed to start Samba NMB Daemon.
[FAILED] Failed to start Samba NMB Daemon.
[FAILED] Failed to start Samba SMD Daemon.
[FAILED] Failed to start Samba NMB Daemon.
```

![image](https://user-images.githubusercontent.com/5415893/185812772-f33b8dec-d286-4d52-bbc7-e4044b350f13.png)

Am I doing something wrong?

**Comment by danielemegna** [comment]
Just given a try also to latest nightly build `Lakka-RPi.arm-nightly-v4.x-20220804-9e969c4`, same behavior.

**Comment by gouchi** [comment]
Hi,

I could make a test on RPi  1 Model B+ with `Lakka-RPi.arm-4.2.img.gz` and it is working.

You should try to ask some feedback on our [Discord channel](https://discord.gg/BNFR4hM) if possible.

Thank you.

Kind regards,

**Comment by danielemegna** [comment]
Ouch.. the only different seems to be `Model B` vs `Model B+` :disappointed: 
Thank you @gouchi anyway.

**Comment by nayaabkhan** [comment]
@danielemegna I'm having the same issue, I see you closed the issue. Could you please guide me on how did you manage to solve this?

**Comment by danielemegna** [comment]
No, I didn't solve sadly .. let me know if you discover something new

**Comment by nayaabkhan** [comment]
Ah, that's a bummer. I'll be sure to update if I find a fix. Meanwhile, I was wondering if it is possible for you to reopen this issue. If not I'll file a new one.

**Comment by nayaabkhan** [comment]
So I had no luck fixing the issue on first boot (after partition resizing). It is stuck on "Failed to start Samba SMB Daemon." forever. So I went for compiling RetroArch instead. After a few days of work, I've successfully compiled it and it works like a charm!

For anyone else looking to put their Raspberry Pi 1 to work and has issues with Lakka, they can follow the steps here:
https://github.com/nayaabkhan/rpi1b-retroarch

**Comment by Ntemis** [comment]
can you guys try the 4.3 release

**Comment by LRyu2** [comment]
I try 4.3 stable and nightly 2023 01 30 releases on Rpi4 and I the same bug : fresh installation won't boot.


    What happened instead?

    succefully first boot with resizing file system phase
    automatic reboot
    failure on any now os boot with just the screen logo and version

It is curious this so brutal bug on a new version... the release is tested on which hardware before release ?

**Comment by danielemegna** [comment]
I'm giving a try to latest `Lakka-RPi.arm-4.3.img` for _Raspberry Pi (arm)_ . I'll update you soon.

**Comment by danielemegna** [comment]
Sadly nothing changed on my _Raspberry Pi 1 Model B_.

Nice and smooth first boot with resize and reboot phases:
![image](https://user-images.githubusercontent.com/5415893/216368227-6e65f677-088c-41cf-8bab-06cffecfd52b.png)

Stuck on every next boot, also waiting for several minutes:

![image](https://user-images.githubusercontent.com/5415893/216368988-488f8c9e-1a9f-4206-9c63-2650d92e8705.png)

:sob: :sob: :sob:

**Comment by danielemegna** [comment]
> For anyone else looking to put their Raspberry Pi 1 to work and has issues with Lakka, they can follow the steps here:
> https://github.com/nayaabkhan/rpi1b-retroarch

could you please restore the content on this link @nayaabkhan ? https://github.com/nayaabkhan/rpi1b-retroarch

**Comment by nayaabkhan** [comment]
@danielemegna Uh oh, the repo was private. Now should be OK.

**Comment by gouchi** [comment]
Hi,

Is it working with [Lakka 5.x build](https://nightly.builds.lakka.tv/devbuild_latest/RPi.arm/) ?

Thank you.

**Comment by danielemegna** [comment]
> Hi,
> 
> Is it working with [Lakka 5.x build](https://nightly.builds.lakka.tv/devbuild_latest/RPi.arm/) ?
> 
> Thank you.

Ok @gouchi  I'll give a try in the weekend and I'll update you :+1:

**Comment by danielemegna** [comment]
Sadly is going worst. Immediate kernel panic at the first boot for missing shared library `libzstd.so`:

![image](https://github.com/libretro/Lakka-LibreELEC/assets/5415893/83f95d37-69f8-48c3-8ee2-6f09363b3553)

I tried both `Lakka-RPi.arm-devbuild-v5.x-20231225-36e7aeb` and `Lakka-RPi.arm-devbuild-v5.x-20231229-3cd3d02`

**Comment by ToKe79** [comment]
this behavior is very strange - have you tried different SD card?

**Comment by ToKe79** [comment]
this might be related to neon support - probably model b does not support neon. anyway, nothing that we can/will fix most probably.
