### ISSUE TITLE
My new XFX Radeon RX 6400 Video Card hangs at flower

### ISSUE THREAD

**Issue by TinkerStuff** [libretro/Lakka-LibreELEC#1738]
Full Video Card Product Finder:
XFX SPEEDSTER SWFT105 Radeon RX 6400 4GB GDDR6 PCI Express 4.0 Low Profile Video Card RX-64XL4SFG2

Is this card currently supported?  
I verified it works booting to Windows10 just fine, proper drivers installed.
My previous RX 4100 Pro worked fine.  
The RX 6400 seems to be a popular card for mini gaming rigs now since its one of the very few modern single-slot low-profile cards available. 

I tried the most recent devel build hoping for a fix contained within, but sadly no.
devel-20220908123921-9e969c4

I've tried stopping the service, editing the retroarch.cfg file to change to various video_driver="gl" (and "glcore", "vulkan") but still stuck.

I have attached the relevant logs.

[log-2022-09-10-08.39.55.zip](https://github.com/libretro/Lakka-LibreELEC/files/9539912/log-2022-09-10-08.39.55.zip)

Thanks in advance!

**Comment by gouchi** [comment]
Hi,

May you try to make a test with this [testing build](https://nightly.builds.lakka.tv/members/gouchi/master/Lakka-Generic.x86_64-LE-master-devel-20220724114930-4f0cf20.img.gz) ?

Thank you.

**Comment by TinkerStuff** [comment]
Thanks for such a quick response!  
The menu loads with gl / glcore drivers.  Games seems to work fine.
Vulkan driver won't load the menu.

Again, Thank you!

**Comment by TinkerStuff** [comment]
Leaving open until the fix appears in one of the nightly releases, or unless OK to close now.

**Comment by Ntemis** [comment]
Should be fixed once 5.x nightlies start rolling

**Comment by gouchi** [comment]
Can you try to make a test with [dev build from Lakka 5.x](https://nightly.builds.lakka.tv/devbuild_latest/Generic.x86_64/) ?

Thank you.

**Comment by Axallon** [comment]
Hello, I also recently got an XFX Speedster Radeon RX 6400 Low Profile, hoping for better Vulkan compatibility. I used your link to the Lakka 5.x devbuild. It works! Lakka loads to menu, I can switch the video driver to Vulkan, reboot, and when I go back into the video drivers it detects my new AMD Radeon RX 6400.
I did notice the LAKKA_DISK partition is only 34 MB, so I cannot copy any of my PS2 ROMs to it. My Linux PC will not let me repartition it.
Is there another 5.x version of the devbuild that will allow more space on the LAKKA_DISK partition? I would like to test Vulkan compatibility with LRPS2 (PCSX2).

**Comment by ToKe79** [comment]
LAKKA_DISK should be expanded to the full size of your USB thumb drive during the first boot. If it did not, flash the image again and boot from it. you should see messages on screen during the first boot regarding the expansion of the second partition followed by a countdown and reboot.

**Comment by Axallon** [comment]
I have used Lakka v4.2 and v4.3 and it does just that - on the first boot it creates the LAKKA_DISK partition and automatically expands to fill the remaining disk space. The 5.x devbuild, however, did not. It created LAKKA_DISK, but with only 34 MB partition.
![LAKKA_DISK Partition](https://user-images.githubusercontent.com/124916208/217977218-11d8e74a-210c-4a09-b6d6-e5d22e2737cc.png)

**Comment by ToKe79** [comment]
@Axallon can you check the ext4 partition on a Linux machine? There should a zero-sized hidden (dot) file - `.please_resize_me`. If it is not there, create it. This tells the init script that the partition needs resizing. Also there should be **no** `.kodi`, `.config` and `.cache` folder - if these exist, **remove them**. When these conditions are met, during boot the partition should be resized to the remaining space of the storage device.

**Comment by Axallon** [comment]
What file extension (filetype) does the .please_resize_me file need to be? I tried a folder and a txt, but neither worked.

**Comment by ToKe79** [comment]
It must be a file (not a folder) without any extension.

**Comment by gouchi** [comment]
@TinkerStuff @Axallon If it is ok with you we can close this issue as it is fixed in Lakka 5.x build ?

**Comment by gouchi** [comment]
Closing this issue as it is working using Lakka 5.x.
