### ISSUE TITLE
Retroarch restarts/crashes while browsing through playlists contents, if using thumbnails in Raspberry Pi 3 B

### ISSUE THREAD

**Issue by valter12437** [libretro/Lakka-LibreELEC#1743]
Using thumbnails, like boxarts, will make retroarch restart/crash after browsing through playlists contents quickly or for extended periods of time. Memory usage seems to either decrease extremely slowly or not at all , even if you stop scrolling for a time. Boxart seems to make the restart/crash happen faster.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
arm
Git Version: 9b282aa
Lakka Version: RPi2.arm.devel.20220908125848-9e969c4

aarch64
Git Version: 9b282aa
Lakka Version: RPi3.aarch64-devel-20220908130012-9e969c4

- What system hardware are you using?
Raspberry Pi 3 B, SanDisk 32gb class 10 micro sd card, 5v 3a power supply.

- What did you do?
Browsed through my playlists contents, either quickly or for extended periods of time, while using thumbnails.

- What did you expect to happen?
To be able to browse without problems.

- What happened instead?
Retroarch crashed/restarted.

- Attached log for arm version:
[log-2022-09-18-12.21.07-arm.zip](https://github.com/libretro/Lakka-LibreELEC/files/9594358/log-2022-09-18-12.21.07-arm.zip)

- Attached log for aarch64 version:
[log-2022-09-18-15.54.13-aarch64.zip](https://github.com/libretro/Lakka-LibreELEC/files/9594361/log-2022-09-18-15.54.13-aarch64.zip)

- Attached playlists:
[Playlists.zip](https://github.com/libretro/Lakka-LibreELEC/files/9594026/Playlists.zip)

**Comment by gouchi** [comment]
Thank you for the feedback it is a[ known issue](https://github.com/libretro/Lakka-LibreELEC/issues/1184).

And issues have been opened on RetroArch issue tracker [1](https://github.com/libretro/RetroArch/issues/12063) [2](https://github.com/libretro/RetroArch/issues/6747).

Thank you.
