### ISSUE TITLE
Iwlwifi driver not loading

### ISSUE THREAD

**Issue by Dehaj85** [libretro/Lakka-LibreELEC#1782]
iwlwifi driver is not loading when Lakka is installed. Iwlwifi driver should be incorporated with kernel 4.1 and up. Driver does not display when checking through command line terminal.  Firmware is in the lib directory

**Comment by gouchi** [comment]
On which architecture ?

Because it is already [enabled for some platform](https://github.com/libretro/Lakka-LibreELEC/search?q=CONFIG_IWLWIFI).

Thank you.

**Comment by Dehaj85** [comment]
It is an x86 system with an intel 8260 combo NIC with BT.  confirmed the NIC is working with a live version of unbuntu and windows so the NIC is not dead.

**Comment by gouchi** [comment]
Can you try to provide some with [log](https://lakka.tv/doc/Troubleshooting-Lakka/#automated-collection-of-relevant-logs) with `createlog` ?

Thank you.

**Comment by Ntemis** [comment]
No requested logs provided closing down, feel free to reopen
