### ISSUE TITLE
NSS compile for RPi2 will look for directory that does not exist

### ISSUE THREAD

**Issue by nekoprog** [libretro/Lakka-LibreELEC#1785]
All builds works fine except for plan number `165: install nss` which will cause an error that says make[3]: *** No rule to make target `Linux6.0_x86_armv7ve-libreelec-linux-gnueabihf-gcc-12.2.0_glibc_PTH_OPT.OBJ` but the directory on compiled package is `Linux6.0_arm_armv7ve-libreelec-linux-gnueabihf-gcc-12.2.0_glibc_PTH_OPT.OBJ`.

After renaming the said directories, build will resume without problem.

**Comment by by-gnome** [comment]
Not only for RPi2. However, after 2dfcbcdb3b423d45cbf4d9fe739b2af3852bc5ac this isuue can be closed.
