### ISSUE TITLE
LibreLakka: Build without non-commercial licensed software

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka-LibreELEC#179]
Create a build of Lakka, named LibreLakka, that doesn't have any non-commercial licensed software on it. Having LibreLakka will help manufactures who want a out-of-the-box Lakka-esque experience.

## Resources

- https://docs.libretro.com/tech/licenses/
- https://wiki.libreelec.tv/libreelec_faq#qam_i_allowed_to_sell_hardware_with_libreelec_pre-installed

**Comment by Kivutar** [comment]
For people who want to build a core-less image, here's how to do it:

Edit the option file in distributions/Lakka, and empty the core list.

**Comment by Kivutar** [comment]
Cores from the buildbot need to be tested on Lakka. This can be done by using the overlay system.

**Comment by RobLoach** [comment]
Going to close this one, feel free to re-open if interested. Thanks Kiv!

**Comment by RobLoach** [comment]
Re-purposing this issue to build LibreLakka, which would be Lakka, minus the non-commercial software. Removing the non-commercial cores and software would allow manufacturers to sell hardware with LibreLakka pre-installed.

It would be missing some features, but it is a step in the right direction. See the [libretro Licenses](https://docs.libretro.com/tech/licenses/) to see which software we would remove in this LibreLakka build.

**Comment by ToKe79** [comment]
Altough I do not support this idea (the manufacturers are able to build their own images without the cores that cannot be distributed with sold hardware), but I think that it could be passed as a build argument e.g. `LIBREBUILD=true` and then modify if LIBREBUILD = "true":

- LIBRETRO_CORES in distributions/Lakka/options
- LIBRETRO_CORES in packages/Generic/package.mk (remove I think some of the additional cores for Generic project have non-commercial license, or move this to project/NAME/options and modify there; the remaining depend packages can remain in package.mk) + any modify any additional projects that somewhere add libretro cores (not aware of any others)
- IMAGE_NAME in scripts/image to include "Libre" in image - e.g. LibreLakka-Generic.x86_64-2.1

and also add to config/options
```bash
if [ -z "$LIBREBUILD" ] ; then
  LIBREBUILD=false
else
  LIBREBUILD="$LIBREBUILD"
fi
```
Any other ideas?

**Comment by Ntemis** [comment]
Will be better to flag this as Nonfree=true/false

**Comment by ToKe79** [comment]
As `true` being default? = build including "nonfree" cores and image without "Libre*"

**Comment by bparker06** [comment]
To call it libre, wouldn't you also need to leave out the GPU blobs and any other non-free software not part of RetroArch?

**Comment by markwkidd** [comment]
I think that it would be a great step forward for the emulation community to have an integrated emulation software environment to steer manufacturers/hardware dealers towards rather than just away from.

I'm definitely subscribing to this issue. :)

**Comment by kivutar** [comment]
Ok. I agree with the env var idea of ToKe79.

I don't care much about the variable name, can be LIBRE or NONFREE or anything that is intuitive.

By default, it should build with the non-free software, because it is what we have been doing from the start.

Also, bparker's remark is right. But there are some parts that will always remain proprietary, for example:

 - the bootloader of RPi
 - GPU blobs like mali blobs

And certainly other packages that I forgot.

**Comment by twinaphex** [comment]
I think this is a very bad idea. 

At the very least if we are to make this, I wouldn't make this image open in any way. You don't want even more parasitism and abuse from these 'free-market' libertarians whom honestly just want to make free easy money off this project and deprive the host of any and all resources while they prop themselves up.

**Comment by Ntemis** [comment]
I fully agree with you. Is like giving them our hard work served in a hot plate to consume on our back with a frenic cashflow

**Comment by twinaphex** [comment]
Yeah. Fortunately, vudiq has removed the link on the nightlies so far, so that crisis has been averted for now. We can think this through in a much more smart fashion, and probably somewhere on either Discord or IRC itself.

**Comment by twinaphex** [comment]
Also, I have ordered the Lakka build servers now. E-mails were forwarded to kivutar, so hopefully Lakka will have fully working build servers shortly.

**Comment by TrashMacNugget** [comment]
@twinaphex As an end user; I try to have as little nonfree software in my life as possible. Not being able to do this without manually investigating and installing cores makes me less likely to use Lakka. What options are available for a regular user like me to use Lakka without any nonfree cores?

**Comment by natinusala** [comment]
Yes, remove any core you don't want from there and rebuild the image. Be aware that depending on your platform you won't be able to have a 100% free image.
