### ISSUE TITLE
Please add Wi-FI chipset support for RTL8821CU on x86-x64 build

### ISSUE THREAD

**Issue by welform** [libretro/Lakka-LibreELEC#1791]
More information on chipset:
https://www.realtek.com/en/products/communications-network-ics/item/rtl8821cu

When USB Wi-Fi device is plugged in, Lakka takes 30+ seconds to load displaying a dark screen, until normal Lakka screen comes up.
When the adapter USB Wi-Fi adapter is removed, Lakka boots up in seconds.
Thanks!

**Comment by gouchi** [comment]
Hi,

May you try to provide the [log from createlog](https://www.lakka.tv/doc/Troubleshooting-Lakka/) ?

Thank you.

Kind regards,

**Comment by Ntemis** [comment]
No response to log request, closing down
