### ISSUE TITLE
Lakka intermittent boot failure on Pine64 Plus

### ISSUE THREAD

**Issue by Matias314** [libretro/Lakka-LibreELEC#1792]
I'm using the latest Lakka nightly as of writing (aarch64 2022-11-19) on my Pine64+. It randomly does not boot. It's hard to put a number on it but I'd say about 30% of the time I power on the system it simply does not boot at all.

**Comment by gouchi** [comment]
Can you make a test with [dev builds from Lakka 5.x](https://nightly.builds.lakka.tv/devbuild_latest/) ?

Thank you.

**Comment by Matias314** [comment]
Hello, sorry for the late response. Is it possible to update without reinstalling?

**Comment by gouchi** [comment]
Hi,

Yes please read our [documentation](https://www.lakka.tv/doc/Upgrading-Lakka/).

Thank you.

**Comment by ToKe79** [comment]
closing stale issue
