### ISSUE TITLE
20 sec of black screen 

### ISSUE THREAD

**Issue by sorafire** [libretro/Lakka-LibreELEC#180]
i am using mxqbox M201D lakka

it take 20 sec of black screen after lakka logo and then it load 
is that normal ?

**Comment by Ntemis** [comment]
Depend on your sdcard performance and isnt that box 512mb ram only?

Στις 18 Ιουλ 2017 02:40, ο χρήστης "sorafire" <notifications@github.com>
έγραψε:

**Comment by sorafire** [comment]
i dont think so it says on the box 1 gb and i am using sanDisk ultra with a 10 on a circle  and it have a speed up to 80MB/s

**Comment by Ntemis** [comment]
ok so if you provide me with an up2date meson8b_m201d.dtb thats would
possibly fix your issues.
We are currently using this one
https://github.com/kszaq/LibreELEC.tv/blob/libreelec-8.2/projects/S805/patches/linux/meson8b_m201d_dtd.patch
Feel free to edit compile and test on you box(i don't have it) and sent us
a PR when fixed.
Regards

**Comment by sorafire** [comment]
i am new at this can you help ?
how to add this to a new image ?

**Comment by Ntemis** [comment]
Its added already but apparenlty needs fixing-> your job

Στις 21 Ιουλ 2017 17:18, ο χρήστης "sorafire" <notifications@github.com>
έγραψε:

**Comment by sorafire** [comment]
how to add it with program you use ?

**Comment by Ntemis** [comment]
Closing this as i have no intention to support every Chinese box ever created.
People should stick to something with Q&T
