### ISSUE TITLE
Unable to pair a Nintendo Controller Pro on Lakka 4.3 on Switch

### ISSUE THREAD

**Issue by czerwinski76** [libretro/Lakka-LibreELEC#1823]
Hi,
How to pair my controller please ?
I can only use joycons.

**Comment by ToKe79** [comment]
Hi @czerwinski76 
you either posted incorrect screenshot or you booted wrong thumb drive.

**Comment by czerwinski76** [comment]
> Hi @czerwinski76 you either posted incorrect screenshot or you booted wrong thumb drive.

Sorry, it was a mistake.

**Comment by GavinDarkglider** [comment]
This is an issue with retroarch bluetooth menus, use bluetoothctl via ssh, and manually pair. This should be assigned to the person who implemented wifi/bluetooth menus in retroarch for Lakka, as they are fundamentally broken in so many ways. for example wifi doesnt connect, until you return to main menu, choose something, then go back to wifi menu, then it will connect. Or you reboot, after typing in password.
