### ISSUE TITLE
wrong file  -- ScummVM

### ISSUE THREAD

**Issue by bleckman74** [libretro/Lakka-LibreELEC#1825]
Lakka 4.3
SCUMM VM
PC
I tried to install scummVM and HI-Res-Adventure popped up  instead to download.
i wanted to install SCUMMVM

It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at https://www.lakka.tv/doc/Troubleshooting-Lakka/

Please delete this text before posting.

**Comment by ToKe79** [comment]
Hi, you do not need to download anything, the libretro core is already included in the system. What you have done is you downloaded a game/content for ScummVM to play.
