### ISSUE TITLE
Live and Installer failure with Generic x86_64-4.3 HP Thin Client

### ISSUE THREAD

**Issue by dustbust0000** [libretro/Lakka-LibreELEC#1827]
- _Which version of Lakka are you using?_
- Generic x86_64-4.3
- _What system hardware are you using?_
- HP t510 Thin Client
<html><body>

Processor | VIA Eden X2 U4200 (1 GHz, 2 cores)
-- | --
Chipset | VIA VX900
Memory | 2GB, 1066-MHz DDR3 RAM (128MB reserved for video)

</body>
</html>- 
More deatils can be found here: https://support.hp.com/us-en/document/c03260067

- _What did you do?_
- Attempted to launch live and install on 16GB internal Flash memory
- _What did you expect to happen?_
- Launch or install
- _What happened instead?_
- At boot after waiting or typing live or typing installer a very brief (less than half a second) error appears under the boot: live or boot: installer line and states:
- [     6.265960] acpi_cpufreq: acpucpufreq: failed to register hotplug callbacks
I was only able to catch the exact line by recording the screen in slow motion on my phone :)
if live was selected:
Screen goes black and is unresponsive after ~20 min wait time
if install was selected:
Installer loads and successfully installs on flash drive. Logs show normal installation with no reports of errors. Requests installation media removed and requires reboot. After reboot same error message briefly flashes after SYSLINUX 6.03 Boot screen, then Lakka (official): 4.3 appears in the upper left hand corner and then is unresponsive after 8+ hours. (I left it overnight just in case)

_It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at https://www.lakka.tv/doc/Troubleshooting-Lakka/_
Modifying the Syslinux.config resulted in a blank screen at boot similar to that of attempting to load live.

**Comment by gouchi** [comment]
Hi,

Your system is using VIA GPU and we rely on open source driver.

There is an ongoing project called [OpenChrome](https://www.freedesktop.org/wiki/Openchrome/) to provide open source driver for VIA GPU but it is not on par with other open source graphics driver.

Unfortunately, Lakka won't work on your system.
