### ISSUE TITLE
Empty space after installation and additional partition

### ISSUE THREAD

**Issue by ammnt** [libretro/Lakka-LibreELEC#1844]
Hello,

thanks for your great work and great project👏🏼I install Lakka on my RPi 4B using Raspberry Pi Imager or Balena Etcher. As a result, my 128GB SD card becomes ~2GB, and when I creating a partition from empty space, Lakka does not see this partition. How to burn the image correctly or create an additional partition? Which utility is best used on macOS?🤔

Thank you.
Best regards!

**Comment by ToKe79** [comment]
sorry for late response - you do not need to create additional paritions on the SD card, just boot your RPi4 with the SD card as flashed and during first boot the partition for storate (LAKKA_DISK) will be prepared. However I'm not sure if MacOS can read ext4 partitions, but you can enable wifi + ssh and copy your files using scp client.
