### ISSUE TITLE
Need qca6174 drivers for Amlogic S905X3 SoC (AMLGX) in Lakka v5.x

### ISSUE THREAD

**Issue by eric4gith** [libretro/Lakka-LibreELEC#1845]
The driver is required for X96 Max Plus Q2 box. And it's already added in CoreELEC and EmuELEC. FYI: https://github.com/EmuELEC/EmuELEC/pull/609

**Comment by Ntemis** [comment]
EmuELEC is using the oem kernels we use mainline . Not possible on lakka
