### ISSUE TITLE
8BitDo Ultimate Wired Controller for Xbox not working

### ISSUE THREAD

**Issue by ciphermenial** [libretro/Lakka-LibreELEC#1846]
Version: Lakka 4.3
Hardware: Zotac Mini PC

When running 'lsusb' it shows the controller as 'Bus 002 Device 005: ID 2dc8:2002 8BitDo 8BitDo Ultimate Wired Controller for Xbox' but it does not work.

**Comment by slowpokefarm** [comment]
I couldn't make it work on linux systems without installing https://github.com/medusalix/xone

**Comment by ToKe79** [comment]
do you get a message in RetroArch about gamepad connected, but no autoconfig found? do you see the device as `/dev/input/jsX` (where X is a digit)? could you test with latest [development build for PC](https://nightly.builds.lakka.tv/devbuild_latest/Generic.x86_64/)?

**Comment by Ntemis** [comment]
Can you retest on 5.0 stable? I give you a few days and closing this down.

**Comment by gouchi** [comment]
@ciphermenial @slowpokefarm Please reply.

Thank you.

**Comment by slowpokefarm** [comment]
@Ntemis @gouchi I possibly could as I have said controller at hand, could you point me to the image I could test it on? I have an x86 system and a few orange Pi systems at hand, can test it on any of those.

**Comment by gouchi** [comment]
@slowpokefarm Thank you. 

You can get the stable release for Lakka 5
[https://lakka.tv/get/windows/](https://lakka.tv/get/windows/)

If still not working, you may try [latest nightlies](https://nightly.builds.lakka.tv/latest/).

Thank you

**Comment by slowpokefarm** [comment]
@gouchi @Ntemis I have checked it on nightly build with orange Pi 3 LTS. Controller works without issues. The only unexpected behaviour is that the LED on controller is blinking as if it was trying to connect, but it's already connected and working.

**Comment by Ntemis** [comment]
Excellent  closing  down
