### ISSUE TITLE
PCSX2, achievements can't be activated with this core

### ISSUE THREAD

**Issue by simonboy77** [libretro/Lakka-LibreELEC#1847]
**Which version of Lakka are you using?**
Generic.x86_64-4.3 (Build date Jan 16 2023)
and also tried
Generic.x86_64-devel-20230411030216-948d92b (Nightly downloaded on Apr 30 2023)

**What system hardware are you using?**
https://www.intel.com/content/www/us/en/products/sku/205603/intel-nuc-11-pro-kit-nuc11tnki5/specifications.html

**What did you do?**
I started TimeSplitters 2 using the PCSX2 core.

**What did you expect to happen?**
Being able to earn achievements.

**What happened instead?**
A popup message in the bottom informed me that "_achievements can't be activated with this core_". But the game ran great regardless, so I finished the first level knowing that that would give an achievement, but the achievement didn't unlock.

**What else did you try?**
Then I tried running the game on the nightly build on the same hardware with the same core (now named LRPS2), which gave the same popup message "_achievements can't be activated with this core_" and the same log messages regarding no exposed memory (logs below). I didn't bother finishing the first level to test.

Then I ran the linux PCSX2 emulator on my laptop with the same TimeSplitters 2 ISO, finished the first level and successfully unlocked the achievement for it.
<br/><br/>

<details>
<summary>Logs (From nightly build, but 4.3 reported the same)</summary>
[INFO] [Core]: Using content: "/storage/roms/PS2/TimeSplitters 2 (USA).iso".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 518, Frames dropped: 0.
[INFO] RetroArch 1.14.0 (Git ad89b0c)
[INFO] === Build =======================================
[INFO] CPU Model Name: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jan 29 2023
[INFO] Version: 1.14.0
[INFO] Git: ad89b0c
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/tmp/cores/pcsx2_libretro.so"
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/TimeSplitters 2 (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/TimeSplitters 2 (USA).state".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] Bios Found: USA     v01.90(23/06/2003)  Console
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[libretro INFO] Applying preset n: 1
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] Loading selected BIOS:  /tmp/system/pcsx2/bios/SCPH-50001.rom0
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[libretro INFO] Bios Found: USA     v01.90(23/06/2003)  Console
[libretro INFO] Detected BIOS: USAv01.90(23/06/2003)Console 
[libretro INFO] No injection data found for Bios SCPH-50001.rom0 - language: English 
[libretro WARN] Patches: No CRC found, using 00000000 instead.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[libretro INFO] Renderer option set to: Auto
[INFO] [Environ]: GET_PREFERRED_HW_RENDER, video driver name: glcore.
[INFO] [Environ]: GET_PREFERRED_HW_RENDER - Context callback set to RETRO_HW_CONTEXT_OPENGL_CORE.
[INFO] [Environ]: SET_HW_RENDER, context type: glcore.
[INFO] Requesting core OpenGL context (3.3).
[INFO] Reached end of SET_HW_RENDER.
[INFO] [RCHEEVOS]: Load started, hardcore active
[INFO] [RCHEEVOS]: Using host: http://retroachievements.org
[INFO] [RCHEEVOS]: Found 4 potential consoles for iso file extension
[INFO] [RCHEEVOS]: Trying console 21
[INFO] [RCHEEVOS]: Opened TimeSplitters 2 (USA).iso
[INFO] [RCHEEVOS]: Found SYSTEM.CNF at sector 2278360
[INFO] [RCHEEVOS]: Looking for boot executable: SLUS_203.14
[INFO] [RCHEEVOS]: Found SLUS_203.14 at sector 2276496
[INFO] [RCHEEVOS]: Hashing SLUS_203.14 title (11 bytes) and contents (3817108 bytes) 
[INFO] [RCHEEVOS]: Generated hash 56ff8d862dfc33bfc2017b76a599cd5e
[INFO] [RCHEEVOS]: Attempting to login sjsm (with token)
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48048.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[INFO] [Video]: Using HW render, glcore driver forced.
[INFO] [DRM]: Found 5 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 30 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Connector 3 connected: no
[INFO] [DRM]: Connector 3 has 0 modes.
[INFO] [DRM]: Connector 4 connected: no
[INFO] [DRM]: Connector 4 has 0 modes.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60.000000 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 74.972504 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 59.940201 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 30.000000 Hz
[INFO] [DRM]: Mode 4: (1920x1080i) 1920 x 1080, 29.970100 Hz
[INFO] [DRM]: Mode 5: (1920x1080) 1920 x 1080, 50.000000 Hz
[INFO] [DRM]: Mode 6: (1920x1080i) 1920 x 1080, 25.000000 Hz
[INFO] [DRM]: Mode 7: (1600x1200) 1600 x 1200, 60.000000 Hz
[INFO] [DRM]: Mode 8: (1680x1050) 1680 x 1050, 59.883251 Hz
[INFO] [DRM]: Mode 9: (1280x1024) 1280 x 1024, 75.024673 Hz
[INFO] [DRM]: Mode 10: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM]: Mode 11: (1440x900) 1440 x 900, 74.984428 Hz
[INFO] [DRM]: Mode 12: (1440x900) 1440 x 900, 59.901459 Hz
[INFO] [DRM]: Mode 13: (1280x960) 1280 x 960, 60.000000 Hz
[INFO] [DRM]: Mode 14: (1152x864) 1152 x 864, 75.000000 Hz
[INFO] [DRM]: Mode 15: (1280x720) 1280 x 720, 60.000000 Hz
[INFO] [DRM]: Mode 16: (1280x720) 1280 x 720, 59.940201 Hz
[INFO] [DRM]: Mode 17: (1280x720) 1280 x 720, 50.000000 Hz
[INFO] [DRM]: Mode 18: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM]: Mode 19: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM]: Mode 20: (832x624) 832 x 624, 74.551270 Hz
[INFO] [DRM]: Mode 21: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM]: Mode 22: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM]: Mode 23: (720x576) 720 x 576, 50.000000 Hz
[INFO] [DRM]: Mode 24: (720x480) 720 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 25: (720x480) 720 x 480, 59.940060 Hz
[INFO] [DRM]: Mode 26: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM]: Mode 27: (640x480) 640 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 28: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM]: Mode 29: (720x400) 720 x 400, 70.081665 Hz
[INFO] [GLCore]: Found GL context: "kms".
[INFO] [GLCore]: Detecting screen resolution: 1920x1080.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.5
[INFO] [EGL]: Created shared context: 0x1538b30.
[INFO] [EGL]: Current context: 0x14e7080.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GLCore]: Initializing HW render (1024x1024).
[INFO] [GLCore]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GLCore]: Vendor: Intel, Renderer: Mesa Intel(R) Xe Graphics (TGL GT2).
[INFO] [GLCore]: Version: 4.6 (Core Profile) Mesa 22.1.7.
[INFO] [GLCore]: Using resolution 1920x1080.
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Keyboard #0: "Power Button" (/dev/input/event2).
[INFO] [udev]: Keyboard #1: "Video Bus" (/dev/input/event3).
[INFO] [udev]: Keyboard #2: "Power Button" (/dev/input/event1).
[INFO] [udev]: Keyboard #3: "Sleep Button" (/dev/input/event0).
[INFO] [udev]: Keyboard #4: "Logitech USB Keyboard" (/dev/input/event4).
[INFO] [udev]: Keyboard #5: "Logitech USB Keyboard" (/dev/input/event5).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[WARN] [udev]: Mouse grab/ungrab feature unavailable.
[libretro INFO] OpenGL version supported: 4.6.
ALSA lib /mnt/nvme/lakkabuildbot/nightly/Lakka-v4.x/build.Lakka-Generic.x86_64/build/alsa-lib-1.2.4/src/pcm/pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[ERROR] ALSA: Failed to initialize...
[ERROR] Failed to initialize audio driver. Will continue without audio.
wifi is already enabled
[INFO] [Display]: Found display driver: "glcore".
[libretro INFO] Bios Found: USA     v01.90(23/06/2003)  Console
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Playlist]: Loading history file: "/storage/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/storage/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/storage/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/storage/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/storage/.config/retroarch/content_favorites.lpl".
[ERROR] failed_to_start_audio_driver
[INFO] [RCHEEVOS]: sjsm logged in successfully
[libretro WARN] Patches: No CRC found, using 00000000 instead.
[libretro INFO] Game CRC: 12532f1c
[libretro INFO] [GameDB] Searching for 'slus-20314' in GameDB
[libretro INFO] [GameDB] Found 'slus-20314' in GameDB
[libretro INFO] [GameDB] Searching for patch with CRC '12532f1c'
[libretro INFO] [GameDB] No CRC-specific patch or default patch found
[libretro INFO] Game CRC: 12532f1c
[libretro INFO] [GameDB] Searching for 'slus-20314' in GameDB
[libretro INFO] [GameDB] Found 'slus-20314' in GameDB
[libretro INFO] [GameDB] Searching for patch with CRC '12532f1c'
[libretro INFO] [GameDB] No CRC-specific patch or default patch found
[INFO] [RCHEEVOS]: Fetched user unlocks 2624
[INFO] [RCHEEVOS]: Fetched game data 2624
[INFO] [RCHEEVOS]: Fetched hardcore user unlocks 2624
[INFO] [RCHEEVOS]: Starting periodic rich presence update task for game 2624
[INFO] [RCHEEVOS]: Could not map region starting at $000000
[INFO] [RCHEEVOS]: Registered 0x100000 bytes of SYSTEM RAM at $000000 (null filler)
[INFO] [RCHEEVOS]: Could not map region starting at $100000
[INFO] [RCHEEVOS]: Registered 0x1F00000 bytes of SYSTEM RAM at $100000 (null filler)
[INFO] [RCHEEVOS]: Could not map region starting at $2000000
[INFO] [RCHEEVOS]: Registered 0x4000 bytes of SYSTEM RAM at $2000000 (null filler)
[INFO] [RCHEEVOS]: Could not map region starting at $000000
[INFO] [RCHEEVOS]: Registered 0x100000 bytes of SYSTEM RAM at $000000 (null filler)
[INFO] [RCHEEVOS]: Could not map region starting at $100000
[INFO] [RCHEEVOS]: Registered 0x1F00000 bytes of SYSTEM RAM at $100000 (null filler)
[INFO] [RCHEEVOS]: Could not map region starting at $2000000
[INFO] [RCHEEVOS]: Registered 0x4000 bytes of SYSTEM RAM at $2000000 (null filler)
[ERROR] [RCHEEVOS]: No memory exposed by core
[INFO] [RCHEEVOS]: Asked the load tasks to terminate
[INFO] [RCHEEVOS]: You have 1 of 55 achievements unlocked.
[INFO] [RCHEEVOS]: Error fetching badge: Load aborted
[INFO] [RCHEEVOS]: Error fetching badge 245438: Load aborted
[INFO] [RCHEEVOS]: Error starting session for game 2624: Load aborted
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
</details>

**Comment by Ntemis** [comment]
report here
https://github.com/libretro/pcsx2

**Comment by simonboy77** [comment]
Thank you, will do!

**Comment by Ntemis** [comment]
actually i linked to the wrong repo
this is the correct one 
https://github.com/libretro/LRPS2
