### ISSUE TITLE
Overlay mounts fail with NFS root

### ISSUE THREAD

**Issue by DavidCWGA** [libretro/Lakka-LibreELEC#1848]
I know that NFS roots aren't officially supported so please consider this a feature request?

Lakka boots and retroarch starts just fine when you're booting from the LAN, if you have placed the files in the appropriate places on your fileserver and edited cmdline.txt like so:

`boot=NFS=your.server/boot/lakka disk=NFS=your.server/root/lakka ip=dhcp quiet`

You end up with root and /boot mounted as so:

```
# mount -t nfs
your.server/boot/lakka on /flash type nfs (ro,noatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=your.ip,mountvers=3,mountproto=tcp,local_lock=all,addr=your.ip)
your.server/root/lakka on /storage type nfs (rw,noatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=your.ip,mountvers=3,mountproto=tcp,local_lock=all,addr=your.ip)
```

However, all the overlay mounts fail, because apparently NFS lacks the necessary features to work:

```
May 02 01:35:20 pi systemd[1]: Mounting Assets directory...
May 02 01:35:20 pi kernel: overlayfs: upper fs does not support tmpfile.
May 02 01:35:20 pi mount[787]: mount: mounting none on /tmp/assets failed: Invalid argument
May 02 01:35:20 pi kernel: overlayfs: upper fs does not support RENAME_WHITEOUT.
May 02 01:35:20 pi kernel: overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
May 02 01:35:20 pi kernel: overlayfs: upper fs missing required features.
May 02 01:35:20 pi systemd[1]: tmp-assets.mount: Mount process exited, code=exited, status=255/EXCEPTION
May 02 01:35:20 pi systemd[1]: tmp-assets.mount: Failed with result 'exit-code'.
May 02 01:35:20 pi systemd[1]: Failed to mount Assets directory.
```

It would be nice if there was a workaround for this - but it's difficult to think of one that doesn't involve editing files in the frozen read-only root filesystem.

Thanks for your time.

**Comment by ToKe79** [comment]
you can disable the tmp-xxx.mount units, copy files from the rootfs (lower folder) to /storage/<respective folder> (upper folder) and adjust the directories settings in RetroArch (to point to /storage/... instead of /tmp/...). the purpose of the overlays is for users to add/replace files included in the readonly rootfs.
