### ISSUE TITLE
[4.3][PC] Cannot Access Manage Playlists

### ISSUE THREAD

**Issue by Graham15** [libretro/Lakka-LibreELEC#1852]
Lakka 4.3 installed to SSD (not live)

i5, 8GB ram and 1TB SSD. Using integrated graphics.

Creating playlists via Import Content, Manual Scan and selecting appropriate content directory, system name and default core. Once playlists are created, using Manage Playlists (settings, playlists) to up date (refresh) newly added roms.

Expecting the Manage Playlists to open and allow access to features within.

Displays Lakka logo briefly and then returns back to the main menu.

Note: Seems to occur after creating any playlist. As a workaround, able to delete playlists via SSH (Fedora 38). Didn't notice the issue with 4.2.

**Comment by Graham15** [comment]
Issue also caused when using "Scan Directory" and seems to occur randomly. 

Have also noticed that the console's icon does not match and can show the icon of another console. The icons are usually shifted upwards by one.

Oddly, when the manage playlist is not accessible, re-scanning roms via "Scan Directory" can gain access to this feature again. Have noticed this with FBNeo.

Unfortunately, I have been unable to test the latest development build (v5, 11th Apr) to see if this issue has been fixed or not. Once installed, Lakka would not boot from my pc. The installation went through ok but after the reboot, would not recognize my hard disk as was trying to boot off other media (i.e pxe boot).

I can also confirm, that having installed 4.2 prior to this, the issues didn't occur at all. Currently back on 4.3 again.

Edit: Have tried another development build but this time is booting and stuck on the Lakka logo.

:)

**Comment by Vexnik** [comment]
This also happened on the Nintendo Switch build, after importing Roms Lakka just crashed and restart the os preventing me from opening the Manage Playlist option. I thought I was the only one dealing with this issue.

Edit: After doing some logging, opening "Manage Playlist" option, it display as "Segmentation Fault" at the end of the logs

**Comment by Graham15** [comment]
Interesting. I have set my logging to debug on both "Frontend Logging Level" and "Core Logging Level". Upon viewing my retroarch.log (I have set to log to file only), each line is [INFO] apart from one line [WARN], displaying "[udev]: Full-screen pointer won't be available." I've no idea what is causing this issue or how to resolve it.

:)

**Comment by Graham15** [comment]
Unfortunately, I have been unable to test the latest development build (v5, 11th Apr) to see if this issue has been fixed or not. Once installed, Lakka would not boot from my pc. The installation went through ok but after the reboot, would not recognize my hard disk as was trying to boot off other media (i.e pxe boot). 

I can also confirm, that having installed 4.2 prior to this, the issues didn't occur at all. Currently back on 4.3 again.

:)

**Comment by amak79** [comment]
When I enable the `Settings->Logging->Log to File` option (`Logging Verbosity` is off), the problem goes away and I'm able to access `Manage Playlists`. The problem returns if I disable the option.

I'm using Lakka 4.3 x86_64.

**Comment by Graham15** [comment]
I have since re-installed 4.3 multiple times with development builds inbetween and currently the "Manage Playlists" issue seems to have resolved itself. Thanks for the tip about logging to file. This will comes in handy should this re-appear again. Thanks.

:)

**Comment by gouchi** [comment]
Closing this issue as it has been resolved.
