### ISSUE TITLE
Retroarch x64 wont start without wifi.

### ISSUE THREAD

**Issue by User051226** [libretro/Lakka-LibreELEC#1854]
Im using intel atom N450 based generic pc without wifi module. When i try to install or boot live mode lakka 4.3 it boot loops infinitely. 
With boot argument live textmode i find that retroarch is trying to run wifi and reboot.
"Wifi is not available
Segmentation fault"

**Comment by Ntemis** [comment]
this is interesting report but you have to try libreelec image and report back, thank you
