### ISSUE TITLE
In Lakka 4.3, Bluetooth won't work on Nano PI K2

### ISSUE THREAD

**Issue by inthesun29** [libretro/Lakka-LibreELEC#1860]
Lakka:~ # hciconfig
hci0:	Type: Primary  Bus: UART
	BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
	DOWN 
	RX bytes:2654 acl:0 sco:0 events:302 errors:0
	TX bytes:72874 acl:0 sco:0 commands:304 errors:0

Lakka:~ # dmesg | grep bcm
[   10.166735] hci_uart_bcm serial0-0: supply vbat not found, using dummy regulator
[   10.167044] hci_uart_bcm serial0-0: supply vddio not found, using dummy regulator

Lakka:~ # rfkill list
0: hci0: bluetooth
	Soft blocked: no
	Hard blocked: no
1: phy0: wlan
	Soft blocked: no
	Hard blocked: no

● bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
     Active: active (running) since Sun 2023-06-25 10:16:23 CST; 2 days ago
   Main PID: 685 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 1237)
     Memory: 1.5M
     CGroup: /system.slice/bluetooth.service
             └─685 /usr/lib/bluetooth/bluetoothd

Jun 25 10:16:23 Lakka systemd[1]: Started Bluetooth service.
Jun 25 10:16:23 Lakka bluetoothd[685]: Bluetooth daemon 5.56
Jun 25 10:16:23 Lakka bluetoothd[685]: Starting SDP server
Jun 25 10:16:23 Lakka bluetoothd[685]: profiles/network/bnep.c:bnep_init() kernel lacks bnep-protocol support
Jun 25 10:16:23 Lakka bluetoothd[685]: src/plugin.c:plugin_init() System does not support network plugin
Jun 25 10:16:23 Lakka bluetoothd[685]: Bluetooth management interface 1.19 initialized

[bluetooth]# power on
No default controller available

Lakka:/run/kernel-overlays/firmware/brcm # btmon
Bluetooth monitor ver 5.56
= Note: Linux version 5.11.22 (aarch64)                                                                                                      0.190898
= Note: Bluetooth subsystem version 2.22                                                                                                     0.190914
= New Index: 00:00:00:00:00:00 (Primary,UART,hci0)                                                                                    [hci0] 0.190920
@ MGMT Open: bluetoothd (privileged) version 1.19                                                                                   {0x0001} 0.190926

Lakka:/run/kernel-overlays/firmware/brcm # dmesg | grep Blue
[   10.117394] Bluetooth: Core ver 2.22
[   10.117547] Bluetooth: HCI device and connection manager initialized
[   10.117794] Bluetooth: HCI socket layer initialized
[   10.117810] Bluetooth: L2CAP socket layer initialized
[   10.117919] Bluetooth: SCO socket layer initialized
[   10.165982] Bluetooth: HCI UART driver ver 2.3
[   10.166013] Bluetooth: HCI UART protocol H4 registered
[   10.166147] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   10.166525] Bluetooth: HCI UART protocol Broadcom registered
[   10.166606] Bluetooth: HCI UART protocol QCA registered
[   10.536276] Bluetooth: hci0: BCM: chip id 94
[   10.538316] Bluetooth: hci0: BCM: features 0x2e
[   10.561157] Bluetooth: hci0: BCM43430A1
[   10.561189] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[   10.598351] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.hcd' Patch
[   16.228430] Bluetooth: hci0: command 0x0c03 tx timeout
[   24.292707] Bluetooth: hci0: BCM: Reset failed (-110)
[   24.412152] Bluetooth: hci0: BCM: chip id 94
[   24.415079] Bluetooth: hci0: BCM: features 0x2e
[   24.439869] Bluetooth: hci0: BCM43430A1
[   24.440429] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[   24.446294] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.hcd' Patch
[   30.084021] Bluetooth: hci0: command 0x0c03 tx timeout
[   38.116751] Bluetooth: hci0: BCM: Reset failed (-110)
[ 2123.905547] Bluetooth: hci0: BCM: chip id 94
[ 2123.908195] Bluetooth: hci0: BCM: features 0x2e
[ 2123.931058] Bluetooth: hci0: BCM43430A1
[ 2123.931102] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[ 2124.004353] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.hcd' Patch
[ 2129.668165] Bluetooth: hci0: command 0x0c03 tx timeout
[ 2137.856333] Bluetooth: hci0: BCM: Reset failed (-110)

**Comment by Ntemis** [comment]
4.3 issues is a not fix as we wont release any new versions because we moved on to 5.x
Please test the new branch for issues and report them
