### ISSUE TITLE
pie4.  Lakka-RPi4.aarch64-4.3 Thrustmaster T-Wireless scrolling constantly to the right . 

### ISSUE THREAD

**Issue by pKary86** [libretro/Lakka-LibreELEC#1862]
On Pie 4 withLakka-RPi4.aarch64-4.3 
Thrustmaster T-Wireless keeps scrolling right uncontrollably. 
Tested with 2 controllers, same result.  Tried reinstalling the whole system, same result. 
Tested with a pie 4 Lakka-RPi4.aarch64-4.2 controller works.
I have downgraded my pie4 to Lakka-RPi4.aarch64-4.2 - > controller works flawlessly.

**Comment by gouchi** [comment]
Can you try to make a test with [Lakka 5.x build](https://nightly.builds.lakka.tv/devbuild_latest/RPi4.aarch64/)  ?

Thank you.

**Comment by Ntemis** [comment]
@gouchi request > 1 year closing down
