### ISSUE TITLE
ppsspp core build failed

### ISSUE THREAD

**Issue by kekeqwq** [libretro/Lakka-LibreELEC#1866]
compile command:
```bash
DISTRO=Lakka PROJECT=RPi DEVICE=RPi4-GPICase2 ARCH=aarch64 make image
```
The logs are too long, so I'm transferring them externally
http://ix.io/4Avl

**Comment by Ntemis** [comment]
you should retest this as it should be closed by now, if you dont i will be force to kill this issue myself
i give you by the end of the week and thank you

**Comment by gouchi** [comment]
This issue should have been fixed.

Please open a new issue if not.

Thank you.
