### ISSUE TITLE
[>=4.3][PC]Stuck on startup logo with RX 6600

### ISSUE THREAD

**Issue by stormenergy91** [libretro/Lakka-LibreELEC#1870]
Which version of Lakka are you using?
4.3, nightly-v4.x-20230411-948d92b, devbuild-v5.x-20230415-8199f1e

What system hardware are you using?
DELL Precision T3640 ( I7-10700K - UHD Graphics 630) with Sapphire Pulse Amd RX 6600

What did you do?
Prepared the USB key and do the first start

What did you expect to happen?
Show the Retro Arch GUI

What happened instead?
After the resize of the disk and the first reboot it stuck on the black screen with the logo in the middle. I tried to boot in `textmode` for getting the logs. It seems to not detect the HDMI port (Error: "Couldn't find a suitable DRM device"). I have only one monitor connect to the only one HDMI port of the RX 6600. I also tried to disable the integrated video card from the bios but same result.

Log Files
[log-2023-08-11-18.55.17.zip](https://github.com/libretro/Lakka-LibreELEC/files/12325783/log-2023-08-11-18.55.17.zip)

**Comment by gouchi** [comment]
Hi,

Your AMD GPU `1002:73ff` should be supported from [kernel 5.11](https://github.com/torvalds/linux/blob/v5.11/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c).

So it won't work on Lakka 4.x, you will have to use [Lakka dev build 5.x](https://nightly.builds.lakka.tv/devbuild_latest/Generic.x86_64/).

It is possible to get the logs on Lakka dev 5.x and in addition 

`for p in /sys/class/drm/*/status; do con=${p%/status}; echo -n "${con#*/card?-}: "; cat $p; done`

Thank you.

**Comment by stormenergy91** [comment]
Thanks @gouchi for your reply.
I tried to boot with the last dev build `devbuild-v5.x-20230813-afdaa47` and it works! 
Thanks
