### ISSUE TITLE
"FEATURE" Turning Off LAKKA versions to show up when running a game or close content each time.

### ISSUE THREAD

**Issue by BilonFullHDemon** [libretro/Lakka-LibreELEC#1872]
Could Lakka version show up just once on first boot up of the app, and not every time when running a game or closing content, it Really spoils the custom splash screens, RetroArch does not show its version every time. Big Please

**Comment by Ntemis** [comment]
lakka is hardcoded in retroarch with have lakka = true on compile time, this is doable but not by us sorry
