### ISSUE TITLE
[Request] Update cores (Raspberry Pi 4/400 64bit)

### ISSUE THREAD

**Issue by zzedmore** [libretro/Lakka-LibreELEC#1873]
Hi, i'm using the latest dev build for Raspberry Pi 4 64bit which is `Lakka-RPi4.aarch64-devbuild-v5.x-20230813-afdaa47.img.gz`. Only thing is that the PUAE core is v4.9.1 b2c4acb which is from January ! I'm only interested in the Amiga (PUAE) core and the C64 (vice) core. Both of these have had a TON of updates since January.

**Comment by Ntemis** [comment]
all cores were updated recently but i will take a look, thanks for the ping

**Comment by zzedmore** [comment]
@Ntemis Any idea when a new Lakka RPi 4 64bit image will be built ? Updates to the cores don't really mean much to me unless I have an image to write to an SD card 😂

**Comment by Ntemis** [comment]
Build server is down so no ETA

**Comment by zzedmore** [comment]
As these Lakka images only get compiled about once a year, could you also update the PUAE2021 and VICE cores please ? They've had some useful updates for when I finally get round to using them! Although, all the cores will probably be out of date by the time the images are made 😢
