### ISSUE TITLE
Add Support for S812/M8S bcm4335 Variant(s)

### ISSUE THREAD

**Issue by ilikenwf** [libretro/Lakka-LibreELEC#188]
This dtb/dts should work to support my and others' devices. Building normal Libreelec, it has worked for me, but not for another person - I suspect they have version 8.6 while my board is version 8.9. I'm trying to get a copy of their dtb to confirm.

Raw files and patch included, the built dtb should be added to the image for M8/M8S.

[m8m2_n200C_bcm4335.zip](https://github.com/libretro/Lakka-LibreELEC/files/1167131/m8m2_n200C_bcm4335.zip)

**Comment by Ntemis** [comment]
bcm4335 driver causes issues with all other boxes so we skip support for now until a solution is found
