### ISSUE TITLE
Lakka 5x : Build fail chailove core.

### ISSUE THREAD

**Issue by ShigeakiAsai** [libretro/Lakka-LibreELEC#1881]
I'm trying Lakka 5x build, but build fail is occurred on chailove core.
It occurs on Generic.x86_64/RPi4.aarch64/RPi.arm PROJECT and DEVICE, I confirm.
It will occure on all PROJECT, DEVICE and ARCH maybe.

Each build fails are same reason.
> ...
Cloning into '/home/hoge/Lakka-LibreELEC/sources/chailove/chailove-9677b142ab9562cb278e87d7475c55fe0b9a4333/vendor/SDL_tty'...
fatal: could not read Username for 'https://gitlab.com': No such device or address
fatal: clone of 'https://gitlab.com/grumbel/SDL_tty.git' into submodule path '/home/yasai/Lakka-LibreELEC/sources/chailove/chailove-9677b142ab9562cb278e87d7475c55fe0b9a4333/vendor/SDL_tty' failed
Failed to clone 'vendor/SDL_tty'. Retry scheduled
...
Cloning into '/home/hoge/Lakka-LibreELEC/sources/chailove/chailove-9677b142ab9562cb278e87d7475c55fe0b9a4333/vendor/SDL_tty'...
fatal: could not read Username for 'https://gitlab.com': No such device or address
fatal: clone of 'https://gitlab.com/grumbel/SDL_tty.git' into submodule path '/home/yasai/Lakka-LibreELEC/sources/chailove/chailove-9677b142ab9562cb278e87d7475c55fe0b9a4333/vendor/SDL_tty' failed
Failed to clone 'vendor/SDL_tty' a second time, aborting

chailove core refers to https://gitlab.com/grumbel/SDL_tty.git, but this repository may be removed.
 
 
 
Information :
Build machine OS :  Ubuntu 22.04.3 LTS on WSL
Source files : https://github.com/libretro/Lakka-LibreELEC.git
  Branch : origin/Lakka-v5.x
  Commit : b952691f45d7d62470ba5e2d593590eb7615b87d
Build method : https://docs.libretro.com/guides/building-lakka/
Build command : 
(1) Generic.x86_64 : DISTRO=Lakka PROJECT=Generic ARCH=x86_64 make image
(2) RPi4.aarch64 : DISTRO=Lakka PROJECT=RPi DEVICE=RPi4 ARCH=aarch64 make image
(3) RPi.arm : DISTRO=Lakka PROJECT=RPi DEVICE=RPi ARCH=arm make image

Thanks.
ASAI, Shigeaki

**Comment by gouchi** [comment]
Thank you for the report.

I have opened an [issue](https://github.com/libretro/libretro-chailove/issues/425) in the core repository.

**Comment by gouchi** [comment]
Should be fixed with [778370b](https://github.com/libretro/libretro-chailove/commit/778370bb10013632272b882beee45ea1b030ab8c).

**Comment by ShigeakiAsai** [comment]
Just information:
As issuer, I report confirmation result.

I confirmed that build fail is fixed in latest commit.
Thank you.

Build machine OS : Ubuntu 22.04.3 LTS on WSL
Source files : https://github.com/libretro/Lakka-LibreELEC.git
Branch : origin/Lakka-v5.x
Commit : https://github.com/libretro/Lakka-LibreELEC/commit/639a3074e6b6a1c7070c2e04117a1edc8ae22c15
Build method : https://docs.libretro.com/guides/building-lakka/
Build command :
(1) Generic.x86_64 : DISTRO=Lakka PROJECT=Generic ARCH=x86_64 make image
(2) RPi4.aarch64 : DISTRO=Lakka PROJECT=RPi DEVICE=RPi4 ARCH=aarch64 make image
(3) RPi.arm : DISTRO=Lakka PROJECT=RPi DEVICE=RPi ARCH=arm make image
Build result : Each build were finished with no error.


Thanks.
ASAI, Shigeaki
