### ISSUE TITLE
FUSE (ZX Spectrum) system firmware not reading

### ISSUE THREAD

**Issue by zzedmore** [libretro/Lakka-LibreELEC#1882]
@Ntemis 
Hi, one of my favourite cores (FUSE) is not reading the extra firmware files. These are for TRDOS files which are massively better than TAP/TZX etc. 

The log file (attached) states that it's looking for them in 
 `'/storage/.config/retroarch/system/fuse/'`

(they should be in `'/storage/system/fuse'` with all the rest of the bios files). Wherever I put them, Retroarch says it can't find them but they are there !

Any idea how to fix this because this core is useless (to me) without being able to load SCL/TRD files.
[retroarch log.log](https://github.com/libretro/Lakka-LibreELEC/files/12702267/retroarch.log.log)

**Comment by zoltanvb** [comment]
I just tested this with a recent build and seems to work, .trd files can be loaded when the BIOS is present. What setup are you using?

**Comment by zzedmore** [comment]
Thanks for replying. I am using a Raspberry Pi 400 and this image - `Lakka-RPi4.aarch64-devbuild-v5.x-20230813-afdaa47.img`. When I look at the Core Information it says that the extra firmware bios files are Present but when starting any SCL or TRD it just goes to the 48K prompt and the log says it couldn't find the files ?

**Comment by zzedmore** [comment]
I have just noticed that there is a new DEV build dated `Lakka-RPi4.aarch64-devbuild-v5.x-20230921-25dfb42.img.gz`. Does this contain the latest Retroarch and Cores or are they still from January 2023 ?

**Comment by zzedmore** [comment]
I just backed up and updated to the lastest dev build. It now works, crisis averted !
