### ISSUE TITLE
DualSense causes input from any controller to not to work

### ISSUE THREAD

**Issue by ilya-fedin** [libretro/Lakka-LibreELEC#1894]
I've tried to connect a DualSense controller via both BT and USB, with both the controller itself doesn't work and others stop working, too. I've an other controller and a keyboard, both of which can't do menu navigation after connecting a DualSense controller. Although when I tried to press random keys on the other controller/keyboard, some of them do work. Maybe it's just the arrows that don't work... If I unplug the DualSense controller, other input devices start to work again.
[log-2023-10-22-06.12.14.zip](https://github.com/libretro/Lakka-LibreELEC/files/13062523/log-2023-10-22-06.12.14.zip)

**Comment by RobLoach** [comment]
Mind exporting the config and trying to submit it to the joypad configs? https://github.com/libretro/retroarch-joypad-autoconfig

**Comment by dmrlawson** [comment]
We were missing some kernel options that made them behave weirdly. It was fixed in https://github.com/libretro/Lakka-LibreELEC/pull/1837 for Lakka v5 so you could try a v5 nightly version

**Comment by ilya-fedin** [comment]
How can I install a nightly version with PINE?

**Comment by rtrzebinski** [comment]
Same here, is there any older, stable Lakka version without this issue?

Basically when I plug Dual Sense with cable (or BT, doesn't matter) it replaces the keyboard on Input 1, and neither keyboard nor controller works. It should rather register on an empty, unused slot - input 2 in this case.

If I plug Dual Sense only D-Pad does not work, so I can't navigate to controller setting. Some buttons do random stuff but D-Pad is dead.

I see this -> https://nightly.builds.lakka.tv/devbuild_by_devices/RPi3.aarch64/

But I'd rather avoid using unstable version if possible.

**Edit: downgraded to 4.2 and it works fine**

**Comment by gouchi** [comment]
@ilya-fedin  @rtrzebinski Can you try to make a test with the [Lakka 5.x build ](https://nightly.builds.lakka.tv/devbuild_latest/)as it will be the future stable release.

Thank you.

**Comment by ilya-fedin** [comment]
@gouchi can you explain how can I install it with PINN? Thank you as well.

**Comment by gouchi** [comment]
@ilya-fedin depending on the device you own but for [Pine 64](https://nightly.builds.lakka.tv/devbuild_latest/A64.aarch64/) or [Pine  H64](https://nightly.builds.lakka.tv/devbuild_latest/H6.aarch64/).

Thank you.

**Comment by ilya-fedin** [comment]
@gouchi I own rpi2 and I'm not sure how would I put the image into PINN given that it accepts prepared ones with a manifest. In ideal outcome I would like to be able to update right from Lakka UI or have an option in PINN to download & install (in my case replace already installed) the nightly build. I use multiboot via PINN and so I can't just write the raw image.

**Comment by n2sml** [comment]
Hello there, I'm having the same issue, or very similar one.
I'm using Lakka on Nintendo Switch, and by default (after Nyx dump) my JoyCons works well, but when I try to connect one of my DualShock 4's, my JoyCons simply stops working, and my DualShock don't work as well.
I have tried to do key bindings, but the Lakka simply cannot read the inputs i'm pressing on DS4 and on the Joycons.
I'm already tried using 4.x Lakka and nightly 5.x, and in both cases, this problem happens.

**Comment by gouchi** [comment]
@ilya-fedin I don't know [PINN](https://github.com/procount/pinn) but can't you try to use our [RPi2 build](https://nightly.builds.lakka.tv/devbuild_latest/RPi2.arm/) to SD card using [Etcher](https://etcher.io/) ?

@n2sml This issue is related to DualSense not DS4 with Switch so you should open a new issue with some [logs](https://www.lakka.tv/doc/Troubleshooting-Lakka/). Thank you.

**Comment by ilya-fedin** [comment]
@gouchi no, I don't have a spare SD card

**Comment by Ntemis** [comment]
Please test this on 5.0 stable

**Comment by ilya-fedin** [comment]
I have switched away from Lakka, sorry :(

**Comment by Ntemis** [comment]
Not a problem, closing down
