### ISSUE TITLE
Old Joypad Configs

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka-LibreELEC#1896]
The joypad autoconfigs could use an update. I took the overrides that Lakka had and put them in a PR here:
https://github.com/libretro/retroarch-joypad-autoconfig/pull/938

Anything that we should keep?

**Comment by GavinDarkglider** [comment]
We should keep all of these exactly where I put them, as I put them there for a reason. These configs are specific to the switch kernel/joycond and are not old, but should also not replace the configs upstream for newer kernels. excepting ayn odin one, and that is subject to change, once development continues on the kernel front there. Also if you notice, that the configs are gated based upon build in the package.mk for this reason specifically.

**Comment by RobLoach** [comment]
Sweet! Thanks for the review :+1:
