### ISSUE TITLE
Add fan control for mac computers

### ISSUE THREAD

**Issue by phidahl** [libretro/Lakka-LibreELEC#1897]
Lakka runs great on older iMacs (e.g. mid 2011 models). The only issue is that the fan spins higher and higher because it is not controlled properly.

There is a script available for alle major distros that starts a daemon that sets the fan speed according to temperature sensor data: https://github.com/linux-on-mac/mbpfan

My questions would be:

Is it possible to include this package on an existing lakka instance?
How/where would I best include it to the build of the .iso?

**Comment by Ntemis** [comment]
ask in libreelec github
