### ISSUE TITLE
Thumbnail hiding text in submenues

### ISSUE THREAD

**Issue by ficoos** [libretro/Lakka-LibreELEC#190]
- Which version of Lakka are you using? 2.1 RC3
- What system hardware are you using? Raspi 3
- What did you do?
Tied to configure button remaps or look at achievements
- What did you expect to happen?
Not have the current game thumbnail hide the text for button remaps or retro achievement browsing
- What happened instead?
The thumbnail is displayed over the text for button remaps or when retro achievement browsing

I suggest that the thumbnail be hidden when entering a submenu or be displayed behind the text layer.
If the latter is chosen it needs to be stated that the white text might still be hard to read over the thumbnail image.

**Comment by Kivutar** [comment]
Ah it was already fixed on RetroArch master :o
