### ISSUE TITLE
gamecon_gpio_rpi driver missing

### ISSUE THREAD

**Issue by DerekRoth** [libretro/Lakka-LibreELEC#1903]
I just did a fresh re-install of Lakka 4.3, i was previously running an old Lakka 2 release (probably 2.3) on a Raspberry Pi 3. On the old release i was able to use the gamecon_gpio_rpi driver, but i see that it is gone in the 4.3 ? It was initially added in https://github.com/libretro/Lakka-LibreELEC/pull/685
Was it removed by mistake, or was it replaced by something else ?

**Comment by Ntemis** [comment]
prop didn't compile anymore with gcc12

**Comment by DerekTCS** [comment]
Sorry does this mean that it's now fixed, or that it's gone and won't come back ?

**Comment by ToKe79** [comment]
It was added back in https://github.com/libretro/Lakka-LibreELEC/pull/1960. Wait for next release.
