### ISSUE TITLE
sram not save if rebooting system while a game is running

### ISSUE THREAD

**Issue by ficoos** [libretro/Lakka-LibreELEC#191]
This issue tracker is NOT for help or support. Please use the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general) or IRC @ #lakka on freenode.net for those kinds of posts.

BEFORE you report a bug make sure you have tried the latest nightly version of Lakka at http://le.builds.lakka.tv/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? 2.1 RC3
- What system hardware are you using? Raspi 3
- What did you do? Chose to reboot from the menu while a game is running
- What did you expect to happen? sram be saved to disk before rebooting
- What happened instead? the system rebooted and sram was lost

Closing the content and rebooting will persist sram, also setting up lakka to persist sram every few seconds will make the data loss less prevalent. 

It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at http://www.lakka.tv/doc/Troubleshooting-Lakka/

Please delete this text before posting.

**Comment by ToKe79** [comment]
https://github.com/libretro/RetroArch/issues/4901
please use the option `autosave_interval` to set saving interval of sram data to disk.
