### ISSUE TITLE
rename gpicase.arm and pi02gpi.arm to be more consistent

### ISSUE THREAD

**Issue by jdalmanza** [libretro/Lakka-LibreELEC#1910]
we have three images for the retroflag gpi case line. 

gpicase -> rpi zero/zero w in 1st gen gpi case
Pi02Gpi -> rpi zero 2 w in 1st gen gpi case
RPi4Gpicase2 -> rpi cm 4 in 2nd gen gpi case

My recommendation to rename the devices in the builds to be more descriptive/consistent

GPiCase -> RPIZeroGPiCase
Pi02GPi -> RPiZero2GPiCase
No change to RPi4GPiCase2

If we do this along with the issue#1909 that I just opened we can serve all the variations of the gpi cases better.

**Comment by ToKe79** [comment]
done in devel branch - https://github.com/libretro/Lakka-LibreELEC/commit/b659bb5039da430aae213d6b848dbce133c29540
