### ISSUE TITLE
Xbox Elite Series 2 Controller input broken

### ISSUE THREAD

**Issue by paulwalker-dev** [libretro/Lakka-LibreELEC#1918]
Version: 4.3 on RPi4

### Steps to reproduce:
Pair Xbox Elite Series 2 controller via bluetoothctl (crashes when done via ui)

### Expected Behavior:
Controller should work like an Xbox Series S controller

### Actual Behavior:
Random inputs are received via Xbox Elite Series 2 controller

**Comment by gouchi** [comment]
May you make some test with [Lakka 5.x nightly](https://nightly.builds.lakka.tv/devbuild_latest/RPi3.aarch64/) ?

Thank you.

**Comment by paulwalker-dev** [comment]
It works now. Workaround listed in #1552 is still required though.
