### ISSUE TITLE
[Feature Request] reboot to bootloader or optional payload on switch

### ISSUE THREAD

**Issue by jeyjai** [libretro/Lakka-LibreELEC#1925]
Please add the option to boot into hekate or atmosphere. Currently the reboot function is booting back into lakka through hekate, so it should be easy to implement.

Right now you either have to reboot and hold vol- or shutdown and push a payload again, having the option to boot back into hekate or atmosphere makes it possible to boot into lakka from atmospheres tesla menu and then boot back into atmosphere from lakka, all from the dock.

I googled this a bit and it seems like this used to be possible by changing the "reboot_action" line from payload to bootloader in a file called uenv.txt, a file that no longer exists.

**Comment by GavinDarkglider** [comment]
> Please add the option to boot into hekate or atmosphere. Currently the reboot function is booting back into lakka through hekate, so it should be easy to implement.
> 
> Right now you either have to reboot and hold vol- or shutdown and push a payload again, having the option to boot back into hekate or atmosphere makes it possible to boot into lakka from atmospheres tesla menu and then boot back into atmosphere from lakka, all from the dock.
> 
> I googled this a bit and it seems like this used to be possible by changing the "reboot_action" line from payload to bootloader in a file called uenv.txt, a file that no longer exists.

All uenv.txt options have been moved into lakka.ini in bootloader/ini folder. This is standard with all linux distros on the switch now. As for reboot to specific payload, not really a lakka specific issue, as that is code that needs to be implemented in retroarch. Kernel implementation is there, so one in therory could add a script, or something that sets the proper values for their switch to reboot to whatever they want...... and actually, you might be able to do that via hekate ini file as well.

That being said, when I have the time, and want to work on retroarch issues, it is on my list, with a ton of other stuff, I dont feel like working on at the moment.

**Comment by Ntemis** [comment]
ok to close?

**Comment by GavinDarkglider** [comment]
> ok to close?

Can it be closed, since it is a retroarch side of things issue? sure...... But since it is also lakka specific, and on my long list of things I dont have time to work on........ it might be worth leaving, in case someone else gets to it before i do...... which I doubt will happen, as most look at my code in this tree with confusion, and at that point, it is in retroarch. lol.
