### ISSUE TITLE
240p composite support not working properly (RPi)

### ISSUE THREAD

**Issue by jayare5** [libretro/Lakka-LibreELEC#1932]
Following the instructions here:
https://www.lakka.tv/doc/Raspberry-Pi/#composite-output

In Lakka, I expect 240p, but it's doing 480i.
However in LibreELEC, it does 240p correctly, with those same instructions.

Versions tested:
Lakka: Latest nightly 5.x
LibreELEC: 11.0.6 from Jan 29, 2024

**Comment by gouchi** [comment]
Hi,

Is it fixed with https://lakka.tv/articles/2024/05/02/rpi-composite/ ?

Thank you.

**Comment by jayare5** [comment]
YUP! This issue can close now :D 
(I worked on this release with ToKe79 to have a branch that never gets composite output broken ever again!)
