### ISSUE TITLE
RPi4 FBneo core

### ISSUE THREAD

**Issue by BilonFullHDemon** [libretro/Lakka-LibreELEC#1934]
FBneo core for raspberry pi 4 is missing latest game fixes

**Comment by gouchi** [comment]
Please confirm it is working when new [nightly build](https://nightly.builds.lakka.tv/devbuild_latest/RPi4.aarch64/) is available.

[Source](https://github.com/libretro/Lakka-LibreELEC/pull/1935)

**Comment by Ntemis** [comment]
it works
