### ISSUE TITLE
Gamecon module is not enabled in the latest Lakka Development builds

### ISSUE THREAD

**Issue by BDJoe360** [libretro/Lakka-LibreELEC#1945]
Since Nightly builds (Generic.x86_64) has not been updated for a long time, only Development builds (Generic.x86_64) can be used for the time being.
However, I found that this version of LAKKA does not have a Gamecon module, and I hope to add it to it.

         Thank you!

**Comment by BDJoe360** [comment]
Also, the new Development builds (Lakka-Generic.x86_64-devbuild-v5.x-20240317-95029ef.img.gz) seems to have a problem with Chinese Simplified, and I still get garbled after I choose Chinese font, is it wrong for me to set it up?

**Comment by gouchi** [comment]
Related commits [1](https://github.com/libretro/Lakka-LibreELEC/pull/292) [2](https://github.com/libretro/Lakka-LibreELEC/pull/146). 

> Also, the new Development builds (Lakka-Generic.x86_64-devbuild-v5.x-20240317-95029ef.img.gz) seems to have a 
> problem with Chinese Simplified, and I still get garbled after I choose Chinese font, is it wrong for me to set it up?

You should open another issue for this one. Thank you.

**Comment by ToKe79** [comment]
those options are enabled during build:
https://github.com/libretro/Lakka-LibreELEC/blob/7a8c0735103ff998d978638c0c424e3ccac0d4f0/packages/linux/package.mk#L194-L206

I also checked the resulting `.config` file and the options are present:

![image](https://github.com/libretro/Lakka-LibreELEC/assets/16481520/755354c9-68b1-4fd4-852d-60c572fb4ef5)

![image](https://github.com/libretro/Lakka-LibreELEC/assets/16481520/ce17b3a6-5938-42f9-901c-91504aeac093)

**Comment by gouchi** [comment]
@BDJoe360 Can you make a [test with latest](https://nightly.builds.lakka.tv/devbuild_latest/Generic.x86_64/) and confirm it is working ?

Thank you.

**Comment by BDJoe360** [comment]
OK, I've tested the latest "Lakka-Generic.x86_64-devbuild-v5.x-20240407" and I'm working with the Gamecon controller!

**Comment by BDJoe360** [comment]
But there is still a small bug:
![Gamecon PSX](https://github.com/libretro/Lakka-LibreELEC/assets/28658495/c5e71192-d5e1-4d90-9ef3-e7dad5b1bcfd)
The Device Index does not show the correct model of the controller (the original version shows the PSX Controler).

If you use the Xinput handle series with USB interface, it can be displayed normally
![Xinput](https://github.com/libretro/Lakka-LibreELEC/assets/28658495/84f18e00-b3ec-4cb2-a6cc-80518e766170)
It would be better if it could be solved!
Thank you.

**Comment by ToKe79** [comment]
not sure why the device does not show up with proper name. but at least it works now.
next build (20240408) should fix the issue with chinese symbols (we fixed the path for the fonts in configuration of fontconfig).
