### ISSUE TITLE
No Lakka 5.0 Rpi4 images

### ISSUE THREAD

**Issue by andre-rosa** [libretro/Lakka-LibreELEC#1965]
Link is broken: https://le-builds.lakka.tv/RPi4.aarch64/Lakka-RPi4.aarch64-5.0.img.gz

Could you please also double-check the RPi5 images as well?

Thank you.

**Comment by andre-rosa** [comment]
I believe that because of that the online updater does not work too.

**Comment by ToKe79** [comment]
new images were uploaded. there was a nasty bug in the original images: everybody who updated to Lakka 5.0 gets a crash when Lakka online updater is opened in RetroArch.

For those who updated to 5.0 already, here are the options:
1) you stick to 5.0 and wait for next version and use the lakka-update.sh script to download the next release (ssh access needed), or
2) you manually put the fixed image to the update folder (either via scp, ssh & wget or samba)

**Comment by andre-rosa** [comment]
Thank you, @ToKe79!
