### ISSUE TITLE
Website Download Link broken for Retroflag GPI Case 2W / Raspbery Pi Zero 2 (aarch64)

### ISSUE THREAD

**Issue by dah33** [libretro/Lakka-LibreELEC#1967]
The [Lakka download page](https://www.lakka.tv/get/linux/rpi/) doesn't link to anything for "Retroflag GPI Case 2W / Raspbery Pi Zero 2 (aarch64)", which is a new build image as of v5.0. It just links back to the same page. I believe it should link to [this image](https://le-builds.lakka.tv/RPiZero2-GPiCASE2W.aarch64/Lakka-RPiZero2-GPiCASE2W.aarch64-5.0.img.gz).

**Comment by ToKe79** [comment]
Thanks for the report, we have fixed the URLs, the webpage should be updated soon.
And yes, that image is the right one.
