### ISSUE TITLE
Support for NSO Controller (Nintendo Switch Online NES, SNES & N64 Controller)

### ISSUE THREAD

**Issue by puresick** [libretro/Lakka-LibreELEC#1969]
First of all thank you for Lakka! What a great project!

After installing the most recent version on my Raspberry Pi 4 I tried to connect my NSO SNES and N64 controller to it. The popup on the bottom left corner pops up and correctly reports the both controller, but input does not work. It makes no difference if connected via USB or Bluetooth.

As far as I know proper NSO controller support was added to the Linux kernel just recently with its version 6.8, which includes the `hid-nintendo` kernel module (https://www.phoronix.com/news/Nintendo-Switch-NSO-Controller).

Are there any plans to update the kernel for the next Lakka release yet?

- Which version of Lakka are you using?
Lakka 5.0
- What system hardware are you using?
Raspberry Pi 4 (4GB version).
- What did you do?
I tried to use my SNES and N64 NSO controller via USB and Bluetooth.
- What did you expect to happen?
Them being recognized and working.
- What happened instead?
They were recognized but input does not work.

**Comment by Ntemis** [comment]
neither of the team owns such niche controllers, you have to wait until we upgrade to le12 branch or back port thepatch to 6.1.x and pr if it works for you
