### ISSUE TITLE
Transparency of thumbnails broken on rpi2

### ISSUE THREAD

**Issue by dem1980** [libretro/Lakka-LibreELEC#197]
Which version of Lakka are you using? 2.1 RC4 (& RC3 at least)
What system hardware are you using? Raspi 3
What did you do?
i have homemade thumbnails (screenshot + title) with transparency for a lot of games
What did you expect to happen?
In 2.0, transparency is ok
What happened instead?
in 2.1, transparency is green

https://postimg.org/image/etvc3xh11/

**Comment by Kivutar** [comment]
Not just transparency, even the color space is wrong now on RC5.

**Comment by Kivutar** [comment]
Fixed by https://github.com/libretro/Lakka-LibreELEC/commit/454f6026af8e82783dd23666bdb0c50a697e628a
