### ISSUE TITLE
Lakka-AMLGX.aarch64-5.0-lepotato - cvbs dont work

### ISSUE THREAD

**Issue by efirshik** [libretro/Lakka-LibreELEC#1970]
cvbs out (composite video) dont work.
```
find /sys/devices -name "edid"

/sys/devices/platform/soc/d0100000.vpu/drm/card0/card0-HDMI-A-1/edid
```
find only HDMI out.

I replace meson-gxl-s905x-libretech-cc.dtb from this https://hub.libre.computer/t/lakka-for-libre-computer-boards/231

**Comment by ToKe79** [comment]
does it work with LibreELEC image?

**Comment by ToKe79** [comment]
Also - I'm not sure if the dtb provided by Libre Computer for Lakka 4.2 is still compatible with Lakka 5.0.

**Comment by efirshik** [comment]
> Also - I'm not sure if the dtb provided by Libre Computer for Lakka 4.2 is still compatible with Lakka 5.0.

thx for answer. i test without replace dtb, and write here after test.

**Comment by efirshik** [comment]
without replace dtb:
`/sys/devices/platform/soc/d0100000.vpu/drm/card0/card0-HDMI-A-1/edid
/sys/devices/platform/soc/d0100000.vpu/drm/card0/card0-Composite-1/edid`

but need add option on boot line in file /flash/extlinux/extlinux.conf:
`console=tty0 video=Composite-1:720x480@60ie`
without this cvbs not work.

this solution find on libreelec forum https://forum.libreelec.tv/thread/26430-composite-video-output-on-aml-s905x-cc-le-potato/

**Comment by dsx724** [comment]
@efirshik Lakka previously would only work on CVBS if we did not disable it in the DT. Thanks for testing.
