### ISSUE TITLE
Lakka 5.0 fails at resizing the file system

### ISSUE THREAD

**Issue by port19x** [libretro/Lakka-LibreELEC#1976]
Sup.

I just received the Raspberry Pi 5 today and noticed that the filesystem does not resize as indicated by the messages during first boot.
I have a 256GB microSD card.
I previously used lakka 5.0 upgraded from 4.3 on a Pi 4.

![image](https://github.com/libretro/Lakka-LibreELEC/assets/82055622/5e278c99-fa81-427f-a4a2-1cd3a11220b9)

Partitions appear to be okay.

During second boot, it complains about a corrupted filesystem, I suspect this is the same error.

**Comment by port19x** [comment]
Workaround: [manual resize2fs](https://unix.stackexchange.com/questions/270595/how-do-i-expand-a-file-system-to-fill-a-partition)

<details>
<summary>screenshot</summary>
<img src="https://github.com/libretro/Lakka-LibreELEC/assets/82055622/c765772d-1736-4d43-a853-f463d86cdabf">
</details>

**Comment by port19x** [comment]
Could be 46bb6fa

**Comment by ToKe79** [comment]
the issue presents itself only on SDcards / thumbdrives with size >= 64 GB, so it slipped through during testing. it is already resolved in daily builds.
