### ISSUE TITLE
Change keyboard layout

### ISSUE THREAD

**Issue by rk9qn3j** [libretro/Lakka-LibreELEC#1998]
Hi,

How do I change the default keyboard layout (English) to something else, for both console and graphical interface?

**Comment by gouchi** [comment]
Hi,

This issue tracker is NOT for help or support. Please use one of the following channels for help and support:

- [Lakka forum](https://forums.libretro.com/c/libretro/lakka-tv-general)
- #lakkatv on [Libretro discord](https://discord.gg/retroarch) 
- IRC @ [#lakkatv](https://web.libera.chat/#lakkatv)

[Source](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-v5.x/.github/ISSUE_TEMPLATE.md)

**Comment by rk9qn3j** [comment]
Got it!
