### ISSUE TITLE
Mupen64Plus core better in 2.1RC1 than 2.1 RC4

### ISSUE THREAD

**Issue by dem1980** [libretro/Lakka-LibreELEC#200]
- Which version of Lakka are you using? 
2.1 RC4
- What system hardware are you using? 
RPI3
- What did you do?
Playing at Super Mario 64 with Mupen64Plus core
- What did you expect to happen?
At the beginning we have the face of Mario and Mario have to be red (fastest thing to test)
- What happened instead?
The red texture is blinking white, in this screen and then in the game

I copy the core from Lakka 2.1 RC1 in the "share\cores" directory of the RC4 and the graphics are fine (Mupen64Plus GLES2 2.5 eda9d16) so the core from RC4 (Mupen64Plus GLES2 2.5 9b01067) is not the best to use.

**Comment by Kivutar** [comment]
Yes, I rolled back the version of mupen as a temporary fix. Will be fixed in RC5
