### ISSUE TITLE
Lakka does not connect to NAS on boot if using Wi-Fi: "Network is unreachable"

### ISSUE THREAD

**Issue by b2jammer** [libretro/Lakka-LibreELEC#2007]
### Version
Lakka (official): 5.0 (RPi4.aarch64)

### Hardware
Raspberry Pi 4 Model B

### Steps to Reproduce
1. Connect to a wifi network (I used the GUI in Retroarch, but `connmanctl services` shows the same connection).
2. Follow the instructions on the page [Serving ROMs from a NAS](https://github.com/libretro/Lakka-LibreELEC/wiki/Serving-ROMs-from-a-NAS) to create a .mount file and enable the service using `systemctl`.
3. Reboot Lakka.

### Expected Result
The share mounts successfully, and ROMs will appear in the File Browser under `/storage/roms/nas`.

### Actual Result
The share fails to mount, citing a network error (details below). No files from the NAS appear in the File Browser.

### Notes
- The share can be successfully mounted *after* boot by connecting via SSH, using the command `systemctl restart storage-roms-nas.mount`, then restarting Retroarch, after which the files appear in the File Browser as expected. However, this has to be done every time Lakka is rebooted.
- The share successfully mounts and works as expected if an ethernet cable is connected before Lakka boots.

### Logs/Files
- Contents of `/storage/.config/system.d/storage-roms-nas.mount`:
```
[Unit]
Description=test cifs mount script
Requires=network-online.service
After=network-online.service
Before=retroarch.service

[Mount]
What=//192.168.0.14/roms
Where=/storage/roms/nas
Options=username=lakkashare,password=***,_netdev
Type=cifs

[Install]
WantedBy=multi-user.target
```
- `journalctl -xeu storage-roms-nas.mount` after boot:
```
Apr 03 20:58:46 Lakka systemd[1]: Mounting storage-roms-nas.mount...
Apr 03 20:58:46 Lakka mount[654]: mount: mounting //192.168.0.14/roms on /storage/roms/nas failed: Network is unreachable
Apr 03 20:58:46 Lakka systemd[1]: storage-roms-nas.mount: Mount process exited, code=exited, status=255/EXCEPTION
Apr 03 20:58:46 Lakka systemd[1]: storage-roms-nas.mount: Failed with result 'exit-code'.
Apr 03 20:58:46 Lakka systemd[1]: Failed to mount storage-roms-nas.mount.
```

**Comment by ShigeakiAsai** [comment]
Could you please show full journalctl log?
I was not able to reproduce this issue on my Lakka-v5.0 RPi4 wifi.
But it may be happen by depending on the environment I think.

**Comment by b2jammer** [comment]
I had my router replaced since I opened this issue, and this works as expected now.

I'd like to know what exactly caused it, but now I doubt it's an issue in Lakka.
