### ISSUE TITLE
Playlist symbols of MAME2003 missing in 2.1 RC4

### ISSUE THREAD

**Issue by masid101** [libretro/Lakka-LibreELEC#201]
- Which version of Lakka are you using? **2.1 RC4**
- What system hardware are you using? **x64 PC**
- What did you do? **Installed my premade playlists**
- What did you expect to happen? **Having the playlist show the symbols**
- What happened instead? **Only showing black squares**

**Comment by Kivutar** [comment]
Thank you for the report. I fixed it in RC5, so we can close this.
