### ISSUE TITLE
ShanWan PS3/PC controller, can't save config file

### ISSUE THREAD

**Issue by Cry0stasis** [libretro/Lakka-LibreELEC#204]
- Which version of Lakka are you using? Lakka-RPi2.arm-2.1-rc4
- What system hardware are you using? Rasberry Pi 3, with ShanWan PS3/PC controller (model P65)
- What did you do? Wanted to save controller cofniguration after mapping buttons
- What did you expect to happen? Expected for Lakka to save conf file
- What happened instead? "Error saving autoconf file"

After remapping controller buttons I tried to save the configuration file and got "Error saving autoconf file" message. As far as I understand Lakka creates conf file with the name of found device name. Doing an "dmesg" in ssh I can see that the ShanWan controller device name is "ShanWan PS3/PC Gamepad" so my guess is it's the weird name with the "/" in the middle that prohibits saving. 
It may sound stupid but I thought that if I take another conf file and change the input device, product id and vendor to the Shanwan ones taken from dmesg scan it would work, but it didn't :(
```
input_device = "ShanWan PS3/PC Wired Gamepad"
input_vendor_id = "1a81"
input_product_id = "2002"
```

My question is, is there somekind of workaround for this, so I can save the conf file or create conf file manually?

**Update**

The idea with manually creating config file actually worked. The reason it didn't work the first time, when I changed input device, vendor id and product id, was because dmesg didn't give correct product and vendor id. So when creating manual conf file all you need from dmesg is the correct input device name.
vendor id and product id numbers can be found when you plug in your device into usb port while running Lakka. Yellow message appears at the bottom of the screen that has both id numbers. First number is vendor id and second number product id.
After you have manually created conf file and mapped all the buttons in said file place it in udev folder and restart your Lakka. File name can be anything you like. After that it should automatically find the correct conf file and you are good to go. Just keep in mind that you'll still have to make manual changes in conf file, cos it still wont be able to save it from Lakka. :)
**There still is a problem with l2 and r2 buttons. For some reason they stay unmapped after Lakka restart even though they are mapped in conf file. If anyone knows why is that, please let me know.**
My configuration file for [SnahWan PS3/PC controller](http://genesis-zone.com/en/product/p65-gamepad-2/) is below.
```
input_driver = "udev"
input_device = "ShanWan PS3/PC Wired Gamepad"
input_vendor_id = "8380"
input_product_id = "21760"
input_b_btn = "1"
input_y_btn = "4"
input_select_btn = "10"
input_start_btn = "11"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "0"
input_x_btn = "3"
input_l_btn = "6"
input_r_btn = "7"
input_l2_axis = "8"
input_r2_axis = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
```
After all of that shenanigans with stupid device names, maybe Lakka should save conf file, with file names like Joypad1, Joypad2 etc. For example if there is no saved conf file it would save it as "Joypad1" if there already is one conf file it would save it as "Joypad2" and so on. I'm have no idea how complicated it would be to program but it would definitely help in the future cos there are a lot of controllers with weird names out there.

**Comment by Kivutar** [comment]
I think we should apply the same function we already use to prevent unsafe characters in the thumbnails when creating the joypad file.
