### ISSUE TITLE
Package new PPSSPP core

### ISSUE THREAD

**Issue by kivutar** [libretro/Lakka-LibreELEC#206]
The core builds find for PC, but has 3 compilation errors for ARM:

https://github.com/libretro/ppsspp/issues/7
https://github.com/libretro/ppsspp/issues/8
https://github.com/libretro/ppsspp/issues/9

**Comment by Mr-Jake** [comment]
@Kivutar

Does this commit fix the problem?
https://github.com/libretro/ppsspp/pull/11

**Comment by Kivutar** [comment]
It fixes the ArmThunk issue at least.

**Comment by Kivutar** [comment]
Now I got the core working, but it gives a black screen (tested on RPi)

**Comment by kivutar** [comment]
Works everywhere now
