### ISSUE TITLE
Update custom theme information in Lakka docs

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#211]
Now that there is an asset folder override, it is much simpler to modify or add to the existing themes. Awesome!

However the documentation does not reflect this new feature. Take a look at the bottom of this page, under the Icons heading: http://www.lakka.tv/doc/Playlists/

There should perhaps be a short new page dedicated to themeing Lakka now that it is so easy. Because there is a RetroArch themeing guide, it can be linked to for the full details once the differences with Lakka are explained. That can keep the new doc short.

**Comment by Kivutar** [comment]
Fixed
