### ISSUE TITLE
Missing Core: tgbdual_libretro.so ( Lakka 2.1 RC4)

### ISSUE THREAD

**Issue by Kazter** [libretro/Lakka-LibreELEC#212]
Hi guys,

trying to set up the core mentioned above:
tgbdual_libretro.so

I cannot find it in the core section (:/tmp/cores). There is only the .info file placed. What is the problem with this core and what can I do now?

I am using Rpi3 with latest Lakka 2.1 RC4.

**Comment by Mr-Jake** [comment]
Did you try to download the core from the Libretro buildbot website and copy it to the core folder?

**Comment by gouchi** [comment]
It seems we don't provide it but I don't know why.

**Comment by Kazter** [comment]
Well, I could not find the file on the Libretro buildbot website. Could you provide a link to that file?
Thank you.
