### ISSUE TITLE
Double typing in XMB

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka-LibreELEC#217]
With 2.1-RC5, tested on my laptop, when typing the wifi password with my keyboard, the letters are added two times. So if I type 123, I see 112233.
I can't reproduce it outside of Lakka.
And it's a regression.

**Comment by gouchi** [comment]
I can't reproduce it on 2.1 rc5 Generic.

**Comment by Kivutar** [comment]
Strange, I tried it this morning and I do have this issue.

**Comment by Kivutar** [comment]
Fixed by the 8.2 merge
