### ISSUE TITLE
Shared context issue

### ISSUE THREAD

**Issue by kivutar** [libretro/Lakka-LibreELEC#220]
With cores like Dolphin, that forces a shared context, we get the following issues when triggering the menu:

- The game continues to run, even if libretro pause is ON
- The ribbon disapear

**Comment by twinaphex** [comment]
Dolphin is just badly implemented from a libretro core perspective.

As for the ribbon not working, there seems to be some embedded pipeline shader issue going on with core GL context. I'll try to look into it. Hopefully it doesn't require yet more changes made to the basic shaders.

**Comment by Kivutar** [comment]
Thank you. I also notice that the audio continues playing in the menu even if libretro pause is off.
