### ISSUE TITLE
Support Pi Zero W?

### ISSUE THREAD

**Issue by twentytwoo** [libretro/Lakka-LibreELEC#223]
As the title says, any plans to support the Zero W since it has on-board wireless/bluetoooth...

**Comment by Kivutar** [comment]
Hello, the Zero W is supported :)
Use the RPi image

**Comment by Sobient** [comment]
It's supported, as shown in [this video](https://www.youtube.com/watch?v=JYPKZEdAdi0) and many others.

**Comment by twentytwoo** [comment]
>`Use the RPi image`

Which one? There are several...

**Comment by twentytwoo** [comment]
Alright, thanks for your help.
