### ISSUE TITLE
No wireless connection

### ISSUE THREAD

**Issue by DraGiuS** [libretro/Lakka-LibreELEC#229]
I use the 2.1 rc5 of lakka actually.

I need the ath10k driver for having wifi on my device. Just this.

**Comment by Ntemis** [comment]
Thing is we don't know what your "device" is.

**Comment by DraGiuS** [comment]
It's an Atheros QCA 9377 device.

**Comment by ToKe79** [comment]
@DraGiuS The question is about the "Lakka device" - like generic PC (32/64 bit?) or a RPi / Odroid etc. with a USB WiFi.

**Comment by DraGiuS** [comment]
Still no wireless on this device on a generic PC (Arch x86_64)

**Comment by ToKe79** [comment]
@DraGiuS sorry for late response. Can you, please, try image from here: http://nightly.builds.lakka.tv/special_builds/ath10k/
I have added the ath10k driver/module (https://github.com/ToKe79/Lakka-LibreELEC/commit/6ca3efb42f5621b22c0eeef7c4bd8294ee8a5f47)

**Comment by DraGiuS** [comment]
It seems to don't work.

**Comment by ToKe79** [comment]
Please, provide output of: `cat /etc/release`, `lspci -nnk`, `lsusb`, `lsmod` and `dmesg`. Thank you!
See here how to connect to the command line: [Accessing Lakka command line interface](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/)
