### ISSUE TITLE
Test 2.1-rc5 images for every platform

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka-LibreELEC#232]
Just check that the image boots, and can launch a rom.

- [x] Generic.x86_64
- [x] Generic.i386
- [x] RPi.arm
- [x] RPi2.arm
- [x] NOOBS
- [x] a20.arm
- [ ] a10.arm
- [ ] Bananapi.arm
- [ ] imx6.cuboxi.arm
- [ ] imx6.udoo.arm
- [x] OdroidC1.arm
- [x] Odroid_C2.arm
- [x] OdroidXU3.arm
- [ ] WeTek_Core.arm
- [x] WeTek_Hub.arm
- [ ] WeTek_Play.arm
- [x] WeTek_Play_2.arm
- [ ] Gamegirl.arm
- [x] S8X2.arm
- [x] S805.arm
- [x] S905.arm
- [ ] H3.op2.arm
- [x] H3.opipc.arm
- [ ] H3.opiplus.arm
- [ ] H3.opione.arm
- [ ] H3.opilite.arm
- [ ] H3.opiplus2e.arm
- [ ] H3.bpim2p.arm
- [ ] H3.bx2.arm

**Comment by hutzero** [comment]
Is this for SD only or eMMC too?

**Comment by Kivutar** [comment]
SD only

**Comment by Kivutar** [comment]
XU3 looks broken, can somebody confirm?

**Comment by jkms** [comment]
@Kivutar I can test XU3.

do you have an image? or should I just compile the current commit?

**Comment by Kivutar** [comment]
@jkms Thanks, I just uploaded an image there http://static.kivutar.me/Lakka-OdroidXU3.arm-2.1-rc5.img.gz

**Comment by jkms** [comment]
@Kivutar the image boots and I can load roms, however the samba server didn't work for me. had to use scp.

**Comment by Kivutar** [comment]
Cool, thanks for your test.

**Comment by hydraheim** [comment]
RPI Zero W boots and loads up ROMs just fine. There are issues with abnormal controller support for the DS4 though. Menu scrolling moves _way too fast_ and directional buttons only work some times. Reconnecting was needed several times just to get around the menu. Tested with a SNES usb controller and that worked fine. DS4 has worked fine in previous versions both on RPI Zero W and RPI3.

**Comment by Kivutar** [comment]
Ok thanks, this DS4 problem affects all the modern kernels. We'll have to check why the kernel guys are keeping this regression.

**Comment by Kivutar** [comment]
All images should be OK now.

**Comment by Kivutar** [comment]
Also with USB connection

**Comment by Kivutar** [comment]
Mhhh, who checked the opipc line? Somebody here reports it broken: https://forums.libretro.com/t/lakka-2-1-rc5-released/12720/5

**Comment by trulio** [comment]
Hi,

when i boot my MK808B-Plus on image Lakka-S805.MK808B-Plus.arm-2.1.img.gz,

strorage resize behave normally but once retroarch launch screen buffer is corrupted

I tried on a samsung TV but also on a full HD BENQ computer monitor.

I have the same behavior.

I also tried the MXQ 2.1 image with the same results 
(as kodi libreElec says MXQ and MK808 use the same image)

here are the files showing the issue:

Regards,

Trulio
[dmesg.txt](https://github.com/libretro/Lakka-LibreELEC/files/1839198/dmesg.txt)
![img_20180322_201009](https://user-images.githubusercontent.com/8265829/37797289-af960d12-2e19-11e8-87e1-8e558efe848f.jpg)
[log.txt](https://github.com/libretro/Lakka-LibreELEC/files/1839199/log.txt)
