### ISSUE TITLE
parallel-n64 crashes on i386

### ISSUE THREAD

**Issue by kivutar** [libretro/Lakka-LibreELEC#236]
- Which version of Lakka are you using? 2.1-rc5
- What system hardware are you using? i386
- What did you do? Launch Mario 64

**Comment by gouchi** [comment]
I reproduce the issue on 2.1, and nightly but it works fine if I compiled latest RA and latest parallel core on my PC from today.

I will try to build an image with latest RA and for latest core the last commit from [dbccb3f](https://github.com/libretro/parallel-n64/commits/master) won't help as it is adding Haiku build.
