### ISSUE TITLE
ScummVM keyboard passthrough stopped working RPi3 2.1 RC5

### ISSUE THREAD

**Issue by masid101** [libretro/Lakka-LibreELEC#239]
Which version of Lakka are you using? 2.1 RC5 (http://static.kivutar.me/Lakka-RPi2.arm-2.1-rc5.img.gz)
What system hardware are you using? RPi3
What did you do? Try to enter copy protection code on Monkey Island 2 using keyboard
What did you expect to happen? Successfully enter some numbers
What happened instead? Nothing

It worked with an older version. I just forgot if it was 2.0 or one of the release candidates for 2.1!

**Comment by Kivutar** [comment]
Certainly related to https://github.com/libretro/Lakka-LibreELEC/issues/238

**Comment by masid101** [comment]
Thought so too...
