### ISSUE TITLE
NES (nestopia) segmentation fault on RPi3 2.1 RC5

### ISSUE THREAD

**Issue by masid101** [libretro/Lakka-LibreELEC#240]
Which version of Lakka are you using? 2.1 RC5 (http://static.kivutar.me/Lakka-RPi2.arm-2.1-rc5.img.gz)
What system hardware are you using? RPi3
What did you do? Try to start an NES game
What did you expect to happen? Playing an NES game
What happened instead? Core crashed

Here is the Log ...

Lakka (community): 2.1-rc5 (RPi2.arm)
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
[INFO] RetroArch 1.6.7 (Git 28397b3)
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Oct  3 2017
[INFO] Version: 1.6.7
[INFO] Git: 28397b3
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] [Video]: Video @ 960x720
[INFO] [Video]: Starting threaded video driver ...
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: videocore
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] Querying EGL extension: KHR_image => exists
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev] Adding device /dev/input/event0 as type ID_INPUT_KEYBOARD.
[INFO] [udev] Adding device /dev/input/mouse0 as type ID_INPUT_KEYBOARD.
[INFO] [udev] Adding device /dev/input/event0 as type ID_INPUT_MOUSE.
[INFO] [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
[INFO] [udev]: Plugged pad: PLAYSTATION(R)3 Controller (0:0) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event1) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event1) supports 16 force feedback effects.
[INFO] [Autoconf]: 186 profiles found.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Autoconf]: selected configuration: /tmp/joypads/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] Using content: /storage/roms/stick/nes/1943 - The Battle of Midway (USA).zip#1943 - The Battle of Midway (USA).nes.
[INFO] arg #0: retroarch
[INFO] arg #1: /storage/roms/stick/nes/1943 - The Battle of Midway (USA).zip#1943 - The Battle of Midway (USA).nes
[INFO] arg #2: -s
[INFO] arg #3: /storage/savefiles
[INFO] arg #4: -S
[INFO] arg #5: /storage/savestates
[INFO] arg #6: -c
[INFO] arg #7: /storage/.config/retroarch/retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: /tmp/cores/nestopia_libretro.so
[INFO] Threaded video stats: Frames pushed: 1023, Frames dropped: 0.
[INFO] Set config file to : /storage/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.6.7 (Git 28397b3)
[INFO] Redirecting save file to "/storage/savefiles/1943 - The Battle of Midway (USA).srm".
[INFO] Redirecting savestate to "/storage/savestates/1943 - The Battle of Midway (USA).state".
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Oct  3 2017
[INFO] Version: 1.6.7
[INFO] Git: 28397b3
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/tmp/cores/nestopia_libretro.so"
[INFO] [overrides] no core-specific overrides found at /storage/.config/retroarch/config/Nestopia/Nestopia.cfg.
[INFO] [overrides] no game-specific overrides found at /storage/.config/retroarch/config/Nestopia/1943 - The Battle of Midway (USA).cfg.
[INFO] Shaders: preset directory: /tmp/shaders/presets
[INFO] Shaders: no game-specific preset found at /tmp/shaders/presets/Nestopia/1943 - The Battle of Midway (USA).cgp.
[INFO] Shaders: no game-specific preset found at /tmp/shaders/presets/Nestopia/1943 - The Battle of Midway (USA).glslp.
[INFO] Shaders: no core-specific preset found at /tmp/shaders/presets/Nestopia/Nestopia.cgp.
[INFO] Shaders: no core-specific preset found at /tmp/shaders/presets/Nestopia/Nestopia.glslp.
[INFO] Environ SET_VARIABLES.
[INFO] Remaps: remap directory: /storage/remappings
[INFO] Remaps: no game-specific remap found at /storage/remappings/Nestopia/1943 - The Battle of Midway (USA).rmp.
[INFO] Remaps: no core-specific remap found at /storage/remappings/Nestopia/Nestopia.rmp.
[INFO] Redirecting save file to "/storage/savefiles/1943 - The Battle of Midway (USA).srm".
[INFO] Redirecting savestate to "/storage/savestates/1943 - The Battle of Midway (USA).state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ PERFORMANCE_LEVEL: 6.
[INFO] Loading content file: /storage/roms/stick/nes/1943 - The Battle of Midway (USA).nes.
[INFO] Did not find a valid content patch.
[INFO] CRC32: 0xd131bf15 .
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] RetroPad, User 1, Button "B (bottom)" => "B"
[INFO] RetroPad, User 1, Button "Y (left)" => "Turbo B"
[INFO] RetroPad, User 1, Button "Select" => "Select"
[INFO] RetroPad, User 1, Button "Start" => "Start"
[INFO] RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] RetroPad, User 1, Button "A (right)" => "A"
[INFO] RetroPad, User 1, Button "X (up)" => "Turbo A"
[INFO] RetroPad, User 1, Button "L" => "(FDS) Disk Side Change"
[INFO] RetroPad, User 1, Button "R" => "(FDS) Eject Disk"
[INFO] RetroPad, User 1, Button "L2" => "(VSSystem) Coin 1"
[INFO] RetroPad, User 1, Button "R2" => "(VSSystem) Coin 2"
[INFO] RetroPad, User 1, Button "L3" => "(Famicom) Microphone"
[INFO] RetroPad, User 2, Button "B (bottom)" => "B"
[INFO] RetroPad, User 2, Button "Y (left)" => "Turbo B"
[INFO] RetroPad, User 2, Button "Select" => "Select"
[INFO] RetroPad, User 2, Button "Start" => "Start"
[INFO] RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
[INFO] RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
[INFO] RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
[INFO] RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
[INFO] RetroPad, User 2, Button "A (right)" => "A"
[INFO] RetroPad, User 2, Button "X (up)" => "Turbo A"
[INFO] RetroPad, User 2, Button "L" => "(FDS) Disk Side Change"
[INFO] RetroPad, User 2, Button "R" => "(FDS) Eject Disk"
[INFO] RetroPad, User 3, Button "B (bottom)" => "B"
[INFO] RetroPad, User 3, Button "Y (left)" => "Turbo B"
[INFO] RetroPad, User 3, Button "Select" => "Select"
[INFO] RetroPad, User 3, Button "Start" => "Start"
[INFO] RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
[INFO] RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
[INFO] RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
[INFO] RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
[INFO] RetroPad, User 3, Button "A (right)" => "A"
[INFO] RetroPad, User 3, Button "X (up)" => "Turbo A"
[INFO] RetroPad, User 3, Button "L" => "(FDS) Disk Side Change"
[INFO] RetroPad, User 3, Button "R" => "(FDS) Eject Disk"
[INFO] RetroPad, User 4, Button "B (bottom)" => "B"
[INFO] RetroPad, User 4, Button "Y (left)" => "Turbo B"
[INFO] RetroPad, User 4, Button "Select" => "Select"
[INFO] RetroPad, User 4, Button "Start" => "Start"
[INFO] RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
[INFO] RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
[INFO] RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
[INFO] RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
[INFO] RetroPad, User 4, Button "A (right)" => "A"
[INFO] RetroPad, User 4, Button "X (up)" => "Turbo A"
[INFO] RetroPad, User 4, Button "L" => "(FDS) Disk Side Change"
[INFO] RetroPad, User 4, Button "R" => "(FDS) Eject Disk"
[INFO] Environ SYSTEM_DIRECTORY: "/storage/system".
[libretro INFO] Custom palette path: /storage/system/custom.pal
Segmentation fault (core dumped)

**Comment by Kivutar** [comment]
I confirm this bug

**Comment by Kivutar** [comment]
Fixes with https://github.com/libretro/nestopia/commit/fe2db2e92f3ebfb0c6350752ff62e68445a9f488
