### ISSUE TITLE
Awkward navigation after scanning single file rom. 

### ISSUE THREAD

**Issue by Zerauskire** [libretro/Lakka-LibreELEC#241]
So this is a very minor bug. It's more like a quirk. I don't think it's specific to Lakka. It's probably a RetroArch issue. I'm not certain though because all I use is Lakka currently.

Issue:
I was going through a folder that contained several N64 roms to scan individual roms from that folder. I was navigating through the list using the R1 and L1 buttons on my joypad so that I could jump to games starting with the next letter. Once I found a game I wanted to scan, I scanned it. After doing that I went on to locate the next game to scan. That's when I noticed that pressing the R1 button wasn't jumping to the next letter. I was in the M's and when I pressed R1 for some reason it jumped back up to the D's. I pressed it again and it jumped down to the last file in the list. I pressed it again and this time it jumped to the first file in the list. I pressed it again and it jumped back to the D's. This pattern repeated no matter how many times I pressed it.

Going back a directory and then going back in to that roms directory seems to fix the issue. After doing that I could navigate with the R1 and L1 buttons again no problem.

- Which version of Lakka are you using?
2.1 RC4
- What system hardware are you using?
Alienware Alpha with i5 (x86_64)
- What did you do?
Scanned a single rom then tried to scroll through other roms using R1 and L1 to skip by letter.
- What did you expect to happen?
Browse through roms by skipping to a new letter every time I pressed R1 or L1 like usual.
- What happened instead?
It jumped just to a particular letter, then to the top, then to the bottom. It did not jump to the next letter in the list.

**Comment by ToKe79** [comment]
Hi,
(L1)/(R1) work as Page Up / Page Down, as far as I know, not jumping by letters.

From https://www.libretro.com/index.php/getting-started-with-retroarch/:
> In the menu, (A) is used to accept/select and (B) is used for back/cancel, **(L1) is used to scroll up and (R1) is used to scroll down quickly**.

Then there is a setting, if you hit the upper/lower end, if you should move to the last/first entry (endless loop), but I do not recall that setting name/location.
