### ISSUE TITLE
Storage partition does not get resized despite saying it does (2.0 and 2.1-rc5)

### ISSUE THREAD

**Issue by NessInOnett** [libretro/Lakka-LibreELEC#249]
---

**UPDATE** (solved but there's still an issue somewhere): 
I tested a really old, slow piece of crap SD card I had laying around and sure enough it worked.  I noticed that my Sandisk card, which didn't work, went through the "Resizing /storage..." process very quickly (1-2 seconds), but the generic SD card, which did work, took about 1 minute to resize.  The Generic card also successfully rebooted, whereas the Sandisk did not.  Whatever is doing the resizing is incorrectly reporting success when it was not actually resized.

---

- Version 2.1 RC5 (Oct 11), same issue with 2.0 stable currently on the site
- Raspberry Pi 3
- Installed Lakka exactly as instructed on the step-by-step wizard
- Client system: Solus linux

On first boot, Lakka goes through its normal processess:

```
Checking layout....  done
Deleting /storage... done
Creating /storage... done
Checking /storage... done
Resizing /storage... done
Rebooting in 15s...  NOW
```

My Pi never reboots on its own when it says "Rebooting in 15s... NOW".  There's no disk activity, and nothing appears to be going on in the background.  I've given it 10+ minutes just in case.. and eventually I have to power cycle it.  Lakka then boots up just fine, but I cannot copy any files to it.. it says there's not enough space (32GB Sandisk Extreme Plus micro SD). 

After closer examination, it looks like the storage partition never gets resized.  If I pop the SD card into my main PC and look at gparted, it shows that the space is unallocated.

![](https://i.imgur.com/KvhXtXe.png)
![](https://i.imgur.com/jFDzGOK.png)

Tested in windows as well:
![](https://i.imgur.com/6lyMe3J.png)

I had this problem with the original 2.0 image I downloaded from the site, so I tested the latest nightly of 2.1 and the issue persists.  I've reinstalled this thing probably a dozen or more times now.. and I cannot get any storage space.  I've tried with dd and Etcher for what it's worth. 

```
Lakka (community): 2.1-rc5 (RPi2.arm)
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
[INFO] RetroArch 1.6.7 (Git 28397b3)
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Oct 10 2017
[INFO] Version: 1.6.7
[INFO] Git: 28397b3
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: videocore
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] Querying EGL extension: KHR_image => exists
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
[INFO] [udev]: Plugged pad: Logitech Gamepad F710 (1133:49695) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event0) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event0) supports 16 force feedback effects.
[INFO] [Autoconf]: 186 profiles found.
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] ALSA: Using signed 16-bit format.
[INFO] [Autoconf]: selected configuration: /tmp/joypads/udev/Logitech_Gamepad_F710.cfg
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
```

**EDIT**: I completely changed this thread because the issue is different than I thought it was.  Let me know if there is any other information I should share, I'm not sure where to look for more info.

**Comment by AnicetusCer** [comment]
This is still an issue (lakka 2.1) tried install on 32GB Samsung SD HC card, formatted with etcher.
The initial format created the 512 MB lakka partition and a 32Mb second partition (assume boot) 
The final partition never gets created on the initial boot, the system fails to boot as it can not find the storage area.

**Comment by ToKe79** [comment]
@AnicetusCer on which system did you try? If on generic, try to switch between Legacy / EFI boot in your BIOS settings. If on Amlogic (e.g. S905), make sure you are using correct dtb.img file for your box. The 32 MB partition is the storage partitions - the image file contains only 32 MB of this partition, this then gets resized during the initial boot to the remaining capacity of the SD card / USB thumb drive.

**Comment by AnicetusCer** [comment]
Thanks for the comment, the system I am installing on is a "pi zero w" so the boot loader sits in within the system on chip's ROM and points the system to the SD card for its files, but boot loading is not the problem.
Thank you for pointing out the 32mb partitions use, nice solution to utilise all a systems space. 
So it seems the issue is with the resize, on first boot lakka should resize and mount the "storage" file system, the resize job runs, but does not resize the 32mb partition when I check the SD on my pc, the next message I see on reboot is that lakka failed to boot /dev/mccblk***** , can't remember the whole message, will run again tomorrow to check, if I remember correctly it was the storage FS.
