### ISSUE TITLE
(RPi3) Lakka still can't connect to hidden wifi networks

### ISSUE THREAD

**Issue by autofire372** [libretro/Lakka-LibreELEC#251]
Lakka still offers no way to manually enter the SSID of a hidden network to connect to it.

**Comment by Kivutar** [comment]
Even using connmanctl in command line?

**Comment by autofire372** [comment]
Managed to connect through connmanctl (hint for others: remember to start the connmanctl agent if your network is hidden). I still feel this should be possible through the GUI, especially given that on RPi and its successors, command line access is only possible through ssh.
