### ISSUE TITLE
Odroid-XU3/4: Keyboard locks UX

### ISSUE THREAD

**Issue by ashleyhull-versent** [libretro/Lakka-LibreELEC#255]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? 2.1 RC5
- What system hardware are you using? Odroid-XU4
- What did you do? Used menu to wifi menu
- What did you expect to happen? enter password
- What happened instead? UX locked up

**Comment by Kivutar** [comment]
Certainly the same bug as https://github.com/libretro/Lakka-LibreELEC/issues/251

**Comment by Kivutar** [comment]
Sorry, this one https://github.com/libretro/Lakka-LibreELEC/issues/238

**Comment by Kivutar** [comment]
I close the duplicate report
