### ISSUE TITLE
Wrong default core list for playlists in Lakka 2.1-RC5

### ISSUE THREAD

**Issue by metchebe** [libretro/Lakka-LibreELEC#269]
- Which version of Lakka are you using? 2.1 RC5
- What system hardware are you using? PC i386 / Raspberry Pi 3
- What did you do? Open Arcade game from playlist (FB Alpha)
- What did you expect to happen? Start FB Alpha core and load game
- What happened instead? Starts Vecx core and fails

This happens because the default playlist core list in retroarch.cfg is shifted for some reason:

playlist_names | playlist_cores
-- | --
ChaiGame.lpl | /tmp/cores/bluemsx_libretro.so
Coleco - ColecoVision.lpl | /tmp/cores/dinothawr_libretro.so
Dinothawr.lpl | /tmp/cores/prboom_libretro.so
DOOM.lpl | /tmp/cores/dosbox_libretro.so
DOS.lpl | /tmp/cores/fbalpha_libretro.so
FB Alpha - Arcade Games.lpl | /tmp/cores/vecx_libretro.so
GCE - Vectrex.lpl | /tmp/cores/lutro_libretro.so
Lutro.lpl | /tmp/cores/chaigame_libretro.so

**Comment by Kivutar** [comment]
Thank you. It was due to the chaigame core missing from a list. I just fixed it.
