### ISSUE TITLE
Steam Controller support in Lakka

### ISSUE THREAD

**Issue by jphaskins** [libretro/Lakka-LibreELEC#271]
I'm using Lakka 2.1-RC5 on a Raspberry Pi 3. I plugged in a paired Steam Controller and dongle but it wasn't detected and I wasn't able to control the user interface. I believe that currently steam controllers only work with SDL since I didn't see a driver for it in /tmp/joypads/udev/.

Retropie and recalbox-os support the steam controller using a stand alone driver https://github.com/ynsta/steamcontroller. Perhaps the same solution could be used?

**Comment by MasterGroosha** [comment]
Same here with the latest release :(
Steam Controller isn't detected.

**Comment by Ntemis** [comment]
Steam controller isnt supported

**Comment by MasterGroosha** [comment]
Any chance to have its support in future? There is a confog for SC in repo, isn't it?

**Comment by Ntemis** [comment]
I personally dont have any of those so from my side is a nope.

**Comment by ckdarby** [comment]
@Ntemis Yo, if I buy you one can you support it with the wireless features?

**Comment by Ntemis** [comment]
I could try yes

**Comment by Xscratch** [comment]
@ckdarby We could split the amount if you want.

**Comment by ckdarby** [comment]
@Xscratch That would be much appreciated.

@Ntemis Can you pass along a way to send you $ like paypal and the cost of a steam controller in your country?

**Comment by Ntemis** [comment]
Sorry guys there is no local store that sells those around here
Best move imo is to sent one from italy by @Xscratch as i live in Cyprus

**Comment by ckdarby** [comment]
@Ntemis You can't order directly off steam store or Amazon?

**Comment by Xscratch** [comment]
I found some used controllers on a craiglist-like italian site. I think one of those could do the job?

**Comment by gouchi** [comment]
If [this driver](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg1614763.html) is accepted upstream, it will be great.

**Comment by Ntemis** [comment]
Guys looks like its  99,49€  on steam store
![screenshot at 2018-02-25 17-50-13](https://user-images.githubusercontent.com/2123893/36643465-674cdd52-1a54-11e8-8446-18f0d2b3f540.png)

**Comment by FM1337** [comment]
I know this is an old issue, but I'm curious if there's been any progress made/news on adding support for this controller?

**Comment by natinusala** [comment]
Actually I do own it, do you want me to try ?

**Comment by ckdarby** [comment]
@natinusala :+1:

**Comment by natinusala** [comment]
Not immediately though, I will be quite busy until mid January

**Comment by jphaskins** [comment]
On newer kernels the driver I linked when I opened this issue shouldn't be necessary anymore. Starting with Linux 4.18 (and some fixes went into 4.19) there is a kernel driver module called hid_steam.

**Comment by gouchi** [comment]
Indeed [hid_steam](https://cateee.net/lkddb/web-lkddb/HID_STEAM.html) has been integrated [from kernel 4.18](https://kernelnewbies.org/Linux_4.18#Tablets.2C_touch_screens.2C_keyboards.2C_mouses).

When this [issue](https://github.com/libretro/Lakka-LibreELEC/issues/556) will be fixed, we should get kernel 4.18 for generic platform.

**Comment by FM1337** [comment]
> Indeed [hid_steam](https://cateee.net/lkddb/web-lkddb/HID_STEAM.html) has been integrated [from kernel 4.18](https://kernelnewbies.org/Linux_4.18#Tablets.2C_touch_screens.2C_keyboards.2C_mouses).
> 
> When this [issue](https://github.com/libretro/Lakka-LibreELEC/issues/556) will be fixed, we should get kernel 4.18 for generic platform.

That's great, hopefully that issue will be fixed in the near future.

**Comment by Ntemis** [comment]
so guys shall we close this since it links to https://github.com/libretro/Lakka-LibreELEC/issues/556 ?

**Comment by FM1337** [comment]
I'd probably recommend keeping this open until #556 is resolved. *shrug*

**Comment by natinusala** [comment]
Would the driver work on older versions of Linux ? If so we can make it a patch and make it available for every platform at once.

**Comment by FM1337** [comment]
It might be possible, if someone could link to the driver and a means of getting it to load I would be more than happy to test it.

**Comment by gouchi** [comment]
For the [commit](https://git.kernel.org/linus/c164d6abf3841ffacfdb757c10616f9cb1f67276) if you want to try.

**Comment by kivutar** [comment]
I also own this controller. I'm against patching the old kernels to support new controllers because we did it for xbox one and it was too much of a pain.

We can start supporting it for devices that have a recent kernel.

**Comment by natinusala** [comment]
Fair enough. My ROCKPro64 will cry in a corner until Rockchip updates the kernel :p

**Comment by untuned** [comment]
Happy new year, I also have a steam controller and would like this.

**Comment by gouchi** [comment]
@FM1337 @untuned you may try this [testing build](https://drive.google.com/drive/folders/128MaH09bjVcB2pR4Kj2XxdBabR-oDP75) for x86_64 plateform.

[Source](https://github.com/libretro/Lakka-LibreELEC/issues/556#issuecomment-455847385)

**Comment by ToKe79** [comment]
HI,
we have new devel builds which should support the steam controller. All feedback is appreciated!
http://nightly.builds.lakka.tv/Lakka-LE9.2/latest/

**Comment by ToKe79** [comment]
I created this config file for the Wireless Steam Controller https://github.com/libretro/retroarch-joypad-autoconfig/pull/549
Steam controller confirmed working on Lakka-LE9.2 Generic 64-bit.
