### ISSUE TITLE
lakka 2.1rc6 asus tinkerboard

### ISSUE THREAD

**Issue by db1005** [libretro/Lakka-LibreELEC#284]
tried this update on asus tinkerboard i was using my 8bitdo bluetooth nes pro with it working just fine when i tried my usb n64, usb nes, or usb snes nothing happens it was like my usb ports quit working. i thought usb stopped working till i verified by plugging in a usb thumb drive with video files on it and it reads the files no problem. i was using lakka 2.1rc5 with no problems except usb n64 pad anolog stick would not bind correctly. lakka 2.1rc6 and usb controllers work out of the box running on pc and rpi3 so it must be a problem only for asus tinkerboard.

**Comment by Ntemis** [comment]
Fixed with https://github.com/libretro/Lakka-LibreELEC/commit/0086029edd4b36732ad8fbec22183869358690fc
