### ISSUE TITLE
Recording function doesn't work in Orange Pi Plus 2e

### ISSUE THREAD

**Issue by zarkon0** [libretro/Lakka-LibreELEC#285]
The Recording function doesn't work in Orange Pi Plus 2e.
Recording doesn't work saving to .mkv file.
Recording doesn't work streaming to twitch.

The file name and other options in the Recoding option menu never save to retroarch.cfg file.
If edit manually retroarch.cfg to include recording options lakka clear this options.

**Comment by Kivutar** [comment]
Ok, can you try recording using the command line?

**Comment by zarkon0** [comment]
Where I can use the command line?

I connect with putty to the Orange Pi Plus 2e but I don't know the location
of the retroarch executable and the command line that I must be used.

**Comment by Kivutar** [comment]
Take a look at our wiki, everything is explained about accessing the command line
