### ISSUE TITLE
SSH doesn't work on Lakka 2.1 on Orange Pi Plus 2e 

### ISSUE THREAD

**Issue by zarkon0** [libretro/Lakka-LibreELEC#291]
Hi.

The SSH service doesn't work in the AllWinner versión of lakka 2.1 for Orange Pi Plus 2e.

The other versions like 2.1 rc-5 works perfectly.

**Comment by Ntemis** [comment]
we can only test on pi pc because no one of the team have your board sorry.
If it works am closing this down

**Comment by zarkon0** [comment]
I've installed in the intermal eMMC 2.1 rc-5 and the SSH works.
I've installed in the SD the 2.1 final and the SSH doesn't connect.
I've tryed several times booting from the SD and from the eMMC and the SSH
in the 2.1 final never works.
