### ISSUE TITLE
The command lines is showed in Orange Pi Plus 2e

### ISSUE THREAD

**Issue by zarkon0** [libretro/Lakka-LibreELEC#293]
Hi.

In the Allwinner version, during the start, update and shutdown the lakka shows command lines than with older versions than 2.1-rc5 doesn't show.

**Comment by Ntemis** [comment]
Confirmed but now we are using mainline kernel and mainline u-boot.
Until we know more about it and with direct relation to https://github.com/libretro/Lakka-LibreELEC/issues/257 am closing it down for now.
