### ISSUE TITLE
Lakka 2.1 cannot boot on cubietruck

### ISSUE THREAD

**Issue by CliffHan** [libretro/Lakka-LibreELEC#300]
Downloaded lakka 2.1 (Lakka-Allwinner.Cubietruck.arm-2.1.img.gz) from lakka.tv, and extracted without error.
Used etcher to flash it on a 8gb tf (sdhc) card without error. And connected a Logitech F710 usb receiver to the cubietruck. Connected the board to tv with hdmi.
When the board boot, I can see nothing on the screen. I waited a long time and it's keeping black.
TV is a SONY 24EX520.

P.S. the tf card is not that good I think, but it can still boot on cubietruck with latest armbian.

**Comment by Kivutar** [comment]
Well, I just tested it now, and it boots for me. I can't reproduce.

**Comment by Matt1234321** [comment]
I have the same issue with 2.1.1

**Comment by kacherga** [comment]
I confirm it does not work on the CUBETRUCK! neither 2.1 nor 2.2 - black screen!

**Comment by CliffHan** [comment]
I just tested 2.2 and it cannot work either, the phenomenon was same as 1st comment.

**Comment by LennyLip** [comment]
it seems it's hdmi/vga issue related.
