### ISSUE TITLE
Lakka bootloop

### ISSUE THREAD

**Issue by Alexius77** [libretro/Lakka-LibreELEC#312]
Hello, I have a bootloop after flashing lakka to an usb-drive.
- Which version of Lakka are you using?
2.1 stable i386 and x64
- What system hardware are you using?
Usb kingston 101, cpu amd athlon II 170u, gpu integrated radeon 2100, 3 gb ddr2 800 mhz
- What did you do?
Nothing, just inserted usb flash drive into pc
- What did you expect to happen?
That Lakka should start
- What happened instead?
Bootloop on lakka berry image

**Comment by gouchi** [comment]
Please boot with 
`live textmode`

And provide some [Lakka system and graphic logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/).

Thank you.

**Comment by Alexius77** [comment]
![img_20171217_003902](https://user-images.githubusercontent.com/34558500/34074636-796b315e-e2c4-11e7-9fa9-0824c5448e72.jpg)
I've entered the commands, what should I do next?

**Comment by Alexius77** [comment]
i don't have internet connection or lan on pc running lakka and none of three linux fs drivers work in my windows 10

**Comment by Alexius77** [comment]
at last here it is
[log2.txt](https://github.com/libretro/Lakka-LibreELEC/files/1565177/log2.txt)

**Comment by gouchi** [comment]
Same [issue](https://forums.libretro.com/t/stuck-at-first-time-boot-screen-infinite-reboot-loop/10599) with R300 graphic card family. Yours is R400.

`Unable to find target for this triple (no targets are registered)`

It seems an issue related to llvm.

**Comment by Alexius77** [comment]
So, what's the solution then?

**Comment by gouchi** [comment]
I don't know yet the solution.

**Comment by gouchi** [comment]
May you  try to do some test with our [nightly builds](http://nightly.builds.lakka.tv/) and provides some log ?

**Comment by Alexius77** [comment]
oh, well, i can try

**Comment by gouchi** [comment]
Please check [this comment](https://github.com/libretro/Lakka-LibreELEC/issues/312#issuecomment-352193187).

**Comment by Alexius77** [comment]
[log.txt](https://github.com/libretro/Lakka-LibreELEC/files/2078460/log.txt)
here is the log from that build

**Comment by gouchi** [comment]
Unfortunately, you got a [segfault](https://en.wikipedia.org/wiki/Segmentation_fault).

Can you try to use the rgui menu driver ? Boot with `live textmode` then

```
sed -i -e "s/menu_driver = \"xmb\"/menu_driver = \"rgui\"/g" .config/retroarch.cfg
retroarch -v
```

**Comment by Alexius77** [comment]
sed: .config/retroarch.cfg: No such file or directory

**Comment by ToKe79** [comment]
should be
```
.config/retroarch/retroarch.cfg
```

**Comment by Alexius77** [comment]
![img_20180607_194519](https://user-images.githubusercontent.com/34558500/41116419-e94414cc-6a92-11e8-8aad-b853e8110253.jpg)
ls says that there is no config directory

**Comment by ToKe79** [comment]
it is a hidden folder (starting with a dot), so you need `ls -a`. absolute path is `/storage/.config/retroarch/retroarch.cfg`. i just checked on my s912 box.

**Comment by Alexius77** [comment]
done, again this segmentation fault

**Comment by Alexius77** [comment]
by the way, what causes this segfault in general - cpu/ram/hdd?

**Comment by gouchi** [comment]
Please provide the log with rgui menu.

**Comment by Alexius77** [comment]
[logrgui.txt](https://github.com/libretro/Lakka-LibreELEC/files/2085054/logrgui.txt)

**Comment by gouchi** [comment]
Same error with rgui menu driver

```
Unable to find target for this triple (no targets are registered)
Segmentation fault (core dumped)
```
We need to search/find a fix for this issue as I don't know how to fix it currently.

**Comment by gouchi** [comment]
Can you try to launch RA with

`DRAW_USE_LLVM=0 retroarch -v`

Thank you.

**Comment by Alexius77** [comment]
yes, it worked - the system has started with rgui driver, but i don't know whether it is an error or not - when i press ESC in any screen, the system quits to the textmode, and when I try to connect to wi-fi and enter the password, nothing happens - so I don't know works my connection or not
and my USB flash drive doesn't look like working properly - when I connect it to PC, Windows doesn't allow to format it in any way :( and when I try to view it in Control Panel - Administrative Tools - Computer Management, the system hangs

**Comment by gouchi** [comment]
It is normal when you press Esc that RA closed as you started it manually.

You may try to [setup the network with  conmannctl](http://www.lakka.tv/doc/Network-settings/).

It is normal you don't see the usb stick as the partition format is [not recognized natively on Windows](http://www.lakka.tv/doc/Accessing-Lakka-filesystem/#direct-drive-access).

**Comment by Alexius77** [comment]
no, I mean it wasn't recognized before, but I could easily format it into NTFS or smth and then flash it with a new build of Lakka, now I can't do it at all

**Comment by gouchi** [comment]
I will close this issue as the original issue is fixed.
