### ISSUE TITLE
Unable to (cross) compile for ROCK64

### ISSUE THREAD

**Issue by andrebraga** [libretro/Lakka-LibreELEC#313]
Hi, I'm attempting to compile Lakka under a standard Debian docker environment.

I'm finiding myself stuck at:

```
/root/Lakka-LibreELEC/build.LibreELEC-ROCK64.arm-8.2-devel/kodi-5bd45ab/xbmc/windowing/egl/EGLWrapper.cpp: In function 'bool {anonymous}::CorrectGuess(CEGLNativeType*, const string&)':
/root/Lakka-LibreELEC/build.LibreELEC-ROCK64.arm-8.2-devel/kodi-5bd45ab/xbmc/windowing/egl/EGLWrapper.cpp:63:13: error: invalid use of incomplete type 'class CEGLNativeType'
```

Any pointers for building? I tried both `arm` and `aarch64` and both break at the same point.

`PROJECT=Rockchip DEVICE=ROCK64 ARCH=arm make image`

**Comment by ToKe79** [comment]
seems like you are missing  `DISTRO=Lakka` anywhere before `make`

**Comment by Kivutar** [comment]
Yep.
