### ISSUE TITLE
PS4 Mini Wired Gamepad not working

### ISSUE THREAD

**Issue by catzoo** [libretro/Lakka-LibreELEC#314]
Thank you for developing Lakka. Currently i'm trying to make a present for my Grandparents, they always talked about miss playing old games (such as Tetris and Doctor Mario)

- Which version of Lakka are you using? 
I believe 2.1    (RPi2.arm-2.1)
- What system hardware are you using? 
Raspberry Pi 3
- What did you do? 
Plugged in the controller and tried to bind all the inputs
- What did you expect to happen?
Bind and Save the inputs
- What happened instead?
Did not recognize the inputs and did nothing

I did test the controllers on other computers making sure the controllers aren't broken.
And i'm using this controller: [Link](https://www.playstation.com/en-us/explore/accessories/gaming-controllers/mini-wired-gamepad/)

Thank you for reading

---Input Logs---

Lakka:~ # lsusb
Bus 001 Device 006: ID 0f0d:00ee Hori Co., Ltd
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast                                                                                                     Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Lakka:~ # dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.9.59 (kivutar@Server01) (gcc version 6.2.0 (GCC)                                                                                                     ) #1 SMP Sun Nov 19 07:05:16 CST 2017
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instructio                                                                                                    n cache
[    0.000000] OF: fdt:Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] cma: Reserved 8 MiB at 0x2f800000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 196608
[    0.000000] free_area_init_node: node 0, pgdat 80c363c0, node_mem_map af13600                                                                                                    0
[    0.000000]   Normal zone: 1728 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 196608 pages, LIFO batch:31
[    0.000000] percpu: Embedded 14 pages/cpu @af0f0000 s25420 r8192 d23732 u5734                                                                                                    4
[    0.000000] pcpu-alloc: s25420 r8192 d23732 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pag                                                                                                    es: 194880
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1920 bcm2                                                                                                    708_fb.fbheight=1080 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_s                                                                                                    ize=0x40000000  boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 quiet  vt.global_cursor_                                                                                                    default=0 loglevel=2 root=/dev/ram0 rdinit=/init BOOT_IMAGE=/kernel.img usbcore.                                                                                                    autosuspend=-1
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 758304K/786432K available (6144K kernel code, 222K rwdata                                                                                                    , 1376K rodata, 3072K init, 394K bss, 19936K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xb0800000 - 0xff800000   (1264 MB)
[    0.000000]     lowmem  : 0x80000000 - 0xb0000000   ( 768 MB)
[    0.000000]     modules : 0x7f000000 - 0x80000000   (  16 MB)
[    0.000000]       .text : 0x80008000 - 0x80700000   (7136 kB)
[    0.000000]       .init : 0x80900000 - 0x80c00000   (3072 kB)
[    0.000000]       .data : 0x80c00000 - 0x80c378a0   ( 223 kB)
[    0.000000]        .bss : 0x80c39000 - 0x80c9ba6c   ( 395 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 19.20MHz (ph                                                                                                    ys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles:                                                                                                     0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 43980                                                                                                    46511078ns
[    0.000016] Switching to timer-based delay loop, resolution 52ns
[    0.000204] Console: colour dummy device 80x30
[    0.000219] console [tty0] enabled
[    0.000234] Calibrating delay loop (skipped), value calculated using timer fr                                                                                                    equency.. 38.00 BogoMIPS (lpj=64000)
[    0.000247] pid_max: default: 32768 minimum: 301
[    0.000379] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000386] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001193] Disabling memory control group subsystem
[    0.001227] CPU: Testing write buffer coherency: ok
[    0.001552] CPU0: update cpu_capacity 1024
[    0.001559] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.001586] Setting up static identity map for 0x100000 - 0x100034
[    0.003167] CPU1: update cpu_capacity 1024
[    0.003175] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.003804] CPU2: update cpu_capacity 1024
[    0.003810] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.004385] CPU3: update cpu_capacity 1024
[    0.004391] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.004469] Brought up 4 CPUs
[    0.004478] SMP: Total of 4 processors activated (153.00 BogoMIPS).
[    0.004482] CPU: All CPU(s) started in HYP mode.
[    0.004486] CPU: Virtualization extensions available.
[    0.005045] devtmpfs: initialized
[    0.015035] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3                                                                                                     rev 4
[    0.015270] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, ma                                                                                                    x_idle_ns: 6370867519511994 ns
[    0.015285] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.015759] pinctrl core: initialized pinctrl subsystem
[    0.016627] NET: Registered protocol family 16
[    0.018680] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.033335] cpuidle: using governor ladder
[    0.046699] cpuidle: using governor menu
[    0.047228] Serial: AMBA PL011 UART driver
[    0.048867] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.049327] uart-pl011 3f201000.serial: could not find pctldev for node /soc/                                                                                                    gpio@7e200000/uart0_pins, deferring probe
[    0.101043] bcm2835-dma 3f007000.dma: DMA legacy API manager at b080f000, dma                                                                                                    chans=0x1
[    0.102640] SCSI subsystem initialized
[    0.102912] usbcore: registered new interface driver usbfs
[    0.102988] usbcore: registered new interface driver hub
[    0.103065] usbcore: registered new device driver usb
[    0.103590] raspberrypi-firmware soc:firmware: Attached to firmware from 2017                                                                                                    -10-24 17:13
[    0.104868] clocksource: Switched to clocksource arch_sys_counter
[    0.105159] FS-Cache: Loaded
[    0.115936] NET: Registered protocol family 2
[    0.116620] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.116728] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.116912] TCP: Hash tables configured (established 8192 bind 8192)
[    0.116996] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.117037] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.117237] NET: Registered protocol family 1
[    0.117564] RPC: Registered named UNIX socket transport module.
[    0.117569] RPC: Registered udp transport module.
[    0.117572] RPC: Registered tcp transport module.
[    0.117576] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.256180] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.270237] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.271617] FS-Cache: Netfs 'nfs' registered for caching
[    0.272502] NFS: Registering the id_resolver key type
[    0.272526] Key type id_resolver registered
[    0.272530] Key type id_legacy registered
[    0.272543] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.272781] FS-Cache: Netfs 'cifs' registered for caching
[    0.275925] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 2                                                                                                    51)
[    0.275933] io scheduler noop registered (default)
[    0.275938] io scheduler deadline registered
[    0.276164] io scheduler cfq registered
[    0.281606] BCM2708FB: allocated DMA memory ef910000
[    0.281626] BCM2708FB: allocated DMA channel 0 @ b080f000
[    0.333766] Console: switching to colour frame buffer device 240x67
[    0.364969] bcm2835-rng 3f104000.rng: hwrng registered
[    0.365074] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000                                                                                                    000(1024 MiB)
[    0.365544] vc-sm: Videocore shared memory driver
[    0.378672] brd: module loaded
[    0.378834] loop: module loaded
[    0.382483] nbd: registered device at major 43
[    0.394059] usbcore: registered new interface driver rtsx_usb
[    0.394066] Loading iSCSI transport class v2.0-870.
[    0.394490] iscsi: registered transport (tcp)
[    0.395021] libphy: Fixed MDIO Bus: probed
[    0.395026] tun: Universal TUN/TAP device driver, 1.6
[    0.395030] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.395320] usbcore: registered new interface driver dm9601
[    0.395401] usbcore: registered new interface driver smsc95xx
[    0.395438] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.623497] Core Release: 2.80a
[    0.623505] Setting default values for core params
[    0.623532] Finished setting default values for core params
[    0.823897] Using Buffer DMA mode
[    0.823902] Periodic Transfer Interrupt Enhancement - disabled
[    0.823906] Multiprocessor Interrupt Enhancement - disabled
[    0.823913] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.823927] Dedicated Tx FIFOs mode
[    0.824261] WARN::dwc_otg_hcd_init:1032: FIQ DMA bounce buffers: virt = 0xaf9                                                                                                    04000 dma = 0xef904000 len=9024
[    0.824287] FIQ FSM acceleration enabled for :
[    0.824287] Non-periodic Split Transactions
[    0.824287] Periodic Split Transactions
[    0.824287] High-Speed Isochronous Endpoints
[    0.824287] Interrupt/Control Split Transaction hack enabled
[    0.824294] dwc_otg: Microframe scheduler enabled
[    0.824341] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x80534cb0
[    0.824349] WARN::hcd_init_fiq:460: FIQ ASM at 0x80535010 length 36
[    0.824361] WARN::hcd_init_fiq:486: MPHI regs_base at 0xb087e000
[    0.824415] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.824447] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number                                                                                                     1
[    0.824477] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.824524] Init: Port Power? op_state=1
[    0.824528] Init: Power Port (0)
[    0.824705] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.824714] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                                                                    1
[    0.824721] usb usb1: Product: DWC OTG Controller
[    0.824728] usb usb1: Manufacturer: Linux 4.9.59 dwc_otg_hcd
[    0.824735] usb usb1: SerialNumber: 3f980000.usb
[    0.825461] hub 1-0:1.0: USB hub found
[    0.825495] hub 1-0:1.0: 1 port detected
[    0.826116] dwc_otg: FIQ enabled
[    0.826120] dwc_otg: NAK holdoff enabled
[    0.826123] dwc_otg: FIQ split-transaction FSM enabled
[    0.826135] Module dwc_common_port init
[    0.826342] usbcore: registered new interface driver usb-storage
[    0.826540] mousedev: PS/2 mouse device common for all mice
[    0.826686] i2c /dev entries driver
[    0.828006] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.828302] bcm2835-cpufreq: min=600000 max=1200000
[    0.828784] sdhci: Secure Digital Host Controller Interface driver
[    0.828788] sdhci: Copyright(c) Pierre Ossman
[    0.829067] sdhost-bcm2835 3f202000.sdhost: could not get clk, deferring prob                                                                                                    e
[    0.831228] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.831316] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.835357] ledtrig-cpu: registered to indicate activity on CPUs
[    0.835451] hidraw: raw HID events driver (C) Jiri Kosina
[    0.836398] usbcore: registered new interface driver usbhid
[    0.836400] usbhid: USB HID core driver
[    0.836832] vchiq: vchiq_init_state: slot_zero = 0xaf980000, is_master = 0
[    0.837794] [vc_sm_connected_init]: start
[    0.846078] [vc_sm_connected_init]: end - returning 0
[    0.846771] NET: Registered protocol family 10
[    0.847314] NET: Registered protocol family 17
[    0.847364] Key type dns_resolver registered
[    0.847576] Registering SWP/SWPB emulation handler
[    0.851562] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.851610] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud                                                                                                     = 0) is a PL011 rev2
[    0.852468] sdhost: log_buf @ af907000 (ef907000)
[    0.904876] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.906890] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.906894] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.958255] console [netcon0] enabled
[    0.958258] netconsole: network logging started
[    0.958260] of_cfs_init
[    0.958323] of_cfs_init: OK
[    0.961057] Freeing unused kernel memory: 3072K
[    0.965656] mmc0: host does not support reading read-only switch, assuming wr                                                                                                    ite-enable
[    0.968007] mmc0: new high speed SDHC card at address 0001
[    0.969369] mmcblk0: mmc0:0001 GB1QT 29.8 GiB
[    0.972437]  mmcblk0: p1 p2
[    0.978588] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.980112] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.981631] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.984380] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.031610] Indeed it is in host mode hprt0 = 00021501
[    1.094020] random: fast init done
[    1.146000] mmc1: new high speed SDIO card at address 0001
[    1.204884] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.204980] Indeed it is in host mode hprt0 = 00001101
[    1.395144] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.395154] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.395638] hub 1-1:1.0: USB hub found
[    1.395686] hub 1-1:1.0: 5 ports detected
[    1.536765] EXT4-fs (mmcblk0p2): couldn't mount as ext3 due to feature incomp                                                                                                    atibilities
[    1.537144] EXT4-fs (mmcblk0p2): couldn't mount as ext2 due to feature incomp                                                                                                    atibilities
[    1.618346] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. O                                                                                                    pts: (null)
[    1.674887] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.765255] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.765268] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber                                                                                                    =0
[    1.768225] smsc95xx v1.0.5
[    1.820828] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-                                                                                                    1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:71:a0:9b
[    1.908258] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.003489] usb 1-1.2: New USB device found, idVendor=046d, idProduct=c52b
[    2.003499] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                    =0
[    2.003503] usb 1-1.2: Product: USB Receiver
[    2.003506] usb 1-1.2: Manufacturer: Logitech
[    2.017776] logitech-djreceiver 0003:046D:C52B.0003: hiddev0,hidraw0: USB HID                                                                                                     v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.2/input2
[    2.122862] systemd[1]: System time before build time, advancing clock.
[    2.135855] input: Logitech K360 as /devices/platform/soc/3f980000.usb/usb1/1                                                                                                    -1/1-1.2/1-1.2:1.2/0003:046D:C52B.0003/0003:046D:4004.0004/input/input0
[    2.136449] logitech-hidpp-device 0003:046D:4004.0004: input,hidraw1: USB HID                                                                                                     v1.11 Keyboard [Logitech K360] on usb-3f980000.usb-1.2:1
[    2.140358] systemd[1]: systemd 232 running in system mode. (-PAM -AUDIT -SEL                                                                                                    INUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -                                                                                                    XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
[    2.140666] systemd[1]: Detected architecture arm.
[    2.140942] systemd[1]: Set hostname to <Lakka>.
[    2.201593] usb 1-1.3: new full-speed USB device number 5 using dwc_otg
[    2.210258] systemd[1]: Started Dispatch Password Requests to Console Directo                                                                                                    ry Watch.
[    2.210473] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.210741] systemd[1]: Listening on RPCbind Server Activation Socket.
[    2.210792] systemd[1]: Reached target RPC Port Mapper.
[    2.210917] systemd[1]: Started Forward Password Requests to Wall Directory W                                                                                                    atch.
[    2.210961] systemd[1]: Reached target Paths.
[    2.211073] systemd[1]: Listening on Journal Socket.
[    2.294903] usb 1-1.3: New USB device found, idVendor=0f0d, idProduct=00ee
[    2.294911] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                    =0
[    2.294916] usb 1-1.3: Product: HORIPAD mini4
[    2.294920] usb 1-1.3: Manufacturer: HORI CO.,LTD.
[    2.300280] input: HORI CO.,LTD. HORIPAD mini4 as /devices/platform/soc/3f980                                                                                                    000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0F0D:00EE.0005/input/input1
[    2.303835] hid-generic 0003:0F0D:00EE.0005: input,hiddev0,hidraw2: USB HID v                                                                                                    1.11 Gamepad [HORI CO.,LTD. HORIPAD mini4] on usb-3f980000.usb-1.3/input0
[    2.471074] systemd-journald[227]: Received request to flush runtime journal                                                                                                     from PID 1
[    3.377447] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f2                                                                                                    00000
[    3.427102] Console: switching to colour dummy device 80x30
[    3.559557] usbcore: registered new interface driver brcmfmac
[    3.937426] brcmfmac: Firmware version = wl0: Aug  7 2017 00:46:29 version 7.                                                                                                    45.41.46 (r666254 CY) FWID 01-f8a78378
[    3.939252] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.                                                                                                    11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data:                                                                                                     9.10.41 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-08-07 00:37:4                                                                                                    7
[    4.017038] uart-pl011 3f201000.serial: no DMA platform data
[    4.037088] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    4.037380] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    4.204834] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    4.204846] brcmfmac: power management disabled
[    4.467719] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[    8.426307] Bluetooth: Core ver 2.22
[    8.426588] NET: Registered protocol family 31
[    8.426596] Bluetooth: HCI device and connection manager initialized
[    8.428698] Bluetooth: HCI socket layer initialized
[    8.428733] Bluetooth: L2CAP socket layer initialized
[    8.428820] Bluetooth: SCO socket layer initialized
[    8.440986] Bluetooth: HCI UART driver ver 2.3
[    8.441006] Bluetooth: HCI UART protocol H4 registered
[    8.441011] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.441333] Bluetooth: HCI UART protocol Broadcom registered
[   10.504957] Bluetooth: hci0 command 0x0c14 tx timeout
[   10.505401] Bluetooth: hci0: Frame reassembly failed (-84)
[   10.505413] Bluetooth: hci0: Frame reassembly failed (-84)
[   14.520944] random: crng init done
[  301.481993] usb 1-1.2: USB disconnect, device number 4
[  306.082311] usb 1-1.3: USB disconnect, device number 5
[  310.544891] usb 1-1.2: new full-speed USB device number 6 using dwc_otg
[  310.637889] usb 1-1.2: New USB device found, idVendor=0f0d, idProduct=00ee
[  310.637906] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                    =0
[  310.637913] usb 1-1.2: Product: HORIPAD mini4
[  310.637920] usb 1-1.2: Manufacturer: HORI CO.,LTD.
[  310.649225] input: HORI CO.,LTD. HORIPAD mini4 as /devices/platform/soc/3f980                                                                                                    000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:0F0D:00EE.0006/input/input2
[  310.650241] hid-generic 0003:0F0D:00EE.0006: input,hiddev0,hidraw0: USB HID v                                                                                                    1.11 Gamepad [HORI CO.,LTD. HORIPAD mini4] on usb-3f980000.usb-1.2/input0
[  753.938122] usb 1-1.4: new full-speed USB device number 7 using dwc_otg
[  754.033509] usb 1-1.4: New USB device found, idVendor=046d, idProduct=c52b
[  754.033530] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber                                                                                                    =0
[  754.033537] usb 1-1.4: Product: USB Receiver
[  754.033545] usb 1-1.4: Manufacturer: Logitech
[  754.052911] logitech-djreceiver 0003:046D:C52B.0009: hiddev0,hidraw1: USB HID                                                                                                     v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.4/input2
[  754.174337] input: Logitech K360 as /devices/platform/soc/3f980000.usb/usb1/1                                                                                                    -1/1-1.4/1-1.4:1.2/0003:046D:C52B.0009/0003:046D:4004.000A/input/input3
[  754.177194] logitech-hidpp-device 0003:046D:4004.000A: input,hidraw2: USB HID                                                                                                     v1.11 Keyboard [Logitech K360] on usb-3f980000.usb-1.4:1
[  776.808114] usb 1-1.4: reset full-speed USB device number 7 using dwc_otg
[  777.479756] usb 1-1.4: USB disconnect, device number 7

**Comment by ToKe79** [comment]
HI,
to me it looks like the gamepad is detected, e.g starting from 301 seconds.
You can list the input devices:
```bash
ls /dev/input
```
joysticks / gamepads should be listed as `jsN`, e.g. `js0`. And then try to test the input:
```bash
jstest /dev/input/jsN
```
where the `N` is replaced with a number, most probably `0`. Pressing the D-Pad, buttons, moving the sticks should trigger either `on` for buttons or axis changes for analog sticks/buttons.

**Comment by catzoo** [comment]
Hey, and yes I did have a wireless keyboard during that time, I only have one keyboard so I kept plugging it in and unplugging it. I should've said this in the report, sorry about that.
They keyboard is a old Wireless Logitech keyboard, I forgot what type it is.

During this time I only have the controller connected and nothing else. Its weird that it thinks its a mice and not a controller.

I try to test it out and I pushed everything and moved the analogs, and nothing came up.

```
Lakka:~ # ls /dev/input
mice
Lakka:~ # jstest /dev/input/mice
Joystick (Unknown) has 2 axes and 2 buttons. Driver version is 0.8.0.
Testing ... (interrupt to exit)

^?
^C
Lakka:~ #
```
When I tried to stop it, I missed the Ctrl-C at first.

**Comment by ToKe79** [comment]
Hm, the gamepad is not listed in `/dev/input`, but according to `dmesg` it was detected. The `mice` device does not have to be related to the gamepad - you can confirm when you unplug the gamepad and do `ls /dev/input` - if `mice` will be still there -> not related to gamepad.

Have you tried navigating in the RetroArch using the keyboard `cursor keys`, `enter` and `backspace`? If navigation with keyboard works, try to get to `Settings` -> `Input` -> `Input User 1 Binds` and check what you have under the item `User 1 Device Index` and try to configure the controls below.

**Comment by catzoo** [comment]
I checked to see if Mice is unrelated, I unplugged and plugged it back in and I found the js0.
```
Lakka:~ # ls /dev/input
by-id    by-path  event0   js0      mice
```
I tested out the input on js0 and it all worked.


When I turn the Raspberry Pi on I always have the controller plugged in before turning it on. Whenever I try to bind it, it doesn't work and I can't find it in `Device 1 Index`. After I found out unplugging the controller and plugging it back in detected it, it all started working. I found it in the `Device 1 Index` and I can bind all of it.

Whats weird is it doesn't detect it when its plugged in on bootup, But if you plug it in after its been turned on and on the main screen it all starts working.

**Comment by gouchi** [comment]
Hi,

Can you try to give the output with the block related to your game controller 

`cat /proc/bus/input/devices`

Then provide the output of

`udevadm info --name=input/eventX` where X is the number related to your game controller. You can get it from the line starting with `H: Handlers=`

For example, for this output

I: Bus=0003 Vendor=054c Product=0268 Version=8111
N: Name="**Gasia Co.,Ltd PS(R) Gamepad**"
P: Phys=usb-0000:00:1d.1-2/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.1/usb3/3-2/3-2:1.0/0003:054C:0268.0004/input/input11
U: Uniq=00:26:5c:00:77:f6
H: Handlers=js1 **event12** 
B: PROP=0
B: EV=20001b
B: KEY=f00000000 0 0 0 7fdb000000000000 0 0 0 0
B: ABS=3f
B: MSC=10
B: FF=107030000 

I should enter udevadm info --name=input/**event12**

Thank you.

**Comment by catzoo** [comment]
Hey, and sure
```Lakka:~ # cat /proc/bus/input/devices
I: Bus=0003 Vendor=0f0d Product=00ee Version=0111
N: Name="HORI CO.,LTD. HORIPAD mini4"
P: Phys=usb-3f980000.usb-1.3.2/input0
S: Sysfs=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3.2/1-1.3.2:1.0/0003:0F0D:00EE.0001/input/input0
U: Uniq=
H: Handlers=js0 event0
B: PROP=0
B: EV=1b
B: KEY=3fff0000 0 0 0 0 0 0 0 0 0
B: ABS=3003f
B: MSC=10
```

and here is the output:
```Lakka:~ # udevadm info --name=input/event0
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3.2/1-1.3.2:1.0/0003:0F0D:00EE.0001/input/input0/event0
N: input/event0
S: input/by-id/usb-HORI_CO._LTD._HORIPAD_mini4-event-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.3.2:1.0-event-joystick
E: DEVLINKS=/dev/input/by-id/usb-HORI_CO._LTD._HORIPAD_mini4-event-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.3.2:1.0-event-joystick
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3.2/1-1.3.2:1.0/0003:0F0D:00EE.0001/input/input0/event0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_3_2_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=HORIPAD_mini4
E: ID_MODEL_ENC=HORIPAD\x20mini4
E: ID_MODEL_ID=00ee
E: ID_PATH=platform-3f980000.usb-usb-0:1.3.2:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_3_2_1_0
E: ID_REVISION=0100
E: ID_SERIAL=HORI_CO._LTD._HORIPAD_mini4
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=HORI_CO._LTD.
E: ID_VENDOR_ENC=HORI\x20CO.\x2cLTD.
E: ID_VENDOR_ID=0f0d
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=3392365
```

After I found out unplugging it and plugging it back in worked, I binded it all and it started to work.
When I start up the raspberry pi with the controller plugged in it worked.

**Comment by gouchi** [comment]
Hi,

It is detected as game controller so it is ok. Did you try to push PS button before using it ?

Thank you.
