### ISSUE TITLE
Can't change disk index with m3u file (Metal Gear Solid on RPi3)

### ISSUE THREAD

**Issue by RaydenX93** [libretro/Lakka-LibreELEC#320]
Hello, I am using the latest version of Lakka on a RPi3.
I am trying to play Metal Gear Solid. I have bin and cue files for each of the 2 CDs and i created a m3u file in the same folder with two lines, containing each the name of a .cue file. I also modified the playlist so that the actual m3u file is loaded and not the cue of a single cd but when I load up the m3u an go to change the disk index, the number does not change.
Any help?
Thanks

**Comment by ToKe79** [comment]
Hi @RaydenX93,
I found [this](https://forums.libretro.com/t/how-to-play-multidisc-games-ps1-dreamcast-ect/10596/2) in the forum. In one of the posts it suggest using three steps to swap the disks: `Open Disk Tray`, `Switch Disk`, `Close Disk Tray`.
Does this help?
