### ISSUE TITLE
Feature request: menu option to access tty command line.

### ISSUE THREAD

**Issue by draperjames** [libretro/Lakka-LibreELEC#323]
It would be great if there was an option in the menu to access Lakka's tty commandline. Right now the only way to access it requires using ssh from another machine or modifying the boot loader which is pretty difficult for weekend-warriors/noobs like me.

I'd submit a PR myself on this but have no idea where to start. Any advice would be appreciated.

**Comment by RobLoach** [comment]
A Terminal Emulator libretro core would be pretty cool.

**Comment by RobLoach** [comment]
Haven't tested lately, but use to be able to use CTRL SHIFT F1-6 to switch between screens.

**Comment by draperjames** [comment]
@RobLoach by switch screens do you mean change monitor index? I've been able to access the command line by adding tty to the bootloader then when running Lakka pressing escape then Ctrl+F3 quickly and typing `systemctl stop retoarch`. It's not an elegant method but it works.

**Comment by RobLoach** [comment]
Correction: CTRL-ALT-F2 and CTRL-ALT-F7 ..... I use that on my Kodi-buntu box, haven't tested on LibreELEC/Lakka.

**Comment by Ntemis** [comment]
CTRL+ALT+F2 should land you in terminal

**Comment by draperjames** [comment]
@Ntemis I just tried CTRL+ALT+F2 on a fresh install of the most recent build of Lakka for PC on a flash drive and it did not work at all. Granted I didn't mess around with the bootloader or anything. How did you enable that?

**Comment by Ntemis** [comment]
I meant pressing CTRL+ALT+F2 keys should land you in command line as all Linux distros normally do, i didn't said it works

**Comment by ToKe79** [comment]
Terminal console is not enabled by default. [Here](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/) are guides how to access the shell and [here](http://www.lakka.tv/doc/The-bootloader/) are guides how to modify cmdline for individual builds/systems.

**Comment by kivutar** [comment]
Even when tty is enabled, retroarch doesn't let you CTRL+ALT+F
