### ISSUE TITLE
Rock64 images freezing after boot

### ISSUE THREAD

**Issue by Jturn777** [libretro/Lakka-LibreELEC#330]
Neither of the available Rock64 images will function more than a few minutes after booting is complete. Tried on multiple boards and SD cards.

**Comment by Ntemis** [comment]
No reports of such issue from others users, you sure its not your setup?

**Comment by Jturn777** [comment]
I've tried both images available. My Rock64 board works with 3 other
distros without freezing. I've tried running with no peripherals as well.

**Comment by Ntemis** [comment]
I would recommend to get a heatsink.Closing issue but for sure my heatsink was on fire when i was testing latest image

**Comment by f0xx0f** [comment]
Hello. I have the same problem for rock64. Lakka freezing after boot. I have no idea how to solve this problem=( I will be glad to any advice. Thanks!

**Comment by Jturn777** [comment]
Havent figured it out yet. Developers were no help. Try recalbox or retropie
