### ISSUE TITLE
Black screen after updating XU4 with cd2ff40be73ae42533197d41ffd415a0442de22b

### ISSUE THREAD

**Issue by Arnochocobo** [libretro/Lakka-LibreELEC#335]
And here we go again...

Compiling -> No problem
However, after updating, system reboots and then black screen, and getting stuck there.

Did you try on an actual XU4? Multiple people on the HK forums were reporting issues with this kernel and even opened a debug party (!!!), which is a very good sign (NOT).

Or did you update just for the sake of it without checking anything on the actual hardware?

**Comment by Ntemis** [comment]
Kernel is missing gbm/kms blobs

**Comment by Arnochocobo** [comment]
I had no issue to compile it, and now I am stuck with a black screen and can't do anything (except reinstalling an older version). I am stuck there and can't provide logs. Not much more I can do in this situation.

What is the point of committing something unstable, with missing parts apparently, and that has tons of other issues? Did you check on the actual hardware it was not breaking anything before sending your commit?

**Comment by Ntemis** [comment]
Stick to 2.1 stable until we announce new rc.

**Comment by Arnochocobo** [comment]
This is the whole point of github, check WIP and compile your own version if you feel like it.

Why are you committing broken crap (for something that didn't need to get updated at all) without checking anything on the real hardware? Is that a "responsible" behavior?

**Comment by Arnochocobo** [comment]
Kivutar just mentioned that a fresh install on emmc works for him. Updating is definitely not the way to go.
If this is working for Kivutar, then it can be closed, I will try a fresh install as well.

**Comment by Ntemis** [comment]
This should be fixed by now
