### ISSUE TITLE
Audio jack not working on OrangePi PC

### ISSUE THREAD

**Issue by JackyYuenDacai** [libretro/Lakka-LibreELEC#339]
I use lakka2.1 img orangepi pc build on nanopi m1
which the hardware is exactly compatible with orangepi pc, and you can run retrorangepie on it no issue encounter.
I tried to switch the audio device through gui, but no matter how, only hdmi audio works, theres no sound through audio jack at all, I even tried to altering the driver settings. 
As theres no config.txt like rpi build, I could not find a way or doc to solve this.

**Comment by JackyYuenDacai** [comment]
there's sound after
amixer cset numid=3,iface=MIXER,name='Line Out Playback Volume' -c 1 31
amixer cset numid=4,iface=MIXER,name='Line Out Playback Switch' on,on -c 1
but the system fs is read only.... I cannot understand that.

**Comment by JackyYuenDacai** [comment]
#enable_audio_jack.service
#need to add one service ... to enable audio jack output
[Unit]
Description=enable audio codec line output
After=sound.target
Before=retroarch.service
[Service]
ExecStart=/bin/sh "amixer cset numid=3,iface=MIXER,name='Line Out Playback Volume' -c 1 31 && amixer cset numid=4,iface=MIXER,name='Line Out Playback Switch' on,on -c 1"
RemainAfterExit=yes
[Install]
WantedBy=retroarch.service

**Comment by ToKe79** [comment]
Hi, you can put systemd unit files in `/storage/.config/system.d/` folder.
Yes, the rootfs is read only, as it uses squashfs.

**Comment by ToKe79** [comment]
As there is no response, I consider this as solved. Feel free to reopen/comment in case further support is needed.
