### ISSUE TITLE
add FreeIntv to Lakka cores

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#342]
FreeIntv is a new emulator, written from the ground up as a libretro core. https://github.com/markwkidd/FreeIntv

As of January 24, it is compiling and usable on many, albeit not all, platforms supported by the buildbot. Would you consider adding FreeIntv to Lakka?

**Comment by Ntemis** [comment]
Sure will check it out today. Thanks

Στις 24 Ιαν 2018 08:31, ο χρήστης "markwkidd" <notifications@github.com>
έγραψε:

**Comment by markwkidd** [comment]
The repository is now part of the libretro organization, so it has a new link: http://github.com/libretro/FreeIntv

Also if you have access to a RetroArch installation, FreeIntv is available from the buildbot. Windows and Linux builds are generally known to be working via buildbot

**Comment by Ntemis** [comment]
Sorry that took so much time, i will prep a package soon thanks for the link

**Comment by ToKe79** [comment]
core is merged.

**Comment by markwkidd** [comment]
Thank you!!
