### ISSUE TITLE
Allwinner performance regression

### ISSUE THREAD

**Issue by kivutar** [libretro/Lakka-LibreELEC#381]
Tested on Allwinner.orangepi_pc with commit id https://github.com/libretro/Lakka-LibreELEC/commit/707fbbbc2e75536cb65a586f4d7e51d1eeb3b4f1

On mupen64plus, Zelda is not 30FPS.

On PPSSPP, Fl0w is not 30FPS.

These two games used to be playable at full speed before the switch to GBM.

**Comment by Ntemis** [comment]
I don't think retroarch supports buffer sharing using gbm
