### ISSUE TITLE
Error with M8s Ap6330 wifi chipset

### ISSUE THREAD

**Issue by aceboy50** [libretro/Lakka-LibreELEC#402]
#Wifi on Enybox M8s with ap6330 version does not work. When I select Wifi on the menu nothing shows up except for a small box symbol.
Lakka 2.1 Stable Build

**Comment by Ntemis** [comment]
wrong board dts file then for your device and we only support devices we own sorry.
As an advice to help you, try to find your board file and change wifi gpio to your android one
