### ISSUE TITLE
Strange behavior with xbox360 controller

### ISSUE THREAD

**Issue by martinoturrina** [libretro/Lakka-LibreELEC#409]
Which version of Lakka are you using? 2.1 
What system hardware are you using? RPi zero W
What did you do? Try to use xbox 360 controller to play and move in menus
What did you expect to happen? good movement with the controller
What happened instead? after some random time the controller start to stuck in one direction and after a couple o second stop completely to response to input. After unplugging it and replugging everything begin to work again for some time ad after that the same problem show up. Quite frustrating to use :(

All this while trying to write the wifi password witch for another bug was impossible to enter with the keyboard.

**Comment by RobLoach** [comment]
Analog to Digital controller enabled?

**Comment by martinotu94** [comment]
Sorry but i don't know what you are talking about. Can you explain?
thank you a lot

**Comment by RobLoach** [comment]
![screenshot at 2018-03-11 16-43-48](https://user-images.githubusercontent.com/25086/37258251-62ad3146-254b-11e8-93ba-945e5083b2e7.png)

**Comment by martinotu94** [comment]
I'll try asap and let you know!

**Comment by martinotu94** [comment]
Even enabling analog to digit i keep having the same problem. After some time the input stop responding. 

Trying on the latest available build

**Comment by ToKe79** [comment]
@martinoturrina can you try latest nightly build, e.g. from here: http://nightly.builds.lakka.tv/2018-05-28/
Should at least fix the keyboard issue.

**Comment by martinoturrina** [comment]
@ToKe79 yes, the latest nightly build have this problem fixed! hope to see this fix on final release soon :)

**Comment by ToKe79** [comment]
@martinoturrina Is also the controller issue fixed?

**Comment by martinoturrina** [comment]
@ToKe79 no, sadly the issue is already there!
