### ISSUE TITLE
Scrolling thru roms with thumbnails scanned

### ISSUE THREAD

**Issue by jdca** [libretro/Lakka-LibreELEC#414]
Lakka-RPi2.arm-2.1-devel-20180305031024-r28154-gb552a9a26

If you scroll (hold down button for a while) thru all the roms the ui get slow and no images shows, just black boxes. Restart of ui "fixes" the issue. This is also in 2.1 stable.

**Comment by gouchi** [comment]
There is already a [bug opened on RA issue tracker](https://github.com/libretro/RetroArch/issues/2791).

**Comment by RobLoach** [comment]
There's been a whole bunch of performance updates, and you can also disable the horizontal scroll animation now too. Closing this one.
