### ISSUE TITLE
Add to favorite

### ISSUE THREAD

**Issue by jdca** [libretro/Lakka-LibreELEC#416]
Lakka-RPi2.arm-2.1-devel-20180305031024-r28154-gb552a9a26

Add to favorites only works if you are inside a loaded game.

This is also in 2.1 stable.

**Comment by gouchi** [comment]
Yes it is the [case for now](https://github.com/libretro/RetroArch/issues/5807).

**Comment by RobLoach** [comment]
Follow the issue gouchi posted. RA issue. Thanks.
