### ISSUE TITLE
Savestate in Dolphin on PC

### ISSUE THREAD

**Issue by jdca** [libretro/Lakka-LibreELEC#421]
Generic.x86_64/Lakka-Generic.x86_64-2.1.img.gz

Using an intel nuc i5

It freezez 9 times out of 10 when doin a savestate.

The state gets saved but everything freezez and i have to restart retroarch.

Lakka:~ # systemctl stop retroarch.service ; retroarch -v
[INFO] RetroArch 1.6.9 (Git c056726)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Nov 21 2017
[INFO] Version: 1.6.9
[INFO] Git: c056726
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 25 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 4: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 5: (1920x1080i) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 6: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 7: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 8: (1920x1080) 1920 x 1080, 25 Hz
[INFO] [DRM]: Mode 9: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 10: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 11: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 12: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 13: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 14: (1280x720) 1280 x 720, 50 Hz
[INFO] [DRM]: Mode 15: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 16: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 17: (720x576) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 18: (720x576i) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 19: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 20: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 21: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 22: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 23: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 24: (640x480) 640 x 480, 60 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x7f1c34135f10.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Mobile .
[INFO] [GL]: Version: 3.0 Mesa 17.1.3.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [GL]: Async PBO readback enabled.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event3).
[INFO] [udev]: Keyboard #1 (/dev/input/mouse0).
[ERROR] [udev] Failed to open device: /dev/input/event3 (Success).
[INFO] [udev]: Mouse #0 (/dev/input/mouse0).
[INFO] [udev]: Plugged pad: Wireless Controller (2578:1) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event13) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event13) supports 16 force feedback effects.
[INFO] [Autoconf]: 0 profiles found.
[INFO] [Autoconf]: no profiles found for Wireless Controller (2578/1).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[WARN] Input device ID 517 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).

[INFO] Using content: /storage/roms/FreeNAS/Roms/Roms/Nintendo/Gamecube/Skies of Arcadia Legends (USA).iso.
[INFO] arg #0: retroarch
[INFO] arg #1: /storage/roms/FreeNAS/Roms/Roms/Nintendo/Gamecube/Skies of Arcadia Legends (USA).iso
[INFO] arg #2: -s
[INFO] arg #3: /storage/savefiles
[INFO] arg #4: -S
[INFO] arg #5: /storage/savestates
[INFO] arg #6: -c
[INFO] arg #7: /storage/.config/retroarch/retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: /tmp/cores/dolphin_libretro.so
[INFO] Threaded video stats: Frames pushed: 381, Frames dropped: 0.
[INFO] Set config file to : /storage/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.6.9 (Git c056726)
[INFO] Redirecting save file to "/storage/savefiles/Skies of Arcadia Legends (USA).srm".
[INFO] Redirecting savestate to "/storage/savestates/Skies of Arcadia Legends (USA).state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Nov 21 2017
[INFO] Version: 1.6.9
[INFO] Git: c056726
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/tmp/cores/dolphin_libretro.so"[INFO] [overrides] no core-specific overrides found at /storage/.config/retroarch/config/Dolphin/Dolphin.cfg.
[INFO] [overrides] no game-specific overrides found at /storage/.config/retroarch/config/Dolphin/Skies of Arcadia Legends (USA).cfg.
[INFO] Shaders: preset directory: /tmp/shaders/presets
[INFO] Shaders: no game-specific preset found at /tmp/shaders/presets/Dolphin/Skies of Arcadia Legends (USA).cgp.
[INFO] Shaders: no game-specific preset found at /tmp/shaders/presets/Dolphin/Skies of Arcadia Legends (USA).glslp.
[INFO] Shaders: no core-specific preset found at /tmp/shaders/presets/Dolphin/Dolphin.cgp.
[INFO] Shaders: no core-specific preset found at /tmp/shaders/presets/Dolphin/Dolphin.glslp.
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ SET_VARIABLES.
[INFO] Remaps: remap directory: /storage/remappings
[INFO] Remaps: no game-specific remap found at /storage/remappings/Dolphin/Skies of Arcadia Legends (USA).rmp.
[INFO] Remaps: no core-specific remap found at /storage/remappings/Dolphin/Dolphin.rmp.
[INFO] Redirecting save file to "/storage/savefiles/Dolphin/Skies of Arcadia Legends (USA).srm".
[INFO] Redirecting savestate to "/storage/savestates/Dolphin/Skies of Arcadia Legends (USA).state".
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ GET_RUMBLE_INTERFACE.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] Environ SYSTEM_DIRECTORY: "/storage/system".
[INFO] Environ CORE_ASSETS_DIRECTORY: "/storage/roms/downloads".
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    WiiMote (ID: 257)
[INFO]    WiiMote (sideways) (ID: 513)
[INFO]    WiiMote + Nunchuk (ID: 769)
[INFO]    WiiMote + Classic Controller (ID: 1025)
[INFO]    WiiMote + Classic Controller Pro (ID: 1281)
[INFO] Controller port: 2
[INFO]    WiiMote (ID: 257)
[INFO]    WiiMote (sideways) (ID: 513)
[INFO]    WiiMote + Nunchuk (ID: 769)
[INFO]    WiiMote + Classic Controller (ID: 1025)
[INFO]    WiiMote + Classic Controller Pro (ID: 1281)
[INFO] Controller port: 3
[INFO]    WiiMote (ID: 257)
[INFO]    WiiMote (sideways) (ID: 513)
[INFO]    WiiMote + Nunchuk (ID: 769)
[INFO]    WiiMote + Classic Controller (ID: 1025)
[INFO]    WiiMote + Classic Controller Pro (ID: 1281)
[INFO] Controller port: 4
[INFO]    WiiMote (ID: 257)
[INFO]    WiiMote (sideways) (ID: 513)
[INFO]    WiiMote + Nunchuk (ID: 769)
[INFO]    WiiMote + Classic Controller (ID: 1025)
[INFO]    WiiMote + Classic Controller Pro (ID: 1281)
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 1, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 1, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 1, Button "Select" => "Select"
[INFO]  RetroPad, User 1, Button "Start" => "Start"
[INFO]  RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 1, Button "A (right)" => "A"
[INFO]  RetroPad, User 1, Button "X (up)" => "X"
[INFO]  RetroPad, User 1, Button "L" => "L"
[INFO]  RetroPad, User 1, Button "R" => "R"
[INFO]  RetroPad, User 1, Button "R2" => "Z"
[INFO]  RetroPad, User 2, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 2, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 2, Button "Select" => "Select"
[INFO]  RetroPad, User 2, Button "Start" => "Start"
[INFO]  RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 2, Button "A (right)" => "A"
[INFO]  RetroPad, User 2, Button "X (up)" => "X"
[INFO]  RetroPad, User 2, Button "L" => "L"
[INFO]  RetroPad, User 2, Button "R" => "R"
[INFO]  RetroPad, User 2, Button "R2" => "Z"
[INFO]  RetroPad, User 3, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 3, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 3, Button "Select" => "Select"
[INFO]  RetroPad, User 3, Button "Start" => "Start"
[INFO]  RetroPad, User 3, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 3, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 3, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 3, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 3, Button "A (right)" => "A"
[INFO]  RetroPad, User 3, Button "X (up)" => "X"
[INFO]  RetroPad, User 3, Button "L" => "L"
[INFO]  RetroPad, User 3, Button "R" => "R"
[INFO]  RetroPad, User 3, Button "R2" => "Z"
[INFO]  RetroPad, User 4, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 4, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 4, Button "Select" => "Select"
[INFO]  RetroPad, User 4, Button "Start" => "Start"
[INFO]  RetroPad, User 4, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 4, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 4, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 4, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 4, Button "A (right)" => "A"
[INFO]  RetroPad, User 4, Button "X (up)" => "X"
[INFO]  RetroPad, User 4, Button "L" => "L"
[INFO]  RetroPad, User 4, Button "R" => "R"
[INFO]  RetroPad, User 4, Button "R2" => "Z"
[INFO] Environ GET_VARIABLE dolphin_fastmem:
[INFO]  ON
[INFO] Environ GET_VARIABLE dolphin_pal60:
[INFO]  OFF
[INFO] Environ GET_VARIABLE dolphin_progressive_scan:
[INFO]  OFF
[INFO] Environ GET_VARIABLE dolphin_dsp_mode:
[INFO]  HLE
[INFO] Environ GET_VARIABLE dolphin_internal_resolution:
[INFO]  1x (640x528)
[INFO] Environ GET_VARIABLE dolphin_skip_efb_access_from_cpu:
[INFO]  OFF
[INFO] Environ GET_VARIABLE dolphin_efb_ignore_format_changes:
[INFO]  ON
[INFO] Environ GET_VARIABLE dolphin_store_efb_copies_to_texture_only:
[INFO]  ON
[INFO] Environ GET_VARIABLE dolphin_internal_resolution:
[INFO]  1x (640x528)
[INFO] Environ GET_VARIABLE dolphin_renderer:
[INFO]  Hardware
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.1).
EFBScale is: 2
[INFO] Environ SET_GEOMETRY.
[INFO] SET_GEOMETRY: 640x528, aspect: 1.333.
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [INFO] [CHEEVOS]: system RAM: (nil) 0
[Audio]: Set audio input rate to: 32027.74 Hz.
[INFO] [CHEEVOS]: save RAM:   (nil) 0
[INFO] [CHEEVOS]: video RAM:  (nil) 0
[INFO] [CHEEVOS]: RTC:        (nil) 0
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 25 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 4: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 5: (1920x1080i) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 6: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 7: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 8: (1920x1080) 1920 x 1080, 25 Hz
[INFO] [DRM]: Mode 9: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 10: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 11: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 12: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 13: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 14: (1280x720) 1280 x 720, 50 Hz
[INFO] [DRM]: Mode 15: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 16: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 17: (720x576) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 18: (720x576i) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 19: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 20: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 21: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 22: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 23: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 24: (640x480) 640 x 480, 60 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Created shared context: 0xd7efe0.
[INFO] [EGL]: Current context: 0xeabbf0.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Mobile .
[INFO] [GL]: Version: 4.5 (Core Profile) Mesa 17.1.3.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 140.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (1024 x 1024).
[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [GL]: Async PBO readback enabled.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event3).
[INFO] [udev]: Keyboard #1 (/dev/input/mouse0).
[ERROR] [udev] Failed to open device: /dev/input/event3 (Success).
[INFO] [udev]: Mouse #0 (/dev/input/mouse0).
[INFO] [udev]: Plugged pad: Wireless Controller (2578:1) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event13) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event13) supports 16 force feedback effects.
[INFO] [Autoconf]: 0 profiles found.
[INFO] [Autoconf]: no profiles found for Wireless Controller (2578/1).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[WARN] Input device ID 517 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 1, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 1, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 1, Button "Select" => "Select"
[INFO]  RetroPad, User 1, Button "Start" => "Start"
[INFO]  RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 1, Button "A (right)" => "A"
[INFO]  RetroPad, User 1, Button "X (up)" => "X"
[INFO]  RetroPad, User 1, Button "L" => "L"
[INFO]  RetroPad, User 1, Button "R" => "R"
[INFO]  RetroPad, User 1, Button "R2" => "Z"
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 2, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 2, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 2, Button "Select" => "Select"
[INFO]  RetroPad, User 2, Button "Start" => "Start"
[INFO]  RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 2, Button "A (right)" => "A"
[INFO]  RetroPad, User 2, Button "X (up)" => "X"
[INFO]  RetroPad, User 2, Button "L" => "L"
[INFO]  RetroPad, User 2, Button "R" => "R"
[INFO]  RetroPad, User 2, Button "R2" => "Z"
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 3, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 3, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 3, Button "Select" => "Select"
[INFO]  RetroPad, User 3, Button "Start" => "Start"
[INFO]  RetroPad, User 3, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 3, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 3, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 3, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 3, Button "A (right)" => "A"
[INFO]  RetroPad, User 3, Button "X (up)" => "X"
[INFO]  RetroPad, User 3, Button "L" => "L"
[INFO]  RetroPad, User 3, Button "R" => "R"
[INFO]  RetroPad, User 3, Button "R2" => "Z"
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO]  RetroPad, User 4, Button "B (bottom)" => "B"
[INFO]  RetroPad, User 4, Button "Y (left)" => "Y"
[INFO]  RetroPad, User 4, Button "Select" => "Select"
[INFO]  RetroPad, User 4, Button "Start" => "Start"
[INFO]  RetroPad, User 4, Button "D-Pad Up" => "Up"
[INFO]  RetroPad, User 4, Button "D-Pad Down" => "Down"
[INFO]  RetroPad, User 4, Button "D-Pad Left" => "Left"
[INFO]  RetroPad, User 4, Button "D-Pad Right" => "Right"
[INFO]  RetroPad, User 4, Button "A (right)" => "A"
[INFO]  RetroPad, User 4, Button "X (up)" => "X"
[INFO]  RetroPad, User 4, Button "L" => "L"
[INFO]  RetroPad, User 4, Button "R" => "R"
[INFO]  RetroPad, User 4, Button "R2" => "Z"
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] Trying to write to playlist file: /storage/.config/retroarch/content_history.lpl
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
Error: Trying to access Windows-1252 fonts but they are not loaded. Games may not show fonts correctly, or crash.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] Audio volume: -22.5 dB
[INFO] Audio volume: -22.0 dB
[INFO] Audio volume: -21.5 dB
[INFO] Audio volume: -21.0 dB
[INFO] Audio volume: -20.5 dB
[INFO] Audio volume: -20.0 dB
[INFO] Audio volume: -19.5 dB
[INFO]
[INFO] Loading state: "/storage/savestates/Dolphin/Skies of Arcadia Legends (USA).state".
[INFO] State size: 91567750 bytes.
[INFO] Saving state: "RAM".
[INFO] State size: 91567750 bytes.
[INFO] Saving state: "/storage/savestates/Dolphin/Skies of Arcadia Legends (USA).state".
[INFO] State size: 91567750 bytes.
[INFO] File already exists. Saving to backup buffer ...
[INFO]
[INFO] Loading state: "/storage/savestates/Dolphin/Skies of Arcadia Legends (USA).state".
[INFO] State size: 91567750 bytes.

**Comment by gouchi** [comment]
Please open an issue on [Dolphin libretro core](https://github.com/libretro/dolphin).

Please in bear mind the dolphin is core is still a work in progress.
