### ISSUE TITLE
Lakka doesn't boot on Eny m8S usb or SD-card

### ISSUE THREAD

**Issue by keiem** [libretro/Lakka-LibreELEC#426]
Lakka 2.1 doesn't boot on Eny M8S.  I did try with burning it on a USB stick and on a SD-card.  It stucks on the flower and doesn't give a error message, only the flower.  Previous version did boot OK with a USB stick, not with a sd-card (filesystem corruption error)

**Comment by gouchi** [comment]
Did you try to flas your usb or sdcard with [Etcher](https://etcher.io/) ?

Also you may test with [nightly builds](http://nightly.builds.lakka.tv/).

Thank you.

**Comment by Ntemis** [comment]
Some chinese boxes have issue booting from sdcard ask for support from your seller not us as is probably a bootloader issue
