### ISSUE TITLE
MK808B-Plus graphic driver configuration issue on 2.1

### ISSUE THREAD

**Issue by trulio** [libretro/Lakka-LibreELEC#427]
Hi,

when i boot my MK808B-Plus on image Lakka-S805.MK808B-Plus.arm-2.1.img.gz,

strorage resize behave normally but once retroarch launch screen buffer is corrupted

I tried on a samsung TV but also on a full HD BENQ computer monitor.

I have the same behavior.

I also tried the MXQ 2.1 image with the same results
(as kodi libreElec says MXQ and MK808 use the same image)

here are the files showing the issue:

Regards,

Trulio

[dmesg.txt](https://github.com/libretro/Lakka-LibreELEC/files/1842909/dmesg.txt)
![s805 boot issue](https://user-images.githubusercontent.com/8265829/37846179-21f54752-2ecd-11e8-8b5d-31aa01b6bb46.jpg)
[log.txt](https://github.com/libretro/Lakka-LibreELEC/files/1842910/log.txt)

**Comment by gouchi** [comment]
Hi,

Do you reproduce the issue with [nightly builds](http://nightly.builds.lakka.tv/) ?

Thank you.

**Comment by trulio** [comment]
Hello,

i just tried it and it works.

Do you know if bluetooth works? because it says service is enabled but vendor preset :  disabled

Thanks for your hard work.

Trulio

**Comment by gouchi** [comment]
ping @Ntemis ;-)

**Comment by Ntemis** [comment]
It has no bluetooth support ( fake advertising)

**Comment by gouchi** [comment]
Thank you for the feedback.

So I will close the issue as it is running well with nightly.
