### ISSUE TITLE
enabling CONFIG_DRM_SIS1 and CONFIG_AGP_SIS1 for i386

### ISSUE THREAD

**Issue by drtrppr** [libretro/Lakka-LibreELEC#432]
Details in forum-post:
https://forums.libretro.com/t/no-suitable-drm-device-sis-771-671/14998/3

**Comment by gouchi** [comment]
Hi,

Thank you for opening the issue. Indeed we can enable kernel driver but I checked mesa (opengl driver) and unfortunately [SiS has been deprecated](https://www.mesa3d.org/systems.html).

So we are sorry but for now you will have to use Intel, AMD or Nvidia graphic cards.
