### ISSUE TITLE
ASUS Tinker Board 2.1 BUG

### ISSUE THREAD

**Issue by ksgt0025** [libretro/Lakka-LibreELEC#437]
Lakka-Rockchip.TinkerBoard.arm-2.1

1.WiFi does not work.

2.Onboard sound card Realtek ALC4040 does not work.(Audio drive without this)

3.occasionally black screen,Recovery after 2～3 seconds. (HDMI TO DVI 1920*1080 60hz)

**Comment by autofire372** [comment]
Switch to the latest nightly; you can get it [here](http://nightly.builds.lakka.tv/2018-04-01/Rockchip.TinkerBoard.arm/). They fixed the wifi issue a while ago.
