### ISSUE TITLE
Bug in PPSSPP in RetroArch (Lakka Nightly) (Generic X86_64) When playing GTA Vice City Stories 

### ISSUE THREAD

**Issue by RetroFan90** [libretro/Lakka-LibreELEC#439]
I Am running into an issue with the PPSSPP core in the latest Lakka Nightly Build.
The issue is noticable when i compare it to the nightly build of PPSSPP (Version 1.4.2-git <<Lakka Version)(Currently 1.5.4 against the Windows X64 version.)
I'm left with the conclusion that the nightly version isn't keeping up with the newer cores.
![gtavcs_ppsspp_1 5 4](https://user-images.githubusercontent.com/25295483/38195726-6ed92234-3655-11e8-89dc-a436410700ea.png)
![gtavcs_ppsspp_1 4 2](https://user-images.githubusercontent.com/25295483/38195727-6ee6f828-3655-11e8-9dd4-c4d6e19568b6.png)
The Picture with the garbled lines is from Lakka, whereas the Clean Image is from the Windows Version 1.5.4
Please Look Into This. :)

**Comment by ToKe79** [comment]
Hi,

I [updated the core](https://github.com/ToKe79/Lakka-LibreELEC/commit/99a12be9215517bdec0bdddfff7f8f3947d517d5) to the latest and started build of all targets. You can download the images from here:
http://nightly.builds.lakka.tv/special_builds/ppsspp-update/

Currently there is only image for Generic.x86_64, but the remaining images  should appear as soon as they built.

For the future, please fill out as much as possible information in the [issue template](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.1-dev/ISSUE_TEMPLATE.md) that is shown when opening new issue.

Please report your test results back in this thread. Thank you!

**Comment by Ntemis** [comment]
This is not lakka related closing down,
@RetroFan90 please report the issue here https://github.com/libretro/ppsspp
as this is a bug clearly about standalone vs libretro core
