### ISSUE TITLE
S912 ethernet doesn't work

### ISSUE THREAD

**Issue by ksgt0025** [libretro/Lakka-LibreELEC#450]
network card:rtl8211f

box:beelink gt1,x92

gxm_201_3g

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3447cf2e9a11fd672de8b3cc613eabd97fe82053

https://www.cnx-software.com/2016/09/09/beelink-gt1-4k-tv-box-review-part-1-unboxing-and-teardown/

**Comment by Ntemis** [comment]
incorrect board file used you must find the correct one to initialize the correct gpios so eth0 can start
check @kszaq  device tree maybe you find a compatible one
