### ISSUE TITLE
Tinker Board: DS4 rumble no longer works

### ISSUE THREAD

**Issue by autofire372** [libretro/Lakka-LibreELEC#462]
Newer Dualshock 4 controllers do not rumble in the latest build of Lakka, regardless of whether they are connected over bluetooth or USB.

I was using Pokémon Pinball (GBC) in the mGBA core to test. The DS4 happily rumbles when appropriate with this setup on both Windows 10 and Linux Mint 18.3 (both x64).

Retropad w/ Analog was enabled prior to testing.

I should note that rumble still works for DS3s.

Some investigation revealed that an older DS4 (model CUH-ZCT1U) also rumbles in Lakka. The non-rumbling controller (which still rumbles in Linux Mint, mind) is model CUH-ZCT2U,

**Comment by Ntemis** [comment]
Yeah looks like is unsupported, check newer versions with nightlies especially when there is a kernel update or wait until the migration to mainline kernel
