### ISSUE TITLE
PC Audio Device 'Soundcard' with no sound output

### ISSUE THREAD

**Issue by harmhoek** [libretro/Lakka-LibreELEC#467]
When I select the sound card CA0106, no audio is given. Latest Lakka build, PC 32bit, gigabyte motherboard. Logs below.

Found 3 older sound issues but with no success in relation to this one:
hdmi_ignore_edid_audio=1
echo "options snd_hda_intel index=-2" > /storage/.config/modprobe.d/snd_intel_hda.conf
disabling "Azalia" codec in BIOS (onboard sound) doesn't work

Example Audio device "surround21:CARD=CA0106,DEV=0" no sound output.

Note, when I use audio device = "sysdefault:CARD=Intel" it provides me audio via the motherboard. The card "CA0106" however seems properly loaded?

Log lsmod:
> Module                  Size  Used by
> hidp                   24576  2
> 8021q                  24576  0
> bnep                   20480  2
> snd_hda_codec_realtek    57344  1
> snd_hda_codec_generic    57344  1 snd_hda_codec_realtek
> btusb                  32768  0
> btrtl                  16384  1 btusb
> btbcm                  16384  1 btusb
> btintel                16384  1 btusb
> bluetooth             303104  35 btrtl,hidp,btintel,bnep,btbcm,btusb
> **snd_ca0106             40960  3
> snd_ac97_codec         94208  1 snd_ca0106
> ac97_bus               16384  1 snd_ac97_codec
> snd_rawmidi            24576  1 snd_ca0106**
> snd_hda_intel          28672  0
> snd_hda_codec          81920  3 snd_hda_intel,snd_hda_codec_generic,snd_hda_codec_realtek
> snd_hda_core           49152  4 snd_hda_intel,snd_hda_codec,snd_hda_codec_generic,snd_hda_codec_realtek
> snd_hwdep              16384  1 snd_hda_codec
> snd_pcm                65536  8 snd_hda_intel,snd_hda_codec,snd_hda_core,snd_ca0106,snd_ac97_codec
> parport_pc             32768  0
> parport                36864  1 parport_pc
> Lakka:~ # cat /proc/asound/cards
>  0 [Intel          ]: HDA-Intel - HDA Intel
>                       HDA Intel at 0xfa100000 irq 30
>  1 [CA0106         ]: CA0106 - CA0106
>                       Audigy SE [SB0570] at 0xd000 irq 19
> Lakka:~ # lspci | grep -i audio
> 00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 02)
> 05:01.0 Multimedia audio controller: Creative Labs CA0106/CA0111 [SB Live!/Audigy/X-Fi Series]

Log aplay -L:
> null
>     Discard all samples (playback) or generate zero samples (capture)
> default:CARD=Intel
>     HDA Intel, ALC889A Analog
>     Default Audio Device
> sysdefault:CARD=Intel
>     HDA Intel, ALC889A Analog
>     Default Audio Device
> front:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     Front speakers
> surround21:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     2.1 Surround output to Front and Subwoofer speakers
> surround40:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     4.0 Surround output to Front and Rear speakers
> surround41:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     4.1 Surround output to Front, Rear and Subwoofer speakers
> surround50:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     5.0 Surround output to Front, Center and Rear speakers
> surround51:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     5.1 Surround output to Front, Center, Rear and Subwoofer speakers
> surround71:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Analog
>     7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
> iec958:CARD=Intel,DEV=0
>     HDA Intel, ALC889A Digital
>     IEC958 (S/PDIF) Digital Audio Output
> default:CARD=CA0106
>     CA0106, CA0106
>     Default Audio Device
> sysdefault:CARD=CA0106
>     CA0106, CA0106
>     Default Audio Device
> front:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     Front speakers
> rear:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     Rear speakers
> center_lfe:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     Center and Subwoofer speakers
> side:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     Side speakers
> surround21:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     2.1 Surround output to Front and Subwoofer speakers
> surround40:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     4.0 Surround output to Front and Rear speakers
> surround41:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     4.1 Surround output to Front, Rear and Subwoofer speakers
> surround50:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     5.0 Surround output to Front, Center and Rear speakers
> surround51:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     5.1 Surround output to Front, Center, Rear and Subwoofer speakers
> surround71:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
> iec958:CARD=CA0106,DEV=0
>     CA0106, CA0106
>     IEC958 (S/PDIF) Digital Audio Output

lspci -v | grep -B1 -A12 -i audio
> 00:1b.0 Audio device: Intel Corporation 82801I (ICH9 Family) HD Audio Controller (rev 02)
>         Subsystem: Gigabyte Technology Co., Ltd 82801I (ICH9 Family) HD Audio Controller
>         Flags: bus master, fast devsel, latency 0, IRQ 30
>         Memory at fa100000 (64-bit, non-prefetchable) [size=16K]
>         Capabilities: [50] Power Management version 2
>         Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
>         Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
>         Capabilities: [100] Virtual Channel
>         Capabilities: [130] Root Complex Link
>         Kernel driver in use: snd_hda_intel
>         Kernel modules: snd_hda_intel
> 
> 00:1c.0 PCI bridge: Intel Corporation 82801I (ICH9 Family) PCI Express Port 1 (rev 02) (prog-if 00 [Normal decode])
>         Flags: bus master, fast devsel, latency 0, IRQ 25
> 
> 
> 05:01.0 Multimedia audio controller: Creative Labs CA0106/CA0111 [SB Live!/Audigy/X-Fi Series]
>         Subsystem: Creative Labs CA0106/CA0111 [SB Live!/Audigy/X-Fi Series] (SB0570 [SB Audigy SE])
>         Flags: bus master, medium devsel, latency 32, IRQ 19
>         I/O ports at d000 [size=32]
>         Capabilities: [dc] Power Management version 2
>         Kernel driver in use: snd_ca0106
>         Kernel modules: snd_ca0106

# for i in /proc/asound/card[0-9]*; do echo "--- $i ---";amixer -c $(cat
 $i/id); done;
> --- /proc/asound/card1 ---
> Simple mixer control 'Master',0
>   Capabilities: pvolume pvolume-joined pswitch pswitch-joined
>   Playback channels: Mono
>   Limits: Playback 0 - 64
>   Mono: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'Headphone',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 64
>   Mono:
>   Front Left: Playback 64 [100%] [0.00dB] [on]
>   Front Right: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'Front',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 64
>   Mono:
>   Front Left: Playback 64 [100%] [0.00dB] [on]
>   Front Right: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'Front Mic',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]
> Simple mixer control 'Front Mic Boost',0
>   Capabilities: volume
>   Playback channels: Front Left - Front Right
>   Capture channels: Front Left - Front Right
>   Limits: 0 - 3
>   Front Left: 0 [0%] [0.00dB]
>   Front Right: 0 [0%] [0.00dB]
> Simple mixer control 'Surround',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 64
>   Mono:
>   Front Left: Playback 58 [91%] [-6.00dB] [on]
>   Front Right: Playback 58 [91%] [-6.00dB] [on]
> Simple mixer control 'Center',0
>   Capabilities: pvolume pvolume-joined pswitch pswitch-joined
>   Playback channels: Mono
>   Limits: Playback 0 - 64
>   Mono: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'LFE',0
>   Capabilities: pvolume pvolume-joined pswitch pswitch-joined
>   Playback channels: Mono
>   Limits: Playback 0 - 64
>   Mono: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'Side',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 64
>   Mono:
>   Front Left: Playback 64 [100%] [0.00dB] [on]
>   Front Right: Playback 64 [100%] [0.00dB] [on]
> Simple mixer control 'Line',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]
> Simple mixer control 'Line Boost',0
>   Capabilities: volume
>   Playback channels: Front Left - Front Right
>   Capture channels: Front Left - Front Right
>   Limits: 0 - 3
>   Front Left: 0 [0%] [0.00dB]
>   Front Right: 0 [0%] [0.00dB]
> Simple mixer control 'CD',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]
> Simple mixer control 'IEC958',0
>   Capabilities: pswitch pswitch-joined cswitch cswitch-joined
>   Playback channels: Mono
>   Capture channels: Mono
>   Mono: Playback [on] Capture [off]
> Simple mixer control 'IEC958 Default PCM',0
>   Capabilities: pswitch pswitch-joined
>   Playback channels: Mono
>   Mono: Playback [on]
> Simple mixer control 'Beep',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]
> Simple mixer control 'Capture',0
>   Capabilities: cvolume cswitch
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 46
>   Front Left: Capture 0 [0%] [-16.00dB] [off]
>   Front Right: Capture 0 [0%] [-16.00dB] [off]
> Simple mixer control 'Capture',1
>   Capabilities: cvolume cswitch
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 46
>   Front Left: Capture 0 [0%] [-16.00dB] [off]
>   Front Right: Capture 0 [0%] [-16.00dB] [off]
> Simple mixer control 'Capture',2
>   Capabilities: cvolume cswitch
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 46
>   Front Left: Capture 0 [0%] [-16.00dB] [off]
>   Front Right: Capture 0 [0%] [-16.00dB] [off]
> Simple mixer control 'Input Source',0
>   Capabilities: cenum
>   Items: 'Rear Mic' 'Front Mic' 'Line' 'CD'
>   Item0: 'Rear Mic'
> Simple mixer control 'Input Source',1
>   Capabilities: cenum
>   Items: 'Rear Mic' 'Front Mic' 'Line' 'CD'
>   Item0: 'Rear Mic'
> Simple mixer control 'Input Source',2
>   Capabilities: cenum
>   Items: 'Rear Mic' 'Front Mic' 'Line' 'CD'
>   Item0: 'Rear Mic'
> Simple mixer control 'Loopback Mixing',0
>   Capabilities: enum
>   Items: 'Disabled' 'Enabled'
>   Item0: 'Disabled'
> Simple mixer control 'Rear Mic',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]
> Simple mixer control 'Rear Mic Boost',0
>   Capabilities: volume
>   Playback channels: Front Left - Front Right
>   Capture channels: Front Left - Front Right
>   Limits: 0 - 3
>   Front Left: 0 [0%] [0.00dB]
>   Front Right: 0 [0%] [0.00dB]
> --- /proc/asound/card2 ---
> Simple mixer control 'Master',0
>   Capabilities: pvolume pvolume-joined pswitch pswitch-joined
>   Playback channels: Mono
>   Limits: Playback 0 - 255
>   Mono: Playback 255 [100%] [0.00dB] [on]
> Simple mixer control 'Line in',0
>   Capabilities: cvolume
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 255
>   Front Left: Capture 207 [81%] [0.00dB]
>   Front Right: Capture 207 [81%] [0.00dB]
> Simple mixer control 'Mic',0
>   Capabilities: cvolume
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 255
>   Front Left: Capture 0 [0%] [-99999.99dB]
>   Front Right: Capture 0 [0%] [-99999.99dB]
> Simple mixer control 'Phone',0
>   Capabilities: cvolume
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 255
>   Front Left: Capture 207 [81%] [0.00dB]
>   Front Right: Capture 207 [81%] [0.00dB]
> Simple mixer control 'IEC958',0
>   Capabilities: pswitch pswitch-joined
>   Playback channels: Mono
>   Mono: Playback [on]
> Simple mixer control 'IEC958 Center/LFE',0
>   Capabilities: pvolume
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 207 [81%] [0.00dB]
>   Front Right: Playback 207 [81%] [0.00dB]
> Simple mixer control 'IEC958 Front',0
>   Capabilities: pvolume
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 207 [81%] [0.00dB]
>   Front Right: Playback 207 [81%] [0.00dB]
> Simple mixer control 'IEC958 Rear',0
>   Capabilities: pvolume
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 207 [81%] [0.00dB]
>   Front Right: Playback 207 [81%] [0.00dB]
> Simple mixer control 'IEC958 Unknown',0
>   Capabilities: pvolume
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 207 [81%] [0.00dB]
>   Front Right: Playback 207 [81%] [0.00dB]
> Simple mixer control 'Aux',0
>   Capabilities: cvolume
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 255
>   Front Left: Capture 207 [81%] [0.00dB]
>   Front Right: Capture 207 [81%] [0.00dB]
> Simple mixer control 'Analog Center/LFE',0
>   Capabilities: pvolume pswitch pswitch-joined
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 255 [100%] [12.00dB] [on]
>   Front Right: Playback 255 [100%] [12.00dB] [on]
> Simple mixer control 'Analog Front',0
>   Capabilities: pvolume pswitch pswitch-joined
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 255 [100%] [12.00dB] [on]
>   Front Right: Playback 255 [100%] [12.00dB] [on]
> Simple mixer control 'Analog Rear',0
>   Capabilities: pvolume pswitch pswitch-joined
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 255 [100%] [12.00dB] [on]
>   Front Right: Playback 255 [100%] [12.00dB] [on]
> Simple mixer control 'Analog Side',0
>   Capabilities: pvolume pswitch pswitch-joined
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 207 [81%] [0.00dB] [on]
>   Front Right: Playback 207 [81%] [0.00dB] [on]
> Simple mixer control 'Analog Source',0
>   Capabilities: cenum
>   Items: 'Phone' 'Mic' 'Line in' 'Aux'
>   Item0: 'Line in'
> Simple mixer control 'CAPTURE feedback',0
>   Capabilities: pvolume
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 255
>   Mono:
>   Front Left: Playback 0 [0%] [-99999.99dB]
>   Front Right: Playback 0 [0%] [-99999.99dB]
> Simple mixer control 'Digital Source',0
>   Capabilities: cenum
>   Items: 'IEC958 out' 'i2s mixer out' 'IEC958 in' 'i2s in' 'AC97 in' 'SRC out'
>   Item0: 'i2s in'
> Simple mixer control 'Shared Mic/Line in',0
>   Capabilities: cenum
>   Items: 'Line in' 'Mic in'
>   Item0: 'Line in'

http://www.alsa-project.org/main/index.php/Matrix:Module-ca0106

Ps. May just be incompatiliby between Gigabyte GA-P35C-DS3R and sb0570?

**Comment by gouchi** [comment]
If you want to use your SB card you should have something 

```
grep audio_device /storage/.config/retroarch/retroarch.cfg
audio_device = "sysdefault:CARD=CA0106"
```
Don't forget to stop RetroArch when you [edit configuration file](http://www.lakka.tv/doc/Configuring-Lakka/).

Please provide [Lakka system logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/).

Thank you.

**Comment by harmhoek** [comment]
audio_device = "surround21:CARD=CA0106,DEV=0"

**Comment by gouchi** [comment]
Thank you and [Lakka system logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/) ?

**Comment by harmhoek** [comment]
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting t o pick a suitable driver.

lol. Is this a problem?

**Comment by gouchi** [comment]
There are no audio related issue can you try other [audio device](http://www.lakka.tv/doc/Audio-settings/#switching-audio-device-from-the-gui) ?

**Comment by harmhoek** [comment]
As stated when I use audio device = "sysdefault:CARD=Intel" it provides me audio via the motherboard.

**Comment by gouchi** [comment]
Yes I meant other audio device related to SB not motherboard.

May you try to connect on [our irc channel](http://webchat.freenode.net/?channels=%23lakkatv).

**Comment by harmhoek** [comment]
I selected Front, Side, Rear etcetera. Everything on this card doesn't work.
Also tried another PCI slot.

I get the feeling it's a hardware problem with this motherboard and this soundcard.

**Comment by harmhoek** [comment]
Just noted -> DIGITAL OUTPUT works somehow with current setup 
(i get distorted sounds when I put analog in there)

-- I need to switch the card to digital output OFF / MUTE --   how?

**Comment by harmhoek** [comment]
How do I default the audio and then put the commands as above?

**Comment by harmhoek** [comment]
Halleluya, it is fixed!! Got analog sound on the Soundblaster Audigy Card!

One of the following commands likely did the job:
amixer -c1 set Master 100% unmute
amixer -c1 cset name='IEC958 Playback Switch' off
amixer -c1 set IEC958 off
