### ISSUE TITLE
Banana Pi images broken

### ISSUE THREAD

**Issue by CaptainStouf** [libretro/Lakka-LibreELEC#475]
Hi,
Banana Pi images after 2.1 RC5 are broken (tested RC6 and 2.1). 2.1 RC5 is the last working one.

- Which version of Lakka are you using?
2.1 RC6, 2.1
- What system hardware are you using?
Banana Pi A20
- What did you do?
Install, boot
- What did you expect to happen?
Starting Lakka
- What happened instead?
Boot stuck on "Reached target retroarch" (not sure of the last line, screen borders are truncated) with lakka logo in the middle.

Lakka 2.1 RC5 is working fine. Problem occurs since the update to the new kernel and uboot.

**Comment by Ntemis** [comment]
Did you ever supported bananas?
@CaptainStouf  what image did you use for your banana?

**Comment by Ioalevia** [comment]
banana pi a20. tried all latest versions of images. tried nightly versions. two varians: stucks with kernel fail or has ethernet fail. one year ago i used lakka on my device and it worked perfect. if anybody has lakka image for banana pi from 2016-2017????

**Comment by Ntemis** [comment]
As i already said 1st we dont support any bananas 2nd A20 is EOL.
Please stop posting everywhere, is not going to happen any time soon
