### ISSUE TITLE
GLIBC 2.27 - "make" from toolchain needs patch to compile

### ISSUE THREAD

**Issue by pandel** [libretro/Lakka-LibreELEC#480]
Hi!

I tried to compile the current revision.

OS: Ubuntu 18.04 LTS (Bionic Beaver)

I needed this patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891365

Seems as if glibc 2.27 changed things so make didn't compile at first.

Regards,
Holger

**Comment by ToKe79** [comment]
fixed with https://github.com/libretro/Lakka-LibreELEC/commit/1f269306b14a4acbd84138a86d4f7120275be611
