### ISSUE TITLE
Hyperkin DUKE (Xbox one Controller ) not working 

### ISSUE THREAD

**Issue by Maximo1979** [libretro/Lakka-LibreELEC#483]
Hyperkin DUKE (Xbox one Controller ) not working 

The official xbox one controller work

in the Logs I can see that the system detect an usb device when this one is connected and disconnected 

[  278.826008] usb 3-1: USB disconnect, device number 2
[  280.951032] usb 3-1: new full-speed USB device number 3 using xhci_hcd
[  372.627326] usb 3-1: USB disconnect, device number 3
[  471.075094] usb 3-2: new full-speed USB device number 4 using xhci_hcd
[log1.txt](https://github.com/libretro/Lakka-LibreELEC/files/2066202/log1.txt)
[lsusb.txt](https://github.com/libretro/Lakka-LibreELEC/files/2066203/lsusb.txt)
[dmesg.txt](https://github.com/libretro/Lakka-LibreELEC/files/2066204/dmesg.txt)

- Which version of Lakka are you using?
Lakka-Generic.x86_64-2.1-devel-20180528160406-r28190-gcc135d4
- What system hardware are you using?
Laptop Lenovo W510
- What did you do?
Plug the controller , I only have the initial vibration and after that nothing ( no animation on the Controller LCD screen )
- What did you expect to happen?
Have the animation and have a notification that a XBOX One Controller Is Detected ( This problem is not present with the Original Xbox One Controller )
- What happened instead?
Plug the controller , I only have the initial vibration and after that nothing ( no animation on the Controller LCD screen )

**Comment by gouchi** [comment]
Can you try to type 

`echo "2e24 0652" > /sys/bus/usb/drivers/xpad/new_id`

First, you will need to get access to [Lakka command line interface](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/).

[Source](https://www.youtube.com/watch?v=zYTMTaeB0P4)
