### ISSUE TITLE
Dolphin not working

### ISSUE THREAD

**Issue by pirix-gh** [libretro/Lakka-LibreELEC#485]
Lakka Version: Git #[cc135d4](https://github.com/libretro/Lakka-LibreELEC/commit/cc135d465fe61306e2843a5cd0189945503d45b7)
Hardware: Tinkerboard / Rockchip

I compiled this git (dev) version of Lakka for my ASUS Tinker Board.

I expected Dolphin to be able to run GameCube ISOs but it doesn't seem to work.
The game has been found and placed in the GameCube menu, it sits in the rom folder. 
Then if I try to run it, I can see other cores but not Dolphin. 

Can you please help me debug ? How do I get Dolphin to work ?

**Comment by RobLoach** [comment]
Mind sharing the logs? What game? What's the CRC of the game?

**Comment by ToKe79** [comment]
no response
