### ISSUE TITLE
Continued compile issues following 489 patch to fix 488 issue

### ISSUE THREAD

**Issue by alphanu1** [libretro/Lakka-LibreELEC#490]
There are still compile issues here, its now just after cloning the new git.

UNPACK higan-sfc-balanced
Cloning into '/mnt/8c026599-057d-4201-8616-ab6cbff6593e/lakka_X11/build.Lakka-Generic.x86_64-2.1-devel/higan-sfc-balanced-f43168a'...
remote: Counting objects: 2506, done.
remote: Compressing objects: 100% (1968/1968), done.
remote: Total 2506 (delta 496), reused 2506 (delta 496), pack-reused 0
Receiving objects: 100% (2506/2506), 2.52 MiB | 572.00 KiB/s, done.
Resolving deltas: 100% (496/496), done.
Checking connectivity... done.
error: pathspec 'f43168a' did not match any file(s) known to git.
Makefile:27: recipe for target 'image' failed
make: *** [image] Error 1

@RobLoach
@kivutar

**Comment by ToKe79** [comment]
should be fixed with fb434af274703f408fe24ae33f0d112aa0844e41
