### ISSUE TITLE
Wifi not workink on s905x box

### ISSUE THREAD

**Issue by Lordjontan** [libretro/Lakka-LibreELEC#502]
Wifi isn't working on Lakka 2.1.1 on a s905x. It doesn' find any network when scaning

**Comment by Ntemis** [comment]
We dont support 10/100mbit S905 boxes
Also it could use a fancy unsupported chip as well.

**Comment by Lordjontan** [comment]
But Wifi works perfectly on Lakka 2.1

**Comment by Ntemis** [comment]
what is the wifi chip?

**Comment by Lordjontan** [comment]
The chip is AP6212A

**Comment by Ntemis** [comment]
Can you compile from source?

**Comment by Marley2018** [comment]
I have the same problem on my X96 android box player with Amilogic s905x processor with 2gb ram and 16 rom, the wifi does not work at all, I would like it possible in a next update to concert this problem, thanks in advance ...

**Comment by ToKe79** [comment]
Did you use correct dtb.img?
See https://github.com/libretro/Lakka-LibreELEC/wiki/S905

**Comment by Lordjontan** [comment]
Yep

**Comment by ToKe79** [comment]
can you test this build?
http://nightly.builds.lakka.tv/PRs/pr_800_000093/S905.arm/
it is based on latest release + some wifi drivers
