### ISSUE TITLE
bugs, and a question.

### ISSUE THREAD

**Issue by Yolotroll101** [libretro/Lakka-LibreELEC#503]
- Which version of Lakka are you using?
- What system hardware are you using?
- What did you do?
- What did you expect to happen?
- What happened instead?
First, question: Do you help with the Nintendo Switch Port?
## Bugs:
1. when left joycon is neutral, mario moves foward in SM64.
2. Textures in Majora's Mask (N64) sometimes do not load until I get close. (In West ClockTown, at the top of the stairs there is a huge patch of unloaded textures until I am literally standing on invisible ground, then they load until back away.)
3. When loading a .3ds file of Majora's Mask (For 3ds, obviously) I get: "Fatal Error encountered:" but doesn't state what error.

**Comment by gouchi** [comment]
It will be better if you [open the issue in the original repository](https://github.com/lakka-switch/Lakka-LibreELEC/issues) until this [PR](https://github.com/libretro/Lakka-LibreELEC/pull/471) is merged.

Thank you.
