### ISSUE TITLE
make clean command doesn't clear .ccache

### ISSUE THREAD

**Issue by natinusala** [libretro/Lakka-LibreELEC#506]
The make clean command should delete the `.ccache` folder inside of the build folder. 

I had this scenario where a previously aborted build yielded an incomplete .so file, and LD didn't want it, making subsequent builds fail, even after a clean. Deleting `.ccache` solved the issue.

**Comment by ToKe79** [comment]
use `make distclean` for wiping the build folders completely.

**Comment by natinusala** [comment]
I see, thanks ! What is the point of using clean then ?

**Comment by natinusala** [comment]
Shouldn't ccache be considered as a build folder ?

**Comment by kivutar** [comment]
I don't know ccache enough

**Comment by kivutar** [comment]
The best would be to ask LibreELEC why they designed the build system this way. From what I understand, ccache is detecting when the same compilation is run a second time. They use hashes to make sure that if a file changed, it will be recompiled by gcc.

**Comment by natinusala** [comment]
Alright, I'm fine with using distclean in the meantime. There must be a reason why clean doesn't delete it. I'll see what I can find about this.
