### ISSUE TITLE
New Core: Ishiiruka (Dolphin)

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka-LibreELEC#511]
https://github.com/libretro/Ishiiruka

**Comment by ToKe79** [comment]
The libretro core/fork has not been updated for almost a year - is it worth adding this core to Lakka?

**Comment by natinusala** [comment]
It's only useful for platforms that can barely run Dolphin and can make use of the speed hacks of Ishiiruka... 

And we don't have any for now, except for Generic which has no trouble running it.

Seeing that the core is outdated, I wouldn't bother adding it for now 

But Lakka Switch has a package.mk for it, we tried it and we didn't notice any significant speed difference
