### ISSUE TITLE
[Docs] Raspberry Pi config file

### ISSUE THREAD

**Issue by vffhr** [libretro/Lakka-LibreELEC#529]
Regarding this page: http://www.lakka.tv/doc/Raspberry-Pi/

(I'm using Lakka for Raspberry Pi 2/3, so I'm not sure the information is accurate for Raspberry Pi 0/1.)

Under "Audio not working on some TVs" it says that the line "hdmi_drive=2" in "config.txt" can be uncommented, but that line does not seem to be in that file.

Under "HDMI to DVI adaptor" it says that "hdmi_drive=2" can be removed from "config.txt", however this line is found in "distroconfig.txt".

Thanks! :)

Edit: I just noticed that the same information is on http://www.lakka.tv/doc/FAQ/ as well. Also, I probably should have made this issue in the lakka-website repo.

**Comment by ToKe79** [comment]
thank you, fixed in the wiki
