### ISSUE TITLE
Lakka images in ZIP instead of GZ for Windows users

### ISSUE THREAD

**Issue by vffhr** [libretro/Lakka-LibreELEC#533]
Lakka IMG files are available to download in GZ format. Windows by default can't extract GZ files. It can however extract ZIP files. Would it be better to use ZIP files instead of GZ files so that they can be extracted on Windows (and I assume all other platforms) without requiring additional software?

**Comment by vffhr** [comment]
Thanks @Ntemis, I had no idea! Now that I look it's right there in the GUI; under "Select image" and hovering over "others", there is "gz" listed.

**Comment by RobLoach** [comment]
Would be good to have a link during the install process: https://github.com/lakkatv/lakka-website/issues/24 .

**Comment by ToKe79** [comment]
Lakka.tv website now directs the end user to use Etcher, which can handle .img.gz files.

**Comment by RobLoach** [comment]
Nice work! :+1:  Thanks a lot.

**Comment by vffhr** [comment]
@ToKe79 I just noticed that the heading on the [download page](http://www.lakka.tv/get/windows/rpi2/) still says "Download and unzip Lakka", should this be changed to just "Download Lakka" now?

**Comment by ToKe79** [comment]
Thank you, I will send PR to correct the heading(s).
