### ISSUE TITLE
Remove redream?

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka-LibreELEC#536]
Didn't realize this, but [redream went closed source](https://github.com/libretro/RetroArch/issues/6066), and the libretro package is an old version of what redream use to be.

Since it's no longer inline with what redream actually is, should we remove the libretro redream package from Lakka?

**Comment by Ntemis** [comment]
+1 from my part

**Comment by dmschwartzii** [comment]
It went closed awhile ago

**Comment by gouchi** [comment]
Fixed with #555
