### ISSUE TITLE
gpio-key dtoverlay not working as documented in Lakka 2.1.1

### ISSUE THREAD

**Issue by 32teeth** [libretro/Lakka-LibreELEC#546]
### Which version of Lakka are you using?
> Lakka 2.1.1

### What system hardware are you using?
> Raspberry Pi Zero W

### What did you do?
> dtoverlay call in config.txt
```shell
# never works
dtoverlay=gpio-key,gpio=13,label="RIGHT",keycode=103 
```
> command line call
does not work either, but gives no errors
```
dtoverlay gpio-key gpio=13 keycode=106 label="RIGHT"
```

### What did you expect to happen?
> Be able to press a button connected to GPIO13 and be able to have it simulate keycode 103 (right arrow)

### What happened instead?
> **NOTHING**

**Comment by Gadgetoid** [comment]
I'm a bit late to the party here, but in order for `gpio-key` bindings to be recognised as keyboard input you need a udev rule like this - https://github.com/pimoroni/picade-hat/blob/lakka/lakka-driver/10-picade.rules

```
SUBSYSTEM=="input", ATTRS{name}=="gpio_keys", ENV{ID_INPUT_KEYBOARD}="1"
```

You should place this in: `/storage/.config/udev.rules.d/`
