### ISSUE TITLE
Wi-Fi not working on RockPro64

### ISSUE THREAD

**Issue by gmichlicki-neducatio** [libretro/Lakka-LibreELEC#566]
- Which version of Lakka are you using?
Lakka-Rockchip.ROCKPro64.arm-2.2-devel-20181012054605-r28245-gfa5a150.img.gz

- What system hardware are you using?
RockPro64 4GB + [dedicated Wi-Fi module](https://www.pine64.org/?product=rockpro64-2x2-mimo-dual-band-wifi-802-11acbluetooth-4-1-module)

- What did you do?
Turned on wifi using UI, also from shell using `connmanctl enable wifi`

- What did you expect to happen?
wi-fi will be enabled or at least network list will show

- What happened instead?
error message: "Method "SetProperty" with signature "sv" on interface "net.connman.Technology" doesn't exist".

**Comment by Ntemis** [comment]
We dont have that but i will try to build you an image to try if you can test

**Comment by natinusala** [comment]
This is the only part of the ROCKPro64 image that I didn't try, and of course it doesn't work. I will need some time to setup the Wi-Fi module on my board, I will get back to you once I have some news.

**Comment by gmichlicki-neducatio** [comment]
Great guys, thank you. If you need more information or I can help you with something just let mi know.
Thanks again and keep up the good work!

**Comment by smitty-exos** [comment]
Any traction on this? The nightly builds still fail to pick up wifi/bt module. ayufan has this working in his latest releases.
