### ISSUE TITLE
unrecognized command line option '-m64'?

### ISSUE THREAD

**Issue by keeno1982** [libretro/Lakka-LibreELEC#569]
I make rpi3 image with command "DISTRO=Lakka PROJECT=RPi2 ARCH=arm make image" on my NANOPC-T4 fail:

gcc: error: unrecognized command line option '-m64'
make[2]: *** [<builtin>: cryptlib.o] Error 1
make[2]: Leaving directory '/mnt/HDD2/lakka/Lakka-LibreELEC/build.Lakka-RPi2.arm-2.2-devel/openssl-1.0.2o/.aarch64-linux-gnu/crypto'
make[1]: *** [Makefile:287: build_crypto] Error 1
make[1]: Leaving directory '/mnt/HDD2/lakka/Lakka-LibreELEC/build.Lakka-RPi2.arm-2.2-devel/openssl-1.0.2o/.aarch64-linux-gnu'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 2

Please help

**Comment by asakous** [comment]
Lakka needs a x64 computer to do the cross compile. 
or change  openssl package.mk  ,replace linux-x86_64 with linux-generic32
