### ISSUE TITLE
GameHAT GPIO support via mk_arcade_joystick_rpi

### ISSUE THREAD

**Issue by RiRilot** [libretro/Lakka-LibreELEC#572]
I’ve recently picked up a GameHat: https://www.waveshare.com/game-hat.htm 4 It’s quite a fun little thing but the drivers it uses are based on mk_arcade_joystick_rpi which is GPIO based. https://github.com/recalbox/mk_arcade_joystick_rpi

Could this package be integrated in to Lakka?

**Comment by Luraktinus** [comment]
any news on this, i wanna buy that GameHAT

**Comment by natinusala** [comment]
I just had a look at what the driver package looks like - it's nothing but a kernel module, `mk_arcade_joystick_rpi`, probably a modified version of https://github.com/recalbox/mk_arcade_joystick_rpi (or the same, I didn't look). 

In addition, there's a dtb overlay and some additional config.txt entries for the HDMI display.

I would add the kernel module as a driver in the kernel directly (as a `linux` package patch), and add an entry to the Lakka wiki to explain how to make the appropriate changes needed to use the display. Finally, I would add an entry to the joypad autoconfig repo to add the automagic mapping.

However while I do own a RPi3B I don't own the Game HAT. I can order one if needed.

**Comment by natinusala** [comment]
Status update: driver added to Lakka, everything works, input, audio and video. 

Expect a PR by the end of the week end ;)

**Comment by RiRilot** [comment]
Brilliant! Looking forward to testing it.

**Comment by RiRilot** [comment]
Just tested this. Works perfectly. Nice one!
