### ISSUE TITLE
Mouse buttons do not work on x86_64 - bugfix included ;)

### ISSUE THREAD

**Issue by smoky19x** [libretro/Lakka-LibreELEC#573]
Hello,

I found out that the mouse buttons do not work in all cores. After a felt eternity I could find the cause and fix it.

Retroarch is compiled in Lakka with the "HAVE_X11" flag if X11 is installed on the build host. This wrong assumption leads to the mouse buttons not being evaluated in the udev device query.

In the file "udev_input.c", the function "udev_pointer_is_off_window (udev)" is called in line 821, which evaluates the flag "HAVE_X11" and returns an incorrect return at this point.

This can be fixed by setting the parameter "HAVE_X11" in the file "qb / config.params.sh" from "HAVE_X11 = auto" to "HAVE_X11 = no":

```
diff qb/config.params.sh qb/config.params.sh.dist
61c61
< HAVE_X11=no                # X11 not included in Lakka
---
> HAVE_X11=auto              # everything X11.
```

**EDIT: Maybe the better way: add `--disable-x11` to `RETROARCH_GL` in file packages/libretro/retroarch/package.mk**

Can you please integrate a patch into Lakka? Together with the bug fix for PPSSPP (https://github.com/libretro/Lakka-LibreELEC/issues/499#issuecomment-444504307) it might be worthwhile to create a new Nightly ;)

**Comment by smoky19x** [comment]
I do not know the build scripts of Lakka in detail yet. I've now added `--disable-x11` to the `TARGET_CONFIGURE_OPTS` of the "scripts/build" file, but RetroArch still generates "HAVE_X11" in the "common.h" file. So that's not enough to fix it. Maybe this parameter should still be set globally to prevent other problems.

**Comment by natinusala** [comment]
`HAVE_X=auto` and `--disable-x11` should be equivalent to `HAVE_X11=no`, something is wrong here

**Comment by smoky19x** [comment]
OK. Could you possibly try to simulate this on your system? You certainly know the Lakka build scripts better.

**Comment by natinusala** [comment]
You should be looking at `config.h` and not `common.h`. I just looked at my local build of Lakka for the ROCKPro64, and I see those :

```
#define HAVE_NO_X11 1
/* #undef HAVE_X11 */
```
X11 support is indeed disabled, and I use X11 on the host PC. In fact, RetroArch couldn't even build with C11 support because the libs aren't in the system.

**Comment by smoky19x** [comment]
Yes, I also meant `config.h` and not `common.h`. I forgot to mention that i am building for `ARCH=x86_64`.  I have also seen that the variables `TARGET_CONFIGURE_OPTS` and `PKG_CONFIGURE_OPTS_TARGET` are overridden in `packages/libretro/retroarch/package.mk`. If I add there `--disable-x11` to RETROARCH_GL, it works too.

**Comment by natinusala** [comment]
Oh yeah you've been doing it in the wrong place, you should always put options for a package in its file.

**Comment by smoky19x** [comment]
But is there a way to define `--disable-x11` system-wide?

**Comment by natinusala** [comment]
Well add it to `PKG_CONFIGURE_OPTS_TARGET` in the RetroArch package ? What's the issue ?

**Comment by smoky19x** [comment]
One way to disable X11 globally would be nice, then it could not be forgotten at any point ;) You asked yourself if `--disable-x11` isn't  set for all platforms.

**Comment by smoky19x** [comment]
In one place, like in the `scripts/build` script for the build of all the Lakka packages.

**Comment by natinusala** [comment]
`--disable-x11` is a flag unique to RetroArch, why would you want to put it on the whole system ? You're just going to break packages using `configure` without an `--disable-x11` option.

**Comment by smoky19x** [comment]
Ah, thanks for clarification. If it is unique to RetroArch it indeed does not make sense to set it globally.
