### ISSUE TITLE
[doc][website] Broken link to 'alternative flashing methods'

### ISSUE THREAD

**Issue by apnof** [libretro/Lakka-LibreELEC#574]
Hi, 

on the site http://www.lakka.tv/get/linux/rpi2/install/ the link to 'alternative flashing methods' (http://www.lakka.tv/doc/Alternative-image-flashing-methods/) leads to a page not found. 

Regards.

**Comment by gouchi** [comment]
Thank you for the report, is it possible to open an issue on the [dedicated repository](https://github.com/lakkatv/lakka-website) ?

**Comment by apnof** [comment]
wrong issue tracker/duplicate of https://github.com/lakkatv/lakka-website/issues/63
