### ISSUE TITLE
S905 DTB links in docs point to compromised domain

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#579]
The Lakka docs for the S905 include links to a site for downloading the necessary DTB file. Here is the docs page I'm referring to: http://www.lakka.tv/doc/S905/

The DTB link points to https://sx05.eu/ which give me a security warning when I click on it in the Chromse browser. When I override the security warning, I see that the site looks to have gone offline.

**Comment by gouchi** [comment]
I don't understand links go to [https://kszaq.libreelec.tv/s905/8.2/device_trees/S905/](https://kszaq.libreelec.tv/s905/8.2/device_trees/S905/) on the website.

And there is an explanation why [sx05.eu is no more available](https://forum.libreelec.tv/thread/12432-notice-sx05-eu-domain-for-kszaq-builds-no-longer-in-use/).

**Comment by ToKe79** [comment]
I concur with @gouchi - on lakka.tv/docs and also in the wiki here it points to kszaq.libreelec.tv site. Maybe you have cached older version of the sub-page.
