### ISSUE TITLE
S905 install guide doesn't tell how to install Lakka

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#580]
The last step of the S905 install guide as it is currently written is to boot into live mode. At that point, the docs say: **Congratulations, you have successfully installed Lakka!**

However, at that point, Lakka is not installed, it is just running live. Here is a direct link to the docs I'm referring to: http://www.lakka.tv/get/linux/s905/install/first-boot/

**Comment by ToKe79** [comment]
I forgot one thing - after you install to internal storage, you have to run the command `rebootfromnand`.
