### ISSUE TITLE
Dolphin not visible on aarch64 Linux

### ISSUE THREAD

**Issue by jkaberg** [libretro/Lakka-LibreELEC#584]
- Which version of Lakka are you using?
2.2
- What system hardware are you using?
Amlogic s905x
- What did you do?
Try to find Dolphin core
- What did you expect to happen?
Find it
- What happened instead?
Didn't find it

According to https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/dolphin/package.mk it should be in /usr/lib/libretro

```
Lakka:~ # ls -l /usr/lib/libretro/ | grep -i dolphin
-rw-rw-r--    1 root     root           409 Dec 24 11:33 dolphin_launcher_libretro.info
-rw-rw-r--    1 root     root           538 Dec 24 11:33 dolphin_libretro.info
Lakka:~ #
```

Since https://github.com/libretro/dolphin/pull/20 and https://github.com/libretro/RetroArch/issues/6841, it should be there?

**Comment by jkaberg** [comment]
Here's some info, couldn't find "Lakka build name" but I'm guessing this will do?

Lakka version: S905.arm-2.2
Git version: b55ed9e
CPU Architecture: ARMv8
CPU Cores: 4

**Comment by natinusala** [comment]
`S905.arm-2.2` there you have it ;)

You would need an aarch64 build of Lakka to use Dolphin. But I wouldn't bother for two reasons :

1. It currently doesn't build 
2. It will not run good enough to be even playable
