### ISSUE TITLE
lakka 2.2 nightly builds Wi-Fi not working on s905 (Onboard Wi-Fi)

### ISSUE THREAD

**Issue by jzwtxp** [libretro/Lakka-LibreELEC#586]
s905 & s905x devices Wi-Fi not working

**Comment by jzwtxp** [comment]
Onboard Wi-Fi not working （rtl8189）

But the onboard wireless network card can work

**Comment by hojnikb** [comment]
It's not working for me either from 2.1.1 onwards. 
Also, what is the state of rtl8723bs based S905/x/w devices ? On my TX3 Max with Tanix libreelec dtb wifi works (on 2.0) but bluetooth works only partially. 

For example, i can see one MAC address of my dualshock3 controller, but i can't connect to it. When using an external usb bluetooth, it connects just fine.

**Comment by markwkidd** [comment]
Probably the same issue as https://github.com/libretro/Lakka-LibreELEC/issues/581

**Comment by markwkidd** [comment]
Also probably the same issue as https://github.com/libretro/Lakka-LibreELEC/issues/502

**Comment by ToKe79** [comment]
can you test this build?
http://nightly.builds.lakka.tv/PRs/pr_800_000093/S905.arm/
it is based on latest release + some wifi drivers
