### ISSUE TITLE
(/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)

### ISSUE THREAD

**Issue by carlucci9660** [libretro/Lakka-LibreELEC#588]
This issue tracker is NOT for help or support. Please use the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general) or IRC @ #lakka on freenode.net for those kinds of posts.

BEFORE you report a bug make sure you have tried the latest nightly version of Lakka at http://le.builds.lakka.tv/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? 2.21
- What system hardware are you using? dell envy
- What did you do? tried to connect wii remote
- What did you expect to happen? wii remote to be connected
- What happened instead? telling me onboard bluetooth is not supported maybe ?

It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at http://www.lakka.tv/doc/Troubleshooting-Lakka/

TO CONNECT A WII REMOTE ON A DELL ENVY

bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-01-01 20:51:18 UTC; 30s ago
 Main PID: 457 (bluetoothd)
   Status: "Running"
   CGroup: /system.slice/bluetooth.service
           └─457 /usr/lib/bluetooth/bluetoothd

Jan 01 20:51:18 Lakka systemd[1]: Started Bluetooth service.
Jan 01 20:51:18 Lakka bluetoothd[457]: Bluetooth daemon 5.43
Jan 01 20:51:18 Lakka bluetoothd[457]: Starting SDP server
Jan 01 20:51:18 Lakka bluetoothd[457]: Bluetooth management interface 1.14 initialized
Jan 01 20:51:18 Lakka bluetoothd[457]: Failed to obtain handles for "Service Changed" characteristic

Jan 01 20:51:18 Lakka bluetoothd[457]: Failed to obtain handles for "Service Changed" characteristic

Jan 01 20:51:18 Lakka bluetoothd[457]: Failed to set privacy: Rejected (0x0b)

~

**Comment by kprav33n** [comment]
The symptoms of this issue look similar to that of #597.
