### ISSUE TITLE
Tinker Board Lakka bluetooth issues

### ISSUE THREAD

**Issue by TranSeMental** [libretro/Lakka-LibreELEC#597]
I am using Lakka 2.2.1 but have also tried this with Lakka 2.2 and the latest nightly build
Using a standard Asus Tinker Board
Bluetooth just plain does not work
Tried bluetoothctl, got it to discovery mode and scan on but no devices are ever discovered despite putting 4 different controllers in discovery mode at different times

**Comment by gouchi** [comment]
Is it possible to provide bluetooth log with 
`journalctl -u bluetooth.service -r`

Thank you.

**Comment by kprav33n** [comment]
I also have trouble getting my Sony Dualshock 4 controller paired using Bluetooth on  Tinkerboard S using Lakka 2.2.

```
Lakka:~ # uname -a
Linux Lakka 4.4.154 #1 SMP Tue Oct 23 14:02:21 CEST 2018 armv7l GNU/Linux
```

Here is the status of bluetooth service.

```
Lakka:~ # systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2013-01-18 08:50:29 UTC; 6 years 0 months ago
 Main PID: 363 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/bluetooth.service
           └─363 /usr/lib/bluetooth/bluetoothd

Jan 18 08:50:29 Lakka systemd[1]: Started Bluetooth service.
Jan 18 08:50:29 Lakka bluetoothd[363]: Bluetooth daemon 5.43
Jan 18 08:50:29 Lakka bluetoothd[363]: Starting SDP server
Jan 18 08:50:29 Lakka bluetoothd[363]: kernel lacks bnep-protocol support
Jan 18 08:50:29 Lakka bluetoothd[363]: System does not support network plugin
Jan 18 08:50:29 Lakka bluetoothd[363]: Bluetooth management interface 1.10 initialized
Jan 18 08:50:30 Lakka bluetoothd[363]: Failed to obtain handles for "Service Changed" characteristic
Jan 18 08:50:30 Lakka bluetoothd[363]: Failed to set privacy: Rejected (0x0b)
```

Here is systemd journal output.

```
Lakka:~ # journalctl -u bluetooth.service -r
-- Logs begin at Fri 2013-01-18 08:50:29 UTC, end at Wed 2019-02-13 06:19:38 UTC. --
Jan 18 08:50:30 Lakka bluetoothd[363]: Failed to set privacy: Rejected (0x0b)
Jan 18 08:50:30 Lakka bluetoothd[363]: Failed to obtain handles for "Service Changed" characteristic
Jan 18 08:50:29 Lakka bluetoothd[363]: Bluetooth management interface 1.10 initialized
Jan 18 08:50:29 Lakka bluetoothd[363]: System does not support network plugin
Jan 18 08:50:29 Lakka bluetoothd[363]: kernel lacks bnep-protocol support
Jan 18 08:50:29 Lakka bluetoothd[363]: Starting SDP server
Jan 18 08:50:29 Lakka bluetoothd[363]: Bluetooth daemon 5.43
Jan 18 08:50:29 Lakka systemd[1]: Started Bluetooth service.
```

**Comment by gouchi** [comment]
Can you try to make a test with [2.2.2 testing image](http://le.builds.lakka.tv/Rockchip.TinkerBoard.arm/Lakka-Rockchip.TinkerBoard.arm-2.2.2.img.gz) ?

Thank you.

**Comment by angerman** [comment]
Hi all, so I've got bluetooth to work on the Tinker Board with the 2.2.2 image. It does however not work out of the box :(

In #538, [hciattach-realtek.service](https://github.com/libretro/Lakka-LibreELEC/pull/538/files#diff-8d5cfcc88adf5484c8a5451c4f5367a3) was added. Previously in 55a0301a16, `rtl8723b_bt.service` was added.

[rtl8723b_bt.service](https://github.com/libretro/Lakka-LibreELEC/blob/a3bbc74f5291e3155bbe0a50a478b33be7d11eb0/projects/Rockchip/packages/rtl8723b_bt/system.d/rtl8723b_bt.service) is
https://github.com/libretro/Lakka-LibreELEC/blob/a3bbc74f5291e3155bbe0a50a478b33be7d11eb0/projects/Rockchip/packages/rtl8723b_bt/system.d/rtl8723b_bt.service#L1-L14

and [hciattach-realtek.service](https://github.com/natinusala/Lakka-LibreELEC/blob/71f5830142b6e1063157cb4951c518bfdb54b385/projects/Rockchip/packages/rockchip-firmware/system.d/hciattach-realtek.service) is
https://github.com/natinusala/Lakka-LibreELEC/blob/71f5830142b6e1063157cb4951c518bfdb54b385/projects/Rockchip/packages/rockchip-firmware/system.d/hciattach-realtek.service#L1-L11

which are essentially the same.

copying `rtl8723b_bt.service` into `/storage/.config/system.d` with an additional `Restart=on-failure` in the `Service` section, will cause bluetooth to eventually come up in after ~3-5min.

My suspicion is that the `rtl8723b_bt` and the `attach-realtek` services, which appear to start simultaneously, end up stepping on each others toes. `rfkill` will subsequently report that bluetooth is soft blocked.

**Comment by ToKe79** [comment]
you can also test the alpha builds based on LibreELEC 9 - http://nightly.builds.lakka.tv/Lakka-LE9.0-experimental/012_Rockchip.arm/

**Comment by angerman** [comment]
@ToKe79 what's the relevant source they are built from? I've tried building from source (master) yesterday on a debian9 machine, but that failed due to some missing libraries for samba.

**Comment by ToKe79** [comment]
this branch https://github.com/libretro/Lakka-LibreELEC/tree/Lakka-LE9.0

**Comment by angerman** [comment]
@ToKe79 finally got around trying that one.

+ bluetooth works out of the box
- input lag is noticeably worse
- in general `bluetoothctrl` feels laggy

**Comment by ToKe79** [comment]
we moved to the LE9.2 base and have new images (http://nightly.builds.lakka.tv/Lakka-LE9.2/latest/TinkerBoard.arm/).
