### ISSUE TITLE
Build segfaults on Debian 9

### ISSUE THREAD

**Issue by Zlika** [libretro/Lakka-LibreELEC#598]
On Debian 9 / AMD64, there is a segfault when compiling openssl:

```
make[2]: Entering directory '/home/thomas/git/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/openssl-1.0.2o/.x86_64-libreelec-linux-gnu/test'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/thomas/git/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/openssl-1.0.2o/.x86_64-libreelec-linux-gnu/test'
making install in tools...
make[2]: Entering directory '/home/thomas/git/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/openssl-1.0.2o/.x86_64-libreelec-linux-gnu/tools'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[2]: Leaving directory '/home/thomas/git/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/openssl-1.0.2o/.x86_64-libreelec-linux-gnu/tools'
installing libcrypto.a
installing libssl.a
installing libcrypto.so.1.0.0
installing libssl.so.1.0.0
Segmentation fault
make[1]: *** [Makefile:552: install_sw] Error 139
make[1]: Leaving directory '/home/thomas/git/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/openssl-1.0.2o/.x86_64-libreelec-linux-gnu'
Makefile:26 : la recette pour la cible « release » a échouée
make: *** [release] Erreur 2
```

I found a thread on this compilation bug in the Libreelec forum (https://forum.libreelec.tv/thread/12422-openssl-compilation-issue-for-8-2-5-9/), but I don't know how to fix it.

Regards

**Comment by gouchi** [comment]
Did you try ?

> You have to install libssl1.0-dev instead of libssl-dev on Debian Stretch

**Comment by Zlika** [comment]
Yes. Without success.

**Comment by bite-your-idols** [comment]
I have the same issue using ubuntu 16.04 docker container, just for Generic devices, for RPi it builds fine... any solution?

I found another user with the [same issue](https://github.com/libretro/Lakka-LibreELEC/pull/461#issuecomment-387655862)

**Comment by toolboc** [comment]
@bite-your-idols, I had the same issue using the included Dockerfile and attempting to build for Generic.x86_64.  I was able to resolve by applying this [modification](https://forum.libreelec.tv/thread/14975-openssl-compilation-issue/?postID=114573#post114573) to the `makeinstall_target()` function in `packages/security/openssl/package.mk`.

**Comment by bite-your-idols** [comment]
thanks @toolboc, but finally I moved back to virtualbox so I can not test it, If I give docker another try I will remember this fix.

**Comment by gouchi** [comment]
@bite-your-idols or @Zlika your issue should be fixed now, can you confirm it is the case.

Thank you.

**Comment by ToKe79** [comment]
Debian (stretch, 9.9) - working.
