### ISSUE TITLE
Please include rsync

### ISSUE THREAD

**Issue by YodaDaCoda** [libretro/Lakka-LibreELEC#599]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
2.2.1
- What system hardware are you using?
Intel NUC (x86_64)
- What did you do?
Tried to use rsync
- What did you expect to happen?
rsync to be available
- What happened instead?
rsync is not available

See issue #289. This was closed with commit 74237b3, which added rsync for the S8X2 project. I believe that this should be added for all projects.

**Comment by jeapostrophe** [comment]
Rsync is a great way to use ssh to synchronize my big storage with my small Pi SD card!
