### ISSUE TITLE
LAKKA as AccessPoint - enchancement

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka-LibreELEC#60]
```
[Unit]
Description=Local AP via Connman
ConditionKernelCommandLine=|localap
ConditionPathExists=|/storage/.cache/services/localap.conf

[Service]
EnvironmentFile=-/storage/.cache/services/localap.conf
#ExecStart=/usr/bin/sshd -D $SSH_ARGS
ExecStart=/usr/bin/connmanctl tether wifi on $APNAME $PASSWORD
ExecStop=/usr/bin/connmanctl tether wifi off
TimeoutStopSec=1s
StartLimitInterval=0

[Install]
WantedBy=multi-user.target

```
The above systemd service triggers when **localap** is defined as a kernel parameter (similar to how SSH works).
It will then look in /storage/.cache/services/localap.conf which should contain:
APNAME=LAKKA
PASSWORD=BLAHBLAH
Connman will then tether the WIFI AP (192.168.1.0/24) to the onboard ethernet (useful for hotels as well).

**Comment by markwkidd** [comment]
I created a bounty to this issue. Seems like it would be a neat feature.

https://www.bountysource.com/issues/42484309-lakka-as-accesspoint-enchancement

**Comment by Kivutar** [comment]
I added it here https://github.com/libretro/Lakka-LibreELEC/commit/8bd547482a6e4576e002b44efc95bd9bcccf41df

You can try this image please? http://static.kivutar.me/Lakka-RPi2.arm-8.0-devel-20170511070237-r26126-gf275cda.img.gz

**Comment by markwkidd** [comment]
@Kivutar I spend much of May, June, and July traveling for my work. Thank you for taking on this project but I'm unfortunately not able to test that image in the immediate future.

**Comment by Kivutar** [comment]
@duduke I get a

    connmanctl> tether wifi on LAKKA TEST
    Wifi SSID set
    Error setting wifi passphrase: Passphrase required

**Comment by duduke** [comment]
I think the password should be at least 8 chars length. It is WPA2.

**Comment by Kivutar** [comment]
OK, it works now, but I can't connect SSH:

    root@192.168.1.2's password: 
    Permission denied, please try again.

**Comment by Kivutar** [comment]
Documented here: https://github.com/libretro/Lakka-LibreELEC/wiki/Lakka-as-AccessPoint

**Comment by duduke** [comment]
Possibly a restart of SSHd and SMBd is required to pickup the new IP address.
