### ISSUE TITLE
joyutils package upstream URL broken

### ISSUE THREAD

**Issue by Zlika** [libretro/Lakka-LibreELEC#603]
Hi,
The upstream URL of the joyutils package (ftp://atrey.karlin.mff.cuni.cz/pub/linux/joystick/) seems to be broken. Debian maintains a fork at https://salsa.debian.org/debian/joystick with tags for upstream versions, but the oldest upstream version is 1.4, whereas Lakka's current version is 1.2.15.
Regards,
Thomas

**Comment by Zlika** [comment]
It seems that joyutils is now part of linux-console-tools (https://sourceforge.net/projects/linuxconsole/).

**Comment by shantigilbert** [comment]
I've been using this one https://github.com/datrh/joyutils with minor changes to  package.mk

**Comment by Zlika** [comment]
Thanks for your workaround, it fixed my problem.
