### ISSUE TITLE
Lakka 2.2 Ozone Menu Driver, Crash when Show / Hide Advance settings

### ISSUE THREAD

**Issue by iokzero** [libretro/Lakka-LibreELEC#605]
Using Lakka 2.2 

Enable "Show Advance Settings" in order to get to "Driver" Menu then change Menu Driver to Ozone.
When going back to "User Interface" to switch off "Show Advanced Settings" , the system will crash. 

The "Show Advanced Settings", however, can be done in the retroarch config file using text editor, but need to disable "Save settings when close retroarch". otherwise it wouldn't take any effect.

And if you, then going back "User Interface" and enable "Show Advance Setting" using the Ozone Menu Driver, the system will crash too. 

Seems like a Ozone Menu Driver issue. 

Sorry about not be able to try out the Night Build to see if this has been fix, But It would be worth a mention for those Lakka 2.2 stable release user. 
(maybe a point release to fix this? or label Ozone as experimental.) 
This is issues is very noticeable, sense you need to use "Show Advance Settings" in order to change it to Ozone, 

Thanks for all the wonderful works on LAKKA!

**Comment by natinusala** [comment]
I don't think ozone is supported on Lakka for now, but it should at least be stable and not crash

Do you have access to a terminal (through SSH) ? If so, I can guide you through the steps to diagnose the crash and help me fix it

**Comment by iokzero** [comment]
Hi Nathan,

Thanks for your quick response,
Yes, I do have access to a terminal using SSH. It would be great, if you
can guide me to see what might cause this problem.
I assumed Ozone is supported because it is one of the highlight on the
Lakka 2.2 release note.
<http://www.lakka.tv/articles/2018/12/24/lakka-22-christmas-release/>

Overall I think Ozone works great (Other then the problem I mentioned of
course.),
I like the interface, and definitely a great addition to the menu driver
library.

Again thanks for the wonderful work on Lakka.

I.O.K.

**Comment by natinusala** [comment]
Oh well I didn't know it was showcased on the release note haha!

However I just realized that regular Lakka doesn't ship with debug symbols... it means that if you successfully get a stack trace from the crash, we won't be able to do anything with it without the debug symbols.

I don't know what to do sadly, apart from providing you with a debug image

**Comment by iokzero** [comment]
would the the debug image work on live mode?
or are you able to test it on  your end?

I can try to help test it on the weekend.

I.O.K.

**Comment by iokzero** [comment]
Oh forget to mention that, I am using X86_64 version.

I.O.K.

**Comment by natinusala** [comment]
What is your device ? Generic ?

Thing is, ozone has evolved since Lakka 2.2 came out, and I would not be surprised if the crash was already solved in RetroArch master

**Comment by iokzero** [comment]
I am using the nuc7i7bnh with the X86_64 Lakka 2.2

I am sure Ozone is getting better, and if you think it might not worth a
fix for this version. It is also fair to wait for the next version.
Just want to reported this, just so people know the issue exist (at least
on this platform anyway)

I.O.K.

**Comment by iokzero** [comment]
So I did some initial trouble shooting with verbose mode

having Hide Advance setting on / off.
For some reason now turning it back ON seem to work fine with an issue.

but then again turning it OFF crash the system, and the Terminal just says
"Segmentation fault (core dumped)" with no additional information.

I.O.K.

**Comment by Mr-Jake** [comment]
Has Lakka been updated to RetroArch 1.7.6?
1.7.6 has the Ozone improvements.

**Comment by ToKe79** [comment]
you can try devel builds, there were some updates on retroarch and cores. http://nightly.builds.lakka.tv/
