### ISSUE TITLE
SSH not work (Lakka-OdroidC1.arm-2.2.img)

### ISSUE THREAD

**Issue by vebmaster** [libretro/Lakka-LibreELEC#606]
Hello.
Image: Lakka-OdroidC1.arm-2.2.img
Odroid c1

http://www.lakka.tv/doc/The-bootloader/
boot.ini
add "ssh" in bootargs.

SSH not connect.
22/tcp port closed

On "Lakka-OdroidC1.arm-2.1.1.img" ssh good work.

**Comment by gouchi** [comment]
Can you make a test on [testing image Lakka 2.2.2](http://le.builds.lakka.tv/Odroid_C2.arm/Lakka-Odroid_C2.arm-2.2.2.img.gz) ?

Thank you.

**Comment by Ntemis** [comment]
C1 is not supported anymore as we no longer have any boards
Marking this as do not fix and closing down
