### ISSUE TITLE
Lakka 2.2.1 image (for Raspberry Pi)

### ISSUE THREAD

**Issue by clach04** [libretro/Lakka-LibreELEC#617]
1. latest download not listed on the website (causes extra upgrade step for new users).
 2. Missing changelog for 2.2.1 since 2.2

I went to download the latest Lakka image from http://www.lakka.tv/get/windows/rpi2/ this leads to http://le.builds.lakka.tv/RPi2.arm/Lakka-RPi2.arm-2.2.img.gz

However after install the download/upgrade option offers 2.2.1 which was not listed on the website. You can see this if the download URL is reduced to http://le.builds.lakka.tv/RPi2.arm/

The Lakka releases https://github.com/libretro/Lakka-LibreELEC/releases does not mention this. Latest is currently https://github.com/libretro/Lakka-LibreELEC/releases/tag/v2.2

**Comment by gouchi** [comment]
Can you try to add issue to [Lakka website repository](https://github.com/lakkatv/lakka-website) ?

Thank you.

**Comment by clach04** [comment]
@gouchi thanks! I'd not realized that was a repo :-)

Opened https://github.com/lakkatv/lakka-website/issues/67

**Comment by gouchi** [comment]
Thank you.
