### ISSUE TITLE
Automount local network shares

### ISSUE THREAD

**Issue by kivutar** [libretro/Lakka-LibreELEC#62]
First, we need to find a bugfix to allow retroarch to unzip content on network shares.

Then, we need to find a service that detects network shares and automatically mounts them.

    smbtree -N

**Comment by markwkidd** [comment]
I started a bounty for this issue. Seems like it would be a neat feature.

https://www.bountysource.com/issues/42484309-lakka-as-accesspoint-enchancement

**Comment by RobLoach** [comment]
http://wiki.openelec.tv/index.php/Mounting_network_shares

I find using a `/storage/.config/system.d/storage-retroarch.mount` file the easiest way to automount drives. Not sure if Lakka will wait until the network is connected before making the mount though.

**Comment by Kivutar** [comment]
By automounting I mean automatic discovery of the shares on the network. Without manual files editing.

**Comment by RobLoach** [comment]
Ah, that would be cool.
