### ISSUE TITLE
glibc 2.28 breaks the current m4 release

### ISSUE THREAD

**Issue by marcfehling** [libretro/Lakka-LibreELEC#621]
See: https://lists.gnu.org/archive/html/bug-m4/2018-08/msg00000.html

Lakka can not be built with the latest `glibc 2.28` release. Those issues have been fixed upstream in `gnulib`, but `m4` hard-copied parts of older `gnulib` versions that do not involve this workaround. A new `m4` release fixing this was announced in August, but has not happened yet.

**Comment by slav0nic** [comment]
with patch from debian `m4` build passed http://cdn-fastly.deb.debian.org/debian/pool/main/m/m4/m4_1.4.18-2.debian.tar.xz but this libs aslo broken on other packages like `bison` =\

**Comment by natinusala** [comment]
The LE9.2 branch should build fine with latest glibc
