### ISSUE TITLE
2.2.2 rpi2 does not include rdb for Commodore Amiga

### ISSUE THREAD

**Issue by noromamai** [libretro/Lakka-LibreELEC#624]
- downloaded rpi2 lakka 2.2 image
- installed onto sd card
- updated to 2.2.2 via interface
(- scanning amiga games yields nothing)
- checked /usr/share/libretro-database/rdb/ and don't see the "Commodore - Amiga.rdb" file there.

tried copying the rdb file into /storage/database, /storage/database/rdb (had to create the rdb dir), /storage/.config/retroarch/database/rdb but still did not scan anything. 
not sure if that's where they should be copied, could not find any docs on this.

i think i saw an "update databases" option somewhere on another build some time ago, but can't find it now, removed?

**Comment by ToKe79** [comment]
You can switch to the latest devel build, it is quite stable (http://nightly.builds.lakka.tv/2019-07-02/). rdb for Commodore Amiga is included. If you want to update manually only the database files, put them manually to `/tmp/database/rdb` - don't be scared of the `/tmp/database` - this is just a mountpoint for overlayfs, no temporary folder - all changes here are permanent. The option to update the database is most probably not removed, only hidden - you should be able to enable it via settings / views (you must have advanced settings enabled) and enable online updater.
