### ISSUE TITLE
Lakka_disk empty

### ISSUE THREAD

**Issue by xslackx** [libretro/Lakka-LibreELEC#641]
Something is wrong with the image Lakka-RPi2.arm-2.2.2.img
This morning I wrote the SD card using the dd command, but at the end of the process the partition LAKKA_DISK was empty, it only contained the lost and found folder and a hidden file.
I have used raspberry pi b + v1.2.
Thank you

**Comment by natinusala** [comment]
Isn't LAKKA_DISK the storage partition? If so, it's normal to be empty, you need to boot at least once for it to be resized and populated

**Comment by xslackx** [comment]
This procedure has already been performed.
I left for more than 10 minutes connected but nothing happened, the LEDs turn on normally, I downloaded and burned the sdcard again and the same error occurred.
The card is working normally because I tested another operating system on the same sdcard.

**Comment by ToKe79** [comment]
the case might be it is not booting? are you using correct image? is your sbc rpi0/rpi/rpi2/rpi3?
try RPi.arm instead of RPi2.arm?

**Comment by xslackx** [comment]
My board is raspberry pi b + v1.2
I already tried to use the image of raspberry pi 3 and also raspberry pi 2 and both presented the same error.
I will try to use the image from the first version.

**Comment by natinusala** [comment]
Are you using the RPi2 Image on a RPI1? That won't work

**Comment by xslackx** [comment]
No, I'm using the rpi2 image and it still throws the error.
md5sum
38faf8cf23a0384a953fc428e39d7e6a Lakka-RPi2.arm-2.2.2.img.gz
I took a print
https://imgur.com/pr787Vq

**Comment by natinusala** [comment]
> My board is raspberry pi b + v1.2

So is it a RPi1 or RPi2 ?

**Comment by xslackx** [comment]
Eu desisto.
