### ISSUE TITLE
Thumbnails don't support "&" symbols

### ISSUE THREAD

**Issue by kmssd** [libretro/Lakka-LibreELEC#642]
- Which version of Lakka are you using?
2.2.2
- What system hardware are you using?
Raspberry Pi3 B+
- What did you do?
FTP thumbnails to proper folders
- What did you expect to happen?
Boxart, snaps and title images to appear while scrolling through games.
- What happened instead?
Png files with & in the filename don't appear. Changing filename of rom to match png breaks extra information for rom.

**Comment by Ntemis** [comment]
https://github.com/libretro/libretro-thumbnails
