### ISSUE TITLE
Preinstall unrar, 7z, xz etc..

### ISSUE THREAD

**Issue by snbuback** [libretro/Lakka-LibreELEC#644]
Lakka version 2.2

Frequently roms pack are rar/7z/xz,etc.. files. Systems like raspberry are slow to upload individual files so is better upload the compressed ones, but there is no too to unpack.
These tools are smaller and are already part of the package system in debian for example.

The idea is able to run on the command line. I'm planning to have them on the interface.

**Comment by RobLoach** [comment]
.zip is supported. Other compression methods are iffy. Doesn't work for CD media.

**Comment by snbuback** [comment]
I'm aware of the zip. But many rom packs are rar or 7z (few are zip due to the size and low compression rate)

**Comment by RobLoach** [comment]
Would need to be added to RetroArch before in Lakka. Here's an issue for ya! https://github.com/libretro/RetroArch/issues/4122
