### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ezar** [libretro/Lakka-LibreELEC#648]
- Which version of Lakka are you using?
2.2
- What system hardware are you using?
Pi 3b

ERROR:

ALSA lib /home/neil/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/alsa-lib-1.1.8/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

**Comment by natinusala** [comment]
This is an error with a missing MIDI device, irrelevant and meaningless.

Why is this message an issue for you?

**Comment by ezar** [comment]
Not relevant error.
