### ISSUE TITLE
Lakka 2.2.2 Performance issue

### ISSUE THREAD

**Issue by simply1233** [libretro/Lakka-LibreELEC#652]
I am relatively new to lakka, but I'm having a strange performance issue involving lakka 2.2.2 on the asus tinker board, I'm having strange performance issues with fullspeed PlayStation and decent n64 emulation where it lags at odd intervals and, they work, but not very well.

**Comment by Ntemis** [comment]
we cant help you by only this info. sorry.
Make sure you have a decent heatsink with a fan on it and report back if issue persist with logs.
Closing it down atm, let me know

**Comment by simply1233** [comment]
I already had a heatsink, I also had a fan.
