### ISSUE TITLE
Why doesn't Lakka use system's already-provided toolchain?

### ISSUE THREAD

**Issue by AnClark** [libretro/Lakka-LibreELEC#671]
I'm building Lakka from source, but I discovered that Lakka's build system always fetch these toolchain's source code, then build them, regardless of that they can be easily installed through an `apt install XXX`.

For example: GNU Make, CMake, Bison, libtool, GCC, etc.

As you know, most of time in building Lakka is wasted on building those toolchains.

**Comment by ToKe79** [comment]
Because you are cross-compiling. This is not a bug, but a feature of the sysroot build system.
Locally provided "build essentials" are used to compile the toolchain, so they are not wasted.

**Comment by AnClark** [comment]
No wonder! But I saw that Android's build system provided prebuilt toolchain binaries. For example, GCC for multiple platforms and ABIs.
