### ISSUE TITLE
Does lakka support nvidia Jetson nano?

### ISSUE THREAD

**Issue by chaogehen** [libretro/Lakka-LibreELEC#674]
I love Lakka, I hope to run it on nvidia jetson nano, will it be compatible? Thanks!

GPU | 128-core Maxwell
CPU | Quad-core ARM A57 @ 1.43 GHz
Memory | 4 GB 64-bit LPDDR4 25.6 GB/s
Storage | microSD (not included)
Video Encode | 4K @ 30 \| 4x 1080p @ 30 \| 9x 720p @ 30 (H.264/H.265)
Video Decode | 4K @ 60 \| 2x 4K @ 30 \| 8x 1080p @ 30 \| 18x 720p @ 30 (H.264/H.265)
Camera | 1x MIPI CSI-2 DPHY lanes
Connectivity | Gigabit Ethernet, M.2 Key E
Display | HDMI 2.0 and eDP 1.4
USB | 4x USB 3.0, USB 2.0 Micro-B
Others | GPIO, I2C, I2S, SPI, UART
Mechanical | 100 mm x 80 mm x 29 mm

https://developer.nvidia.com/embedded/buy/jetson-nano-devkit
https://developer.nvidia.com/embedded/downloads#?search=Jetson%20Nano

**Comment by natinusala** [comment]
As I already said on Discord, the Switch port is based on the Jetson Nano Ubuntu distribution (Linux4Tegra revision 32-something). One can easily take the Switch port, remove the Switch changes and config (to use the regular Nano ones instead) and it should just work. The bootloader will need changes too.

That being said, I'm not sure that I want to support it here, on the official Lakka repo. L4T is really weird (it uses 8 different git repositories for the kernel alone), and I had to introduce many breaking changes in the Switch port to make it work (and it's super, super dirty).

So, your best bet is currently rebuilding Lakka Switch, until we find a way to properly add L4T, in which case the Switch port + Jetson Nano will be officially supported here.

**Comment by Ntemis** [comment]
Close it maybe?

**Comment by natinusala** [comment]
Not sure, I would like to have it as an issue because Jetson Nano is really something that I want to eventually have for Lakka

**Comment by Ntemis** [comment]
we all do but is nvidia willing to sent some boards over?

**Comment by mrcmunir** [comment]
Hi I don't have much free time but I would be interested in providing support to support nvidia jetson nano based on a 4.9.140 kernel and actually are based l4t 32.2.0 branch.

https://nv-tegra.nvidia.com/gitweb/?p=device/hardware/nvidia/platform/t210/porg.git (For dts files )
https://nv-tegra.nvidia.com/gitweb/?p=3rdparty/u-boot.git (For u-boot)
https://nv-tegra.nvidia.com/gitweb/?p=linux-nvgpu.git   ( Nvgpu driver)
https://nv-tegra.nvidia.com/gitweb/?p=linux-4.9.git (Kernel 4.9)

**Comment by natinusala** [comment]
Again, Lakka-Switch has everything needed to compile a L4T version of Lakka, with nvgpu.

1. Take Lakka Switch
2. Remove the Switch specific repositories (use nvidia's gitweb instead of switchroot) and various userland patches
3. Change DTS
4. Change/adapt bootloader
5. ???
6. Profit

**Comment by ezar** [comment]
Nobody lnterested in make Nano port?

**Comment by Ntemis** [comment]
It must be done by someone that owns it.
Feel free to try what @natinusala suggested

**Comment by ezar** [comment]
> Hi I don't have much free time but I would be interested in providing support to support nvidia jetson nano based on a 4.9.140 kernel and actually are based l4t 32.2.0 branch.
> 
> https://nv-tegra.nvidia.com/gitweb/?p=device/hardware/nvidia/platform/t210/porg.git (For dts files )
> https://nv-tegra.nvidia.com/gitweb/?p=3rdparty/u-boot.git (For u-boot)
> https://nv-tegra.nvidia.com/gitweb/?p=linux-nvgpu.git ( Nvgpu driver)
> https://nv-tegra.nvidia.com/gitweb/?p=linux-4.9.git (Kernel 4.9)

@mrcmunir Can you try it?

**Comment by ezar** [comment]
https://www.reddit.com/r/SBCGaming/comments/eia0yh/nvidia_jetson_nano_rotn_retropie_on_the_nano_v1/?utm_source=amp&utm_medium=&utm_content=post_body

**Comment by mrcmunir** [comment]
@ezar Sorry For now I have not tried anything to much with lakka all the work is focused on Retro-Arena (At the moment internally)
Some system need debugging buit it's working 32 system and some platform experimental to do in comming

**Comment by ezar** [comment]
thanks mrcmunir
i try Retro-Arena beta at jetson :) works fantastic

**Comment by natinusala** [comment]
Someone on the switchroot team is willing to redo the Switch port on the LE9 branch, which will bring cleaner Switch and Jetson Nano support for both upstream Lakka and LibreELEC
