### ISSUE TITLE
ASUS VivoMini PB40-BC009MD stuck on Berry Screen, can't SSH

### ISSUE THREAD

**Issue by NTrixner** [libretro/Lakka-LibreELEC#686]
Hi!

I tried installing Lakka on my Asus VivoMini PB40-BC009MD (With the Intel CELERON N4000 CPU - https://www.asus.com/Mini-PCs/Mini-PC-PB40), but after the installation, the boot gets stuck on the Berry Screen. Also, it doesn't seem like I'm able to SSH it, since I can see the IP on my router, but putty reports a connection refused.
I also tried to pull the SSD out of the VivoMini and access the file system directly. However, I'm only able to access the files on the data volume, and I couldn't find any logs there.
I know that that's not a lot, but I'm honestly not sure how I would be able to produce logs at this point.

**Comment by gouchi** [comment]
Can you try to boot with ?

`live ssh`

and provide some [Lakka system and graphic logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/) ?

Thank you.

**Comment by NTrixner** [comment]
Alright, that took a while to get it to work, but here:
https://pastebin.com/Xq4K1pJg

**Comment by gouchi** [comment]
Thank you for the information.

```
[    0.702747] [drm] The driver support for your hardware in this kernel version is alpha quality
[    0.702747] See CONFIG_DRM_I915_ALPHA_SUPPORT or i915.alpha_support module parameter
[    0.702747] to enable support in this kernel version, or check for kernel updates.
```
Unfortunately,  [CONFIG_DRM_I915_ALPHA_SUPPORT](https://github.com/libretro/Lakka-LibreELEC/blob/master/projects/Generic/linux/linux.x86_64.conf#L3473)  is not enabled on Generic platform kernel.

You may try to boot with `i915.alpha_support=1` in the cmdline.

Also you may try a [testing build](https://drive.google.com/drive/folders/128MaH09bjVcB2pR4Kj2XxdBabR-oDP75) based on LE9.

Thank you.

**Comment by NTrixner** [comment]
Hi!

I tried the testing build, that one works for me.

Thank you very much for your help!

**Comment by gouchi** [comment]
We are [working on LE9 ](https://github.com/libretro/Lakka-LibreELEC/issues/556) and we have some [new testing builds](http://nightly.builds.lakka.tv/Lakka-LE9.0-experimental/) if you want to try.

Thank you.

**Comment by NTrixner** [comment]
I'll try it out as soon as I find time to do so.

Thank you!

**Comment by gouchi** [comment]
Hi,

Did you have time to make some tests ?

Thank you.

**Comment by NTrixner** [comment]
Hi!
No I'm sorry, I couldn't find the time yet.
Probably won't either the next one or two months, I have a lot of stress at work ATM.

**Comment by gouchi** [comment]
Hi,

No problem, take your time.

Thank you.
