### ISSUE TITLE
ozone theme glitchy on odroid c2

### ISSUE THREAD

**Issue by G-Michel** [libretro/Lakka-LibreELEC#698]
Hi i've already posted something on lakka's forum but i think it's more appropriate to post it here.

The Ozone theme seems to have issues on odroid c2 boards 

There are many graphic elements missing and texts that are not visible 

sometimes the theme appears corerectly (on some submenues ) but it is mainly unusable 

finally the bug is present in all update since ozone implementation even nightly builds 

have a nice day :)

**Comment by gouchi** [comment]
May you provide some screenshot or video ?

Thank you.
