### ISSUE TITLE
[Requests] Add/Remove somes cores

### ISSUE THREAD

**Issue by wwark** [libretro/Lakka-LibreELEC#705]
Hello,

Do you think it is possible to add/remove following cores in the master branch?

- Add Play- (PS2 Emulator) - https://github.com/libretro/Play-
- Add Mesen-s (Snes Emulator) - https://github.com/libretro/libretro-super/commit/077c5e0981067ad9e11ad24eb6fd897fc4f27dff
- Remove Mupen64plus (archived in libretro side : https://github.com/libretro/mupen64plus-libretro)

Thank you,
Wwark

**Comment by natinusala** [comment]
We have a package.mk for Play it will be added eventually

Mupen can't be removed as some platforms can't use mupen-next

**Comment by pcs3rd** [comment]
Also https://github.com/libretro/minibrowser. 
Would make a good addition to lakka

**Comment by RobLoach** [comment]
> Also https://github.com/libretro/minibrowser.

Last time I tried that, it didn't work.

**Comment by pcs3rd** [comment]
Oh :(. So no way to authorize captive portals?

**Comment by natinusala** [comment]
I understand your request, but I really don't want people to exit RetroArch when running Lakka, so using a standalone browser is a no-go.

However, if you can find / create a lightweight browser libretro core that works with controllers (that's very important), feel free to notice us.

**Comment by wwark** [comment]
Thank you for adding play- core !

**Comment by gouchi** [comment]
- Play!: new libretro core #707

**Comment by wwark** [comment]
Thanks again for adding mesen-s.

I closed this ticket !

**Comment by gouchi** [comment]
- mesen-s : add mesen-s libretro core  #740
