### ISSUE TITLE
Feature Request: local coop without internet

### ISSUE THREAD

**Issue by pcs3rd** [libretro/Lakka-LibreELEC#710]
For those places that don't have convenient for compatible networks, have one capable device host wifi (and the net play session) and set the other to just connect to the wifi then the hosted net play session

**Comment by RobLoach** [comment]
This should be possible right now?

- Disable Publically Anounce Netplay
- Disable Relay Server
- Start the server
- Input the IP of the host in your client
- Connect

Haven't tried this before, but should work just fine.

If not, feelf ree to create an issue on the [RetroArch Issue Queue](https://github.com/libretro/retroarch/issues).

**Comment by gouchi** [comment]
Moreover, you can use [Lakka as access point](https://www.lakka.tv/doc/lakka-as-accesspoint/) if needed.

**Comment by pcs3rd** [comment]
@gouchi don't realize that... Thanks for bringing it up. Are there any plans to implement settings for that into the gui

**Comment by pcs3rd** [comment]
Closed.
