### ISSUE TITLE
Wrong screen-scaling on Rpi4

### ISSUE THREAD

**Issue by boschili** [libretro/Lakka-LibreELEC#759]
Nightly august 13th release in RPi4 2gb

I‘m using the RPi on a tv with a resolution of 1280x720@60Hz via HDMI.

The OS recognizes 1440x1080@60Hz

Strange thing is: the scaling looks right but feels kinda wrong. Maybe there’s some strange kind of tearing or an issue with rescaling on the tv. If i manually set the right resolution for the tv the picture shown on screen feels right when playing but looks wrong, because of being kind of Pixeled.

**Comment by RobLoach** [comment]
Does the same happen on Windows?

**Comment by boschili** [comment]
No, my Win10 laptop recognizes the tv with its native resolution of 1280x720@60Hz

I‘m not home at the moment. Will post a log, as soon as I get my hands in the Pi.

**Comment by boschili** [comment]
Problem solved. retroarch did a fualty scaling. I went ahead and fitted the picture to the screen manually in the video-settings. looks anf feels fine now!
