### ISSUE TITLE
Dolphin not loading on RPI4

### ISSUE THREAD

**Issue by Pittsie72** [libretro/Lakka-LibreELEC#761]
Which version of Lakka are you using?
Latest nightly: Lakka-RPi2.RPi4.arm-2.2-devel-20190815003103-r28324-g35a9e03144.img

What system hardware are you using?
Raspberry Pi 4B / 4GB memory at default clock speeds

What did you do? Downloaded dolphin core via online updator

What did you expect to happen? 
Dolphin core added and GameCube games playable 

What happened instead?:
Nothing at all

When I download dolphin or any other GameCube/Wii core, the core will extract but never appear. Even try scanning all files in the downloaded folders. Unsure if applies to any other extra core.

**Comment by natinusala** [comment]
Did you enable the online updater manually?

If so, you shouldn't, it's disabled because we don't support it.

As for Dolphin, sorry to break your dreams but it will probably never work on the Raspberry Pi (too weak hardware, no aarch64 userland)

**Comment by natinusala** [comment]
Then it got enabled again somehow

Even if it runs on aarch64 userland (which is not supported), it would be too slow to be playable
