### ISSUE TITLE
Downloads fecked

### ISSUE THREAD

**Issue by xcs011** [libretro/Lakka-LibreELEC#769]
Okay sorry for fucking with pull requests.

But yeah, the download mirror appears to be down, and gives me a 404 error for every version.

**Comment by Ntemis** [comment]
http://nightly.builds.lakka.tv/

**Comment by natinusala** [comment]
The main download server indeed yields a 404 error, I'll see what is the cause this evening

**Comment by natinusala** [comment]
Will be fixed with the 2.3 release
