### ISSUE TITLE
Raspberry Pi 4 B nightly build, no display output

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#773]
For nightly build  Rpi4 9--02- 2019.  For one of the TV's it was tested on It does not show any output whatsoever. But upon bringing it to another tv it shows and displays well. I did find this odd issue with a Raspbian OS install on the same pi when it was used on a Tv as well.

**Comment by aberusugi** [comment]
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

Sounds like EDID detection issue for one of your monitors. If you are going through an HDMI switcher, remove that out of the equation. If that doesnt' work, take out he microSD card, plug it back into your PC you used to write the image, it should allow you to go to the /boot/config.txt file. In there try adding this line:

hdmi_safe=1

save the file.

And try it again. If it doesnt' work, comment out that line again in the config.txt.

Next go to the tv where it worked, go to the video options and set "windowed fullscreen mode" to on, and save configuration. This is what worked for me for it being way off center, maybe it will work for you. Make sure you save configuration and shutdown, wait a bit, unplug, and try it on the tv it wasn't working on.
