### ISSUE TITLE
[Requests] Mame cores from Libretro

### ISSUE THREAD

**Issue by wwark** [libretro/Lakka-LibreELEC#775]
Hi,
Lakka have just these cores enable mame2003-plus mame2010 in options file.

Could you plan to add/enable these cores below ?
https://github.com/libretro/mame
https://github.com/libretro/mame2016-libretro (not present in Lakka)
https://github.com/libretro/mame2015-libretro (named 2014 in lakka side  packages/libretro/mame2014/package.mk/ the git url forward to https://github.com/libretro/mame2015-libretro)
https://github.com/libretro/mame2003-libretro
https://github.com/libretro/mame2000-libretro (for information the git url of "packages/libretro/imame4all/package.mk" forward to mame2000-libretro of libretro so I think we can remove this package because packages/libretro/mame2000-libretro/package.mk already exist in lakka)
 
Thanks in advance,
Wwark

**Comment by natinusala** [comment]
Hey

That's a lot of new core, do you have a game in particular you want to play?

**Comment by wwark** [comment]
Not in my mind just to have the same cores as retroarch.
the core Mame with the last upstream from mame will be good if we need to choose :)
