### ISSUE TITLE
Lakka is slow on NVIDIA Quadro FX 1700

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka-LibreELEC#78]
From facebook:

> Hi, just wanted to let you know in setting up a PC to use with Lakka I tried NVIDIA cards. The first didn't work very well, an NVIDIA Quadro FX 1700 512MB the second worked much better and is an NVIDIA GeForce 6600 512MB. Just wanted to let you know, I don't know much about Linux so am not sure how to update drivers. The Quadro FX card was very slow / flickering etc.

**Comment by gouchi** [comment]
Please provide some Lakka system and graphic [logs](http://www.lakka.tv/doc/Troubleshooting-Lakka/).

It was slow with every core ?

**Comment by Kivutar** [comment]
No reply from the OP, I close this.
