### ISSUE TITLE
Playstation 2 Play! games fail to boot

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#780]
I am currently using nightly build 2019 9/11 for Generic PC x86_64

CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb
SSD 60gb

I've noticed that this has not worked for me for quite a while and with several nightlies as well. The Rom I tested is good since it was working when I had PCSX2 installed.

It would fail to boot and not even the bios would show up. Any configuration I had made prior to had been reseted. I also tried to enable logging for it to troubleshoot it, it ended up crashing so when I re-enabled it I saved the configuration this time so I can have logs for it. When attempting to launch the rom with the PS2 Core Play! it still crashed and failed to log anything. I don't see documentation for PS2 Play! either for it's bios if those are required at all. So far I have dumped these ps2 bios files.

- scph10000.bin   scph10000.MEC   scph39001.bin   scph39001.MEC   scph10000.NVM   scph39001.NVM

Those bios files are spelled exactly as the ones in the folder in case Lakka OS is case-sensitive 
I wish I could also screenshot some of the info within Lakka OS but screenshots are not allowing me to do so.

**Comment by wwark** [comment]
Hi,
For information Play! doesn't required a bios https://www.libretro.com/index.php/play-libretro-core-ready-for-download-on-the-buildbot/
You can try one of the games in the screenshot in this news. The compatibility of play! is not so important as pcsx2
Thanks,
Wwark.

**Comment by ToKe79** [comment]
can you upload some logs?

**Comment by Gitlab1111** [comment]
@ToKe79 The logs are not saving it. I even tried messing with its logging level and same result with logs not being saved. It's as if it crashes Retroarch, so Retroarch doesn't even have the chance to save progress before it's lost. I have seen this happened before with previous versions of Lakka and Retorarch. Any changes that were made prior to crashing ends up being lost.  I do hope there is some documentation for us to better understand and use the logs as well.

I did try it out with 3 different **PS2 Iso's** and one of which I know from prior experience worked when I had **PCSX2** on my system. None of those are working with that **PS2 core.** I do have PS2 **bios** on hand but maybe not properly implemented in my **SSD** drive where my Lakka OS is installed upon.

I do appreciate what you guys are doing for Retro Game emulation.

**Comment by natinusala** [comment]
Do the games work on standalone Play! ?

**Comment by ToKe79** [comment]
@gitlab1111 have you tried obtaining the logs this way?
https://www.lakka.tv/doc/troubleshooting-lakka/

**Comment by Gitlab1111** [comment]
It does not save upon crashing but this is what my current log shows. I did flip it from level 0 debug to info and yet still nothing on PS2 play. The file for it is under retroarch.log. Im not sure how usefull this is but I'll do another attempt before trying out a nightly build.

[INFO] RetroArch 1.7.8 (Git ea7e682253)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
[INFO] Built: Sep 16 2019
[INFO] Version: 1.7.8
[INFO] Git: ea7e682253
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[INFO] [DRM]: Connector 2 connected: yes
[INFO] [DRM]: Connector 2 has 22 modes.
[INFO] [DRM]: Connector 2 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 4: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 5: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 6: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 7: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 8: (1024x768) 1024 x 768, 75 Hz
[INFO] [DRM]: Mode 9: (1024x768) 1024 x 768, 70 Hz
[INFO] [DRM]: Mode 10: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 11: (1440x480i) 1440 x 480, 60 Hz
[INFO] [DRM]: Mode 12: (800x600) 800 x 600, 75 Hz
[INFO] [DRM]: Mode 13: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 14: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 15: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 16: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 17: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 18: (640x480) 640 x 480, 75 Hz
[INFO] [DRM]: Mode 19: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 20: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 21: (720x400) 720 x 400, 70 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x7f5290121ef0.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Desktop .
[INFO] [GL]: Version: 3.0 Mesa 17.1.3.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event4).
[INFO] [udev]: Mouse #0 (/dev/input/event3).
[INFO] [udev]: Mouse #1 (/dev/input/mouse0).
[INFO] [udev]: Plugged pad: Logitech Gamepad F310 (1133:49693) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Autoconf]: 284 profiles found.
[INFO] [Autoconf]: selected configuration: /tmp/joypads/udev/Logitech_Gamepad_F310.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] Found shader "/tmp/shaders/bilinear.glslp"
[INFO] Found shader "/tmp/shaders/nearest.glslp"
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x9e26e0
[INFO] [MIDI]: Initializing ...
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [config] Saved new config to "/storage/.config/retroarch/retroarch.cfg".
[INFO] [config] Saved new config to "/storage/.config/retroarch/retroarch.cfg".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 281, Frames dropped: 0.

**Comment by Gitlab1111** [comment]
So this time I tried nightly build October 12, 2019. It still crashed when booting the  rom iso. 
[retroarch__2019_10_21__02_33_45.txt](https://github.com/libretro/Lakka-LibreELEC/files/3748867/retroarch__2019_10_21__02_33_45.txt)

**Comment by natinusala** [comment]
Did you check if the game was supported by Play! first?

**Comment by Gitlab1111** [comment]
In the Retroarch video on the Playstation 2 Play! core I tried one of the games that they made a video for showing it running and playing. Eternal Ring is one that I tried and failed to work no matter what version of Lakka OS.  I have noticed with the nightly for October 12,2019 that 2 other cores may have been broken as well. PSPPPP seems to have troubles with framerates and lagging now, while gameboy advance SP core doesn't work at all.

**Comment by natinusala** [comment]
Okay, does Eternal Ring work on the Play! core on a desktop OS? Is the issue with the core, or with Lakka?

**Comment by gouchi** [comment]
I can launch the [game](https://github.com/jpd002/Play-Compatibility/issues/819) with buildbot Play! core on my desktop.

So it is our build which is the issue. We may try first to update to [latest commit](https://github.com/libretro/Play-/commits/master) ?

**Comment by Gitlab1111** [comment]
I have revisited this issue and is using the current nightly build of Nov 4, 2009. Issues are still present for this core as it is still not working for me despite adding some bios for it just in case.

[Retroarch PS2.txt](https://github.com/libretro/Lakka-LibreELEC/files/4084182/Retroarch.PS2.txt)

[Lakka OS ps2.txt](https://github.com/libretro/Lakka-LibreELEC/files/4084183/Lakka.OS.ps2.txt)

**Comment by gouchi** [comment]
May you try to make a test with [this build](http://nightly.builds.lakka.tv/PRs/pr_838_000137/Generic.x86_64/).

Thank you.

**Comment by cinnamonmatexfce** [comment]
Same problem here!
i3-4130T (Intel HD4400)
TV output: 1920x1080@120
Video driver: gl
LAKKA: stable
RETROARCH: 1.8.4
Release: PC amd64 x86_64
Installed on HDD

P. S.: can't find an explanation of why in LAKKA there is `Play!` instead of `PCSX2`. Someone could please explain? Thanks! ;)
