### ISSUE TITLE
S905W Wifi (Broadcom BCM4334) not working

### ISSUE THREAD

**Issue by wakawaka99** [libretro/Lakka-LibreELEC#791]
Using nightly build --> Lakka-S905.arm-nightly-2019-09-17.img
Using hardware H96 mini  --> S905W 2gb/16gb Wifi chipset BCM4334

Scan for wifi showing no AP even though router is less than 3 feet away.
Booting android box into default OS, wifi works as usual.

most roms run fine on that nightly build

**Comment by wakawaka99** [comment]
Using stable build -->-S905.arm-2.3.img

same issue

**Comment by Ntemis** [comment]
When the port of s905 started s905w didn't exist. The focus was only given to those boards who had Gbit Ethernet and only.New inferior X/W revisions were left to the individual owner to self supporting his/her device. 
In short we wont break others to fix one board.
Best bet is to wait until 9.2 branch is ready.

**Comment by ToKe79** [comment]
can you test this build?
http://nightly.builds.lakka.tv/PRs/pr_800_000093/S905.arm/
it is based on latest release + some wifi drivers
