### ISSUE TITLE
Banana Pi Lakka 2.1 not loading!

### ISSUE THREAD

**Issue by ilyichzc** [libretro/Lakka-LibreELEC#801]
I tried a lot but It not works. I have clean install after sd card burning, it starts to load and hangs in one place of the boot log always.

**Comment by gouchi** [comment]
Hi,

Is there any reason why you are not using l[atest stable release 2.3.1](https://www.lakka.tv/articles/2019/09/15/lakka-2.3-with-retroarch-1.7.8/) ?
