### ISSUE TITLE
[Feature request] Bluetooth GUI?

### ISSUE THREAD

**Issue by MrGlockenspiel** [libretro/Lakka-LibreELEC#807]
My DualShock 4 controller will not connect via the command line. Is there any chance of a Bluetooth GUI in the near future? I think this would help people with very little command line experience as well.

**Comment by natinusala** [comment]
There is currently a bounty to write such a menu right here : https://www.bountysource.com/issues/75063854-bluetooth-driver-bounty

If you want to encourage a dev to write this feature, you can contribute to the bounty :)
