### ISSUE TITLE
“Lakka v2.3.1” on RP3B isn’t detecting any bluetooth devices

### ISSUE THREAD

**Issue by MisterFloppy** [libretro/Lakka-LibreELEC#808]
- Which version of Lakka are you using?
2.3.1 for RaspberryPie 3B (Lakka-RPi2.arm-2.3.1.img.gz)
- What system hardware are you using?
RaspberryPie 3B
- What did you do?
I'm trying to detect bluetooth devices under "SSH" with command line operations.
- What did you expect to happen?
Get a list of BT devices nearby.
- What happened instead?
"Lakka" isn’t detecting any bluetooth devices.

Hi folks,

"Lakka v2.3.1" running on my RP3B isn't detecting any bluetooth devices when using its onboard bluetooth!

I've tested my RP3B's hardware, it's working fine, when using "LibreELEC" on it, all bluetooth devices (e. g. my and the wives' smartphones) nearby are immediately detected!

When running "Lakka v2.3.1." on another kind of hardware, for example a S905 box ("Wetek Play 2"), all bluetooth devices nearby are immediately detected, too, so obviously it's only the version for RP3B that has the problem mentioned above...

Here's a session log according to the instructions for testing bluetooth functionality given at https://www.lakka.tv/doc/wireless-dualshock/ :

###########################################

 Lakka - The DIY retro emulation console 

###########################################

Lakka (official): 2.3.1 (RPi2.arm)

Lakka:~ # touch /storage/.cache/services/bluez.conf

Lakka:~ # systemctl enable bluetooth

Lakka:~ # systemctl start bluetooth

Lakka:~ # systemctl status bluetooth

● bluetooth.service - Bluetooth service

Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)

Active: active (running) since Tue 2019-09-24 11:03:44 CEST; 6h ago

Main PID: 518 (bluetoothd)

Status: "Running"

CGroup: /system.slice/bluetooth.service

        └─518 /usr/lib/bluetooth/bluetoothd

		Sep 24 11:03:44 Lakka systemd[1]: Started Bluetooth service.

		Sep 24 11:03:44 Lakka bluetoothd[518]: Bluetooth daemon 5.47

		Sep 24 11:03:44 Lakka bluetoothd[518]: Starting SDP server

		Sep 24 11:03:44 Lakka bluetoothd[518]: kernel lacks bnep-protocol support

		Sep 24 11:03:44 Lakka bluetoothd[518]: System does not support network plugin

		Sep 24 11:03:44 Lakka bluetoothd[518]: Bluetooth management interface 1.14 initialized
		Sep 24 11:03:45 Lakka bluetoothd[518]: Failed to set privacy: Rejected (0x0b)

Lakka:~ # bluetoothctl   
                
[NEW] Controller B8:27:EB:2C:FE:B4 %h [default]

Agent registered

[bluetooth]# agent on

Agent is already registered

[bluetooth]# default-agent

Default agent request successful

bluetooth]# power on

Changing power on succeeded

bluetooth]# discoverable on

Changing discoverable on succeeded

bluetooth]# pairable on

Changing pairable on succeeded

bluetooth]# scan on

Discovery started

[CHG] Controller B8:27:EB:2C:FE:B4 Discovering: yes

[bluetooth]#

After that, nothing happens anymore - compared to the session log when testing the same as mentioned above on this RP3B model under "LibreELEC" (where right after the scanning start my BT enabled smartphone is detected immediately), the only differences are that there under "LibreELEC" Bluetooth daemon 5.50 is installed and instead of "Failed to set privacy: Rejected (0x0b)" it says "Endpoint registered: sender=:1.2 path=/MediaEndpoint/A2DPSource" and "Endpoint registered: sender=:1.2 path=/MediaEndpoint/A2DPSink".

I don't know if it is related to v5.50 of Bluetooth daemon.. is it possible to force a manual update of it? Or how could I get rid of the "Failed to set privacy: Rejected (0x0b)"?

So - could you please look into this and/or give me further instructions?

**Comment by andreabellitto** [comment]
This command fixed the issue for me on RPI4:

`echo 1 > /sys/module/bluetooth/parameters/disable_ertm`
