### ISSUE TITLE
Add VitaQuakeII and VitaQuakeIII once it's done

### ISSUE THREAD

**Issue by natinusala** [libretro/Lakka-LibreELEC#825]
- https://github.com/libretro/vitaquake2
- https://github.com/libretro/vitaquake3

The cores will only work with OpenGL and not OpenGL ES for now.

**Comment by gouchi** [comment]
- Also I tested on Linux [dhewm3 libretro core](https://github.com/libretro/dhewm3-libretro) and it works fine.
