### ISSUE TITLE
Dreamcast Playlist error, m3u files

### ISSUE THREAD

**Issue by JuakinBM** [libretro/Lakka-LibreELEC#828]
Lakka version: 2.3
System: Raspberry Pi 4B, 4GB

Hello, first of all I want to thank you for your amazing work with Lakka.

I've made a Maual Playlist with *.m3u files that point to *.chd files for mi Dreamcast games.
In example, Shenmue has four disc and I think this is the optimal way to load all them and change them on the fly.

The problem comes when I try to load a game from the Playlist, It says it can not find the core, and then gives you a list of cores to select (same behavior if you select "reset core association"), this would be perfect if it listed ALL cores, but only some cores are listed and "Flycast" is NOT one of them, a list with all cores would be great and I think will solve this issue.

Thanks in advance.

**Comment by natinusala** [comment]
This commit https://github.com/libretro/libretro-super/commit/9f5cccadf5828f864952983cfbc0af497f5f5fe7

Adds m3u support for Flycast - the next Lakka update will have this fixed. In the meantime you can download the file here https://github.com/libretro/libretro-super/raw/master/dist/info/flycast_libretro.info and put it in /storage/cores
