### ISSUE TITLE
Reset configuration doesn't work and makes Lakka crash

### ISSUE THREAD

**Issue by JuakinBM** [libretro/Lakka-LibreELEC#829]
Lakka version: 2.3
System: Raspberry Pi 4B, 4GB

Hi!, Like the title says, if you use the option "Configuration File" -> "Reset to Defaults" lakka crashes and I've got to power off my Pi4 because doesn't recover from the error, also the configuration stays the same, so the option it's not working.

Thank you.

**Comment by natinusala** [comment]
Resetting the configuration in RetroArch is a really bad idea when running Lakka, I will see to have this option hidden
