### ISSUE TITLE
Orange Pi - Bluetooth pairings lost after reboot

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/Lakka-LibreELEC#83]
- Which version of Lakka are you using?
Lakka-H3.opilite.arm-8.0-devel-20170305054450-r25834-g76ebcbd
- What system hardware are you using?
Orange Pi Lite. Also reproducible on Orange Pi PC.
- What did you do?
Pair, Connect, and Trust bluetooth gamepad.
Controller works fine for that session.
After restarting the system the pairing is lost, and the controller will not connect.
```
[bluetooth]# info F0:65:DD:BF:48:2A
Device F0:65:DD:BF:48:2A
        Name: Razer Serval
        Alias: Razer Serval
        Class: 0x002508
        Icon: input-gaming
        Paired: no
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Human Interface Device... (00001124-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1532p0900d3A16
```

- What did you expect to happen?
The pairing should have been retained across reboots.
This functionality is working on the OpenELEC fork on other hardware (ODROID).

**Comment by hooby3dfx** [comment]
@Kivutar this is still reproducible in RC4 and also on Raspberry Pi (reported by @travisghansen ).
Is there any other info I can provide?
Seems like a major issue.

**Comment by Kivutar** [comment]
I just tested on RPi3 RC4 with an official DualShock 3. It autopairs fine then is able to reconnect after a reboot. I'm going to test on OPiPC now.

**Comment by Ntemis** [comment]
Looks like Orange Pi Lite doesn't have onboard bluetooth @hooby3dfx

**Comment by hooby3dfx** [comment]
Yes, I have been using a USB bluetooth adapter... (Which works fine on
odroid / stable Lakka)

**Comment by Ntemis** [comment]
So issue is fixed?

**Comment by hooby3dfx** [comment]
No, the problem is that in RC4 after reboot all pairings are lost.

**Comment by Ntemis** [comment]
you face this issue only with orange pi soc?

**Comment by Kivutar** [comment]
He also has this error on RPi.

**Comment by hooby3dfx** [comment]
@travisghansen are you able to consistently reproduce this on your RPi3 & Ouya controller?

I have been trying to figure out exactly when this happens and it seems inconsistent.

It does seem to consistently occur with the Ouya controller though. I also have a pretty high quality Razer controller that after pairing tonight seems to be retaining its pairing after many reboots and power cycles.

**Comment by travisghansen** [comment]
Out for a few days but will review when I get back early next week.

**Comment by Kivutar** [comment]
I could reproduce the problem on RPi3 with my 8Bitdo NES30 Pro.

After receiving these two messages, I was able to reconnect using bluetoothctl:

```
[CHG] Device 69:01:3C:D3:67:00 LegacyPairing: yes
[CHG] Device 69:01:3C:D3:67:00 RSSI: -56
```

**Comment by hooby3dfx** [comment]
My Razer controller pairing remains resilient.

I have another controller though ("GEN GAME S3") that is doing the same thing as the Ouya. 

One other thing to note is that for both of these controllers, not just the reboot results in not being able to reconnect - even if you just disconnect it from bluetoothctl, it will not successfully reconnect.

**Comment by hooby3dfx** [comment]
Breakthrough/face-palm!
I reviewed the instructions here http://www.lakka.tv/doc/8Bitdo-Wireless-Controller/
and found that the pairings seem to stick much better when these commands are run pre-pairing (and possibly every boot):
```
agent on
default-agent
discoverable on
pairable on
```

I was only doing:
```
scan on
pair
connect
trust
```

Will update once confirmed.

**Comment by R3d-Sky** [comment]
I followed the whole set of instructions, pairing still does not stick with my NVidia Shield (2017) Controller and RPi3. Pairing on the controller does stick with my Shield Android TV when paired to it, though.

**Comment by Kivutar** [comment]
Same here, I was doing the agent stuff before paring, and I still have some controllers that don't reconnect.

**Comment by hooby3dfx** [comment]
I have been messing around with this quite a bit and found that
1. the timing which pairing and connecting is done in for the first time seems to matter.
2. sometimes you will actually have a good pairing that sticks, but the controller will fail to reconnect on the first or second try - but then will connect.

There is some black magic. I think it would be good to look at the files that bluez is using internally to store pairings, or watch its debug logs to get a deeper understanding.

However, I have been able to now automate the pairing process pretty well in a script that results in sticky pairings on all of my controllers (Razer, Ouya, and Gen Game).
https://github.com/hooby3dfx/lakka-addons/blob/master/btautopair.sh

**Comment by Kivutar** [comment]
Interesting script. I was thinking that it was impossible to automate pairing because of the agent stuff. I was not aware of *empty*. I need to study this and integrate it in RA.

**Comment by hooby3dfx** [comment]
Great - it would be awesome to integrate via a GUI option so that you can choose "Pair Bluetooth controller" and then the GUI waits until one controller pairs, or the script times out (ex 30 seconds).

**Comment by luksireiku** [comment]
I have the same bug with Raspberry Pi 3 and 8Bitdo Zero controller, I get some error messages like `Can't get HIDP connection info` with `systemctl status bluetooth`, I can post the exact messages when I go home later.

**Comment by Kivutar** [comment]
We're working on a new Allwinner unified image, with mainline kernel. It may fix this issue if we success.

**Comment by alexandertreutel-spec** [comment]
FIX FOR ME:
Remove the --bd_addr_rand flag from bt settings
sudo sed -i 's/--bd_addr_rand//g' /usr/lib/systemd/system/ap6256s-bluetooth.service

Problem was the bt address was asigned randomly each start so paired devices got lost. have a nice day

**Comment by Ntemis** [comment]
Check if you got a valid bt address without the hack and then you can celebrate
