### ISSUE TITLE
Settings Directory default paths are set incorrectly

### ISSUE THREAD

**Issue by JuakinBM** [libretro/Lakka-LibreELEC#830]
Lakka version: 2.3
System: Raspberry Pi 4B, 4GB

Hi!, If you mess up with paths in Lakka and try to set them to default using the "Start" button, default paths stablished are incorrect.
In example, if you press start in assets folders it sets it to "/storage/.config/assets/" (or something like that) which is incorrect (I think correct path is something like "/tmp/assets") because assets are not located there and when you restart Lakka it would be a total mess (doesn't load icons or fonts). This also happens with the rest of the folders.

Thanks.

**Comment by natinusala** [comment]
Same as the reset config entry, this is a bad idea to use it. I will have it removed as well, thanks for reporting!
