### ISSUE TITLE
Option Save Core Overrides doesn't appear in quick menu

### ISSUE THREAD

**Issue by JuakinBM** [libretro/Lakka-LibreELEC#831]
Lakka version: 2.3
System: Raspberry Pi 4B, 4GB

Hi!, when you load a core, open quick menu and try to save pesonalizations made, the option "Save Cores Overrides" is not showing, I think you can work around this by using the option "Save new configuration" in the main menu, but it is a pain, having the option in the quick menu is way easier.
Standalone retroarch (Win10 x64) does include this option and is way more confortable.

Thanks.

**Comment by ToKe79** [comment]
by default this option is hidden:
https://github.com/libretro/Lakka-LibreELEC/blob/a915a2a3930b7cc1604359f22216b134937619d8/packages/libretro/retroarch/package.mk#L144
many such features are hidden by default in Lakka, but can be manually changed via settings menu (for some one needs to enable advanced settings). the reason many options are hidden is to make RetroArch for non-initiated more clutter free.
