### ISSUE TITLE
Audio Settings Don't Save

### ISSUE THREAD

**Issue by MetaNite64** [libretro/Lakka-LibreELEC#832]
If Lakka and Retroarch versions are the same, I'm running 1.7.8., and I'll edit if the update changes anything. I'm on the Raspberry Pi 3 B+. I have it plugged into hdmi-to-vga, and used `amixer cset numid=3 1` to get audio out of the headphone jack. Every time I reboot, as I am using it as my main computer in addition to Lakka, I have to ssh back in and rerun the amixer command. It would be really hard to test on the nightly build, as I don't have another computer to install it on. It's a minor annoyance, but I would like it fixed.

**Comment by RobLoach** [comment]
Steps to reproduce? I'm having a difficult time parsing reproduce steps.
