### ISSUE TITLE
Sonic Adventure Track clipping

### ISSUE THREAD

**Issue by Mikau28** [libretro/Lakka-LibreELEC#834]
This issue tracker is NOT for help or support. Please use the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general) or IRC @ #lakka on freenode.net for those kinds of posts.

BEFORE you report a bug make sure you have tried the latest nightly version of Lakka at http://le.builds.lakka.tv/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
2.3.1
- What system hardware are you using?
Optiplex 3010 Core i5 intel HD 4000
- What did you do?
Playing Sonic adventure using flycast 652e1af1 Sonic falls off the "automated" running track segments. 
- What did you expect to happen?
Pushing forward to keep going he should complete the loop
- What happened instead?
Windy Valley is unplayable as he falls off the track in the loops.

I will get logs, but technically the game continues to play, he wont stay on the track. This issue was fixed on Windows 10 previously. https://github.com/reicast/reicast-emulator/issues/1489

**Comment by natinusala** [comment]
Can you make an issue on the libretro flycast repository?
