### ISSUE TITLE
Flycast black screen with sound

### ISSUE THREAD

**Issue by Mikau28** [libretro/Lakka-LibreELEC#842]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
2.3 nightly
- What system hardware are you using?
Generic x86_x64
- What did you do?
Launch flycast
- What did you expect to happen?
The game would display video
- What happened instead?
Sound plays as the game is running but it’s a black screen. Tried different games and different time.

**Comment by gouchi** [comment]
Please provide some [logs](https://www.lakka.tv/doc/troubleshooting-lakka/#introduction-to-lakka-logs).

Thank you.

**Comment by Mikau28** [comment]
> Please provide some [logs](https://www.lakka.tv/doc/troubleshooting-lakka/#introduction-to-lakka-logs).
> 
> Thank you.

https://paste.ubuntu.com/p/4YRbx4h5W6/

**Comment by natinusala** [comment]
What is your GPU? What GL version does it support?

**Comment by Mikau28** [comment]
> What is your GPU? What GL version does it support?

Intel HD Graphics 2500
OGL 4.0
Alpha sorting is per triangle.

**Comment by Mikau28** [comment]
Bought a Lenovo tiny with a 4th gen i5. Flycast runs flawless, might not be a concern for older hardware?

**Comment by gouchi** [comment]
Do you reproduce also the issue with [Lakka from LE9.2](http://nightly.builds.lakka.tv/Lakka-LE9.2/latest/Generic.x86_64/) ?
