### ISSUE TITLE
Framecounter/stadistics overlay shows N/A

### ISSUE THREAD

**Issue by Xzesstool** [libretro/Lakka-LibreELEC#844]
Some bugs I have found:
- Framerate counter overlay shows N/A instead of the framerate, and stadistics ram etc... are not shown.
- When selecting "download content" from "Online updater" menú, the meny goes crazy.
- I don't know if it is a bug, but I cannot scan roms from MAME, it blocks on random roms, I also slipted roms in folders of 1000, but again in a random rom it gets stuck. Snes, megadrive scan works perfect even with +5000 rom in a folder.

This is with S805 build in a generic TV box. Rom used is MXQ one.

**Comment by natinusala** [comment]
> Framerate counter overlay shows N/A instead of the framerate

Is this solved if you disable threaded video?

> When selecting "download content" from "Online updater" menú, the meny goes crazy.

Crazy in what way?

> I don't know if it is a bug, but I cannot scan roms from MAME, it blocks on random roms

Blocks?

**Comment by ToKe79** [comment]
I think I had similar issue in the past, when the folder contained .chd files iirc. I solved it by moving temporarily the .chd files to different (parent) folder and then added them back after the scan of that folder was complete.

**Comment by natinusala** [comment]
Isn't scanning done on a separate thread though? It shouldn't block even with heavy CHDs to decompress

**Comment by Xzesstool** [comment]
> > Framerate counter overlay shows N/A instead of the framerate
> 
> Is this solved if you disable threaded video?
> 
> > When selecting "download content" from "Online updater" menú, the meny goes crazy.
> 
> Crazy in what way?
> 
> > I don't know if it is a bug, but I cannot scan roms from MAME, it blocks on random roms
> 
> Blocks?

Thanks for the replys to all.

- Yes, with threaded video off FPS counter works, but now i realize that vsync doesn't work at least in that mode, frames keep going up and down.

- Rom scanning solved by moving chd files to another folder

- I went to take a photo on crazy menú in "download content" and it was okey now maybe was a server fault when searching for content.
