### ISSUE TITLE
Lakka won't boot up

### ISSUE THREAD

**Issue by MarkussLV** [libretro/Lakka-LibreELEC#848]
Hello!
I have a problem with Lakka. I just downloaded and flashed lakka on a 16gb usb drive. When I try to boot in live mode it shows for a second the home screen but black and it shows lakka logo and it is doing repeatedly. I read few posts from other people and I think maybe it is a fault with my gpu because it's too old. P.s sorry for my bad English.
Computer specs:
Dell optiplex 755
Cpu: Intel core 2 duo e6550 2.33Ghz
Ram: A single DDR2 2GB stick😆
GPU: Intel q35 express chipset (Intel GMA 3100)😂
I didn't try other builds because I didn't have time for it. As for the log, I can't use ssh because i can't boot up lakka. I used textmode with a command, I remember none of them, and used a command to generate a system log file. It successfully generated the log, but i couldn't save it. I used commands which would save but without success.
I don't have a picture, but I do remember some of the lines:

failed to create rendering backend: stb-unicode

Segmentation fault (core dumped)

/home/natinusala/release/Lakka-LibreELEC/build.Lakka-Generic.i386/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: no such file or directory

Sorry that I couldn't provide with log files, because I didn't had limited time for fixing the problem.

**Comment by gouchi** [comment]
Try to [edit retroarch.cfg](https://www.lakka.tv/doc/configuring-lakka/) with [those values](https://www.lakka.tv/doc/faq/#menu-xmb-is-too-slow).

If it is not working even with rgui menu driver, your gpu is too old unfortunately.
