### ISSUE TITLE
[Question] RetroArch Nightly Cores

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka-LibreELEC#854]
Currently using: Lakka 2.3.1 and Lakka-LE9.2 on Pi0.
In the past, it was possible to add/update cores from RetroArch nightly (ex. http://raw.libretro.com/nightly/linux/armhf/latest/mame2003_plus_libretro.so.zip). 
This doesn't work anymore, and leads to a core dump whenever the new core is loaded.

What's the difference (Kernel, LIBC)? Can this be fixed?

Thanks.

**Comment by natinusala** [comment]
Using the prebuilt cores isn't supported (and shouldn't be done on Linux anyway). If you want to fix this you're on your own, sorry
