### ISSUE TITLE
[Request] ScummVM core update

### ISSUE THREAD

**Issue by lordgiotto** [libretro/Lakka-LibreELEC#855]
Hi,
I'm not completely sure here is the right place to post this request. If not, I'm sorry :)
Btw, few months ago ScummVM 2.1.0 has been released: are you planning to update ScummVM core to that version in one of the next releases?

Cheers!

**Comment by RobLoach** [comment]
https://github.com/libretro/Lakka-LibreELEC/pull/838/files#diff-ef67d38ca3c1394c3160831431b0d01d

**Comment by RobLoach** [comment]
The PR to update it is over at https://github.com/libretro/Lakka-LibreELEC/pull/838 .... Still needs build fixes and testing.
