### ISSUE TITLE
PrBoom Textures

### ISSUE THREAD

**Issue by MicrosoftTakeover** [libretro/Lakka-LibreELEC#856]
- Which version of Lakka are you using?
Lakka-RPi.arm-2.3.1.img
- What system hardware are you using?
Raspberry Pi Model B
- What happened?
When playing DOOM 1 and 2 using PrBoom, the floor texture is oddly rotating depending on the perspective of the player camera.

**Comment by Ntemis** [comment]
https://github.com/libretro/libretro-prboom/issues
