### ISSUE TITLE
[Feature Request] Button to delete core settings

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#862]
It would be very convenient to have a button to delete core preferences. Sometimes I try to scale up settings and the core does not load anymore. Thus I can also not change the settings and I have to use SSH or Samba to delete the necessary lines in retroarch/retroarch-core-options.cfg.

Best practice would be to delete only the settings from a specific core, of course. Should be easy to implement!

**Comment by natinusala** [comment]
This would be a RetroArch feature, can you fill an issue there? Thanks

**Comment by coldspark29** [comment]
Will do
