### ISSUE TITLE
BGM sound laggy with NOOBS on RPi4

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#865]
- Which version of Lakka are you using? 
Lakka 2.3.1

- What system hardware are you using? 
RPi4

- What did you do? 
Nothing

- What did you expect to happen? 
The sound to be normal

- What happened instead? 
It was laggy

**Comment by natinusala** [comment]
Menu sounds are not supported at the moment, please don't use them

**Comment by coldspark29** [comment]
Alright. Pity though, since the music is very soothing :)

**Comment by natinusala** [comment]
Yeah the composer did a great job with the sounds
