### ISSUE TITLE
[Feature Request] Ability to set latency settings per core

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#867]
For some cores, lilke N64 and Dreamcast GPU/CPU Hard Sync makes the game not boot. On some PSP games it seems to improve the synchronicity a lot. Therefore this settings should be different for some cores.

**Comment by natinusala** [comment]
This is a RetroArch feature, could you fill an issue there? Thanks

**Comment by coldspark29** [comment]
Will do
