### ISSUE TITLE
[Feature Request] Set Analog Stick sensitivity per core

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#868]
For the Dual Shock 3 on N64 and Dreamcast the best sensitivity seems to be 0.8 and for PSP 1.1 to 1.2. It is annoying to always set this again, when switching cores.

**Comment by natinusala** [comment]
This would be a RetroArch feature, can you fill an issue there?

**Comment by coldspark29** [comment]
Will do
