### ISSUE TITLE
PPSSPP core crashing  Generic PC Nightly

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#875]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb
SSD 60gb

I noticed for **Metal Slug XX** for PSP that it crashes sometimes upon mission completions and will crash if going to the Retroarch menu at times as well. Can someone clarify that PPSSPP **assets** help with better performance because before I never had that added to the Retroarch system PPSSPP folder before running any PSP games in the past.

Another Issue is that movie clips durring BlazBlue PSP games would get to the point of having a black screen and the Retroarch/Lakka would then be rendered inoperative. I noticed another game has the same issue with movie clips, the movies are lagging as well. Proceeding to press the hotkeys to exit the game did not work when trying to close the content, I end up having to restart the computer. 

The past nightly versions also showed **missing assets** from games. I also had this issue with another game when using a **higher resolution**.

[Retroarch log](https://github.com/libretro/Lakka-LibreELEC/files/4083980/Retroarch.log)

[Retroarch log 2.txt](https://github.com/libretro/Lakka-LibreELEC/files/4083987/Retroarch.log.2.txt)

**Comment by Gitlab1111** [comment]
Not sure if its a Rom issue but there was also some graphical errors as well.
![2166 - BlazBlue - Calamity Trigger Portable (USA) (En,Ja,Zh,Ko)-200118-101357](https://user-images.githubusercontent.com/41243135/72691391-d8edd180-3ad9-11ea-99d1-1fa6a56c87bc.png)
![2629 - BlazBlue - Continuum Shift II (Asia) (En,Ja,Zh,Ko) (v1 01)-200118-105040](https://user-images.githubusercontent.com/41243135/72691393-da1efe80-3ad9-11ea-9f13-fb593492fcf2.png)

**Comment by gouchi** [comment]
May you try to make a test with [this build](http://nightly.builds.lakka.tv/PRs/pr_838_000137/Generic.x86_64/).

Thank you.

**Comment by Gitlab1111** [comment]
build /PRs/pr_838_000137/Generic.x86_64

Even with that build mention I still get the black screen which freezes retroarch/lakka and the movie clips like the one in the intro's still lag almost entirely before freezing and requiring to restart the who desktop pc.

**Comment by Gitlab1111** [comment]
Still crashing when movie clips end on PSP even when using a different build. It crashed and didn't leave me any logs for it on the nightly Generic PC build of 1/24/2020.

**Comment by emersonnovais** [comment]
I had this issues with "Metal Slug XX" and "Space Invaders Xtreme" in Ubuntu x64 since the 18.04 version.

**Comment by gouchi** [comment]
May  you try to make a test with [this image.](https://nightly.builds.lakka.tv/members/gouchi/ra-1.8.7/Lakka-Generic.x86_64-2.9-devel-20200525183638-43653b3.img.gz)

Thank you.

**Comment by gouchi** [comment]
Hi @emersonnovais,

Please try to make a test now with this [nightly build image.](https://nightly.builds.lakka.tv/2020-08-10/Generic.x86_64/Lakka-Generic.x86_64-3.0-devel-20200810061340-46502e1.img.gz)

Thank you.

**Comment by emersonnovais** [comment]
Thanks, @gouchi. Since the last update before the annoying cracker sabotaged your repositories, they crashed any time. I will test now and give an feedback. Thank you so much. ; )
