### ISSUE TITLE
What are the standard settings for the gpu_memory section in config.txt?

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#879]
I know this is not really an issue in the right sense, but I did not know where else to ask for it.

Since I have a 4GB RPi4, I tried to increase the GPU memory, but the performance got worse. I just read that the GPU memory is only used for video decoding and the VPU uses its own memory handler, which uses the memory not used by the GPU. So increasing GPU memory means less memory for the VPU. Unfortunately I did not write down the standard settings and can also not find any info on it on the internet, so can you please tell me the values for

gpu_mem=
gpu_mem_256=
gpu_mem_512=
gpu_mem_1024=

I think this will also be interesting to other users and should maybe be documented on lakka.tv

**Comment by ToKe79** [comment]
the default values can be found here, for example:
https://github.com/libretro/Lakka-LibreELEC/blob/bf8721be07755a8ab653a9b0941d6844651f9014/packages/tools/bcm2835-bootloader/files/3rdparty/bootloader/config.txt#L25-L31

More on `gpu_mem`: https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md

**Comment by coldspark29** [comment]
Thanks a lot! I already searched, but it was dug too deep, I guess
