### ISSUE TITLE
Wrong screen scaling for N64 on 2.3.2 and RPi4

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#883]
For some games, e.g. Conker's Bad Fur Day, the scaling is wrong. For others, e.g. Mario Kart 64, it works fine. I've had zero issues on 2.3.1. I can set the overscan to match, but then it is wrong in the games, that work fine.

**Comment by natinusala** [comment]
This is likely a new issue on mupen64plus_next, can you fill an issue on the mupen repo please? You'll probably need to give more details like what the exact core options you are using

**Comment by coldspark29** [comment]
Will do. Thanks!




On Thu, Jan 23, 2020 at 10:20 AM +0100, "Nathan S." <notifications@github.com> wrote:












This is likely a new issue on mupen64plus_next, can you fill an issue on the mupen repo please? You'll probably need to give more details like what the exact core options you are using

**Comment by coldspark29** [comment]
I also have seen this issue now on Flycast. It occurs for MupenPlus and MupenPlusNext. I believe that this is a Lakka issue and would be really glad if it would be resolved before the release of Lakka 3.0
