### ISSUE TITLE
Feature Request : Lakka menu screenshots

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#886]
There have been times when I needed to explain or show something on Lakka OS where a screenshot of the **menu** would have been helpful. The current screenshot feature only works within **cores** for screenshots of games only.

**Comment by natinusala** [comment]
Yes that is a known limitation of RetroArch. Can you fill an issue there please?

**Comment by Gitlab1111** [comment]
Yes I post the feature request there. Does that mean this is now closed?

**Comment by natinusala** [comment]
No I will close it once it's implemented in RA and we update it in Lakka, thanks
