### ISSUE TITLE
Logging / Report logs issue

### ISSUE THREAD

**Issue by ghost** [libretro/Lakka-LibreELEC#887]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb
SSD

It not limited to Generic PC lakka builds but also I have experienced this on the Raspberry Pi 4 B is that logs do not work correctly when setting **logging levels**.  In trying to trim the fat on emulation errors the settings of levels do not work at all and the only way I have gotten logs to actually log and work is by changing settings to create new **logs**, then setting both level settings to **Debug 0**.  

When I had it to just logging the Retroarch single log without creating new log files it ends up not working correctly. Especially when Lakka OS crashes the logs don't get recorded. This issue has been going on for months as well. 

Neither stable or nighties work just to clarify. I needed it to show what went wrong with the PSP emulation I have been having troubles with. Will update when I can since I see a new nightly available already for 1/24/2020.

**Comment by natinusala** [comment]
The preferred (and only reliable way) of getting logs is to run RA manually from command line with the `--verbose` option and redirect the output to a file. This way the file won't be deleted if RA crashes (since the terminal writes it).
