### ISSUE TITLE
Lakka stuck on flower after update 

### ISSUE THREAD

**Issue by Tatespi** [libretro/Lakka-LibreELEC#895]
Hi guys, just updated lakka and suddenly getting flower screen not a clue why, im using an msi dc windbox which has been running psp and ps1 games full speed

**Comment by natinusala** [comment]
It's most probably a RetroArch crash caused by your settings, can you backup then reset (= delete) your RetroArch config?

**Comment by gouchi** [comment]
You can try this [documentation](http://lakka.tv/doc/Upgrading-Lakka/#purging-your-retroarchcfg) to do so.

**Comment by gouchi** [comment]
@Tatespi Any news ?
