### ISSUE TITLE
Raspberry Pi 4 directory save bug

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#900]
When changing the directory to save to the USB the Saves and Savestates will forget when you do a reboot and you have to set it again when booting into Lakka. Using 2020-01-24 build.

**Comment by ToKe79** [comment]
can you try following as workaround if this works:
Change the setting you want. Instead of "Shutdown" select "Restart RetroArch" from the "Lakka" menu. It should then quit and start again. Let me know if the setting was preserved.

**Comment by Cibomatto2002** [comment]
It was not preserved. It shows Content dir. 
![20200217_135820](https://user-images.githubusercontent.com/21169038/74683318-24090c00-518e-11ea-86f8-1e6f38775e00.jpg)

**Comment by ekx** [comment]
Also happens to me on x86_64 on a Lenovo m93p tiny. Additionally it will not be set to default on reboot, instead it will be set to "<content directory>"

**Comment by Cibomatto2002** [comment]
Just downloaded 2020-07-19/RPi4.arm nightly the bug is still there.

**Comment by Ntemis** [comment]
@Cibomatto2002 can you try https://nightly.builds.lakka.tv/2020-08-20/RPi4.arm/Lakka-RPi4.arm-3.0-devel-20200820023653-59d5c4b.img.gz please

**Comment by Cibomatto2002** [comment]
Still not saving to my usb 
![1](https://user-images.githubusercontent.com/21169038/90848367-514b9800-e332-11ea-82ea-0e6d2cf67102.jpg)

**Comment by Cibomatto2002** [comment]
Tried the Aug 23 build bug still there.

**Comment by Cibomatto2002** [comment]
tried it with another usb stick and now it works :)
