### ISSUE TITLE
Joystick problem Lakka Rpi4

### ISSUE THREAD

**Issue by Iniard** [libretro/Lakka-LibreELEC#901]
Hello! I did not find such a branch, I write here. The problem is this: I am using Raspberry Pi 4 to create a retro console. Everything is fine, but when emulating PSP games, my USB joystick does not work correctly. I tried the game Daxter, the legend of the tomb raider. In these games, when you press the cross, the function appears - to look around, and not move forward. How can i fix this?
I also share this problem: the Wall-e game forces Lakka to reboot after the first video. My joystick - CBR CBG 915 - https://beru.ru/product/geimpad-cbr-cbg-915-belyi/11593871?utm_source=market&utm_medium=cpc&utm_content=91117&clid=698

**Comment by RobLoach** [comment]
It's possible the autoconfig is not defined:
https://github.com/libretro/retroarch-joypad-autoconfig

You could try exporting the config and pushing it forwards.
