### ISSUE TITLE
mGBA  jerky rewind sometimes.

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/Lakka-LibreELEC#909]
RPi2.RPi4.arm-2.3.2.img

Pie 4

If I press rewind on some GBA games it will struggle to rewind this is the game I found the rewind problem on  Final Fight One (USA). There are other GBA game that do it to. just start playing the game then press rewind you will see it having trouble rewinding it's like it almost can't do it. I did not try gameboy games or gameboy color games. this does not happen on retroarch.

Here is a video I made to explane it better.

https://www.youtube.com/watch?v=iLS_7IHEwRc

**Comment by RobLoach** [comment]
Rewind is pretty CPU intensive, since it saves and loads every frame. I've seen this happen on my raspberry pis too. Surprised you got it to work at all :wink:

**Comment by Cibomatto2002** [comment]
Do I need to close this then? I noticed the Mesen (NES Emulator) can barley run on Pie 4 and the rewind works correct even on the snes9x 1.60 it works. That's why I thought it was a bug in mGBA because those emulators it would work.
