### ISSUE TITLE
5ghz wifi does not work in Lakka, works in Raspbian

### ISSUE THREAD

**Issue by Pxtl** [libretro/Lakka-LibreELEC#911]
Using Lakka 2.3.2, on Raspberry Pi 4 2GB running the latest firmware.  Also existed on a seperate Pi42GB I have using Lakka 2.3.1.

Use the Wifi menu, both of my networks (we'll call them MyWifi and MyWifi-5) are visible.  If I connect to MyWifi, it works, and shows a "connected" indicator on the menu.  If I connect to MyWifi-5, it does not appear to connect - operations that would communicate with a server fail, and I cannot see my Pi4 on my lan, but the Wifi menu does not show any error message, it just fails silently.

It looks like this is a known issue in LibreElec.

https://forum.libreelec.tv/thread/20578-fresh-install-raspberry-pi-4-5ghz-wifi-not-working/

So it may go away when move to latest LibreElec.  Maybe.  I don't really understand the resolution they posted in that thread.

**Comment by natinusala** [comment]
That fix is a command you can run on your RPi (using SSH)
