### ISSUE TITLE
Steam controller wrong vid:pid and no input

### ISSUE THREAD

**Issue by RucajDenisa** [libretro/Lakka-LibreELEC#916]
As reported [elsewhere](https://www.reddit.com/r/Lakka/comments/e80gan/steam_controller_on_lakka/), some steam controllers have different vid:pid than the ones stated in the shipped controller cfg [file](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/sdl2/Steam%20Controller.cfg). Indeed a more accurate vid:pid is present in that file and commented out. 

For this or some other reason, my steam controller isn't working -- the light on the device indicates its connected to the dongle, but controller input has no effect on lakka.

I can't update the cfg file to change the ids because it's read only (via ssh), and the files seem to be inaccessible when the partitions are mounted on another pc.

- Which version of Lakka are you using?
Build date Jan 2020. Git ...601a56
- What system hardware are you using?
Rpi 4
- What did you do?
Plugged in steam controller. Added a joypad config file to /Joypads with updated vid and pid. Tried changing controller config options via ui menus.
- What did you expect to happen?
Controller input would affect lakka menu navigation or be detecred as mappable input.
- What happened instead?
Nothing.

**Comment by 2m** [comment]
Hey. I had the same problem. It turns out that Steam controller is only supported on the nightly builds of the upcoming Lakka 3. I installed a build from https://nightly.builds.lakka.tv/Lakka-LE9.2/latest/ and my Steam Wireless controller works!

Before I tried v2.3.2 and it did not work.
