### ISSUE TITLE
Some games wouldn't run after company logos on PPSSPP

### ISSUE THREAD

**Issue by iokzero** [libretro/Lakka-LibreELEC#919]
All version of Lakka scines 2.3 + (including Lakka 3.0 Nightly)
Running on Intel i7 NUC7i7BNH NUC - CPU i7 7567U W/ intel iris plus 650 iGPU

Running PPSSPP, for games like Castlevania, the game just stop after the intro company logo shows up.

All version of Lakka with PPSSPP before Lakka 2.3 is fine

I post the bug here sense the issues report for PPSSPP under Libretro is not longer there.

**Comment by Ntemis** [comment]
try this image
https://nightly.builds.lakka.tv/2020-08-10/Generic.x86_64/

**Comment by iokzero** [comment]
Would love to do some testing. Thanks

**Comment by iokzero** [comment]
Tried the image you suggested can't get any game to launch With or Without the PPSSPP assists file in the system folder.

**Comment by Ntemis** [comment]
Then is either a faulty iso or not supported by the emulator

**Comment by iokzero** [comment]
They work just fine on LAKKA 2.2.2 ,is it possible that, the latest PPSSPP
no longer support .CSO format? Assuming no additional system files need to
be added from the user.

**Comment by Ntemis** [comment]
please try the same game in iso format and let me know

**Comment by iokzero** [comment]
I tried the original iso, PPSSPP failed to load as well, nothing launched.
I can't get a log out of it because I keep having ssh problems trying to
connect the box (For some reason always happens on nightbuild, not sure
why, the service is on for sure, but it keeps giving me "Host Key
verification failed..." error.)

**Comment by iokzero** [comment]
Sorry I think I speak too soon, I finally got SSH working, forget to remove Keygen (LOL such 101 mistake, my bad)
`[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 3840x2160.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x2611340.
[INFO] [KMS]: New FB: 3840x2160 (stride: 15360).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Iris Plus Graphics 650 (Kaby Lake GT3e) .
[INFO] [GL]: Version: 3.0 Mesa 19.3.5.
[INFO] [GL]: Using resolution 3840x2160
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
[INFO] [udev]: Pad #0 (/dev/input/event4) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] [Shaders]: Found shader "/tmp/shaders/bilinear.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/nearest.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] [Shaders]: Found shader "/tmp/shaders/stock.glsl"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 1024 frames
[INFO] ALSA: Buffer size: 2048 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x900e40
ALSA lib /mnt/data/PROJECTS/Lakka-LE9.2/build.Lakka-Generic.x86_64/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [GL]: VSync => on
[INFO] [KMS]: New FB: 3840x2160 (stride: 15360).
[INFO] [KMS]: New FB: 3840x2160 (stride: 15360).
[INFO] [CONTENT LOAD]: Updating firmware status for: /tmp/cores/ppsspp_libretro.so on /tmp/system
[INFO] [CORE]: Using content: /storage/roms/Samsung USB/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).iso.
[INFO] [CORE]: Arg #0: retroarch
[INFO] [CORE]: Arg #1: /storage/roms/Samsung USB/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).iso
[INFO] [CORE]: Arg #2: -s
[INFO] [CORE]: Arg #3: /storage/savefiles
[INFO] [CORE]: Arg #4: -S
[INFO] [CORE]: Arg #5: /storage/savestates
[INFO] [CORE]: Arg #6: -c
[INFO] [CORE]: Arg #7: /storage/.config/retroarch/retroarch.cfg
[INFO] [CORE]: Arg #8: -L
[INFO] [CORE]: Arg #9: /tmp/cores/ppsspp_libretro.so
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [CORE]: Unloading core..
[INFO] [CORE]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.8.9 (Git 857b0da555)
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Aug 10 2020
[INFO] Version: 1.8.9
[INFO] Git: 857b0da555
[INFO] =================================================
[INFO] [CORE]: Loading dynamic libretro core from: "/tmp/cores/ppsspp_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /storage/.config/retroarch/config/PPSSPP/PPSSPP.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /storage/.config/retroarch/config/PPSSPP/Samsung USB.cfg.
[INFO] [Overrides]: No game-specific overrides found at /storage/.config/retroarch/config/PPSSPP/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).cfg.
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Remaps]: remap directory: /storage/remappings
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_USERNAME: "".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[libretro INFO] [SYSTEM] Using OpenGL backend
[INFO] [Environ]: GET_LANGUAGE: "0".
[libretro INFO] [BOOT] PPSSPP v1.10.3
[libretro INFO] [MEMMAP] base: 0xffffffffffffffff
[libretro INFO] [MEMMAP] aligned_base: (nil)
[libretro INFO] [MEMMAP] Memory system initialized. Base at (nil) (RAM at @ 0x8000000, uncached @ 0x48000000)
[libretro INFO] [LOADER] ULUS10277 : Castlevania The Dracula X Chronicles
[libretro INFO] [LOADER] Failed to read ULUS10277_ppsspp.ini. No game-specific settings found, using global defaults.
[libretro INFO] [LOADER] Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /tmp/database/cht/PPSSPP/1229 - Castlevania - The Dracula X Chronicles (USA) (v1.02).cht
[INFO] [Audio]: Set audio input rate to: 44144.10 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[INFO] [DRM]: Found 3 connectors.
[libretro INFO] [SCEKERNEL] Kernel and user memory pools initialized
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 39 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[libretro INFO] [SCEGE] PPGe drawing library initialized. DL: 08000200 Data: 08010200 Atlas: 08020b00 (2097152) Args: 08020200
[libretro INFO] [SCEKERNEL] Kernel initialized.
[libretro INFO] [LOADER] Decrypting tag C0CB167C
[libretro INFO] [LOADER] Decrypting tag C0CB167C
[libretro INFO] [SCEKERNEL] -----------
[libretro INFO] [SCEKERNEL] Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
[libretro INFO] [SCEKERNEL] Block: 08804000 - 08cdd000 size 004d9000 taken=1 tag=ELF/simple
[libretro INFO] [SCEKERNEL] Block: 08cdd000 - 0a000000 size 01323000 taken=0 tag=(untitled)
[libretro INFO] [SCEKERNEL] -----------
[libretro INFO] [LOADER] Module simple: 08af8590 08a31e90 08a31ea8
[libretro INFO] [HLE] Replaced memcpy at 0880fcf8 with hash 8c3fd997a544d0b1
[libretro INFO] [HLE] Replaced memmove at 0880fe40 with hash 368f6cf979709a31
[libretro INFO] [HLE] Replaced memset at 08810140 with hash 4bb677dace6ca526
[libretro INFO] [HLE] Replaced memcpy at 088188c0 with hash 9e2941c4a5c5e847
[libretro INFO] [LOADER] Exporting ent 0 named simple, 2 funcs, 4 vars, resident 08a32270
[libretro INFO] [LOADER] Module entry: 08a31424
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Mode 0: (3840x2160) 3840 x 2160, 60 Hz
[INFO] [DRM]: Mode 1: (4096x2160) 4096 x 2160, 60 Hz
[INFO] [DRM]: Mode 2: (4096x2160) 4096 x 2160, 60 Hz
[INFO] [DRM]: Mode 3: (4096x2160) 4096 x 2160, 50 Hz
[INFO] [DRM]: Mode 4: (4096x2160) 4096 x 2160, 30 Hz
[INFO] [DRM]: Mode 5: (4096x2160) 4096 x 2160, 30 Hz
[INFO] [DRM]: Mode 6: (4096x2160) 4096 x 2160, 25 Hz
[INFO] [DRM]: Mode 7: (4096x2160) 4096 x 2160, 24 Hz
[INFO] [DRM]: Mode 8: (4096x2160) 4096 x 2160, 24 Hz
[INFO] [DRM]: Mode 9: (3840x2160) 3840 x 2160, 60 Hz
[INFO] [DRM]: Mode 10: (3840x2160) 3840 x 2160, 50 Hz
[INFO] [DRM]: Mode 11: (3840x2160) 3840 x 2160, 30 Hz
[INFO] [DRM]: Mode 12: (3840x2160) 3840 x 2160, 30 Hz
[INFO] [DRM]: Mode 13: (3840x2160) 3840 x 2160, 25 Hz
[INFO] [DRM]: Mode 14: (3840x2160) 3840 x 2160, 24 Hz
[INFO] [DRM]: Mode 15: (3840x2160) 3840 x 2160, 24 Hz
[INFO] [DRM]: Mode 16: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 17: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 18: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 19: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 20: (1920x1080) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 21: (1920x1080i) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 22: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 23: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 24: (1920x1080) 1920 x 1080, 25 Hz
[INFO] [DRM]: Mode 25: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 26: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 27: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 28: (1280x960) 1280 x 960, 60 Hz
[INFO] [DRM]: Mode 29: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 30: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 31: (1280x720) 1280 x 720, 50 Hz
[INFO] [DRM]: Mode 32: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 33: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 34: (720x576) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 35: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 36: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 37: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 38: (640x480) 640 x 480, 60 Hz
corrupted double-linked list
Aborted
`

**Comment by iokzero** [comment]
Nightly Build from #918 

Seems fix this issue as well for some reason.
