### ISSUE TITLE
Wired controllers not working

### ISSUE THREAD

**Issue by bxyanks52** [libretro/Lakka-LibreELEC#923]
I recently bought a RPi 4 and when I first started lakka I was able to use my wired Xbox 360 controller. After shutting it down and starting it back up i can no longer navigate lakkas interface with the controller. Auto configuration is enabled.  My keyboard works but not my controller. When I unplug the controller from my RPi a notification pops up from the bottom left that it was disconnected from Port #0. What is port 0 and how do I get it to work again?

**Comment by emilravn** [comment]
Currently also experiencing this. This happens after I start a game, it crashes (because of wrong core I suppose) restarts and unable to navigate the interface.
 
Tried deleting the retroarch.cfg through SSH and restore from new. Doesn't help.

Only thing that helps me is reinstalling Lakka itself.

**Comment by Ntemis** [comment]
please upgrade to https://nightly.builds.lakka.tv/2020-08-07/RPi4.arm/
