### ISSUE TITLE
Power button and volume button not working. 

### ISSUE THREAD

**Issue by ejruiz3** [libretro/Lakka-LibreELEC#925]
Power button not working on Nintendo switch. When booting lakka from hekkate the power button and volume buttons do not work. The controllers work. 
Lakka-Switch.L4T.aarch64-2.2-devel-20190728151829-r28534-gbd694f826.tar.gz

Edit: volume does work when playing n64 game. But the power button doesn't work.

**Comment by natinusala** [comment]
Lakka Switch is not supported on this repository.

Lakka is outdated and sleep is not implemented, this is why the power button does nothing
