### ISSUE TITLE
RUBAN in pipeline shader menu made my lakka dead slow

### ISSUE THREAD

**Issue by parasolstar** [libretro/Lakka-LibreELEC#927]
i run lakka on my old pentium 4 pc and it was very slow, after a very struggling search in the menu i disabled the ruban in the pipeline shader menu and it became so much more usable so make it deactivated as default.

**Comment by natinusala** [comment]
I'm sorry to say that but your Pentium 4 PC is an absolute toaster... modern computers (and even tiny low power ones such as the Raspberry Pi) have no trouble in displaying the ribbon at full speed. 

We have no way to know what the computer is capable of when running Lakka so we can't disable it for slow computers either.
