### ISSUE TITLE
Default core doesn't work on favorites

### ISSUE THREAD

**Issue by luis-garza** [libretro/Lakka-LibreELEC#930]
I'm running Lakka 2.3.2 on a Raspberry pi 4, and using cores for different systems.

I've setup a default core for each system in his playlist, everything works like is expected, I didn't have to select any core too start a game.

But when I mark as favorite a game from any system, when I try to play it through the favorite list the default core is not defined and I have to select it.

I hope it could be solved easily.

**Comment by Ntemis** [comment]
https://nightly.builds.lakka.tv/2020-08-07/RPi4.arm/
