### ISSUE TITLE
Lakka doesn't work with QXL driver

### ISSUE THREAD

**Issue by blademckain** [libretro/Lakka-LibreELEC#931]
lspci
....
VGA compatible controller: Red Hat, Inc. QXL paravirtual graphic card ( rev 04 )
.....

retroarch -v
....
[ERROR] [KMS]: Could't find a suitable DRM device.
[INFO] [GL]: Found GL context: null
....

It'is possible add the QXL paravirtual driver into Lakka?

**Comment by Ntemis** [comment]
afaik not possible sorry
