### ISSUE TITLE
Issue with renamed games & thumbnails/box arts

### ISSUE THREAD

**Issue by MEGATRES** [libretro/Lakka-LibreELEC#932]
I think I found an error with how thumbnails are handled in Lakka,
When enabling the ability to rename games in the playlist settings & then renaming a game it's thumbnails disappear. For example when adding my copy of MGS it was automatically named "Metal Gear Solid (Europe) (Disc 1 of 2)", to make the menus more tidy I renamed it "Metal Gear Solid (1/2)". This caused it's thumbnails to disappear, even when manually updating thumbnails from the settings they're still missing.
Am using Lakka 2.3.2 on a Raspberry Pi 4

**Comment by natinusala** [comment]
I think this is intended, RetroArch uses the playlist entry name to match the thumbnail

**Comment by RobLoach** [comment]
In Playlist Management, you can toggle display of the game flags, while keeping the thumbnails there
