### ISSUE TITLE
Allow SSH access to be configured to block password based authentication

### ISSUE THREAD

**Issue by t-paul** [libretro/Lakka-LibreELEC#935]
If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
2.3.2

- What system hardware are you using?
Raspberry Pi

- What did you do?
Add ` SSH_ARGS="-o PasswordAuthentication=no"` to `/storage/.cache/services/sshd.conf`

- What did you expect to happen?
Password based access is blocked, but access via ssh-key still works (key copied previously)

- What happened instead?
Works only as long as `retroarch` is not restarted or lakka is rebooted
Restarting `retroarch` truncates the file `/storage/.cache/services/sshd.conf` to zero length, so the config option is lost.

I understand that the file is deleted when disabling the service. So maybe the ENV entry in the service file could point to a different file so the manually changed options are retained independently?
https://github.com/libretro/Lakka-LibreELEC/blob/2480e5dbd7b7e5bc95bccdbf6da319f5933e67e9/packages/network/openssh/system.d/sshd.service#L8

**Comment by amak79** [comment]
I've worked around this issue by making the `sshd.conf` file immutable: `chattr +i /storage/.cache/services/sshd.conf`. This will prevent it from being removed/wiped, even by the root user.

The file isn't removed/wiped when using LibreELEC, so there is an underlying issue with Lakka.
