### ISSUE TITLE
Compilation of Lakka 2.3.2 for Odroid C2 FAIL

### ISSUE THREAD

**Issue by aeloya** [libretro/Lakka-LibreELEC#943]
Hi!
I have try to compile Lakka 2.3.2 on my Ubuntu 18.04.4  
$ DISTRO=Lakka PROJECT=Odroid_C2 ARCH=aarch64 make image
and recieve this error
...
  BUILD    flycast (target)
make[1]: Entering directory '/home/src/Lakka-LibreELEC/build.Lakka-Odroid_C2.aarch64-2.3-devel/flycast-a37ee3c'
...
/home/src/Lakka-LibreELEC/build.Lakka-Odroid_C2.aarch64-2.3-devel/toolchain/bin/aarch64-libreelec-linux-gnueabi-g++  -I./core/libretro -I./core/ -I./core/deps -I./core/deps/picotcp/include -I./core/deps/picotcp/modules -I./core/libretro-common/include -I./core/deps/vixl -I./core/deps/khronos -I./core/deps/glslang -I./core/deps/flac/include -mcpu=cortex-a53+crc+fp+simd -mabi=lp64 -Wno-psabi -fomit-frame-pointer -Wall -pipe -O2   -DTARGET_NO_OPENMP -D__LIBRETRO__  -DHAVE_GLSYM_PRIVATE -DNO_VERIFY -DNDEBUG -flto -DRELEASE -DHAVE_GL3 -funroll-loops -DCORE -DHAVE_TEXUPSCALE -DHAVE_OPENGL -DHAVE_VULKAN -DTARGET_NO_JIT -DFLAC__HAS_OGG=0 -DFLAC__NO_DLL -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -D_7ZIP_ST -DUSE_FLAC -DUSE_LZMA -O3 -c -fno-strict-aliasing -ffast-math -fomit-frame-pointer -fPIC  -mcpu=cortex-a53+crc+fp+simd -mabi=lp64 -Wno-psabi -fomit-frame-pointer -Wall -pipe -O2  -DGIT_VERSION=\"" a37ee3c8"\"  -DTARGET_NO_OPENMP -std=c++11 -D__LIBRETRO__  -DHAVE_GLSYM_PRIVATE -DNO_VERIFY -DNDEBUG -flto -DRELEASE -DHAVE_GL3 -funroll-loops -DCORE -DHAVE_TEXUPSCALE -DHAVE_OPENGL -DHAVE_VULKAN -DTARGET_NO_JIT -DFLAC__HAS_OGG=0 -DFLAC__NO_DLL -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -D_7ZIP_ST -DUSE_FLAC -DUSE_LZMA -fno-rtti -fpermissive -fno-operator-names -fPIC core/deps/chdpsr/cdipsr.cpp -o core/deps/chdpsr/cdipsr.o
In file included from ./core/libretro-common/include/glsm/glsm.h:30,
                 from core/rend/gles/gles.h:6,
                 from core/serialize.cpp:25:
./core/libretro-common/include/glsym/rglgen_headers.h:72:10: fatal error: GL/gl.h: No such file or directory
   72 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1083: core/serialize.o] Error 1

**Comment by natinusala** [comment]
aarch64 is not supported, please try arm instead

**Comment by aeloya** [comment]
Thank you for response!
When try DISTRO=Lakka PROJECT=Odroid_C2 ARCH=arm make image
I recieve 
...
GIT VERSION sameboy - 54f41cb
fatal: ambiguous argument '54f41cb': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 128

**Comment by by-gnome** [comment]
> fatal: ambiguous argument '54f41cb': unknown revision or path not in the working tree.

Branch with commit 54f41cb which should be after bd9ac20 is not exist.
Try c9e547c.

**Comment by aeloya** [comment]
Today I receive new error

Connecting to rpm5.org (rpm5.org)|91.195.240.94|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'sources/popt/popt-1.16.tar.gz'

sources/popt/popt-1.16.tar.gz                   [ <=>                                                                                     ]  18.08K  --.-KB/s    in 0.05s   

2020-05-31 20:05:30 (375 KB/s) - 'sources/popt/popt-1.16.tar.gz' saved [18512]

INFO Calculated checksum is: 9299f31b58f7fab82cd0ee11c9f05a60c31904e4ff47fae873ddb287cb442577

  UNPACK   popt

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 2

rpm5.org looks unavailable. 

What can I do now?

**Comment by by-gnome** [comment]
Use http://sources.lakka.tv/popt-1.16.tar.gz

**Comment by Ntemis** [comment]
2.3.x is eol closing

**Comment by rodneyrod** [comment]
Just posting, no images have been listed for Odroid C2 since this post, if it has been dropped could we get an official post regarding this?

**Comment by Ntemis** [comment]
If libreelec doesn't support it usually we can't do anything about it

Στις Τρί, 25 Μαΐ 2021, 08:14 ο χρήστης rodneyrod ***@***.***>
έγραψε:

**Comment by aeloya** [comment]
http://www.lakka.tv/get/linux/amlogic/ you can find new image here

**Comment by rodneyrod** [comment]
Thank you beautiful people this is perfect 😄
