### ISSUE TITLE
Gamepad button SELECT don't work in PCSX

### ISSUE THREAD

**Issue by petr-akhlamov** [libretro/Lakka-LibreELEC#945]
Lakka 2.3.2, RaspberryPie3.
Gamepad connected to computer and configured. In PCSX when i want to push to SELECT, it don't work, but in other emulators (SEGA, Gameboy, NES) this button are works.

If needed yet anything information, write, i will provide it.

**Comment by RobLoach** [comment]
I'd recommend making an issue in the PCSX libretro issue queue.
