### ISSUE TITLE
Need assist in debugging/ fixing nonplayback of fmv cutscenes on SM3 for psp/ppsspp emulator !!!!

### ISSUE THREAD

**Issue by Raimigboy997** [libretro/Lakka-LibreELEC#947]
Hi, I have a concern about PPSSPP for pc windows 10.  I just recently downloaded and installed spider-man 3 for thr psp onto my drive and the emulator along with it.  It seems to work fine up until the intro roll of the vicarious visions fmv at the start, which then progresses to repeat in a loop until I decided to hit start and it went away.  I saw the main menu pop up, but no sound/music was present, so I hit start and waited for something to happen.  The very next frame after the loading screen was the same damn intro video played again, and once I hit X to rid of it once and finally, the game began... and still, NO SOUND!!!!  WHat' is happening?  the game is fine but the emulator is lacking, or lagging in the management of properly playing the thing.  Anyone agree?  Please, if anybody knows what I have to do, please comment below for a shoutout.

**Comment by gouchi** [comment]
If you are using Windows 10, please check the [forum](https://forums.libretro.com) and our [discord](https://discordapp.com/invite/27Xxm2h).
