### ISSUE TITLE
Any news on the next RPi4 release?

### ISSUE THREAD

**Issue by coldspark29** [libretro/Lakka-LibreELEC#949]
I know Github is not for general questions, but I can't post anything in the forum and the IRC channel seems dead to me. I guess the current Corona situation did not speed up the progress, did it? The last update was almost 4 monthts ago and I was hoping that N64 games would be playable by now. I would try to update the cores myself, if there is a possibility. It seems that there has not been a Mupen64Plus update since February, has it?

**Comment by Ntemis** [comment]
Lakka has a home channel in Retroarch discord
