### ISSUE TITLE
MUPEN* does not copy correct controller mapping

### ISSUE THREAD

**Issue by sektor80** [libretro/Lakka-LibreELEC#951]
Hello LAKKA Team,
thank you for this great software! I like it very much!

- Which version of Lakka are you using?
2.3.2 . The same issue exists with the latest LAKKA 3 beta. It is reproducible under both versions.

- What system hardware are you using?
RPI4 B 4GB

- What did you do?
Started a N64 game with one of the MUPEN* cores. After the game was started I tried to use the triangle/circle buttons to play.

- What did you expect to happen?
I expected the triangle/circle buttons would do what they are supposed to do in the game. 

- What happened instead?
The triangle/circle buttons work only if I hold R2 button while I press triangle/circle. The controller is an original PS3 controller. 

The triangle/circle buttons work with other cores (e.g. snes*) without changing the controller setup in LAKKA (I use the default setup but changing the controller setup doesn't change the behavior). 

_It looks like the Mupen cores do not copy the existing controller setup correctly for some reason._

According to http://www.lakka.tv/doc/Troubleshooting-Lakka/ I try to provide you with useful logs:

1) PS3 via USB : started LAKKA and connected the PS3 controller via USB after bootup, then pressed the playstation button
2) PS3 via Bluetooth : same but without a cable
3) PS3 via Bluetooth - game started : same but started mortal combat 

Please let me know if you need further information.
[PS3 via Bluetooth.txt](https://github.com/libretro/Lakka-LibreELEC/files/4618875/PS3.via.Bluetooth.txt)
[PS3 via Bluetooth - game started.txt](https://github.com/libretro/Lakka-LibreELEC/files/4618876/PS3.via.Bluetooth.-.game.started.txt)
[PS3 via USB.txt](https://github.com/libretro/Lakka-LibreELEC/files/4618877/PS3.via.USB.txt)

**Comment by georgikoemdzhiev** [comment]
I experienced something similar. I used the same version of lakka on my RPI 4. When my PRS 3 controller was automatically detected, the 4 circle buttons did not do anything in any of the games I had.
