### ISSUE TITLE
make image does not pass -j setting down

### ISSUE THREAD

**Issue by zgoda** [libretro/Lakka-LibreELEC#959]
When running 1st build on a machine with large number of cores and with poor connection, the build completely hoses network and fails many times on git clone operations. Passing usual -j param to `make image` (eg. `make -j 8 image`) makes no difference because this param is not passed down to `scripts/image mkimage`.

**Comment by natinusala** [comment]
You have to use MAKEFLAGS=-j12 for it to work

**Comment by natinusala** [comment]
But I think the -j flag is automatically passed to make sub processes, I 
think I read that somewhere

**Comment by zgoda** [comment]
`toolchain/bin/parallel` is running with `--max-procs 100%`. `MAKEFLAGS` does not affect `parallel` invocation.

Looking at `config/multithread` I think it's `THREADCOUNT` that affects number of processes spawned by `parallel`.

**Comment by zgoda** [comment]
Indeed, this is it. `THREADCOUNT` env var controls number of processes spawned by parallel during build. So if you want to limit number of processes that do a `git clone` (eg. libretro cores) this is the way.

Later spawned compilation processes controlled by make will follow `MAKEFLAGS` setting so I guess there may be some conflict there.
