### ISSUE TITLE
Add entry on raspberry pi to force audio through HDMI

### ISSUE THREAD

**Issue by arthurferrai** [libretro/Lakka-LibreELEC#967]
I think it would be a nice add to raspberry pi manual to force audio through HDMI.
I solved it by putting `amixer cset numid=3 2` on `/storage/.config/autostart.sh` script file.
In my setup (rpi 3), it was the only way to solve the audio issue.

**Comment by copyread** [comment]
Would be useful. I had to do this, but the inverse (forcing audio through headphone jack)

**Comment by Ntemis** [comment]
sent a pr, bye and thanks

**Comment by copyread** [comment]
Where?

**Comment by Ntemis** [comment]
https://github.com/libretro/Lakka-LibreELEC/pulls
