### ISSUE TITLE
Lakka for Orange Pi PC2 ?

### ISSUE THREAD

**Issue by DartPower** [libretro/Lakka-LibreELEC#972]
Can you build Lakka for Orange Pi PC2? 
AllWinner H5+ (64-bit)

**Comment by Ntemis** [comment]
Not on this branch but when we migrate to LE-10.x it will be possible

**Comment by DartPower** [comment]
:(

**Comment by DartPower** [comment]
I hope at least you remember... Or can you give me advice, which me select the good alternative? I only have one SoC.
