### ISSUE TITLE
Add MCP23017 on i2c0 (kernel module)

### ISSUE THREAD

**Issue by vince87** [libretro/Lakka-LibreELEC#975]
I would like to use lakka on old arcade cabinets with raspberry, I need to compile this driver

[joypi.zip](https://github.com/libretro/Lakka-LibreELEC/files/4892986/joypi.zip)

Thanks
Vincenzo

**Comment by Ntemis** [comment]
you must create a package for it, then add it to the project you are targetting

**Comment by vince87** [comment]
@Ntemis sorry but I don't have the skills to do it.
Is there a guide i can follow?
lastly, I would like to make it activated and selectable from the lakka menu

**Comment by Ntemis** [comment]
Easily said than done.
Good luck.
