### ISSUE TITLE
recording fails on generic 32 bit machine segmentation fault

### ISSUE THREAD

**Issue by Qiyamah** [libretro/Lakka-LibreELEC#993]
`###########################################
# Lakka - The DIY retro emulation console #
# ...... visit http://www.lakka.tv ...... #
###########################################

Lakka (community): devel-20200721211029-e379a76 (Generic.i386)
Lakka:~ # cd /storage/screenshots/
Lakka:~/screenshots # ls
Metal Slug X-200724-021717.png  Metal Slug X-200724-034959.png
Metal Slug X-200724-022526.png
Lakka:~/screenshots # systemctl stop retroarch.service ; retroarch -v
[INFO] RetroArch 1.8.9 (Git 857b0da555)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Atom(TM) CPU N280   @ 1.66GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3
[INFO] Built: Jul 21 2020
[INFO] Version: 1.8.9
[INFO] Git: 857b0da555
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/.srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 41 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 4: (1920x1080) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 5: (1920x1080i) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 6: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 7: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 8: (1920x1080) 1920 x 1080, 25 Hz
[INFO] [DRM]: Mode 9: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 10: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 11: (1680x1050) 1680 x 1050, 60 Hz
[INFO] [DRM]: Mode 12: (1600x900) 1600 x 900, 60 Hz
[INFO] [DRM]: Mode 13: (1280x1024) 1280 x 1024, 75 Hz
[INFO] [DRM]: Mode 14: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 15: (1440x900) 1440 x 900, 60 Hz
[INFO] [DRM]: Mode 16: (1366x768) 1366 x 768, 60 Hz
[INFO] [DRM]: Mode 17: (1280x800) 1280 x 800, 60 Hz
[INFO] [DRM]: Mode 18: (1152x864) 1152 x 864, 75 Hz
[INFO] [DRM]: Mode 19: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 20: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 21: (1280x720) 1280 x 720, 50 Hz
[INFO] [DRM]: Mode 22: (1024x768) 1024 x 768, 75 Hz
[INFO] [DRM]: Mode 23: (1024x768) 1024 x 768, 70 Hz
[INFO] [DRM]: Mode 24: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 25: (832x624) 832 x 624, 75 Hz
[INFO] [DRM]: Mode 26: (800x600) 800 x 600, 75 Hz
[INFO] [DRM]: Mode 27: (800x600) 800 x 600, 72 Hz
[INFO] [DRM]: Mode 28: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 29: (720x576) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 30: (720x576i) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 31: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 32: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 33: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 34: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 35: (640x480) 640 x 480, 75 Hz
[INFO] [DRM]: Mode 36: (640x480) 640 x 480, 73 Hz
[INFO] [DRM]: Mode 37: (640x480) 640 x 480, 67 Hz
[INFO] [DRM]: Mode 38: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 39: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 40: (720x400) 720 x 400, 70 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xb3f73420.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Mobile Intel® GM45 Express Chipset .
[INFO] [GL]: Version: 2.1 Mesa 19.1.7.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] [Shaders]: Found shader "/tmp/shaders/bilinear.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/nearest.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] [Shaders]: Found shader "/tmp/shaders/stock.glsl"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 1024 frames
[INFO] ALSA: Buffer size: 2048 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x853d760
ALSA lib /home/rra/Lakka-LibreELEC/build.Lakka-Generic.i386-3.0-devel/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [CORE]: Using content: /storage/roms/selected/Bomberman (Japan).zip#Bomberman (Japan).pce.
[INFO] [CORE]: Arg #0: retroarch
[INFO] [CORE]: Arg #1: /storage/roms/selected/Bomberman (Japan).zip#Bomberman (Japan).pce
[INFO] [CORE]: Arg #2: -s
[INFO] [CORE]: Arg #3: /storage/savefiles
[INFO] [CORE]: Arg #4: -S
[INFO] [CORE]: Arg #5: /storage/savestates
[INFO] [CORE]: Arg #6: -c
[INFO] [CORE]: Arg #7: /storage/.config/retroarch/retroarch.cfg
[INFO] [CORE]: Arg #8: -L
[INFO] [CORE]: Arg #9: /tmp/cores/mednafen_pce_fast_libretro.so
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [CORE]: Unloading core..
[INFO] [CORE]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 1915, Frames dropped: 0.
[INFO] RetroArch 1.8.9 (Git 857b0da555)
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/Bomberman (Japan).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/Bomberman (Japan).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Atom(TM) CPU N280   @ 1.66GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3
[INFO] Built: Jul 21 2020
[INFO] Version: 1.8.9
[INFO] Git: 857b0da555
[INFO] =================================================
[INFO] [CORE]: Loading dynamic libretro core from: "/tmp/cores/mednafen_pce_fast_libretro.so"
[INFO] [Overrides]: No core-specific overrides found at /storage/.config/retroarch/config/Beetle PCE Fast/Beetle PCE Fast.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /storage/.config/retroarch/config/Beetle PCE Fast/selected.cfg.
[INFO] [Overrides]: No game-specific overrides found at /storage/.config/retroarch/config/Beetle PCE Fast/Bomberman (Japan).cfg.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] Core requested VFS version >= v1, providing v3
[INFO] [Remaps]: remap directory: /storage/remappings
[INFO] [Overrides]: Redirecting save file to "/storage/savefiles/Bomberman (Japan).srm".
[INFO] [Overrides]: Redirecting save state to "/storage/savestates/Bomberman (Japan).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/tmp/system".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_SUPPORT_ACHIEVEMENTS: yes.
[INFO] [Environ]: PERFORMANCE_LEVEL: 5.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[libretro INFO] PCE CD Audio settings changed.
[libretro INFO] Loading /storage/roms/selected/Bomberman (Japan).pce...

[libretro INFO]  Using module: pce_fast.

[libretro INFO]   ROM:       256KiB

[libretro INFO]   ROM CRC32: 0x9abb4d1f

unhandled setting F: pce_fast.mouse_sensitivity
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]    ndx flags  ptr          offset   start    select   disconn  len      addrspace
[INFO]    001 M1A1bc 0xb48c0d60 00000000 001F0000 FFFFE000 00000000 00002000
[INFO]    002 M1A1bc 0xb48c0540 00000000 001EE000 FFFFF800 00000000 00000800
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /tmp/database/cht/Beetle PCE Fast/Bomberman (Japan).cht
[INFO] [Audio]: Set audio input rate to: 44232.70 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 41 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 2: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
[INFO] [DRM]: Mode 4: (1920x1080) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 5: (1920x1080i) 1920 x 1080, 50 Hz
[INFO] [DRM]: Mode 6: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 7: (1920x1080) 1920 x 1080, 30 Hz
[INFO] [DRM]: Mode 8: (1920x1080) 1920 x 1080, 25 Hz
[INFO] [DRM]: Mode 9: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 10: (1920x1080) 1920 x 1080, 24 Hz
[INFO] [DRM]: Mode 11: (1680x1050) 1680 x 1050, 60 Hz
[INFO] [DRM]: Mode 12: (1600x900) 1600 x 900, 60 Hz
[INFO] [DRM]: Mode 13: (1280x1024) 1280 x 1024, 75 Hz
[INFO] [DRM]: Mode 14: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 15: (1440x900) 1440 x 900, 60 Hz
[INFO] [DRM]: Mode 16: (1366x768) 1366 x 768, 60 Hz
[INFO] [DRM]: Mode 17: (1280x800) 1280 x 800, 60 Hz
[INFO] [DRM]: Mode 18: (1152x864) 1152 x 864, 75 Hz
[INFO] [DRM]: Mode 19: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 20: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 21: (1280x720) 1280 x 720, 50 Hz
[INFO] [DRM]: Mode 22: (1024x768) 1024 x 768, 75 Hz
[INFO] [DRM]: Mode 23: (1024x768) 1024 x 768, 70 Hz
[INFO] [DRM]: Mode 24: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 25: (832x624) 832 x 624, 75 Hz
[INFO] [DRM]: Mode 26: (800x600) 800 x 600, 75 Hz
[INFO] [DRM]: Mode 27: (800x600) 800 x 600, 72 Hz
[INFO] [DRM]: Mode 28: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 29: (720x576) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 30: (720x576i) 720 x 576, 50 Hz
[INFO] [DRM]: Mode 31: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 32: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 33: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 34: (720x480i) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 35: (640x480) 640 x 480, 75 Hz
[INFO] [DRM]: Mode 36: (640x480) 640 x 480, 73 Hz
[INFO] [DRM]: Mode 37: (640x480) 640 x 480, 67 Hz
[INFO] [DRM]: Mode 38: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 39: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 40: (720x400) 720 x 400, 70 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xb4272b60.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Mobile Intel® GM45 Express Chipset .
[INFO] [GL]: Version: 2.1 Mesa 19.1.7.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] [Shaders]: Found shader "/tmp/shaders/bilinear.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/nearest.glslp"
[INFO] [Shaders]: Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] [Shaders]: Found shader "/tmp/shaders/stock.glsl"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 1024 frames
[INFO] ALSA: Buffer size: 2048 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x853d760
ALSA lib /home/rra/Lakka-LibreELEC/build.Lakka-Generic.i386-3.0-devel/alsa-lib-1.1.9/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [Playlist]: Written to playlist file: /storage/.config/retroarch/content_history.lpl
[INFO] SET_GEOMETRY: 256x240, aspect: 1.215.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [recording] Custom timing given: FPS: 59.8200, Sample rate: 44100.0000
[INFO] [recording] Recording to Bomberman (Japan)-200724-042059.mkv @ 256x240. (FB size: 512x243 pix_fmt: 0)
Segmentation fault`

**Comment by Ntemis** [comment]
Generic builds on 32bit is no longer supported upstream as they need to put 32bit to rest. We are not going anywhere with this
marked by me as will not fixed and closed to eternity . Thanks for the time to report it though
