### ISSUE TITLE
Switch pro controller wired configuration

### ISSUE THREAD

**Issue by buildsomestuff** [libretro/Lakka-LibreELEC#997]
Hello, I'm trying to connect my switch pro controller using a wire to Lakka. The controller registers, but does not function as an input. When I press and hold the pairing button on the controller, the menu starts continuously scrolling and only stops when the controller is unplugged. Is there any way to fix this and get the controller paired? Thanks for your help!

**Comment by Ntemis** [comment]
switch pro controller need a special driver to function but we are not yet there
